In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(multi).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0               0        0       0           1          1            0   
1               1        0       0           1          1            1   
2               2        0       0           1          1            0   
3               3        0       0           1          3            0   
4               4        0       0           1          3            0   
...           ...      ...     ...         ...        ...          ...   
15319       23429        0       0           1          1            0   
15320       23430        0       0           1          1            0   
15321       23431        0       0           1          1            0   
15322       23432        0       0           1          1            0   
15323       23433        0       0           1          1            0   

       https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                 0        0              0            0  ...           0   
1                 0        0              0            0  ...           0   
2                 1        0              0            0  ...           0   
3                 0        0              0            0  ...           0   
4                 0        0              0            0  ...           0   
...             ...      ...            ...          ...  ...         ...   
15319             0        0              0            0  ...           0   
15320             0        0              0            0  ...           0   
15321             0        0              0            0  ...           0   
15322             0        0              0            0  ...           0   
15323             0        0              0            0  ...           0   

       Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0              49        691          42       13135                6400   
1               4         66           3        2034                 818   
2               1        100          27       32987               10451   
3               0          0           1           0                  52   
4             117        219          23        7944                3468   
...           ...        ...         ...         ...                 ...   
15319           0          0           1           0                   4   
15320           0          0           1           0                   4   
15321           0          0           1           0                   4   
15322           0          0           1           0                   4   
15323           0          0           1           0                   4   

       Script To Special Chars Ratio  Script To body Ratio  \
0                           2.052344              0.528869   
1                           2.486553              0.676197   
2                           3.156349              0.836681   
3                           0.000000              0.000000   
4                           2.290657              0.524460   
...                              ...                   ...   
15319                       0.000000              0.000000   
15320                       0.000000              0.000000   
15321                       0.000000              0.000000   
15322                       0.000000              0.000000   
15323                       0.000000              0.000000   

       Body To Special Char Ratio  Label  
0                        0.257690      0  
1                        0.271941      0  
2                        0.265079      0  
3                        0.227074      0  
4                        0.228956      0  
...                           ...    ...  
15319                    0.121212      4  
15320                    0.121212      4  
15321                    0.121212      4  
15322                    0.121212      4  
15323                    0.121212      4  

[15324 rows x 46 c

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               1           0                    0                 10   
1               4           1                    2                  3   
2               1           1                    2                  2   
3               4           1                    5                  0   
4               2           0                    0                  1   

   Num of digits  Num of spec char  Label  
0              0                25      0  
1             22                13      0  
2              2                 9      0  
3             19                18      0  
4             17                 7      0  

[5 rows x 25 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15324 entries, 0 to 15323
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Have IP              15324 non-null  int64
 1   Have @               15324 non-null  int64
 2   URL Length           15324 non-null  int64
 3   URL Depth            15324 non-null  int64
 4   Redirection          15324 non-null  int64
 5   https Domain         15324 non-null  int64
 6   TinyURL              15324 non-null  int64
 7   Prefix/Suffix        15324 non-null  int64
 8   Have client          15324 non-null  int64
 9   Have admin           15324 non-null  int64
 10  Have login           15324 non-null  int64
 11  Have server          15324 non-null  int64
 12  .php                 15324 non-null  int64
 13  .html                15324 non-null  int64
 14  .info                15324 non-null  int64
 15  .txt                 15324 non-null  int64
 16  .js                  1

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
2    3002
3    3543
4    2252
dtype: int64

In [8]:

import numpy as np


In [9]:
urldata.describe()

Have IP        Have @    URL Length     URL Depth   Redirection  \
count  15324.0  15324.000000  15324.000000  15324.000000  15324.000000   
mean       0.0      0.003067      0.897938      3.190029      0.027212   
std        0.0      0.055298      0.302740      2.526227      0.162707   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      1.000000      1.000000      0.000000   
50%        0.0      0.000000      1.000000      2.000000      0.000000   
75%        0.0      0.000000      1.000000      4.000000      0.000000   
max        0.0      1.000000      1.000000     18.000000      1.000000   

       https Domain       TinyURL  Prefix/Suffix   Have client    Have admin  \
count  15324.000000  15324.000000   15324.000000  15324.000000  15324.000000   
mean       0.027930      0.034978       0.073871      0.001305      0.010702   
std        0.164778      0.183730       0.261569      0.036104      0.102900   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      0.000000   
50%        0.000000      0.000000       0.000000      0.000000      0.000000   
75%        0.000000      0.000000       0.000000      0.000000      0.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

       ...          .txt           .js          .exe  Num of periods  \
count  ...  15324.000000  15324.000000  15324.000000    15324.000000   
mean   ...      0.003132      0.026429      0.001305        2.598865   
std    ...      0.055881      0.160413      0.036104        1.816973   
min    ...      0.000000      0.000000      0.000000        1.000000   
25%    ...      0.000000      0.000000      0.000000        1.000000   
50%    ...      0.000000      0.000000      0.000000        2.000000   
75%    ...      0.000000      0.000000      0.000000        3.000000   
max    ...      1.000000      1.000000      1.000000       21.000000   

         Is encoded  Num of encoded char  Num of parameters  Num of digits  \
count  15324.000000         15324.000000       15324.000000   15324.000000   
mean       0.211564             5.016445           1.348147      15.870204   
std        0.408430            12.407880           2.519592      16.435665   
min        0.000000             0.000000           0.000000       0.000000   
25%        0.000000             0.000000           0.000000       4.000000   
50%        0.000000             0.000000           0.000000      11.000000   
75%        0.000000             0.000000           2.000000      25.000000   
max        1.000000           201.000000          19.000000     259.000000   

       Num of spec char         Label  
count      15324.000000  15324.000000  
mean          10.220765      1.775907  
std           12.732849      1.471309  
min            0.000000      0.000000  
25%            1.000000      0.000000  
50%            7.000000      2.000000  
75%           13.000000      3.000000  
max          201.000000      4.000000  

[8 rows x 25 columns]

In [10]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                0
Have @                 0
URL Length             0
URL Depth              0
Redirection            0
https Domain           0
TinyURL                0
Prefix/Suffix          0
Have client            0
Have admin             0
Have login             0
Have server            0
.php                   0
.html                  0
.info                  0
.txt                   0
.js                    0
.exe                   0
Num of periods         0
Is encoded             0
Num of encoded char    0
Num of parameters      0
Num of digits          0
Num of spec char       0
Label                  0
dtype: int64

In [11]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          2            0             0        1   
1        0       0           1          2            0             0        0   
2        0       0           1          2            0             0        0   
3        0       0           1          4            0             0        0   
4        0       0           1         10            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               2           0                    0                  0   
1              11           0                    0                  1   
2               4           0                    0                  6   
3               3           0                    0                  0   
4               1           0                    0                  0   

   Num of digits  Num of spec char  Label  
0              0                11      0  
1             31                 1      0  
2             10                11      2  
3             26                11      3  
4             20                 0      0  

[5 rows x 25 columns]

In [12]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [13]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(8428, 24) (6896, 24)
(8428,) (6896,)


In [14]:
output = {}
output['labels'] = y_test

**Random Forest Classifier**

In [15]:
import keras
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  rfc = RandomForestClassifier(n_estimators=50, max_depth=10)
  #compile model using mse as a measure of model performance

  rfc.fit(x_train, y_train)


  y_pred = rfc.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/RFC/model_'+str(n)+'.h5'
  pickle.dump(rfc, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [16]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[253   0   5   1   0]
 [  6  87   8   2   0]
 [  1   0 141   0  12]
 [  5   2  11 185   1]
 [  1   0   4   3 115]]
Precision: 0.9296
Recall: 0.9265
F1 Score: 0.9267
Validation Accuracy: 0.9264531435349941
model 0 saved
[[251   2   4   2   0]
 [  6  95   0   1   3]
 [  3   0 152   0  10]
 [  5   1   6 179   0]
 [  1   0   6   0 116]]
Precision: 0.9418
Recall: 0.9407
F1 Score: 0.9408
Validation Accuracy: 0.9406880189798339
model 1 saved
[[236   3   2   2   1]
 [  2  74   7   4   0]
 [  4   2 154   0  10]
 [  4   1   4 193   0]
 [  1   1   3   0 135]]
Precision: 0.9395
Recall: 0.9395
F1 Score: 0.9393
Validation Accuracy: 0.9395017793594306
model 2 saved
[[282   0   2   2   0]
 [  6  77   4   1   1]
 [  1   2 137   2  14]
 [  8   1   2 180   0]
 [  1   0   2   2 116]]
Precision: 0.9403
Recall: 0.9395
F1 Score: 0.9391
Validation Accuracy: 0.9395017793594306
model 3 saved
[[243   1   3   3   0]
 [  3  69   5   1   1]
 [  2   1 162   3  13]
 [  5   2   2 191   0]
 [  0   0   2   0 131]]
Prec

In [18]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/RFC/model_7.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['rfc_prediction_non'] = [i[0] for i in y_pred_prob];
output['rfc_prediction_phish'] = [i[1] for i in y_pred_prob];
output['rfc_prediction_spam'] = [i[2] for i in y_pred_prob];
output['rfc_prediction_malware'] = [i[3] for i in y_pred_prob];
output['rfc_prediction_defacemen'] = [i[4] for i in y_pred_prob];

output = pd.DataFrame.from_dict(output)
output



[[7.87364872e-01 5.18287072e-02 4.82808594e-02 8.10459247e-02
  3.14796363e-02]
 [9.87364958e-01 8.73814581e-03 7.38339308e-04 2.40254491e-03
  7.56012114e-04]
 [9.87760445e-01 8.34265826e-03 7.38339308e-04 2.40254491e-03
  7.56012114e-04]
 ...
 [7.76125755e-01 9.95155707e-02 2.71152283e-02 2.01746155e-02
  7.70688300e-02]
 [2.21619964e-01 3.84441010e-02 8.09934185e-02 1.80188392e-01
  4.78754124e-01]
 [7.56195286e-02 2.85657788e-01 3.80928862e-01 6.35866930e-02
  1.94207129e-01]]


labels  rfc_prediction_non  rfc_prediction_phish  rfc_prediction_spam  \
0          0            0.787365              0.051829             0.048281   
1          0            0.987365              0.008738             0.000738   
2          0            0.987760              0.008343             0.000738   
3          0            0.958656              0.010700             0.012362   
4          0            0.688658              0.246476             0.032593   
...      ...                 ...                   ...                  ...   
6891       1            0.051053              0.849892             0.072856   
6892       2            0.017013              0.032059             0.807814   
6893       0            0.776126              0.099516             0.027115   
6894       4            0.221620              0.038444             0.080993   
6895       2            0.075620              0.285658             0.380929   

      rfc_prediction_malware  rfc_prediction_defacemen  
0                   0.081046                  0.031480  
1                   0.002403                  0.000756  
2                   0.002403                  0.000756  
3                   0.015703                  0.002579  
4                   0.032273                  0.000000  
...                      ...                       ...  
6891                0.014676                  0.011524  
6892                0.039098                  0.104016  
6893                0.020175                  0.077069  
6894                0.180188                  0.478754  
6895                0.063587                  0.194207  

[6896 rows x 6 columns]

**SVC**

In [ ]:
import keras

import pickle
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics


def model_svc(x_train, x_val, y_train, y_val, opt, n):
  svclassifier = SVC(kernel='rbf', probability= True)
  #compile model using mse as a measure of model performance
  svclassifier.fit(x_train, y_train)

  y_pred = svclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/SVC/model_'+str(n)+'.h5'
  pickle.dump(svclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
# early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_svc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[254   5  13  10   0]
 [ 10  39  24   3   5]
 [  7   6 107  10  31]
 [ 14   7  17 143   8]
 [  4   5   6   2 113]]
Precision: 0.7786
Recall: 0.7782
F1 Score: 0.7757
Validation Accuracy: 0.7781731909845789
model 0 saved
[[265   3  13  10   1]
 [ 12  37  13   1   6]
 [  3   4 129   5  35]
 [ 12  15  20 127  17]
 [ 10   3  11   1  90]]
Precision: 0.7798
Recall: 0.7687
F1 Score: 0.7689
Validation Accuracy: 0.7686832740213523
model 1 saved
[[264   2  13  12   4]
 [  8  48  17   0   1]
 [  4   6 121   0  26]
 [ 12  12  28 133  20]
 [  6   3  14   1  88]]
Precision: 0.7960
Recall: 0.7758
F1 Score: 0.7780
Validation Accuracy: 0.7758007117437722
model 2 saved
[[229   5   9   5   4]
 [ 13  60  12   0   7]
 [  4   4 141   7  11]
 [ 11  14  24 141  16]
 [  2   2   8   2 112]]
Precision: 0.8192
Recall: 0.8102
F1 Score: 0.8089
Validation Accuracy: 0.8102016607354685
model 3 saved
[[252   8  18   4   0]
 [ 14  57  15   0   3]
 [  5   9 118   4  29]
 [  5  12  18 140  10]
 [  7   5  11   0  99]]
Prec

In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/SVC/model_3.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['svc_prediction_non'] = [i[0] for i in y_pred_prob];
output['svc_prediction_phish'] = [i[1] for i in y_pred_prob];
output['svc_prediction_spam'] = [i[2] for i in y_pred_prob];
output['svc_prediction_malware'] = [i[3] for i in y_pred_prob];
output['svc_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[9.49217569e-01 8.55293504e-04 4.08726734e-02 5.47986210e-03
  3.57460170e-03]
 [8.61930054e-01 7.02214796e-02 2.50435292e-02 4.21781415e-02
  6.26795668e-04]
 [8.70795310e-01 6.58764167e-02 2.32992937e-02 3.94649119e-02
  5.64068003e-04]
 ...
 [8.54922712e-01 1.99439552e-02 3.13683976e-02 3.67547882e-02
  5.70101465e-02]
 [5.82464955e-02 1.09128581e-02 7.96081823e-02 3.51443906e-01
  4.99788559e-01]
 [4.40793345e-03 3.77140552e-01 3.20590122e-01 2.91847357e-02
  2.68676656e-01]]


labels  rfc_prediction_non  rfc_prediction_phish  rfc_prediction_spam  \
0          0            0.787365              0.051829             0.048281   
1          0            0.987365              0.008738             0.000738   
2          0            0.987760              0.008343             0.000738   
3          0            0.958656              0.010700             0.012362   
4          0            0.688658              0.246476             0.032593   
...      ...                 ...                   ...                  ...   
6891       1            0.051053              0.849892             0.072856   
6892       2            0.017013              0.032059             0.807814   
6893       0            0.776126              0.099516             0.027115   
6894       4            0.221620              0.038444             0.080993   
6895       2            0.075620              0.285658             0.380929   

      rfc_prediction_malware  rfc_prediction_defacemen  svc_prediction_non  \
0                   0.081046                  0.031480            0.949218   
1                   0.002403                  0.000756            0.861930   
2                   0.002403                  0.000756            0.870795   
3                   0.015703                  0.002579            0.984534   
4                   0.032273                  0.000000            0.760424   
...                      ...                       ...                 ...   
6891                0.014676                  0.011524            0.033051   
6892                0.039098                  0.104016            0.012067   
6893                0.020175                  0.077069            0.854923   
6894                0.180188                  0.478754            0.058246   
6895                0.063587                  0.194207            0.004408   

      svc_prediction_phish  svc_prediction_spam  svc_prediction_malware  \
0                 0.000855             0.040873                0.005480   
1                 0.070221             0.025044                0.042178   
2                 0.065876             0.023299                0.039465   
3                 0.000460             0.003924                0.007816   
4                 0.086305             0.063192                0.087609   
...                    ...                  ...                     ...   
6891              0.877999             0.008323                0.077211   
6892              0.087350             0.700317                0.037563   
6893              0.019944             0.031368                0.036755   
6894              0.010913             0.079608                0.351444   
6895              0.377141             0.320590                0.029185   

      svc_prediction_defacemen  
0                     0.003575  
1                     0.000627  
2                     0.000564  
3                     0.003266  
4                     0.002470  
...                        ...  
6891                  0.003415  
6892                  0.162703  
6893                  0.057010  
6894                  0.499789  
6895                  0.268677  

[6896 rows x 11 columns]

**Logistic Regression**

In [ ]:
import keras

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
import pickle

def model_lr(x_train, x_val, y_train, y_val, opt, n):
  lrclassifier = LogisticRegression()
  #compile model using mse as a measure of model performance
  lrclassifier.fit(x_train, y_train)

  y_pred = lrclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))
  

  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/LR/model_'+str(n)+'.h5'
  pickle.dump(lrclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_lr(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[251   2  16  12   1]
 [ 21  34  14   8   4]
 [ 29   0  93  15  24]
 [ 24   0  18 135  12]
 [  1   0  11   4 114]]
Precision: 0.7525
Recall: 0.7438
F1 Score: 0.7357
Validation Accuracy: 0.7437722419928826
model 0 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[261   1  21   9   0]
 [ 16  28  14   3   8]
 [ 32   3  98  15  28]
 [ 28   3  16 134  10]
 [  5   1  10   1  98]]
Precision: 0.7369
Recall: 0.7343
F1 Score: 0.7262
Validation Accuracy: 0.734282325029656
model 1 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[257   7  20   9   2]
 [ 14  42  10   2   6]
 [ 38   3  92   6  18]
 [ 24   7  27 135  12]
 [  5   3  12   7  85]]
Precision: 0.7303
Recall: 0.7248
F1 Score: 0.7226
Validation Accuracy: 0.7247924080664294
model 2 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[231   3  11   6   1]
 [ 18  51  12   6   5]
 [ 28   1 116  16   6]
 [ 23   1  23 150   9]
 [  1   2  11   4 108]]
Precision: 0.7847
Recall: 0.7782
F1 Score: 0.7747
Validation Accuracy: 0.7781731909845789
model 3 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[236   5  30  10   1]
 [ 23  47   9   8   2]
 [ 26   0 103  11  25]
 [ 13   2  15 147   8]
 [  3   4  11   1 103]]
Precision: 0.7573
Recall: 0.7544
F1 Score: 0.7519
Validation Accuracy: 0.7544483985765125
model 4 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[244   6  18   6   0]
 [ 26  45   6   4   5]
 [ 37   6  95   7  25]
 [ 21   2  18 132  16]
 [  4   5   7   1 107]]
Precision: 0.7438
Recall: 0.7390
F1 Score: 0.7332
Validation Accuracy: 0.7390272835112692
model 5 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[233   5  17  13   1]
 [ 23  39  16   6   9]
 [ 37   1 106  12  21]
 [ 33   0  27 118  15]
 [  4   1   7   3  96]]
Precision: 0.7142
Recall: 0.7023
F1 Score: 0.6939
Validation Accuracy: 0.7022538552787663
model 6 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[250   3  20   7   0]
 [ 21  37  18   3   6]
 [ 33   3  98  17  26]
 [ 36   0  22 125  10]
 [  3   1  11   6  87]]
Precision: 0.7162
Recall: 0.7082
F1 Score: 0.7005
Validation Accuracy: 0.708185053380783
model 7 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[223   2  20  11   0]
 [ 19  49  13   7   3]
 [ 32   7  85  17  26]
 [ 26   3  21 131   3]
 [  2   5  12   3 122]]
Precision: 0.7213
Recall: 0.7245
F1 Score: 0.7187
Validation Accuracy: 0.7244655581947743
model 8 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[233   3  21  13   1]
 [ 27  35  14   2   3]
 [ 27   1 115  11  24]
 [ 31   2  17 127   8]
 [  6   5   8   2 106]]
Precision: 0.7362
Recall: 0.7316
F1 Score: 0.7258
Validation Accuracy: 0.7315914489311164
model 9 saved
Average Validation Accuracy: 0.7340991763946768


In [20]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/LR/model_3.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['lr_prediction_non'] = [i[0] for i in y_pred_prob];
output['lr_prediction_phish'] = [i[1] for i in y_pred_prob];
output['lr_prediction_spam'] = [i[2] for i in y_pred_prob];
output['lr_prediction_malware'] = [i[3] for i in y_pred_prob];
output['lr_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[4.80379775e-01 5.65920233e-03 4.96001272e-01 7.99700603e-03
  9.96274476e-03]
 [7.81591933e-01 8.37217122e-02 6.37656854e-02 7.09171044e-02
  3.56544382e-06]
 [7.71575347e-01 8.95093761e-02 7.05347210e-02 6.83778585e-02
  2.69783122e-06]
 ...
 [7.83562159e-01 3.69834270e-02 1.39089956e-01 9.54407245e-03
  3.08203850e-02]
 [7.44205897e-02 3.68623313e-02 1.55902250e-01 2.37945658e-01
  4.94869171e-01]
 [1.08372950e-01 1.02822848e-01 3.57932181e-01 3.81685385e-02
  3.92703483e-01]]


labels  rfc_prediction_non  rfc_prediction_phish  rfc_prediction_spam  \
0          0            0.787365              0.051829             0.048281   
1          0            0.987365              0.008738             0.000738   
2          0            0.987760              0.008343             0.000738   
3          0            0.958656              0.010700             0.012362   
4          0            0.688658              0.246476             0.032593   
...      ...                 ...                   ...                  ...   
6891       1            0.051053              0.849892             0.072856   
6892       2            0.017013              0.032059             0.807814   
6893       0            0.776126              0.099516             0.027115   
6894       4            0.221620              0.038444             0.080993   
6895       2            0.075620              0.285658             0.380929   

      rfc_prediction_malware  rfc_prediction_defacemen  svc_prediction_non  \
0                   0.081046                  0.031480            0.949218   
1                   0.002403                  0.000756            0.861930   
2                   0.002403                  0.000756            0.870795   
3                   0.015703                  0.002579            0.984534   
4                   0.032273                  0.000000            0.760424   
...                      ...                       ...                 ...   
6891                0.014676                  0.011524            0.033051   
6892                0.039098                  0.104016            0.012067   
6893                0.020175                  0.077069            0.854923   
6894                0.180188                  0.478754            0.058246   
6895                0.063587                  0.194207            0.004408   

      svc_prediction_phish  svc_prediction_spam  svc_prediction_malware  \
0                 0.000855             0.040873                0.005480   
1                 0.070221             0.025044                0.042178   
2                 0.065876             0.023299                0.039465   
3                 0.000460             0.003924                0.007816   
4                 0.086305             0.063192                0.087609   
...                    ...                  ...                     ...   
6891              0.877999             0.008323                0.077211   
6892              0.087350             0.700317                0.037563   
6893              0.019944             0.031368                0.036755   
6894              0.010913             0.079608                0.351444   
6895              0.377141             0.320590                0.029185   

      svc_prediction_defacemen  lr_prediction_non  lr_prediction_phish  \
0                     0.003575           0.480380             0.005659   
1                     0.000627           0.781592             0.083722   
2                     0.000564           0.771575             0.089509   
3                     0.003266           0.878604             0.007249   
4                     0.002470           0.247769             0.686406   
...                        ...                ...                  ...   
6891                  0.003415           0.000901             0.186790   
6892                  0.162703           0.112521             0.064505   
6893                  0.057010           0.783562             0.036983   
6894                  0.499789           0.074421             0.036862   
6895                  0.268677           0.108373             0.102823   

      lr_prediction_spam  lr_prediction_malware  lr_prediction_defacemen  
0               0.496001               0.007997             9.962745e-03  
1               0.063766               0.070917             3.565444e-06  
2               0.070535               0.068378             2.697831e-06  
3               0.065317      

In [21]:
output.shape


(6896, 16)

In [22]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Multi/Base_classifier_result(URL cross)(2).csv', index=False)