In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(multi).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0               0        0       0           1          1            0   
1               1        0       0           1          1            1   
2               2        0       0           1          1            0   
3               3        0       0           1          3            0   
4               4        0       0           1          3            0   
...           ...      ...     ...         ...        ...          ...   
15319       23429        0       0           1          1            0   
15320       23430        0       0           1          1            0   
15321       23431        0       0           1          1            0   
15322       23432        0       0           1          1            0   
15323       23433        0       0           1          1            0   

       https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                 0        0              0            0  ...           0   
1                 0        0              0            0  ...           0   
2                 1        0              0            0  ...           0   
3                 0        0              0            0  ...           0   
4                 0        0              0            0  ...           0   
...             ...      ...            ...          ...  ...         ...   
15319             0        0              0            0  ...           0   
15320             0        0              0            0  ...           0   
15321             0        0              0            0  ...           0   
15322             0        0              0            0  ...           0   
15323             0        0              0            0  ...           0   

       Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0              49        691          42       13135                6400   
1               4         66           3        2034                 818   
2               1        100          27       32987               10451   
3               0          0           1           0                  52   
4             117        219          23        7944                3468   
...           ...        ...         ...         ...                 ...   
15319           0          0           1           0                   4   
15320           0          0           1           0                   4   
15321           0          0           1           0                   4   
15322           0          0           1           0                   4   
15323           0          0           1           0                   4   

       Script To Special Chars Ratio  Script To body Ratio  \
0                           2.052344              0.528869   
1                           2.486553              0.676197   
2                           3.156349              0.836681   
3                           0.000000              0.000000   
4                           2.290657              0.524460   
...                              ...                   ...   
15319                       0.000000              0.000000   
15320                       0.000000              0.000000   
15321                       0.000000              0.000000   
15322                       0.000000              0.000000   
15323                       0.000000              0.000000   

       Body To Special Char Ratio  Label  
0                        0.257690      0  
1                        0.271941      0  
2                        0.265079      0  
3                        0.227074      0  
4                        0.228956      0  
...                           ...    ...  
15319                    0.121212      4  
15320                    0.121212      4  
15321                    0.121212      4  
15322                    0.121212      4  
15323                    0.121212      4  

[15324 rows x 46 c

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char'], axis = 1)

In [6]:
urldata.shape

(15324, 21)

In [7]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15324 entries, 0 to 15323
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   iFrame                         15324 non-null  int64  
 1   Mouse Over                     15324 non-null  int64  
 2   Right Click                    15324 non-null  int64  
 3   Web Forwards                   15324 non-null  int64  
 4   Number of page tokens          15324 non-null  int64  
 5   number of sentences            15324 non-null  int64  
 6   number of html tags            15324 non-null  int64  
 7   number of whitespace           15324 non-null  int64  
 8   url Is Live                    15324 non-null  int64  
 9   HTML Length                    15324 non-null  int64  
 10  Num Objects                    15324 non-null  int64  
 11  Num Embeds                     15324 non-null  int64  
 12  Num Images                     15324 non-null 

In [8]:
urldata.describe()

iFrame    Mouse Over  Right Click  Web Forwards  \
count  15324.000000  15324.000000      15324.0  15324.000000   
mean       0.993148      0.000131          0.0      0.910598   
std        0.082495      0.011424          0.0      0.285333   
min        0.000000      0.000000          0.0      0.000000   
25%        1.000000      0.000000          0.0      1.000000   
50%        1.000000      0.000000          0.0      1.000000   
75%        1.000000      0.000000          0.0      1.000000   
max        1.000000      1.000000          0.0      1.000000   

       Number of page tokens  number of sentences  number of html tags  \
count           15324.000000         15324.000000         15324.000000   
mean             2916.589076          1156.923845           316.643892   
std              5841.863156          2952.857402           644.355934   
min                 1.000000             1.000000             1.000000   
25%                27.000000             7.000000             8.000000   
50%               423.000000            83.000000            42.000000   
75%              3239.000000          1415.000000           416.000000   
max            127712.000000         43777.000000         14280.000000   

       number of whitespace   url Is Live   HTML Length  ...    Num Embeds  \
count               15324.0  15324.000000  1.532400e+04  ...  15324.000000   
mean                    0.0      0.412621  3.038154e+04  ...      0.000261   
std                     0.0      0.499298  8.331941e+04  ...      0.016155   
min                     0.0     -1.000000  0.000000e+00  ...      0.000000   
25%                     0.0      0.000000  7.100000e+01  ...      0.000000   
50%                     0.0      0.000000  2.257000e+03  ...      0.000000   
75%                     0.0      1.000000  3.259600e+04  ...      0.000000   
max                     0.0      1.000000  2.107635e+06  ...      1.000000   

         Num Images     Num Links    Num Titles    Num Script  \
count  15324.000000  15324.000000  15324.000000  1.532400e+04   
mean       9.431480     53.732642      8.138476  1.907060e+04   
std       31.982449    105.014700     30.703307  6.790900e+04   
min        0.000000     -1.000000     -1.000000 -1.000000e+00   
25%        0.000000      0.000000      0.000000  0.000000e+00   
50%        0.000000      2.000000      1.000000  7.770000e+02   
75%        4.000000     66.000000      4.000000  1.592400e+04   
max      816.000000   1740.000000   1042.000000  2.076633e+06   

       Special Characters  Script To Special Chars Ratio  \
count        15324.000000                   15324.000000   
mean          7416.632407                       3.722576   
std          18369.465282                      17.536106   
min              0.000000                      -1.000000   
25%             12.000000                       0.000000   
50%            557.000000                       1.324700   
75%           8311.000000                       2.625806   
max         359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio         Label  
count          15324.000000                15324.000000  15324.000000  
mean               0.367024                    0.192536      1.775907  
std                0.375838                    0.112498      1.471309  
min               -1.000000                    0.000000      0.000000  
25%                0.000000                    0.141286      0.000000  
50%                0.312289                    0.225350      2.000000  
75%                0.718077                    0.263237      3.000000  
max                1.005038                    0.733333      4.000000  

[8 rows x 21 columns]

In [9]:
#checking the data for null or missing values
urldata.isnull().sum()

iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page tokens            0
number of sentences              0
number of html tags              0
number of whitespace             0
url Is Live                      0
HTML Length                      0
Num Objects                      0
Num Embeds                       0
Num Images                       0
Num Links                        0
Num Titles                       0
Num Script                       0
Special Characters               0
Script To Special Chars Ratio    0
Script To body Ratio             0
Body To Special Char Ratio       0
Label                            0
dtype: int64

In [10]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                    501   
1       1           0            0             1                     24   
2       1           0            0             1                   1995   
3       1           0            0             1                    380   
4       1           0            0             1                   3133   

   number of sentences  number of html tags  number of whitespace  \
0                  862                   42                     0   
1                    2                    4                     0   
2                  101                  184                     0   
3                   83                   20                     0   
4                 2697                    1                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1        27093  ...           0           2          0   
1            1            0  ...           0           0          0   
2            1        13234  ...           0           6          2   
3            0         3089  ...           0           0          0   
4            1            0  ...           0           0          0   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0           0       27052                9042                       2.991816   
1           0           0                   0                       0.000000   
2          12           0                2874                       0.000000   
3           1        2369                 972                       2.437243   
4           0           0                   0                       0.000000   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.998487                    0.333739      0  
1              0.000000                    0.000000      4  
2              0.000000                    0.217168      4  
3              0.766915                    0.314665      2  
4              0.000000                    0.000000      3  

[5 rows x 21 columns]

In [11]:
import numpy as np

# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))


print(x.shape, y.shape)


(15324, 20) (15324,)


In [12]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(8428, 20) (6896, 20)
(8428,) (6896,)


In [13]:
output = {}
output['labels'] = y_test

**DecisionTree Classifier**

In [14]:
import keras

from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import pickle
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  dtcclassifier = DecisionTreeClassifier(max_depth=5)
  #compile model using mse as a measure of model performance
  dtcclassifier.fit(x_train, y_train)

  y_pred = dtcclassifier.predict(x_val)
  
  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/DTC/model_'+str(n)+'.h5'
  pickle.dump(dtcclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [15]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[198   0  49   0  30]
 [ 20   3  25   0  33]
 [ 12   1 122   0  30]
 [  9   1  20 142  33]
 [ 17   2  19   0  77]]
Precision: 0.6919
Recall: 0.6429
F1 Score: 0.6352
Validation Accuracy: 0.6429418742586003
model 0 saved
[[201   3   7   2  45]
 [ 20  17   6   0  45]
 [ 30   0  89   2  42]
 [  5   2   0 141  54]
 [ 20   6   5   0 101]]
Precision: 0.7352
Recall: 0.6512
F1 Score: 0.6587
Validation Accuracy: 0.6512455516014235
model 1 saved
[[219   5  12   2  42]
 [ 12   8   5   0  46]
 [ 27   1  87   1  58]
 [  5   4   1 141  44]
 [ 11   6   4   0 102]]
Precision: 0.7358
Recall: 0.6607
F1 Score: 0.6678
Validation Accuracy: 0.66073546856465
model 2 saved
[[227   1  38   0  27]
 [ 21   2  32   1  35]
 [ 11   0 129   0  18]
 [  7   0  21 122  31]
 [ 20   0  22   0  78]]
Precision: 0.7195
Recall: 0.6619
F1 Score: 0.6422
Validation Accuracy: 0.6619217081850534
model 3 saved
[[213   1  27   0  33]
 [ 20   2  30   0  36]
 [ 13   0 135   0  17]
 [  7   0  28 127  33]
 [ 24   0  19   0  78]]
Precis

In [16]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/DTC/model_9.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['dt_prediction_non'] = [i[0] for i in y_pred_prob];
output['dt_prediction_phish'] = [i[1] for i in y_pred_prob];
output['dt_prediction_spam'] = [i[2] for i in y_pred_prob];
output['dt_prediction_malware'] = [i[3] for i in y_pred_prob];
output['dt_prediction_defacemen'] = [i[4] for i in y_pred_prob];

output = pd.DataFrame.from_dict(output)
output


[[0.02277904 0.         0.97722096 0.         0.        ]
 [0.24114833 0.19808612 0.25550239 0.17320574 0.13205742]
 [0.24114833 0.19808612 0.25550239 0.17320574 0.13205742]
 ...
 [0.15522985 0.16722185 0.11125916 0.15656229 0.40972685]
 [0.03448276 0.48275862 0.06896552 0.03448276 0.37931034]
 [0.15522985 0.16722185 0.11125916 0.15656229 0.40972685]]


labels  dt_prediction_non  dt_prediction_phish  dt_prediction_spam  \
0          2           0.022779             0.000000            0.977221   
1          3           0.241148             0.198086            0.255502   
2          1           0.241148             0.198086            0.255502   
3          2           0.155772             0.210014            0.421419   
4          3           0.155230             0.167222            0.111259   
...      ...                ...                  ...                 ...   
6891       1           0.155772             0.210014            0.421419   
6892       0           0.893262             0.030687            0.034690   
6893       1           0.155230             0.167222            0.111259   
6894       0           0.034483             0.482759            0.068966   
6895       4           0.155230             0.167222            0.111259   

      dt_prediction_malware  dt_prediction_defacemen  
0                  0.000000                 0.000000  
1                  0.173206                 0.132057  
2                  0.173206                 0.132057  
3                  0.077886                 0.134910  
4                  0.156562                 0.409727  
...                     ...                      ...  
6891               0.077886                 0.134910  
6892               0.010007                 0.031354  
6893               0.156562                 0.409727  
6894               0.034483                 0.379310  
6895               0.156562                 0.409727  

[6896 rows x 6 columns]

**KNN**

In [17]:
import keras

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_knn(x_train, x_val, y_train, y_val, opt, n):
  knnclassifier = KNeighborsClassifier(n_neighbors=7, weights='uniform', algorithm='kd_tree', leaf_size=5)
  #compile model using mse as a measure of model performance
  knnclassifier.fit(x_train, y_train)

  y_pred = knnclassifier.predict(x_val)
  
  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/KNN/model_'+str(n)+'.h5'
  pickle.dump(knnclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [18]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_knn(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[252   7   6   7   5]
 [ 13  47   5   6  10]
 [  1   7 145   7   5]
 [  3   9   2 188   3]
 [  3   7   0   4 101]]
Precision: 0.8695
Recall: 0.8695
F1 Score: 0.8691
Validation Accuracy: 0.8695136417556346
model 0 saved
[[236   5   4   4   9]
 [ 17  38   7  14  12]
 [  5   3 149   2   4]
 [  3   6   1 186   6]
 [  2   6   1   4 119]]
Precision: 0.8573
Recall: 0.8636
F1 Score: 0.8574
Validation Accuracy: 0.863582443653618
model 1 saved
[[260   1   7   3   9]
 [ 12  44   4   4   7]
 [ 10   3 157   3   1]
 [  5   3   0 184   3]
 [  3   7   0   2 111]]
Precision: 0.8954
Recall: 0.8968
F1 Score: 0.8952
Validation Accuracy: 0.896797153024911
model 2 saved
[[274   7   8   2   2]
 [ 15  48   3  15  10]
 [  2   3 148   4   1]
 [  4   3   2 170   2]
 [  2   5   1   6 106]]
Precision: 0.8804
Recall: 0.8849
F1 Score: 0.8805
Validation Accuracy: 0.8849347568208779
model 3 saved
[[257   7   7   2   1]
 [ 10  41   5  13  19]
 [  6   4 149   4   2]
 [  3   7   0 185   0]
 [  0   9   1   6 105]]
Precis

In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/KNN/model_2.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['knn_prediction_non'] = [i[0] for i in y_pred_prob];
output['knn_prediction_phish'] = [i[1] for i in y_pred_prob];
output['knn_prediction_spam'] = [i[2] for i in y_pred_prob];
output['knn_prediction_malware'] = [i[3] for i in y_pred_prob];
output['knn_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.         0.         1.         0.         0.        ]
 [0.         0.14285714 0.         0.85714286 0.        ]
 [0.         0.14285714 0.         0.85714286 0.        ]
 ...
 [0.28571429 0.42857143 0.         0.         0.28571429]
 [0.14285714 0.         0.         0.14285714 0.71428571]
 [0.         0.         0.         0.         1.        ]]


labels  dt_prediction_non  dt_prediction_phish  dt_prediction_spam  \
0          2           0.022779             0.000000            0.977221   
1          3           0.241148             0.198086            0.255502   
2          1           0.241148             0.198086            0.255502   
3          2           0.155772             0.210014            0.421419   
4          3           0.155230             0.167222            0.111259   
...      ...                ...                  ...                 ...   
6891       1           0.155772             0.210014            0.421419   
6892       0           0.893262             0.030687            0.034690   
6893       1           0.155230             0.167222            0.111259   
6894       0           0.034483             0.482759            0.068966   
6895       4           0.155230             0.167222            0.111259   

      dt_prediction_malware  dt_prediction_defacemen  knn_prediction_non  \
0                  0.000000                 0.000000            0.000000   
1                  0.173206                 0.132057            0.000000   
2                  0.173206                 0.132057            0.000000   
3                  0.077886                 0.134910            0.000000   
4                  0.156562                 0.409727            0.142857   
...                     ...                      ...                 ...   
6891               0.077886                 0.134910            0.000000   
6892               0.010007                 0.031354            1.000000   
6893               0.156562                 0.409727            0.285714   
6894               0.034483                 0.379310            0.142857   
6895               0.156562                 0.409727            0.000000   

      knn_prediction_phish  knn_prediction_spam  knn_prediction_malware  \
0                 0.000000                  1.0                0.000000   
1                 0.142857                  0.0                0.857143   
2                 0.142857                  0.0                0.857143   
3                 0.000000                  1.0                0.000000   
4                 0.285714                  0.0                0.571429   
...                    ...                  ...                     ...   
6891              1.000000                  0.0                0.000000   
6892              0.000000                  0.0                0.000000   
6893              0.428571                  0.0                0.000000   
6894              0.000000                  0.0                0.142857   
6895              0.000000                  0.0                0.000000   

      knn_prediction_defacemen  
0                     0.000000  
1                     0.000000  
2                     0.000000  
3                     0.000000  
4                     0.000000  
...                        ...  
6891                  0.000000  
6892                  0.000000  
6893                  0.285714  
6894                  0.714286  
6895                  1.000000  

[6896 rows x 11 columns]

**XGB Classifier**

In [ ]:
import keras

from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_xgb(x_train, x_val, y_train, y_val, opt, n):
  xgbclassifier = XGBClassifier(n_neighbors=5)
  #compile model using mse as a measure of model performance
  xgbclassifier.fit(x_train, y_train)

  y_pred = xgbclassifier.predict(x_val)
  
  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/XGBoost/model_'+str(n)+'.h5'
  pickle.dump(xgbclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_xgb(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[236   1   4   5  12]
 [ 16  43   1   3  15]
 [  5   1 171   2   6]
 [  5   9   1 182   2]
 [  2   7   2   5 107]]
Precision: 0.8765
Recall: 0.8766
F1 Score: 0.8750
Validation Accuracy: 0.8766310794780545
model 0 saved
[[255   2   3   0  16]
 [ 15  39   3  11  13]
 [  6   0 141   5  10]
 [  5   4   1 173   1]
 [  0  13   1   5 121]]
Precision: 0.8630
Recall: 0.8648
F1 Score: 0.8613
Validation Accuracy: 0.8647686832740213
model 1 saved
[[247   4   4   4   8]
 [ 15  38   2   5  13]
 [  9   4 157   1   4]
 [  6   9   1 189   2]
 [  3   4   3   4 107]]
Precision: 0.8736
Recall: 0.8754
F1 Score: 0.8733
Validation Accuracy: 0.8754448398576512
model 2 saved
[[249   1   7   4   6]
 [ 13  46   4   3  17]
 [ 11   0 155   1   4]
 [  3  16   1 177   8]
 [  7  10   3   0  97]]
Precision: 0.8603
Recall: 0.8588
F1 Score: 0.8581
Validation Accuracy: 0.8588374851720048
model 3 saved
[[258   4   1   0   7]
 [ 18  39   2   2  19]
 [  7   0 152   1   5]
 [  6  12   1 171   7]
 [  3  11   1   1 115]]
Prec

In [20]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/XGBoost/model_6.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['XGB_prediction_non'] = [i[0] for i in y_pred_prob];
output['XGB_prediction_phish'] = [i[1] for i in y_pred_prob];
output['XGB_prediction_spam'] = [i[2] for i in y_pred_prob];
output['XGB_prediction_malware'] = [i[3] for i in y_pred_prob];
output['XGB_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.0296565  0.00304132 0.96195847 0.00360369 0.00174004]
 [0.05149274 0.15141748 0.02522692 0.6971739  0.07468899]
 [0.05149274 0.15141748 0.02522692 0.6971739  0.07468899]
 ...
 [0.13136677 0.4882121  0.0927662  0.08093741 0.20671748]
 [0.273632   0.20691846 0.01990034 0.1361584  0.3633908 ]
 [0.06553915 0.03338118 0.03047783 0.02217826 0.84842366]]


labels  dt_prediction_non  dt_prediction_phish  dt_prediction_spam  \
0          2           0.022779             0.000000            0.977221   
1          3           0.241148             0.198086            0.255502   
2          1           0.241148             0.198086            0.255502   
3          2           0.155772             0.210014            0.421419   
4          3           0.155230             0.167222            0.111259   
...      ...                ...                  ...                 ...   
6891       1           0.155772             0.210014            0.421419   
6892       0           0.893262             0.030687            0.034690   
6893       1           0.155230             0.167222            0.111259   
6894       0           0.034483             0.482759            0.068966   
6895       4           0.155230             0.167222            0.111259   

      dt_prediction_malware  dt_prediction_defacemen  knn_prediction_non  \
0                  0.000000                 0.000000            0.000000   
1                  0.173206                 0.132057            0.000000   
2                  0.173206                 0.132057            0.000000   
3                  0.077886                 0.134910            0.000000   
4                  0.156562                 0.409727            0.142857   
...                     ...                      ...                 ...   
6891               0.077886                 0.134910            0.000000   
6892               0.010007                 0.031354            1.000000   
6893               0.156562                 0.409727            0.285714   
6894               0.034483                 0.379310            0.142857   
6895               0.156562                 0.409727            0.000000   

      knn_prediction_phish  knn_prediction_spam  knn_prediction_malware  \
0                 0.000000                  1.0                0.000000   
1                 0.142857                  0.0                0.857143   
2                 0.142857                  0.0                0.857143   
3                 0.000000                  1.0                0.000000   
4                 0.285714                  0.0                0.571429   
...                    ...                  ...                     ...   
6891              1.000000                  0.0                0.000000   
6892              0.000000                  0.0                0.000000   
6893              0.428571                  0.0                0.000000   
6894              0.000000                  0.0                0.142857   
6895              0.000000                  0.0                0.000000   

      knn_prediction_defacemen  XGB_prediction_non  XGB_prediction_phish  \
0                     0.000000            0.029656              0.003041   
1                     0.000000            0.051493              0.151417   
2                     0.000000            0.051493              0.151417   
3                     0.000000            0.116648              0.061504   
4                     0.000000            0.081969              0.025821   
...                        ...                 ...                   ...   
6891                  0.000000            0.078943              0.510188   
6892                  0.000000            0.949449              0.006096   
6893                  0.285714            0.131367              0.488212   
6894                  0.714286            0.273632              0.206918   
6895                  1.000000            0.065539              0.033381   

      XGB_prediction_spam  XGB_prediction_malware  XGB_prediction_defacemen  
0                0.961958                0.003604                  0.001740  
1                0.025227                0.697174                  0.074689  
2                0.025227                0.697174                  0.074689  
3                0.714449                0.048340     

In [21]:
output.shape


(6896, 16)

In [22]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Multi/Base_classifier_result(HTML cross).csv', index=False)