In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(multi).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0               0        0       0           1          1            0   
1               1        0       0           1          1            1   
2               2        0       0           1          1            0   
3               3        0       0           1          3            0   
4               4        0       0           1          3            0   
...           ...      ...     ...         ...        ...          ...   
15319       23429        0       0           1          1            0   
15320       23430        0       0           1          1            0   
15321       23431        0       0           1          1            0   
15322       23432        0       0           1          1            0   
15323       23433        0       0           1          1            0   

       https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                 0        0              0            0  ...           0   
1                 0        0              0            0  ...           0   
2                 1        0              0            0  ...           0   
3                 0        0              0            0  ...           0   
4                 0        0              0            0  ...           0   
...             ...      ...            ...          ...  ...         ...   
15319             0        0              0            0  ...           0   
15320             0        0              0            0  ...           0   
15321             0        0              0            0  ...           0   
15322             0        0              0            0  ...           0   
15323             0        0              0            0  ...           0   

       Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0              49        691          42       13135                6400   
1               4         66           3        2034                 818   
2               1        100          27       32987               10451   
3               0          0           1           0                  52   
4             117        219          23        7944                3468   
...           ...        ...         ...         ...                 ...   
15319           0          0           1           0                   4   
15320           0          0           1           0                   4   
15321           0          0           1           0                   4   
15322           0          0           1           0                   4   
15323           0          0           1           0                   4   

       Script To Special Chars Ratio  Script To body Ratio  \
0                           2.052344              0.528869   
1                           2.486553              0.676197   
2                           3.156349              0.836681   
3                           0.000000              0.000000   
4                           2.290657              0.524460   
...                              ...                   ...   
15319                       0.000000              0.000000   
15320                       0.000000              0.000000   
15321                       0.000000              0.000000   
15322                       0.000000              0.000000   
15323                       0.000000              0.000000   

       Body To Special Char Ratio  Label  
0                        0.257690      0  
1                        0.271941      0  
2                        0.265079      0  
3                        0.227074      0  
4                        0.228956      0  
...                           ...    ...  
15319                    0.121212      4  
15320                    0.121212      4  
15321                    0.121212      4  
15322                    0.121212      4  
15323                    0.121212      4  

[15324 rows x 46 c

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                  21444   
1       1           0            0             1                   1075   
2       1           0            0             1                   4531   
3       1           0            0             1                     32   
4       1           0            0             1                   4880   

   number of sentences  number of html tags  number of whitespace  \
0                 1853                 3247                     0   
1                  136                  236                     0   
2                 2634                  486                     0   
3                    9                    8                     0   
4                  981                 1412                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1        24836  ...           0          49        691   
1            1         3008  ...           0           4         66   
2            1        39426  ...           0           1        100   
3            0          229  ...           0           0          0   
4            1        15147  ...           0         117        219   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0          42       13135                6400                       2.052344   
1           3        2034                 818                       2.486553   
2          27       32987               10451                       3.156349   
3           1           0                  52                       0.000000   
4          23        7944                3468                       2.290657   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.528869                    0.257690      0  
1              0.676197                    0.271941      0  
2              0.836681                    0.265079      0  
3              0.000000                    0.227074      0  
4              0.524460                    0.228956      0  

[5 rows x 21 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15324 entries, 0 to 15323
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   iFrame                         15324 non-null  int64  
 1   Mouse Over                     15324 non-null  int64  
 2   Right Click                    15324 non-null  int64  
 3   Web Forwards                   15324 non-null  int64  
 4   Number of page tokens          15324 non-null  int64  
 5   number of sentences            15324 non-null  int64  
 6   number of html tags            15324 non-null  int64  
 7   number of whitespace           15324 non-null  int64  
 8   url Is Live                    15324 non-null  int64  
 9   HTML Length                    15324 non-null  int64  
 10  Num Objects                    15324 non-null  int64  
 11  Num Embeds                     15324 non-null  int64  
 12  Num Images                     15324 non-null 

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
2    3002
3    3543
4    2252
dtype: int64

In [8]:

import numpy as np


In [9]:
urldata.describe()

iFrame    Mouse Over  Right Click  Web Forwards  \
count  15324.000000  15324.000000      15324.0  15324.000000   
mean       0.993148      0.000131          0.0      0.910598   
std        0.082495      0.011424          0.0      0.285333   
min        0.000000      0.000000          0.0      0.000000   
25%        1.000000      0.000000          0.0      1.000000   
50%        1.000000      0.000000          0.0      1.000000   
75%        1.000000      0.000000          0.0      1.000000   
max        1.000000      1.000000          0.0      1.000000   

       Number of page tokens  number of sentences  number of html tags  \
count           15324.000000         15324.000000         15324.000000   
mean             2916.589076          1156.923845           316.643892   
std              5841.863156          2952.857402           644.355934   
min                 1.000000             1.000000             1.000000   
25%                27.000000             7.000000             8.000000   
50%               423.000000            83.000000            42.000000   
75%              3239.000000          1415.000000           416.000000   
max            127712.000000         43777.000000         14280.000000   

       number of whitespace   url Is Live   HTML Length  ...    Num Embeds  \
count               15324.0  15324.000000  1.532400e+04  ...  15324.000000   
mean                    0.0      0.412621  3.038154e+04  ...      0.000261   
std                     0.0      0.499298  8.331941e+04  ...      0.016155   
min                     0.0     -1.000000  0.000000e+00  ...      0.000000   
25%                     0.0      0.000000  7.100000e+01  ...      0.000000   
50%                     0.0      0.000000  2.257000e+03  ...      0.000000   
75%                     0.0      1.000000  3.259600e+04  ...      0.000000   
max                     0.0      1.000000  2.107635e+06  ...      1.000000   

         Num Images     Num Links    Num Titles    Num Script  \
count  15324.000000  15324.000000  15324.000000  1.532400e+04   
mean       9.431480     53.732642      8.138476  1.907060e+04   
std       31.982449    105.014700     30.703307  6.790900e+04   
min        0.000000     -1.000000     -1.000000 -1.000000e+00   
25%        0.000000      0.000000      0.000000  0.000000e+00   
50%        0.000000      2.000000      1.000000  7.770000e+02   
75%        4.000000     66.000000      4.000000  1.592400e+04   
max      816.000000   1740.000000   1042.000000  2.076633e+06   

       Special Characters  Script To Special Chars Ratio  \
count        15324.000000                   15324.000000   
mean          7416.632407                       3.722576   
std          18369.465282                      17.536106   
min              0.000000                      -1.000000   
25%             12.000000                       0.000000   
50%            557.000000                       1.324700   
75%           8311.000000                       2.625806   
max         359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio         Label  
count          15324.000000                15324.000000  15324.000000  
mean               0.367024                    0.192536      1.775907  
std                0.375838                    0.112498      1.471309  
min               -1.000000                    0.000000      0.000000  
25%                0.000000                    0.141286      0.000000  
50%                0.312289                    0.225350      2.000000  
75%                0.718077                    0.263237      3.000000  
max                1.005038                    0.733333      4.000000  

[8 rows x 21 columns]

In [10]:
#checking the data for null or missing values
urldata.isnull().sum()

iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page tokens            0
number of sentences              0
number of html tags              0
number of whitespace             0
url Is Live                      0
HTML Length                      0
Num Objects                      0
Num Embeds                       0
Num Images                       0
Num Links                        0
Num Titles                       0
Num Script                       0
Special Characters               0
Script To Special Chars Ratio    0
Script To body Ratio             0
Body To Special Char Ratio       0
Label                            0
dtype: int64

In [11]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                   4621   
1       1           0            0             1                      8   
2       1           0            0             1                    155   
3       1           0            0             1                   1995   
4       1           0            0             1                  15987   

   number of sentences  number of html tags  number of whitespace  \
0                  241                 1234                     0   
1                    2                    3                     0   
2                    4                   16                     0   
3                  101                  184                     0   
4                 2162                 1641                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1        22109  ...           0           1        548   
1            0           56  ...           0           0          0   
2            0          558  ...           0           0          0   
3            1        13234  ...           0           6          2   
4            1        27155  ...           0          54        224   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0           0        2878                4818                       0.597343   
1           1           0                   7                       0.000000   
2           1           0                 119                       0.000000   
3          12           0                2874                       0.000000   
4          71       12440                6484                       1.918569   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.130173                    0.217920      2  
1              0.000000                    0.125000      4  
2              0.000000                    0.213262      1  
3              0.000000                    0.217168      4  
4              0.458111                    0.238777      0  

[5 rows x 21 columns]

In [12]:
import numpy as np
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [13]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(8428, 20) (6896, 20)
(8428,) (6896,)


In [14]:
output = {}
output['labels'] = y_test

**Random Forest Classifier**

In [15]:
import keras
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  rfc = RandomForestClassifier(n_estimators=50, max_depth=10)
  #compile model using mse as a measure of model performance

  rfc.fit(x_train, y_train)


  y_pred = rfc.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/RFC/model_'+str(n)+'.h5'
  pickle.dump(rfc, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [16]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[267   2   1   0   0]
 [ 11  60   0   2   8]
 [  3   5 139   2   2]
 [  4   9   1 197   1]
 [  1   4   2   1 121]]
Precision: 0.9307
Recall: 0.9300
F1 Score: 0.9298
Validation Accuracy: 0.930011862396204
model 0 saved
[[238   5   2   0   5]
 [  6  60   1   1   7]
 [  3   5 163   2   1]
 [  2  12   1 198   7]
 [  2   4   1   1 116]]
Precision: 0.9248
Recall: 0.9193
F1 Score: 0.9210
Validation Accuracy: 0.9193357058125742
model 1 saved
[[278   2   0   1   1]
 [ 13  57   2   9  10]
 [  4   0 162   0   1]
 [  0  15   1 172   0]
 [  1   7   1   3 103]]
Precision: 0.9130
Recall: 0.9158
F1 Score: 0.9139
Validation Accuracy: 0.9157769869513642
model 2 saved
[[274   3   1   2   0]
 [ 10  50   7   5   4]
 [  4   3 148   2   1]
 [  2  14   1 175   0]
 [  0  12   0   3 122]]
Precision: 0.9147
Recall: 0.9122
F1 Score: 0.9130
Validation Accuracy: 0.9122182680901542
model 3 saved
[[253   3   2   0   0]
 [ 15  64   3   2   6]
 [  2   2 166   1   2]
 [  1  12   0 182   2]
 [  3  14   1   0 107]]
Preci

In [17]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/RFC/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['rfc_prediction_non'] = [i[0] for i in y_pred_prob];
output['rfc_prediction_phish'] = [i[1] for i in y_pred_prob];
output['rfc_prediction_spam'] = [i[2] for i in y_pred_prob];
output['rfc_prediction_malware'] = [i[3] for i in y_pred_prob];
output['rfc_prediction_defacemen'] = [i[4] for i in y_pred_prob];

output = pd.DataFrame.from_dict(output)
output



[[4.24847873e-01 1.93576153e-02 2.77523761e-02 4.97839540e-03
  5.23063740e-01]
 [6.74481490e-02 8.98852006e-02 7.22877839e-02 1.10061811e-01
  6.60317055e-01]
 [1.63978773e-01 3.01480284e-01 8.92606208e-02 1.76598448e-01
  2.68681875e-01]
 ...
 [9.85896587e-01 5.95472443e-03 4.63359397e-03 8.88370523e-04
  2.62672415e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00]
 [1.64738762e-01 2.01143486e-01 9.68401810e-02 8.84128889e-02
  4.48864681e-01]]


labels  rfc_prediction_non  rfc_prediction_phish  rfc_prediction_spam  \
0          4            0.424848              0.019358             0.027752   
1          4            0.067448              0.089885             0.072288   
2          2            0.163979              0.301480             0.089261   
3          2            0.066650              0.082535             0.801081   
4          0            0.291278              0.312451             0.100305   
...      ...                 ...                   ...                  ...   
6891       0            0.204102              0.296914             0.088683   
6892       0            0.902812              0.009794             0.077902   
6893       0            0.985897              0.005955             0.004634   
6894       3            0.000000              0.000000             0.000000   
6895       4            0.164739              0.201143             0.096840   

      rfc_prediction_malware  rfc_prediction_defacemen  
0                   0.004978                  0.523064  
1                   0.110062                  0.660317  
2                   0.176598                  0.268682  
3                   0.007228                  0.042506  
4                   0.112899                  0.183068  
...                      ...                       ...  
6891                0.180686                  0.229616  
6892                0.007966                  0.001525  
6893                0.000888                  0.002627  
6894                1.000000                  0.000000  
6895                0.088413                  0.448865  

[6896 rows x 6 columns]

**SVC**

In [ ]:
import keras

import pickle
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics


def model_svc(x_train, x_val, y_train, y_val, opt, n):
  svclassifier = SVC(kernel='rbf', probability= True)
  #compile model using mse as a measure of model performance
  svclassifier.fit(x_train, y_train)

  y_pred = svclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/SVC/model_'+str(n)+'.h5'
  pickle.dump(svclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
# early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_svc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[178   0  15  74   4]
 [  8   0   1  78   9]
 [ 21   0  37  96  16]
 [ 14   0   1 166   3]
 [ 22   0   0  85  15]]
Precision: 0.4925
Recall: 0.4698
F1 Score: 0.4211
Validation Accuracy: 0.4697508896797153


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 0 saved
[[189   0   9  68   6]
 [ 12   0   2  70   4]
 [ 24   0  42  86  16]
 [ 12   0   1 165   6]
 [ 16   0   0  90  25]]
Precision: 0.5394
Recall: 0.4994
F1 Score: 0.4577
Validation Accuracy: 0.49940688018979834


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 1 saved
[[163   0  14  79   9]
 [ 12   0   0  75   2]
 [ 23   0  46  91  17]
 [  8   0   1 175   4]
 [ 18   0   0  88  18]]
Precision: 0.5169
Recall: 0.4769
F1 Score: 0.4333
Validation Accuracy: 0.47686832740213525


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 2 saved
[[172   0  13  76   5]
 [  4   1   0  73   7]
 [ 29   0  37  77   2]
 [ 11   0   1 205   2]
 [ 23   0   0  93  12]]
Precision: 0.6194
Recall: 0.5065
F1 Score: 0.4489
Validation Accuracy: 0.5065243179122183
model 3 saved
[[178   0  16  78   8]
 [ 10   0   1  57   4]
 [ 20   0  51  76  12]
 [ 12   0   2 187   2]
 [ 17   0   0  85  27]]
Precision: 0.5581
Recall: 0.5255
F1 Score: 0.4894
Validation Accuracy: 0.5255041518386714


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 4 saved
[[184   0  18  80   8]
 [  9   0   1  75   7]
 [ 13   0  39  78  10]
 [  2   0   4 187   3]
 [ 16   0   4  88  17]]
Precision: 0.5223
Recall: 0.5065
F1 Score: 0.4624
Validation Accuracy: 0.5065243179122183


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 5 saved
[[168   0  11  69   3]
 [  7   1   1  73   6]
 [ 18   0  50 101  11]
 [  8   0   2 184   0]
 [ 26   0   0  87  17]]
Precision: 0.6448
Recall: 0.4982
F1 Score: 0.4502
Validation Accuracy: 0.498220640569395
model 6 saved
[[170   0  14  77   9]
 [ 10   0   0  61   5]
 [ 20   0  50  90  17]
 [  6   0   1 191   2]
 [ 21   0   0  79  20]]
Precision: 0.5461
Recall: 0.5113
F1 Score: 0.4686
Validation Accuracy: 0.5112692763938316


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 7 saved
[[181   0  15  82   6]
 [  9   0   1  62   4]
 [ 17   0  54  88  16]
 [ 13   0   0 161   2]
 [ 24   0   0  87  20]]
Precision: 0.5455
Recall: 0.4941
F1 Score: 0.4602
Validation Accuracy: 0.49406175771971494


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 8 saved
[[191   0   6  67   8]
 [ 14   0   0  65  10]
 [ 21   0  50  89   9]
 [  1   0   0 178   3]
 [ 18   0   0  92  20]]
Precision: 0.5712
Recall: 0.5214
F1 Score: 0.4765
Validation Accuracy: 0.5213776722090261


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 9 saved
Average Validation Accuracy: 0.5009508231826725


In [18]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/SVC/model_4.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['svc_prediction_non'] = [i[0] for i in y_pred_prob];
output['svc_prediction_phish'] = [i[1] for i in y_pred_prob];
output['svc_prediction_spam'] = [i[2] for i in y_pred_prob];
output['svc_prediction_malware'] = [i[3] for i in y_pred_prob];
output['svc_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.62893342 0.05906903 0.19966856 0.03278498 0.07954401]
 [0.1363203  0.1233526  0.19998996 0.34084318 0.19949396]
 [0.11851908 0.124519   0.1943067  0.38023113 0.18242409]
 ...
 [0.77809064 0.13558305 0.00979911 0.04189823 0.03462898]
 [0.11705761 0.12403447 0.19383006 0.38455165 0.18052622]
 [0.12211226 0.12518591 0.19552471 0.37050751 0.1866696 ]]


labels  rfc_prediction_non  rfc_prediction_phish  rfc_prediction_spam  \
0          4            0.424848              0.019358             0.027752   
1          4            0.067448              0.089885             0.072288   
2          2            0.163979              0.301480             0.089261   
3          2            0.066650              0.082535             0.801081   
4          0            0.291278              0.312451             0.100305   
...      ...                 ...                   ...                  ...   
6891       0            0.204102              0.296914             0.088683   
6892       0            0.902812              0.009794             0.077902   
6893       0            0.985897              0.005955             0.004634   
6894       3            0.000000              0.000000             0.000000   
6895       4            0.164739              0.201143             0.096840   

      rfc_prediction_malware  rfc_prediction_defacemen  svc_prediction_non  \
0                   0.004978                  0.523064            0.628933   
1                   0.110062                  0.660317            0.136320   
2                   0.176598                  0.268682            0.118519   
3                   0.007228                  0.042506            0.203928   
4                   0.112899                  0.183068            0.118799   
...                      ...                       ...                 ...   
6891                0.180686                  0.229616            0.118433   
6892                0.007966                  0.001525            0.794144   
6893                0.000888                  0.002627            0.778091   
6894                1.000000                  0.000000            0.117058   
6895                0.088413                  0.448865            0.122112   

      svc_prediction_phish  svc_prediction_spam  svc_prediction_malware  \
0                 0.059069             0.199669                0.032785   
1                 0.123353             0.199990                0.340843   
2                 0.124519             0.194307                0.380231   
3                 0.114154             0.240610                0.250098   
4                 0.124598             0.194398                0.379418   
...                    ...                  ...                     ...   
6891              0.124478             0.194294                0.380496   
6892              0.035800             0.163693                0.002279   
6893              0.135583             0.009799                0.041898   
6894              0.124034             0.193830                0.384552   
6895              0.125186             0.195525                0.370508   

      svc_prediction_defacemen  
0                     0.079544  
1                     0.199494  
2                     0.182424  
3                     0.191210  
4                     0.182787  
...                        ...  
6891                  0.182298  
6892                  0.004084  
6893                  0.034629  
6894                  0.180526  
6895                  0.186670  

[6896 rows x 11 columns]

**Logistic Regression**

In [ ]:
import keras

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
import pickle

def model_lr(x_train, x_val, y_train, y_val, opt, n):
  lrclassifier = LogisticRegression()
  #compile model using mse as a measure of model performance
  lrclassifier.fit(x_train, y_train)

  y_pred = lrclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))
  

  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/LR/model_'+str(n)+'.h5'
  pickle.dump(lrclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_lr(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[245   0  26   0   0]
 [ 80   0  16   0   0]
 [107   0  63   0   0]
 [170   0  14   0   0]
 [107   0  15   0   0]]
Precision: 0.2059
Recall: 0.3654
F1 Score: 0.2443
Validation Accuracy: 0.365361803084223
model 0 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[245   0  27   0   0]
 [ 83   0   5   0   0]
 [102   0  66   0   0]
 [166   0   9   0   9]
 [116   0  14   0   1]]
Precision: 0.2353
Recall: 0.3701
F1 Score: 0.2539
Validation Accuracy: 0.3701067615658363
model 1 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[236   0  26   3   0]
 [ 80   0   9   0   0]
 [ 97   0  80   0   0]
 [160   0  15   0  13]
 [106   0  18   0   0]]
Precision: 0.2228
Recall: 0.3749
F1 Score: 0.2605
Validation Accuracy: 0.3748517200474496
model 2 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[242   0  24   0   0]
 [ 76   0   9   0   0]
 [ 86   0  59   0   0]
 [199   0  20   0   0]
 [106   0  19   3   0]]
Precision: 0.1852
Recall: 0.3571
F1 Score: 0.2302
Validation Accuracy: 0.3570581257413998
model 3 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[256   0  21   3   0]
 [ 65   0   7   0   0]
 [ 99   0  60   0   0]
 [195   0   8   0   0]
 [113   0  14   2   0]]
Precision: 0.2197
Recall: 0.3749
F1 Score: 0.2528
Validation Accuracy: 0.3748517200474496
model 4 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[260   5  25   0   0]
 [ 82   0  10   0   0]
 [ 86   0  54   0   0]
 [180   0  14   0   2]
 [101   0  20   4   0]]
Precision: 0.1991
Recall: 0.3725
F1 Score: 0.2473
Validation Accuracy: 0.37247924080664296
model 5 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[222   0  25   4   0]
 [ 75   0  13   0   0]
 [116   0  64   0   0]
 [181   0   6   0   7]
 [114   0  13   3   0]]
Precision: 0.2063
Recall: 0.3393
F1 Score: 0.2287
Validation Accuracy: 0.33926453143534996
model 6 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[252   0  16   2   0]
 [ 66   0  10   0   0]
 [112   0  65   0   0]
 [189   0   8   0   3]
 [ 96   0  20   4   0]]
Precision: 0.2276
Recall: 0.3760
F1 Score: 0.2561
Validation Accuracy: 0.3760379596678529
model 7 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[260   0  24   0   0]
 [ 70   0   6   0   0]
 [100   0  75   0   0]
 [157   0   9   0  10]
 [110   0  19   2   0]]
Precision: 0.2430
Recall: 0.3979
F1 Score: 0.2800
Validation Accuracy: 0.3978622327790974
model 8 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[248   0  24   0   0]
 [ 71   0  18   0   0]
 [102   0  67   0   0]
 [163   0  13   0   6]
 [112   0  17   1   0]]
Precision: 0.2119
Recall: 0.3741
F1 Score: 0.2528
Validation Accuracy: 0.37410926365795727
model 9 saved
Average Validation Accuracy: 0.37019833588332585


In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/LR/model_8.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['lr_prediction_non'] = [i[0] for i in y_pred_prob];
output['lr_prediction_phish'] = [i[1] for i in y_pred_prob];
output['lr_prediction_spam'] = [i[2] for i in y_pred_prob];
output['lr_prediction_malware'] = [i[3] for i in y_pred_prob];
output['lr_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[5.01856749e-01 6.28199010e-02 2.36334750e-01 4.32567129e-02
  1.55731887e-01]
 [2.26547993e-01 1.78264848e-01 2.18170051e-01 1.73935154e-01
  2.03081954e-01]
 [2.01474090e-01 1.99976362e-01 1.98626645e-01 1.99781331e-01
  2.00141573e-01]
 ...
 [7.42655838e-01 7.44165787e-02 2.76635047e-04 1.37901368e-01
  4.47495808e-02]
 [2.00371532e-01 1.99706501e-01 1.99553095e-01 2.00175393e-01
  2.00193478e-01]
 [2.06003936e-01 1.97783942e-01 1.99798714e-01 1.96150087e-01
  2.00263321e-01]]


labels  rfc_prediction_non  rfc_prediction_phish  rfc_prediction_spam  \
0          4            0.424848              0.019358             0.027752   
1          4            0.067448              0.089885             0.072288   
2          2            0.163979              0.301480             0.089261   
3          2            0.066650              0.082535             0.801081   
4          0            0.291278              0.312451             0.100305   
...      ...                 ...                   ...                  ...   
6891       0            0.204102              0.296914             0.088683   
6892       0            0.902812              0.009794             0.077902   
6893       0            0.985897              0.005955             0.004634   
6894       3            0.000000              0.000000             0.000000   
6895       4            0.164739              0.201143             0.096840   

      rfc_prediction_malware  rfc_prediction_defacemen  svc_prediction_non  \
0                   0.004978                  0.523064            0.628933   
1                   0.110062                  0.660317            0.136320   
2                   0.176598                  0.268682            0.118519   
3                   0.007228                  0.042506            0.203928   
4                   0.112899                  0.183068            0.118799   
...                      ...                       ...                 ...   
6891                0.180686                  0.229616            0.118433   
6892                0.007966                  0.001525            0.794144   
6893                0.000888                  0.002627            0.778091   
6894                1.000000                  0.000000            0.117058   
6895                0.088413                  0.448865            0.122112   

      svc_prediction_phish  svc_prediction_spam  svc_prediction_malware  \
0                 0.059069             0.199669                0.032785   
1                 0.123353             0.199990                0.340843   
2                 0.124519             0.194307                0.380231   
3                 0.114154             0.240610                0.250098   
4                 0.124598             0.194398                0.379418   
...                    ...                  ...                     ...   
6891              0.124478             0.194294                0.380496   
6892              0.035800             0.163693                0.002279   
6893              0.135583             0.009799                0.041898   
6894              0.124034             0.193830                0.384552   
6895              0.125186             0.195525                0.370508   

      svc_prediction_defacemen  lr_prediction_non  lr_prediction_phish  \
0                     0.079544           0.501857             0.062820   
1                     0.199494           0.226548             0.178265   
2                     0.182424           0.201474             0.199976   
3                     0.191210           0.296597             0.142971   
4                     0.182787           0.201935             0.199713   
...                        ...                ...                  ...   
6891                  0.182298           0.201414             0.199868   
6892                  0.004084           0.732579             0.009458   
6893                  0.034629           0.742656             0.074417   
6894                  0.180526           0.200372             0.199707   
6895                  0.186670           0.206004             0.197784   

      lr_prediction_spam  lr_prediction_malware  lr_prediction_defacemen  
0               0.236335               0.043257                 0.155732  
1               0.218170               0.173935                 0.203082  
2               0.198627               0.199781                 0.200142  
3               0.166052      

In [20]:
output.shape


(6896, 16)

In [21]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Multi/Base_classifier_result(HTML cross)(2).csv', index=False)