In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(multi).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0               0        0       0           1          1            0   
1               1        0       0           1          1            1   
2               2        0       0           1          1            0   
3               3        0       0           1          3            0   
4               4        0       0           1          3            0   
...           ...      ...     ...         ...        ...          ...   
15319       23429        0       0           1          1            0   
15320       23430        0       0           1          1            0   
15321       23431        0       0           1          1            0   
15322       23432        0       0           1          1            0   
15323       23433        0       0           1          1            0   

       https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                 0        0              0            0  ...           0   
1                 0        0              0            0  ...           0   
2                 1        0              0            0  ...           0   
3                 0        0              0            0  ...           0   
4                 0        0              0            0  ...           0   
...             ...      ...            ...          ...  ...         ...   
15319             0        0              0            0  ...           0   
15320             0        0              0            0  ...           0   
15321             0        0              0            0  ...           0   
15322             0        0              0            0  ...           0   
15323             0        0              0            0  ...           0   

       Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0              49        691          42       13135                6400   
1               4         66           3        2034                 818   
2               1        100          27       32987               10451   
3               0          0           1           0                  52   
4             117        219          23        7944                3468   
...           ...        ...         ...         ...                 ...   
15319           0          0           1           0                   4   
15320           0          0           1           0                   4   
15321           0          0           1           0                   4   
15322           0          0           1           0                   4   
15323           0          0           1           0                   4   

       Script To Special Chars Ratio  Script To body Ratio  \
0                           2.052344              0.528869   
1                           2.486553              0.676197   
2                           3.156349              0.836681   
3                           0.000000              0.000000   
4                           2.290657              0.524460   
...                              ...                   ...   
15319                       0.000000              0.000000   
15320                       0.000000              0.000000   
15321                       0.000000              0.000000   
15322                       0.000000              0.000000   
15323                       0.000000              0.000000   

       Body To Special Char Ratio  Label  
0                        0.257690      0  
1                        0.271941      0  
2                        0.265079      0  
3                        0.227074      0  
4                        0.228956      0  
...                           ...    ...  
15319                    0.121212      4  
15320                    0.121212      4  
15321                    0.121212      4  
15322                    0.121212      4  
15323                    0.121212      4  

[15324 rows x 46 c

In [ ]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [ ]:
urldata = urldata.drop(['Unnamed: 0', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               1           0                    0                 10   
1               4           1                    2                  3   
2               1           1                    2                  2   
3               4           1                    5                  0   
4               2           0                    0                  1   

   Num of digits  Num of spec char  Label  
0              0                25      0  
1             22                13      0  
2              2                 9      0  
3             19                18      0  
4             17                 7      0  

[5 rows x 25 columns]

In [ ]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15324 entries, 0 to 15323
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Have IP              15324 non-null  int64
 1   Have @               15324 non-null  int64
 2   URL Length           15324 non-null  int64
 3   URL Depth            15324 non-null  int64
 4   Redirection          15324 non-null  int64
 5   https Domain         15324 non-null  int64
 6   TinyURL              15324 non-null  int64
 7   Prefix/Suffix        15324 non-null  int64
 8   Have client          15324 non-null  int64
 9   Have admin           15324 non-null  int64
 10  Have login           15324 non-null  int64
 11  Have server          15324 non-null  int64
 12  .php                 15324 non-null  int64
 13  .html                15324 non-null  int64
 14  .info                15324 non-null  int64
 15  .txt                 15324 non-null  int64
 16  .js                  1

In [ ]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
2    3002
3    3543
4    2252
dtype: int64

In [ ]:

import numpy as np


In [ ]:
urldata.describe()

Have IP        Have @    URL Length     URL Depth   Redirection  \
count  15324.0  15324.000000  15324.000000  15324.000000  15324.000000   
mean       0.0      0.003067      0.897938      3.190029      0.027212   
std        0.0      0.055298      0.302740      2.526227      0.162707   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      1.000000      1.000000      0.000000   
50%        0.0      0.000000      1.000000      2.000000      0.000000   
75%        0.0      0.000000      1.000000      4.000000      0.000000   
max        0.0      1.000000      1.000000     18.000000      1.000000   

       https Domain       TinyURL  Prefix/Suffix   Have client    Have admin  \
count  15324.000000  15324.000000   15324.000000  15324.000000  15324.000000   
mean       0.027930      0.034978       0.073871      0.001305      0.010702   
std        0.164778      0.183730       0.261569      0.036104      0.102900   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      0.000000   
50%        0.000000      0.000000       0.000000      0.000000      0.000000   
75%        0.000000      0.000000       0.000000      0.000000      0.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

       ...          .txt           .js          .exe  Num of periods  \
count  ...  15324.000000  15324.000000  15324.000000    15324.000000   
mean   ...      0.003132      0.026429      0.001305        2.598865   
std    ...      0.055881      0.160413      0.036104        1.816973   
min    ...      0.000000      0.000000      0.000000        1.000000   
25%    ...      0.000000      0.000000      0.000000        1.000000   
50%    ...      0.000000      0.000000      0.000000        2.000000   
75%    ...      0.000000      0.000000      0.000000        3.000000   
max    ...      1.000000      1.000000      1.000000       21.000000   

         Is encoded  Num of encoded char  Num of parameters  Num of digits  \
count  15324.000000         15324.000000       15324.000000   15324.000000   
mean       0.211564             5.016445           1.348147      15.870204   
std        0.408430            12.407880           2.519592      16.435665   
min        0.000000             0.000000           0.000000       0.000000   
25%        0.000000             0.000000           0.000000       4.000000   
50%        0.000000             0.000000           0.000000      11.000000   
75%        0.000000             0.000000           2.000000      25.000000   
max        1.000000           201.000000          19.000000     259.000000   

       Num of spec char         Label  
count      15324.000000  15324.000000  
mean          10.220765      1.775907  
std           12.732849      1.471309  
min            0.000000      0.000000  
25%            1.000000      0.000000  
50%            7.000000      2.000000  
75%           13.000000      3.000000  
max          201.000000      4.000000  

[8 rows x 25 columns]

In [ ]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                0
Have @                 0
URL Length             0
URL Depth              0
Redirection            0
https Domain           0
TinyURL                0
Prefix/Suffix          0
Have client            0
Have admin             0
Have login             0
Have server            0
.php                   0
.html                  0
.info                  0
.txt                   0
.js                    0
.exe                   0
Num of periods         0
Is encoded             0
Num of encoded char    0
Num of parameters      0
Num of digits          0
Num of spec char       0
Label                  0
dtype: int64

In [ ]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          5            0             0        0   
2        0       0           1         10            0             0        0   
3        0       0           0          1            0             0        0   
4        0       0           1          1            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              1            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               4           0                    0                  2   
1               1           0                    0                  0   
2               1           0                    0                  0   
3               3           0                    0                  1   
4               3           0                    0                  4   

   Num of digits  Num of spec char  Label  
0              2                 4      4  
1              8                11      0  
2             18                 0      0  
3              2                 1      4  
4              6                 9      4  

[5 rows x 25 columns]

In [ ]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [ ]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(8428, 24) (6896, 24)
(8428,) (6896,)


In [ ]:
output = {}
output['labels'] = y_test

**MLP**

In [ ]:
import keras

from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle

def model_mlp(x_train, x_val, y_train, y_val, opt, n):
  mlpclassifier = MLPClassifier(alpha=0.0001, hidden_layer_sizes=([100,100,100]))
  #compile model using mse as a measure of model performance
  mlpclassifier.fit(x_train, y_train)

  y_pred = mlpclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/MLP/model_'+str(n)+'.h5'
  pickle.dump(mlpclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_mlp(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[253   1   1   3   2]
 [  2  72   2   1   1]
 [  0   0 166   0   2]
 [  2   2   1 181   0]
 [  3   0   7   1 140]]
Precision: 0.9635
Recall: 0.9632
F1 Score: 0.9631
Validation Accuracy: 0.963226571767497
model 0 saved
[[267   2   1   2   0]
 [  2  77   2   2   0]
 [  0   2 176   0   5]
 [  1   1   0 177   0]
 [  0   0  11   0 115]]
Precision: 0.9635
Recall: 0.9632
F1 Score: 0.9632
Validation Accuracy: 0.963226571767497
model 1 saved
[[244   2   1   0   0]
 [  5  74   2   5   1]
 [  2   2 162   2   2]
 [  4   2   1 218   0]
 [  3   2   4   0 105]]
Precision: 0.9525
Recall: 0.9526
F1 Score: 0.9522
Validation Accuracy: 0.9525504151838672
model 2 saved
[[270   0   0   4   0]
 [  7  69   1   8   2]
 [  1   0 164   0   3]
 [  1   0   1 202   0]
 [  1   0   1   0 108]]
Precision: 0.9655
Recall: 0.9644
F1 Score: 0.9635
Validation Accuracy: 0.9644128113879004
model 3 saved
[[259   0   1   4   1]
 [  3  76   2   1   1]
 [  3   3 156   2   2]
 [  7   1   0 184   1]
 [  3   1   7   0 125]]
Precis

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/MLP/model_5.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['mlp_prediction_non'] = [i[0] for i in y_pred_prob];
output['mlp_prediction_phish'] = [i[1] for i in y_pred_prob];
output['mlp_prediction_spam'] = [i[2] for i in y_pred_prob];
output['mlp_prediction_malware'] = [i[3] for i in y_pred_prob];
output['mlp_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[2.27930408e-01 3.52669068e-07 3.17896223e-09 7.72068989e-01
  2.47127316e-07]
 [9.99849322e-01 4.83915474e-07 1.51218955e-09 1.50192352e-04
  2.28598272e-10]
 [1.28142616e-06 1.73256713e-08 3.98062294e-11 9.99998200e-01
  5.01489322e-07]
 ...
 [9.99685499e-01 1.59853046e-05 1.31639481e-12 2.98512764e-04
  3.36510890e-09]
 [1.66346146e-10 3.93031973e-02 9.60689680e-01 1.14207633e-11
  7.12230582e-06]
 [1.95998885e-04 9.99801785e-01 1.53610390e-11 2.21641900e-06
  3.52212170e-16]]


labels  mlp_prediction_non  mlp_prediction_phish  mlp_prediction_spam  \
0          0        2.279304e-01          3.526691e-07         3.178962e-09   
1          0        9.998493e-01          4.839155e-07         1.512190e-09   
2          3        1.281426e-06          1.732567e-08         3.980623e-11   
3          3        1.273963e-03          6.203745e-08         6.837719e-12   
4          2        7.031173e-09          1.819293e-04         9.998181e-01   
...      ...                 ...                   ...                  ...   
6891       4        1.892153e-12          2.127109e-12         5.182954e-10   
6892       1        1.789397e-04          9.990517e-01         2.676060e-04   
6893       0        9.996855e-01          1.598530e-05         1.316395e-12   
6894       2        1.663461e-10          3.930320e-02         9.606897e-01   
6895       1        1.959989e-04          9.998018e-01         1.536104e-11   

      mlp_prediction_malware  mlp_prediction_defacemen  
0               7.720690e-01              2.471273e-07  
1               1.501924e-04              2.285983e-10  
2               9.999982e-01              5.014893e-07  
3               9.987260e-01              1.322388e-11  
4               7.719379e-15              2.118226e-11  
...                      ...                       ...  
6891            1.837704e-16              1.000000e+00  
6892            5.004229e-04              1.291414e-06  
6893            2.985128e-04              3.365109e-09  
6894            1.142076e-11              7.122306e-06  
6895            2.216419e-06              3.522122e-16  

[6896 rows x 6 columns]

**Neural Network**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_aa(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]
  # print("check point")
  #create model
  model = Sequential()
  model.add(Dense(30, activation='relu', input_shape=(n_cols,)))
  model.add(Dense(10, activation='relu'))

  model.add(Dense(1, activation = 'sigmoid'))
  # softmax
  #compile model using mse as a measure of model performance
  model.compile(optimizer = opt, loss= 'binary_crossentropy', metrics=["accuracy"])

  history = model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/NN/model_'+str(n)+'.h5'
  pickle.dump(model, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_aa(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
238/238 [==============================] - 5s 5ms/step - loss: -4.4652 - accuracy: 0.1173 - val_loss: -19.0647 - val_accuracy: 0.0925
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -103.4408 - accuracy: 0.0997 - val_loss: -261.0423 - val_accuracy: 0.0925
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -578.5837 - accuracy: 0.0997 - val_loss: -1029.1730 - val_accuracy: 0.0925
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -1682.0343 - accuracy: 0.0997 - val_loss: -2508.3130 - val_accuracy: 0.0925
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -3543.9512 - accuracy: 0.0997 - val_loss: -4815.1465 - val_accuracy: 0.0925
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -6271.7061 - accuracy: 0.0997 - val_loss: -8036.0908 - val_accuracy: 0.0925
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: -9966.2920 - accuracy: 0.09

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://41747de8-b420-4e63-a071-c57ebbda306b/assets
model 0 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -193.0406 - accuracy: 0.0989 - val_loss: -574.7985 - val_accuracy: 0.0985
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1304.1869 - accuracy: 0.0990 - val_loss: -2075.7576 - val_accuracy: 0.0985
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -3278.0110 - accuracy: 0.0990 - val_loss: -4355.7109 - val_accuracy: 0.0985
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -6035.8945 - accuracy: 0.0990 - val_loss: -7361.6226 - val_accuracy: 0.0985
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -9532.9248 - accuracy: 0.0990 - val_loss: -11070.1143 - val_accuracy: 0.0985
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -13717.4229 - accuracy: 0.0990 - val_loss: -15339.2207 - val_accuracy: 0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://34f8973a-9393-492b-a966-1b20a4a27f09/assets
model 1 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -240.4154 - accuracy: 0.0990 - val_loss: -893.6364 - val_accuracy: 0.1032
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1771.9454 - accuracy: 0.0985 - val_loss: -3603.7334 - val_accuracy: 0.1032
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -4753.8169 - accuracy: 0.0985 - val_loss: -7933.2681 - val_accuracy: 0.1032
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -8997.1807 - accuracy: 0.0985 - val_loss: -13699.4473 - val_accuracy: 0.1032
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -14415.7588 - accuracy: 0.0985 - val_loss: -20607.0938 - val_accuracy: 0.1032
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -20745.5703 - accuracy: 0.0985 - val_loss: -28777.9590 - val_accuracy:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://d0c865f7-e4be-466f-aa3d-e2e6a3b689d0/assets
model 2 saved
Epoch 1/100
238/238 [==============================] - 1s 4ms/step - loss: -295.3080 - accuracy: 0.1051 - val_loss: -904.8782 - val_accuracy: 0.1032
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -2113.3872 - accuracy: 0.0985 - val_loss: -3457.2847 - val_accuracy: 0.1032
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -5404.1270 - accuracy: 0.0985 - val_loss: -7252.2617 - val_accuracy: 0.1032
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -9900.4893 - accuracy: 0.0985 - val_loss: -12186.4082 - val_accuracy: 0.1032
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -15465.3291 - accuracy: 0.0985 - val_loss: -18136.6289 - val_accuracy: 0.1032
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -22056.6738 - accuracy: 0.0985 - val_loss: -25014.9844 - val_accuracy:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://6a11525c-41e8-4859-bf27-680941ed98aa/assets
model 3 saved
Epoch 1/100
238/238 [==============================] - 1s 4ms/step - loss: -122.2747 - accuracy: 0.1156 - val_loss: -468.2352 - val_accuracy: 0.0985
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1242.9702 - accuracy: 0.0990 - val_loss: -2280.7512 - val_accuracy: 0.0985
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -3479.5615 - accuracy: 0.0990 - val_loss: -5038.5791 - val_accuracy: 0.0985
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -6667.1250 - accuracy: 0.0990 - val_loss: -8778.6104 - val_accuracy: 0.0985
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -10807.2627 - accuracy: 0.0990 - val_loss: -13446.4746 - val_accuracy: 0.0985
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -15810.6084 - accuracy: 0.0990 - val_loss: -18981.9160 - val_accuracy: 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://75fb7e7d-c767-4d60-bf3d-f706ebc3a01f/assets
model 4 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -273.5657 - accuracy: 0.0972 - val_loss: -751.1539 - val_accuracy: 0.1151
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1824.7648 - accuracy: 0.0972 - val_loss: -2727.2483 - val_accuracy: 0.1151
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -4557.8281 - accuracy: 0.0972 - val_loss: -5672.0054 - val_accuracy: 0.1151
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -8294.6152 - accuracy: 0.0972 - val_loss: -9503.1318 - val_accuracy: 0.1151
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -13020.1230 - accuracy: 0.0972 - val_loss: -14215.6699 - val_accuracy: 0.1151
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -18626.0000 - accuracy: 0.0972 - val_loss: -19680.3359 - val_accuracy: 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://543b56fd-095e-48dc-9d9d-78575c743d69/assets
model 5 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -435.0992 - accuracy: 0.1001 - val_loss: -1438.9122 - val_accuracy: 0.0866
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -3213.3572 - accuracy: 0.1003 - val_loss: -5836.2773 - val_accuracy: 0.0866
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -8372.2773 - accuracy: 0.1003 - val_loss: -12424.5742 - val_accuracy: 0.0866
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -15512.1836 - accuracy: 0.1003 - val_loss: -21005.7988 - val_accuracy: 0.0866
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -24433.1055 - accuracy: 0.1003 - val_loss: -31468.7656 - val_accuracy: 0.0866
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -35148.0469 - accuracy: 0.1003 - val_loss: -43794.9180 - val_accura

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://c70e480d-357c-4fa3-b76e-531fe0b8deec/assets
model 6 saved
Epoch 1/100
238/238 [==============================] - 1s 4ms/step - loss: -184.4959 - accuracy: 0.0982 - val_loss: -502.5780 - val_accuracy: 0.0985
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1227.5472 - accuracy: 0.0990 - val_loss: -1935.6318 - val_accuracy: 0.0985
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -3211.8396 - accuracy: 0.0990 - val_loss: -4110.6211 - val_accuracy: 0.0985
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -5890.2285 - accuracy: 0.0990 - val_loss: -6908.7090 - val_accuracy: 0.0985
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -9265.1836 - accuracy: 0.0990 - val_loss: -10276.5684 - val_accuracy: 0.0985
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -13209.9736 - accuracy: 0.0990 - val_loss: -14228.7559 - val_accuracy: 0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://c98f52de-0fd0-4278-9cd5-0df64a380a6d/assets
model 7 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -344.9666 - accuracy: 0.0999 - val_loss: -959.4754 - val_accuracy: 0.0986
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -2323.0769 - accuracy: 0.0990 - val_loss: -3601.6157 - val_accuracy: 0.0986
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -6024.0283 - accuracy: 0.0990 - val_loss: -7703.2466 - val_accuracy: 0.0986
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -11213.2861 - accuracy: 0.0990 - val_loss: -13082.5459 - val_accuracy: 0.0986
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -17753.9844 - accuracy: 0.0990 - val_loss: -19746.4199 - val_accuracy: 0.0986
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -25702.9941 - accuracy: 0.0990 - val_loss: -27681.8047 - val_accuracy

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://d470ffcc-06ac-4e85-9336-fb046a167176/assets
model 8 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -367.0874 - accuracy: 0.1010 - val_loss: -1254.5363 - val_accuracy: 0.0950
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -2785.1350 - accuracy: 0.0994 - val_loss: -5098.6694 - val_accuracy: 0.0950
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -7371.7246 - accuracy: 0.0994 - val_loss: -10942.3633 - val_accuracy: 0.0950
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -13743.2969 - accuracy: 0.0994 - val_loss: -18590.5312 - val_accuracy: 0.0950
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -21728.8906 - accuracy: 0.0994 - val_loss: -27944.7070 - val_accuracy: 0.0950
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -31296.1641 - accuracy: 0.0994 - val_loss: -38996.9727 - val_accura

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://7c2c57f4-d52c-467a-9091-f60f2365db5c/assets
model 9 saved
Average Validation Accuracy: 0.09895534836279209


In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/NN/model_5.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn_prediction_phish'] = [i[1] for i in y_pred_prob];
output['nn_prediction_spam'] = [i[2] for i in y_pred_prob];
output['nn_prediction_malware'] = [i[3] for i in y_pred_prob];
output['nn_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[2.27930408e-01 3.52669068e-07 3.17896223e-09 7.72068989e-01
  2.47127316e-07]
 [9.99849322e-01 4.83915474e-07 1.51218955e-09 1.50192352e-04
  2.28598272e-10]
 [1.28142616e-06 1.73256713e-08 3.98062294e-11 9.99998200e-01
  5.01489322e-07]
 ...
 [9.99685499e-01 1.59853046e-05 1.31639481e-12 2.98512764e-04
  3.36510890e-09]
 [1.66346146e-10 3.93031973e-02 9.60689680e-01 1.14207633e-11
  7.12230582e-06]
 [1.95998885e-04 9.99801785e-01 1.53610390e-11 2.21641900e-06
  3.52212170e-16]]


labels  mlp_prediction_non  mlp_prediction_phish  mlp_prediction_spam  \
0          0        2.279304e-01          3.526691e-07         3.178962e-09   
1          0        9.998493e-01          4.839155e-07         1.512190e-09   
2          3        1.281426e-06          1.732567e-08         3.980623e-11   
3          3        1.273963e-03          6.203745e-08         6.837719e-12   
4          2        7.031173e-09          1.819293e-04         9.998181e-01   
...      ...                 ...                   ...                  ...   
6891       4        1.892153e-12          2.127109e-12         5.182954e-10   
6892       1        1.789397e-04          9.990517e-01         2.676060e-04   
6893       0        9.996855e-01          1.598530e-05         1.316395e-12   
6894       2        1.663461e-10          3.930320e-02         9.606897e-01   
6895       1        1.959989e-04          9.998018e-01         1.536104e-11   

      mlp_prediction_malware  mlp_prediction_defacemen  nn_prediction_non  \
0               7.720690e-01              2.471273e-07       2.279304e-01   
1               1.501924e-04              2.285983e-10       9.998493e-01   
2               9.999982e-01              5.014893e-07       1.281426e-06   
3               9.987260e-01              1.322388e-11       1.273963e-03   
4               7.719379e-15              2.118226e-11       7.031173e-09   
...                      ...                       ...                ...   
6891            1.837704e-16              1.000000e+00       1.892153e-12   
6892            5.004229e-04              1.291414e-06       1.789397e-04   
6893            2.985128e-04              3.365109e-09       9.996855e-01   
6894            1.142076e-11              7.122306e-06       1.663461e-10   
6895            2.216419e-06              3.522122e-16       1.959989e-04   

      nn_prediction_phish  nn_prediction_spam  nn_prediction_malware  \
0            3.526691e-07        3.178962e-09           7.720690e-01   
1            4.839155e-07        1.512190e-09           1.501924e-04   
2            1.732567e-08        3.980623e-11           9.999982e-01   
3            6.203745e-08        6.837719e-12           9.987260e-01   
4            1.819293e-04        9.998181e-01           7.719379e-15   
...                   ...                 ...                    ...   
6891         2.127109e-12        5.182954e-10           1.837704e-16   
6892         9.990517e-01        2.676060e-04           5.004229e-04   
6893         1.598530e-05        1.316395e-12           2.985128e-04   
6894         3.930320e-02        9.606897e-01           1.142076e-11   
6895         9.998018e-01        1.536104e-11           2.216419e-06   

      nn_prediction_defacemen  
0                2.471273e-07  
1                2.285983e-10  
2                5.014893e-07  
3                1.322388e-11  
4                2.118226e-11  
...                       ...  
6891             1.000000e+00  
6892             1.291414e-06  
6893             3.365109e-09  
6894             7.122306e-06  
6895             3.522122e-16  

[6896 rows x 11 columns]

**Neural Network 2**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_a(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]

  #create model
  model_2 = Sequential()
  model_2.add(Dense(30, activation='sigmoid', input_shape=(n_cols,)))
  model_2.add(Dense(25, activation='sigmoid'))
  model_2.add(Dense(20, activation='sigmoid'))
  model_2.add(Dense(15, activation='sigmoid'))
  model_2.add(Dense(10, activation='sigmoid'))
  model_2.add(Dense(1, activation = 'sigmoid'))

  #compile model using mse as a measure of model performance
  model_2.compile(optimizer='adam', loss='mean_squared_error')



  history = model_2.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model_2.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/NN_2/model_'+str(n)+'.h5'
  pickle.dump(model_2, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_a(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
238/238 [==============================] - 3s 8ms/step - loss: 3.1990 - val_loss: 3.2511
Epoch 2/100
238/238 [==============================] - 1s 4ms/step - loss: 2.8989 - val_loss: 3.1250
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8265 - val_loss: 3.0755
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7953 - val_loss: 3.0511
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7788 - val_loss: 3.0369
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7685 - val_loss: 3.0275
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7615 - val_loss: 3.0208
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7565 - val_loss: 3.0163
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7532 - val_loss: 3.0131
Epoch 10/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7508 - val_lo

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://bfd804e1-f176-4874-97dd-3adba7b54f09/assets
model 0 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.7188 - val_loss: 3.1676
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 3.0523 - val_loss: 2.9123
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.9084 - val_loss: 2.8355
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8544 - val_loss: 2.7993
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8270 - val_loss: 2.7788
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8101 - val_loss: 2.7654
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7993 - val_loss: 2.7572
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7925 - val_loss: 2.7518
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7880 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://75a4cebc-b347-46c2-80b9-e74140d6ee51/assets
model 1 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.5570 - val_loss: 3.1001
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.9640 - val_loss: 2.9288
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8736 - val_loss: 2.8709
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8360 - val_loss: 2.8418
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8156 - val_loss: 2.8247
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8030 - val_loss: 2.8136
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7947 - val_loss: 2.8061
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7890 - val_loss: 2.8008
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7848 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://2f20d77c-c34d-4f39-a64a-150a2e6139e3/assets
model 2 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.1134 - val_loss: 2.7589
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8412 - val_loss: 2.7056
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8108 - val_loss: 2.6896
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7993 - val_loss: 2.6821
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7934 - val_loss: 2.6779
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7899 - val_loss: 2.6752
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7875 - val_loss: 2.6733
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7859 - val_loss: 2.6719
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7847 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://ef4f4ea7-52a2-424f-a0f4-e8e6bfb01240/assets
model 3 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.3387 - val_loss: 3.0786
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8815 - val_loss: 2.9705
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8230 - val_loss: 2.9350
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7997 - val_loss: 2.9176
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7872 - val_loss: 2.9074
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7793 - val_loss: 2.9006
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7741 - val_loss: 2.8960
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7704 - val_loss: 2.8926
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7676 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       265
           1       0.10      1.00      0.18        83
           2       0.00      0.00      0.00       166
           3       0.00      0.00      0.00       193
           4       0.00      0.00      0.00       136

    accuracy                           0.10       843
   macro avg       0.02      0.20      0.04       843
weighted avg       0.01      0.10      0.02       843

Accuracy: 0.09845788849347568
[[  0 265   0   0   0]
 [  0  83   0   0   0]
 [  0 166   0   0   0]
 [  0 193   0   0   0]
 [  0 136   0   0   0]]
Precision: 0.0097
Recall: 0.0985
F1 Score: 0.0177
INFO:tensorflow:Assets written to: ram://3504ccca-50aa-4767-86cc-b84cfd53ac0d/assets
model 4 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.5949 - val_loss: 2.9093
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 3.0101 - val_loss: 2.7221
Epoch 3/100
23

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://2134db9e-a098-4e55-8b38-e0eb16e8ed6d/assets
model 5 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.5667 - val_loss: 3.1184
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.9484 - val_loss: 2.9307
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8516 - val_loss: 2.8785
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8177 - val_loss: 2.8552
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8006 - val_loss: 2.8422
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7906 - val_loss: 2.8340
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7841 - val_loss: 2.8286
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7797 - val_loss: 2.8248
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7765 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://7a984d82-14cc-4125-a032-797f9b8c9aa7/assets
model 6 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.1987 - val_loss: 2.9732
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8689 - val_loss: 2.8884
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8177 - val_loss: 2.8605
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7976 - val_loss: 2.8471
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7871 - val_loss: 2.8396
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7807 - val_loss: 2.8347
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7765 - val_loss: 2.8314
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7736 - val_loss: 2.8290
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7715 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       290
           1       0.10      1.00      0.18        83
           2       0.00      0.00      0.00       151
           3       0.00      0.00      0.00       187
           4       0.00      0.00      0.00       132

    accuracy                           0.10       843
   macro avg       0.02      0.20      0.04       843
weighted avg       0.01      0.10      0.02       843

Accuracy: 0.09845788849347568
[[  0 290   0   0   0]
 [  0  83   0   0   0]
 [  0 151   0   0   0]
 [  0 187   0   0   0]
 [  0 132   0   0   0]]
Precision: 0.0097
Recall: 0.0985
F1 Score: 0.0177
INFO:tensorflow:Assets written to: ram://d26c5225-555c-4b8d-922c-d1250308768d/assets
model 7 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.2215 - val_loss: 2.8027
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8482 - val_loss: 2.7378
Epoch 3/100
23

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://98923242-3a9e-4ded-9ea4-6d1d8179b949/assets
model 8 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.4647 - val_loss: 2.9024
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.9100 - val_loss: 2.7840
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8468 - val_loss: 2.7496
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8225 - val_loss: 2.7327
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8094 - val_loss: 2.7227
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8012 - val_loss: 2.7161
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7958 - val_loss: 2.7116
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7918 - val_loss: 2.7083
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7890 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       270
           1       0.10      1.00      0.17        80
           2       0.00      0.00      0.00       178
           3       0.00      0.00      0.00       201
           4       0.00      0.00      0.00       113

    accuracy                           0.10       842
   macro avg       0.02      0.20      0.03       842
weighted avg       0.01      0.10      0.02       842

Accuracy: 0.09501187648456057
[[  0 270   0   0   0]
 [  0  80   0   0   0]
 [  0 178   0   0   0]
 [  0 201   0   0   0]
 [  0 113   0   0   0]]
Precision: 0.0090
Recall: 0.0950
F1 Score: 0.0165
INFO:tensorflow:Assets written to: ram://57d64eac-f327-4272-883e-2edacb900043/assets
model 9 saved
Average Validation Accuracy: 0.09895534836279209


In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/NN_2/model_5.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn2_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn2_prediction_phish'] = [i[1] for i in y_pred_prob];
output['nn2_prediction_spam'] = [i[2] for i in y_pred_prob];
output['nn2_prediction_malware'] = [i[3] for i in y_pred_prob];
output['nn2_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[2.27930408e-01 3.52669068e-07 3.17896223e-09 7.72068989e-01
  2.47127316e-07]
 [9.99849322e-01 4.83915474e-07 1.51218955e-09 1.50192352e-04
  2.28598272e-10]
 [1.28142616e-06 1.73256713e-08 3.98062294e-11 9.99998200e-01
  5.01489322e-07]
 ...
 [9.99685499e-01 1.59853046e-05 1.31639481e-12 2.98512764e-04
  3.36510890e-09]
 [1.66346146e-10 3.93031973e-02 9.60689680e-01 1.14207633e-11
  7.12230582e-06]
 [1.95998885e-04 9.99801785e-01 1.53610390e-11 2.21641900e-06
  3.52212170e-16]]


labels  mlp_prediction_non  mlp_prediction_phish  mlp_prediction_spam  \
0          0        2.279304e-01          3.526691e-07         3.178962e-09   
1          0        9.998493e-01          4.839155e-07         1.512190e-09   
2          3        1.281426e-06          1.732567e-08         3.980623e-11   
3          3        1.273963e-03          6.203745e-08         6.837719e-12   
4          2        7.031173e-09          1.819293e-04         9.998181e-01   
...      ...                 ...                   ...                  ...   
6891       4        1.892153e-12          2.127109e-12         5.182954e-10   
6892       1        1.789397e-04          9.990517e-01         2.676060e-04   
6893       0        9.996855e-01          1.598530e-05         1.316395e-12   
6894       2        1.663461e-10          3.930320e-02         9.606897e-01   
6895       1        1.959989e-04          9.998018e-01         1.536104e-11   

      mlp_prediction_malware  mlp_prediction_defacemen  nn_prediction_non  \
0               7.720690e-01              2.471273e-07       2.279304e-01   
1               1.501924e-04              2.285983e-10       9.998493e-01   
2               9.999982e-01              5.014893e-07       1.281426e-06   
3               9.987260e-01              1.322388e-11       1.273963e-03   
4               7.719379e-15              2.118226e-11       7.031173e-09   
...                      ...                       ...                ...   
6891            1.837704e-16              1.000000e+00       1.892153e-12   
6892            5.004229e-04              1.291414e-06       1.789397e-04   
6893            2.985128e-04              3.365109e-09       9.996855e-01   
6894            1.142076e-11              7.122306e-06       1.663461e-10   
6895            2.216419e-06              3.522122e-16       1.959989e-04   

      nn_prediction_phish  nn_prediction_spam  nn_prediction_malware  \
0            3.526691e-07        3.178962e-09           7.720690e-01   
1            4.839155e-07        1.512190e-09           1.501924e-04   
2            1.732567e-08        3.980623e-11           9.999982e-01   
3            6.203745e-08        6.837719e-12           9.987260e-01   
4            1.819293e-04        9.998181e-01           7.719379e-15   
...                   ...                 ...                    ...   
6891         2.127109e-12        5.182954e-10           1.837704e-16   
6892         9.990517e-01        2.676060e-04           5.004229e-04   
6893         1.598530e-05        1.316395e-12           2.985128e-04   
6894         3.930320e-02        9.606897e-01           1.142076e-11   
6895         9.998018e-01        1.536104e-11           2.216419e-06   

      nn_prediction_defacemen  nn2_prediction_non  nn2_prediction_phish  \
0                2.471273e-07        2.279304e-01          3.526691e-07   
1                2.285983e-10        9.998493e-01          4.839155e-07   
2                5.014893e-07        1.281426e-06          1.732567e-08   
3                1.322388e-11        1.273963e-03          6.203745e-08   
4                2.118226e-11        7.031173e-09          1.819293e-04   
...                       ...                 ...                   ...   
6891             1.000000e+00        1.892153e-12          2.127109e-12   
6892             1.291414e-06        1.789397e-04          9.990517e-01   
6893             3.365109e-09        9.996855e-01          1.598530e-05   
6894             7.122306e-06        1.663461e-10          3.930320e-02   
6895             3.522122e-16        1.959989e-04          9.998018e-01   

      nn2_prediction_spam  nn2_prediction_malware  nn2_prediction_defacemen  
0            3.178962e-09            7.720690e-01              2.471273e-07  
1            1.512190e-09            1.501924e-04              2.285983e-10  
2            3.980623e-11            9.999982e-01              5.014893e-07  
3            6.837719e-12            9.987260e-01     

In [ ]:
output.shape


In [ ]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Multi/Base_classifier_result(URL cross)(3).csv', index=False)