In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(multi).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0               0        0       0           1          1            0   
1               1        0       0           1          1            1   
2               2        0       0           1          1            0   
3               3        0       0           1          3            0   
4               4        0       0           1          3            0   
...           ...      ...     ...         ...        ...          ...   
15319       23429        0       0           1          1            0   
15320       23430        0       0           1          1            0   
15321       23431        0       0           1          1            0   
15322       23432        0       0           1          1            0   
15323       23433        0       0           1          1            0   

       https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                 0        0              0            0  ...           0   
1                 0        0              0            0  ...           0   
2                 1        0              0            0  ...           0   
3                 0        0              0            0  ...           0   
4                 0        0              0            0  ...           0   
...             ...      ...            ...          ...  ...         ...   
15319             0        0              0            0  ...           0   
15320             0        0              0            0  ...           0   
15321             0        0              0            0  ...           0   
15322             0        0              0            0  ...           0   
15323             0        0              0            0  ...           0   

       Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0              49        691          42       13135                6400   
1               4         66           3        2034                 818   
2               1        100          27       32987               10451   
3               0          0           1           0                  52   
4             117        219          23        7944                3468   
...           ...        ...         ...         ...                 ...   
15319           0          0           1           0                   4   
15320           0          0           1           0                   4   
15321           0          0           1           0                   4   
15322           0          0           1           0                   4   
15323           0          0           1           0                   4   

       Script To Special Chars Ratio  Script To body Ratio  \
0                           2.052344              0.528869   
1                           2.486553              0.676197   
2                           3.156349              0.836681   
3                           0.000000              0.000000   
4                           2.290657              0.524460   
...                              ...                   ...   
15319                       0.000000              0.000000   
15320                       0.000000              0.000000   
15321                       0.000000              0.000000   
15322                       0.000000              0.000000   
15323                       0.000000              0.000000   

       Body To Special Char Ratio  Label  
0                        0.257690      0  
1                        0.271941      0  
2                        0.265079      0  
3                        0.227074      0  
4                        0.228956      0  
...                           ...    ...  
15319                    0.121212      4  
15320                    0.121212      4  
15321                    0.121212      4  
15322                    0.121212      4  
15323                    0.121212      4  

[15324 rows x 46 c

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0'], axis = 1)

In [6]:
urldata.shape

(15324, 45)

In [7]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15324 entries, 0 to 15323
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Have IP                        15324 non-null  int64  
 1   Have @                         15324 non-null  int64  
 2   URL Length                     15324 non-null  int64  
 3   URL Depth                      15324 non-null  int64  
 4   Redirection                    15324 non-null  int64  
 5   https Domain                   15324 non-null  int64  
 6   TinyURL                        15324 non-null  int64  
 7   Prefix/Suffix                  15324 non-null  int64  
 8   Have client                    15324 non-null  int64  
 9   Have admin                     15324 non-null  int64  
 10  Have login                     15324 non-null  int64  
 11  Have server                    15324 non-null  int64  
 12  .php                           15324 non-null 

In [8]:
urldata.describe()

Have IP        Have @    URL Length     URL Depth   Redirection  \
count  15324.0  15324.000000  15324.000000  15324.000000  15324.000000   
mean       0.0      0.003067      0.897938      3.190029      0.027212   
std        0.0      0.055298      0.302740      2.526227      0.162707   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      1.000000      1.000000      0.000000   
50%        0.0      0.000000      1.000000      2.000000      0.000000   
75%        0.0      0.000000      1.000000      4.000000      0.000000   
max        0.0      1.000000      1.000000     18.000000      1.000000   

       https Domain       TinyURL  Prefix/Suffix   Have client    Have admin  \
count  15324.000000  15324.000000   15324.000000  15324.000000  15324.000000   
mean       0.027930      0.034978       0.073871      0.001305      0.010702   
std        0.164778      0.183730       0.261569      0.036104      0.102900   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      0.000000   
50%        0.000000      0.000000       0.000000      0.000000      0.000000   
75%        0.000000      0.000000       0.000000      0.000000      0.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

       ...    Num Embeds    Num Images     Num Links    Num Titles  \
count  ...  15324.000000  15324.000000  15324.000000  15324.000000   
mean   ...      0.000261      9.431480     53.732642      8.138476   
std    ...      0.016155     31.982449    105.014700     30.703307   
min    ...      0.000000      0.000000     -1.000000     -1.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      2.000000      1.000000   
75%    ...      0.000000      4.000000     66.000000      4.000000   
max    ...      1.000000    816.000000   1740.000000   1042.000000   

         Num Script  Special Characters  Script To Special Chars Ratio  \
count  1.532400e+04        15324.000000                   15324.000000   
mean   1.907060e+04         7416.632407                       3.722576   
std    6.790900e+04        18369.465282                      17.536106   
min   -1.000000e+00            0.000000                      -1.000000   
25%    0.000000e+00           12.000000                       0.000000   
50%    7.770000e+02          557.000000                       1.324700   
75%    1.592400e+04         8311.000000                       2.625806   
max    2.076633e+06       359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio         Label  
count          15324.000000                15324.000000  15324.000000  
mean               0.367024                    0.192536      1.775907  
std                0.375838                    0.112498      1.471309  
min               -1.000000                    0.000000      0.000000  
25%                0.000000                    0.141286      0.000000  
50%                0.312289                    0.225350      2.000000  
75%                0.718077                    0.263237      3.000000  
max                1.005038                    0.733333      4.000000  

[8 rows x 45 columns]

In [9]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                          0
Have @                           0
URL Length                       0
URL Depth                        0
Redirection                      0
https Domain                     0
TinyURL                          0
Prefix/Suffix                    0
Have client                      0
Have admin                       0
Have login                       0
Have server                      0
.php                             0
.html                            0
.info                            0
.txt                             0
.js                              0
.exe                             0
Num of periods                   0
Is encoded                       0
Num of encoded char              0
Num of parameters                0
Num of digits                    0
Num of spec char                 0
iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page token

In [10]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          2            0             0        0   
2        0       0           0          4            0             0        0   
3        0       0           0          4            0             0        0   
4        0       0           0          2            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0           0   
1              0            0           0  ...           0           3   
2              0            0           0  ...           0          35   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0           0   

   Num Links  Num Titles  Num Script  Special Characters  \
0          0           1           0                   4   
1          2           3          58                 177   
2        178          44       68319               23741   
3          0           0           0                   0   
4          0           0          44                  16   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       0.000000              0.000000   
1                       0.327684              0.083214   
2                       2.877680              0.861548   
3                       0.000000              0.000000   
4                       2.750000              0.483516   

   Body To Special Char Ratio  Label  
0                    0.121212      0  
1                    0.253945      3  
2                    0.299390      2  
3                    0.000000      4  
4                    0.175824      4  

[5 rows x 45 columns]

In [11]:
import numpy as np

# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))


print(x.shape, y.shape)


(15324, 44) (15324,)


In [12]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(8428, 44) (6896, 44)
(8428,) (6896,)


In [13]:
output = {}
output['labels'] = y_test

**DecisionTree Classifier**

In [14]:
import keras

from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import pickle
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  dtcclassifier = DecisionTreeClassifier(max_depth=5)
  #compile model using mse as a measure of model performance
  dtcclassifier.fit(x_train, y_train)

  y_pred = dtcclassifier.predict(x_val)
  
  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/DTC/model_'+str(n)+'.h5'
  pickle.dump(dtcclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [15]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[229  10   9  15   0]
 [  2  69  11   3   1]
 [  3   8 133   7   9]
 [ 11  11  13 156  11]
 [  3   8   8   4 109]]
Precision: 0.8329
Recall: 0.8256
F1 Score: 0.8276
Validation Accuracy: 0.8256227758007118
model 0 saved
[[247   6   8  14   2]
 [  3  71  12   2   1]
 [  6   7 128  14  16]
 [  3   7  11 155   8]
 [  0  12  10   2  98]]
Precision: 0.8342
Recall: 0.8292
F1 Score: 0.8309
Validation Accuracy: 0.8291814946619217
model 1 saved
[[265   8   5  11   4]
 [  4  62  13   1  12]
 [  1   1 118  10  13]
 [  5   0  14 165   5]
 [  1   3  12   3 107]]
Precision: 0.8568
Recall: 0.8505
F1 Score: 0.8515
Validation Accuracy: 0.8505338078291815
model 2 saved
[[246   5  15   9   2]
 [  3  45  13   4  10]
 [  4   1 127  11  16]
 [  8   0  11 161   4]
 [  4   3  17   5 119]]
Precision: 0.8334
Recall: 0.8280
F1 Score: 0.8281
Validation Accuracy: 0.8279952550415184
model 3 saved
[[235   4   8  11   2]
 [  4  74   9   2   1]
 [  4   6 156   8  11]
 [  9   7   9 153   7]
 [  3   9  17   1  93]]
Prec

In [16]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/DTC/model_2.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['dt_prediction_non'] = [i[0] for i in y_pred_prob];
output['dt_prediction_phish'] = [i[1] for i in y_pred_prob];
output['dt_prediction_spam'] = [i[2] for i in y_pred_prob];
output['dt_prediction_malware'] = [i[3] for i in y_pred_prob];
output['dt_prediction_defacemen'] = [i[4] for i in y_pred_prob];

output = pd.DataFrame.from_dict(output)
output


[[0.05407587 0.062954   0.79176755 0.04923325 0.04196933]
 [0.19602273 0.01988636 0.20454545 0.50568182 0.07386364]
 [0.80042017 0.02310924 0.06092437 0.09453782 0.0210084 ]
 ...
 [0.9952381  0.00272109 0.         0.00204082 0.        ]
 [0.05927835 0.07474227 0.71134021 0.06958763 0.08505155]
 [0.01119821 0.07726764 0.09070549 0.05263158 0.76819709]]


labels  dt_prediction_non  dt_prediction_phish  dt_prediction_spam  \
0          2           0.054076             0.062954            0.791768   
1          3           0.196023             0.019886            0.204545   
2          0           0.800420             0.023109            0.060924   
3          1           0.054076             0.062954            0.791768   
4          0           0.995238             0.002721            0.000000   
...      ...                ...                  ...                 ...   
6891       0           0.054076             0.062954            0.791768   
6892       0           0.800420             0.023109            0.060924   
6893       0           0.995238             0.002721            0.000000   
6894       2           0.059278             0.074742            0.711340   
6895       4           0.011198             0.077268            0.090705   

      dt_prediction_malware  dt_prediction_defacemen  
0                  0.049233                 0.041969  
1                  0.505682                 0.073864  
2                  0.094538                 0.021008  
3                  0.049233                 0.041969  
4                  0.002041                 0.000000  
...                     ...                      ...  
6891               0.049233                 0.041969  
6892               0.094538                 0.021008  
6893               0.002041                 0.000000  
6894               0.069588                 0.085052  
6895               0.052632                 0.768197  

[6896 rows x 6 columns]

**KNN**

In [17]:
import keras

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_knn(x_train, x_val, y_train, y_val, opt, n):
  knnclassifier = KNeighborsClassifier(n_neighbors=7, weights='uniform', algorithm='kd_tree', leaf_size=5)
  #compile model using mse as a measure of model performance
  knnclassifier.fit(x_train, y_train)

  y_pred = knnclassifier.predict(x_val)
  
  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/KNN/model_'+str(n)+'.h5'
  pickle.dump(knnclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [18]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_knn(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[250   3   2   1   7]
 [  9  68   3   3   3]
 [  4   1 152   1   2]
 [ 10   2   1 188   1]
 [  1   3   5   1 122]]
Precision: 0.9255
Recall: 0.9253
F1 Score: 0.9249
Validation Accuracy: 0.9252669039145908
model 0 saved
[[248   9   7   5   8]
 [ 10  56   3  11   9]
 [  7   2 160   2   0]
 [  1   1   1 181   0]
 [  1   5   3   1 112]]
Precision: 0.8959
Recall: 0.8980
F1 Score: 0.8957
Validation Accuracy: 0.8979833926453143
model 1 saved
[[275   3   6   4   5]
 [  8  62   4   8  10]
 [  1   6 135   0   1]
 [  4   6   2 177   0]
 [  0   4   0   0 122]]
Precision: 0.9133
Recall: 0.9146
F1 Score: 0.9133
Validation Accuracy: 0.9145907473309609
model 2 saved
[[266   3   3   3   2]
 [ 10  49   6   3   7]
 [  4   3 146   4   2]
 [  3   5   1 175   0]
 [  5   9   0   0 134]]
Precision: 0.9119
Recall: 0.9134
F1 Score: 0.9124
Validation Accuracy: 0.9134045077105575
model 3 saved
[[240   2   4   6   8]
 [  8  61   5  11   5]
 [  2   4 175   1   3]
 [  6   3   2 174   0]
 [  1   0   1   0 121]]
Prec

In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/KNN/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['knn_prediction_non'] = [i[0] for i in y_pred_prob];
output['knn_prediction_phish'] = [i[1] for i in y_pred_prob];
output['knn_prediction_spam'] = [i[2] for i in y_pred_prob];
output['knn_prediction_malware'] = [i[3] for i in y_pred_prob];
output['knn_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.         0.         1.         0.         0.        ]
 [0.         0.         0.         1.         0.        ]
 [0.42857143 0.         0.         0.57142857 0.        ]
 ...
 [1.         0.         0.         0.         0.        ]
 [0.         0.         1.         0.         0.        ]
 [0.         0.         0.         0.         1.        ]]


labels  dt_prediction_non  dt_prediction_phish  dt_prediction_spam  \
0          2           0.054076             0.062954            0.791768   
1          3           0.196023             0.019886            0.204545   
2          0           0.800420             0.023109            0.060924   
3          1           0.054076             0.062954            0.791768   
4          0           0.995238             0.002721            0.000000   
...      ...                ...                  ...                 ...   
6891       0           0.054076             0.062954            0.791768   
6892       0           0.800420             0.023109            0.060924   
6893       0           0.995238             0.002721            0.000000   
6894       2           0.059278             0.074742            0.711340   
6895       4           0.011198             0.077268            0.090705   

      dt_prediction_malware  dt_prediction_defacemen  knn_prediction_non  \
0                  0.049233                 0.041969            0.000000   
1                  0.505682                 0.073864            0.000000   
2                  0.094538                 0.021008            0.428571   
3                  0.049233                 0.041969            0.000000   
4                  0.002041                 0.000000            1.000000   
...                     ...                      ...                 ...   
6891               0.049233                 0.041969            1.000000   
6892               0.094538                 0.021008            1.000000   
6893               0.002041                 0.000000            1.000000   
6894               0.069588                 0.085052            0.000000   
6895               0.052632                 0.768197            0.000000   

      knn_prediction_phish  knn_prediction_spam  knn_prediction_malware  \
0                      0.0                  1.0                0.000000   
1                      0.0                  0.0                1.000000   
2                      0.0                  0.0                0.571429   
3                      1.0                  0.0                0.000000   
4                      0.0                  0.0                0.000000   
...                    ...                  ...                     ...   
6891                   0.0                  0.0                0.000000   
6892                   0.0                  0.0                0.000000   
6893                   0.0                  0.0                0.000000   
6894                   0.0                  1.0                0.000000   
6895                   0.0                  0.0                0.000000   

      knn_prediction_defacemen  
0                          0.0  
1                          0.0  
2                          0.0  
3                          0.0  
4                          0.0  
...                        ...  
6891                       0.0  
6892                       0.0  
6893                       0.0  
6894                       0.0  
6895                       1.0  

[6896 rows x 11 columns]

**XGB Classifier**

In [ ]:
import keras

from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_xgb(x_train, x_val, y_train, y_val, opt, n):
  xgbclassifier = XGBClassifier(n_neighbors=5)
  #compile model using mse as a measure of model performance
  xgbclassifier.fit(x_train, y_train)

  y_pred = xgbclassifier.predict(x_val)
  
  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/XGBoost/model_'+str(n)+'.h5'
  pickle.dump(xgbclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_xgb(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[255   2   3   5   0]
 [  4  78   5   0   5]
 [  1   0 165   0   7]
 [  1   2   0 187   0]
 [  1   0   0   0 122]]
Precision: 0.9579
Recall: 0.9573
F1 Score: 0.9570
Validation Accuracy: 0.9572953736654805
model 0 saved
[[279   3   2   3   0]
 [  6  67   3   5   0]
 [  1   1 166   2   8]
 [  3   1   2 172   0]
 [  0   1   0   0 118]]
Precision: 0.9512
Recall: 0.9514
F1 Score: 0.9509
Validation Accuracy: 0.9513641755634639
model 1 saved
[[280   3   3   0   1]
 [  5  74   2   3   1]
 [  2   1 145   1   3]
 [  1   2   2 200   1]
 [  0   0   0   0 113]]
Precision: 0.9631
Recall: 0.9632
F1 Score: 0.9630
Validation Accuracy: 0.963226571767497
model 2 saved
[[276   1   1   1   0]
 [  3  63   4   2   0]
 [  0   2 173   0   5]
 [  6   5   2 176   0]
 [  0   0   0   0 123]]
Precision: 0.9622
Recall: 0.9620
F1 Score: 0.9618
Validation Accuracy: 0.9620403321470937
model 3 saved
[[253   3   7   2   0]
 [  3  76   4   4   1]
 [  1   0 164   0   7]
 [  6   4   1 181   0]
 [  0   0   2   0 124]]
Preci

In [20]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/XGBoost/model_2.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['XGB_prediction_non'] = [i[0] for i in y_pred_prob];
output['XGB_prediction_phish'] = [i[1] for i in y_pred_prob];
output['XGB_prediction_spam'] = [i[2] for i in y_pred_prob];
output['XGB_prediction_malware'] = [i[3] for i in y_pred_prob];
output['XGB_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[2.8639063e-02 2.9477334e-02 9.0892577e-01 8.4830858e-03 2.4474759e-02]
 [1.5240810e-02 5.1868642e-03 9.9877119e-03 9.3193430e-01 3.7650362e-02]
 [4.9987015e-01 6.2963925e-02 1.0872601e-01 3.0790192e-01 2.0537954e-02]
 ...
 [9.9744850e-01 4.7131313e-04 5.7347596e-04 1.2164128e-03 2.9025844e-04]
 [1.6116735e-02 1.2909205e-01 7.7065253e-01 7.8795925e-02 5.3427471e-03]
 [2.4265721e-03 4.3358076e-03 5.3683002e-02 1.7545666e-03 9.3779999e-01]]


labels  dt_prediction_non  dt_prediction_phish  dt_prediction_spam  \
0          2           0.054076             0.062954            0.791768   
1          3           0.196023             0.019886            0.204545   
2          0           0.800420             0.023109            0.060924   
3          1           0.054076             0.062954            0.791768   
4          0           0.995238             0.002721            0.000000   
...      ...                ...                  ...                 ...   
6891       0           0.054076             0.062954            0.791768   
6892       0           0.800420             0.023109            0.060924   
6893       0           0.995238             0.002721            0.000000   
6894       2           0.059278             0.074742            0.711340   
6895       4           0.011198             0.077268            0.090705   

      dt_prediction_malware  dt_prediction_defacemen  knn_prediction_non  \
0                  0.049233                 0.041969            0.000000   
1                  0.505682                 0.073864            0.000000   
2                  0.094538                 0.021008            0.428571   
3                  0.049233                 0.041969            0.000000   
4                  0.002041                 0.000000            1.000000   
...                     ...                      ...                 ...   
6891               0.049233                 0.041969            1.000000   
6892               0.094538                 0.021008            1.000000   
6893               0.002041                 0.000000            1.000000   
6894               0.069588                 0.085052            0.000000   
6895               0.052632                 0.768197            0.000000   

      knn_prediction_phish  knn_prediction_spam  knn_prediction_malware  \
0                      0.0                  1.0                0.000000   
1                      0.0                  0.0                1.000000   
2                      0.0                  0.0                0.571429   
3                      1.0                  0.0                0.000000   
4                      0.0                  0.0                0.000000   
...                    ...                  ...                     ...   
6891                   0.0                  0.0                0.000000   
6892                   0.0                  0.0                0.000000   
6893                   0.0                  0.0                0.000000   
6894                   0.0                  1.0                0.000000   
6895                   0.0                  0.0                0.000000   

      knn_prediction_defacemen  XGB_prediction_non  XGB_prediction_phish  \
0                          0.0            0.028639              0.029477   
1                          0.0            0.015241              0.005187   
2                          0.0            0.499870              0.062964   
3                          0.0            0.004872              0.831235   
4                          0.0            0.990593              0.000672   
...                        ...                 ...                   ...   
6891                       0.0            0.086235              0.109657   
6892                       0.0            0.866194              0.030774   
6893                       0.0            0.997449              0.000471   
6894                       0.0            0.016117              0.129092   
6895                       1.0            0.002427              0.004336   

      XGB_prediction_spam  XGB_prediction_malware  XGB_prediction_defacemen  
0                0.908926                0.008483                  0.024475  
1                0.009988                0.931934                  0.037650  
2                0.108726                0.307902                  0.020538  
3                0.123151                0.023490     

In [21]:
output.shape


(6896, 16)

In [22]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Multi/Base_classifier_result(URL-HTML cross).csv', index=False)