In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(multi).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0               0        0       0           1          1            0   
1               1        0       0           1          1            1   
2               2        0       0           1          1            0   
3               3        0       0           1          3            0   
4               4        0       0           1          3            0   
...           ...      ...     ...         ...        ...          ...   
15319       23429        0       0           1          1            0   
15320       23430        0       0           1          1            0   
15321       23431        0       0           1          1            0   
15322       23432        0       0           1          1            0   
15323       23433        0       0           1          1            0   

       https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                 0        0              0            0  ...           0   
1                 0        0              0            0  ...           0   
2                 1        0              0            0  ...           0   
3                 0        0              0            0  ...           0   
4                 0        0              0            0  ...           0   
...             ...      ...            ...          ...  ...         ...   
15319             0        0              0            0  ...           0   
15320             0        0              0            0  ...           0   
15321             0        0              0            0  ...           0   
15322             0        0              0            0  ...           0   
15323             0        0              0            0  ...           0   

       Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0              49        691          42       13135                6400   
1               4         66           3        2034                 818   
2               1        100          27       32987               10451   
3               0          0           1           0                  52   
4             117        219          23        7944                3468   
...           ...        ...         ...         ...                 ...   
15319           0          0           1           0                   4   
15320           0          0           1           0                   4   
15321           0          0           1           0                   4   
15322           0          0           1           0                   4   
15323           0          0           1           0                   4   

       Script To Special Chars Ratio  Script To body Ratio  \
0                           2.052344              0.528869   
1                           2.486553              0.676197   
2                           3.156349              0.836681   
3                           0.000000              0.000000   
4                           2.290657              0.524460   
...                              ...                   ...   
15319                       0.000000              0.000000   
15320                       0.000000              0.000000   
15321                       0.000000              0.000000   
15322                       0.000000              0.000000   
15323                       0.000000              0.000000   

       Body To Special Char Ratio  Label  
0                        0.257690      0  
1                        0.271941      0  
2                        0.265079      0  
3                        0.227074      0  
4                        0.228956      0  
...                           ...    ...  
15319                    0.121212      4  
15320                    0.121212      4  
15321                    0.121212      4  
15322                    0.121212      4  
15323                    0.121212      4  

[15324 rows x 46 c

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0'], axis = 1).copy()

urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0          49   
1              0            0           0  ...           0           4   
2              0            0           0  ...           0           1   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0         117   

   Num Links  Num Titles  Num Script  Special Characters  \
0        691          42       13135                6400   
1         66           3        2034                 818   
2        100          27       32987               10451   
3          0           1           0                  52   
4        219          23        7944                3468   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.052344              0.528869   
1                       2.486553              0.676197   
2                       3.156349              0.836681   
3                       0.000000              0.000000   
4                       2.290657              0.524460   

   Body To Special Char Ratio  Label  
0                    0.257690      0  
1                    0.271941      0  
2                    0.265079      0  
3                    0.227074      0  
4                    0.228956      0  

[5 rows x 45 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15324 entries, 0 to 15323
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Have IP                        15324 non-null  int64  
 1   Have @                         15324 non-null  int64  
 2   URL Length                     15324 non-null  int64  
 3   URL Depth                      15324 non-null  int64  
 4   Redirection                    15324 non-null  int64  
 5   https Domain                   15324 non-null  int64  
 6   TinyURL                        15324 non-null  int64  
 7   Prefix/Suffix                  15324 non-null  int64  
 8   Have client                    15324 non-null  int64  
 9   Have admin                     15324 non-null  int64  
 10  Have login                     15324 non-null  int64  
 11  Have server                    15324 non-null  int64  
 12  .php                           15324 non-null 

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
2    3002
3    3543
4    2252
dtype: int64

In [8]:

import numpy as np


In [9]:
urldata.describe()

Have IP        Have @    URL Length     URL Depth   Redirection  \
count  15324.0  15324.000000  15324.000000  15324.000000  15324.000000   
mean       0.0      0.003067      0.897938      3.190029      0.027212   
std        0.0      0.055298      0.302740      2.526227      0.162707   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      1.000000      1.000000      0.000000   
50%        0.0      0.000000      1.000000      2.000000      0.000000   
75%        0.0      0.000000      1.000000      4.000000      0.000000   
max        0.0      1.000000      1.000000     18.000000      1.000000   

       https Domain       TinyURL  Prefix/Suffix   Have client    Have admin  \
count  15324.000000  15324.000000   15324.000000  15324.000000  15324.000000   
mean       0.027930      0.034978       0.073871      0.001305      0.010702   
std        0.164778      0.183730       0.261569      0.036104      0.102900   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      0.000000   
50%        0.000000      0.000000       0.000000      0.000000      0.000000   
75%        0.000000      0.000000       0.000000      0.000000      0.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

       ...    Num Embeds    Num Images     Num Links    Num Titles  \
count  ...  15324.000000  15324.000000  15324.000000  15324.000000   
mean   ...      0.000261      9.431480     53.732642      8.138476   
std    ...      0.016155     31.982449    105.014700     30.703307   
min    ...      0.000000      0.000000     -1.000000     -1.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      2.000000      1.000000   
75%    ...      0.000000      4.000000     66.000000      4.000000   
max    ...      1.000000    816.000000   1740.000000   1042.000000   

         Num Script  Special Characters  Script To Special Chars Ratio  \
count  1.532400e+04        15324.000000                   15324.000000   
mean   1.907060e+04         7416.632407                       3.722576   
std    6.790900e+04        18369.465282                      17.536106   
min   -1.000000e+00            0.000000                      -1.000000   
25%    0.000000e+00           12.000000                       0.000000   
50%    7.770000e+02          557.000000                       1.324700   
75%    1.592400e+04         8311.000000                       2.625806   
max    2.076633e+06       359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio         Label  
count          15324.000000                15324.000000  15324.000000  
mean               0.367024                    0.192536      1.775907  
std                0.375838                    0.112498      1.471309  
min               -1.000000                    0.000000      0.000000  
25%                0.000000                    0.141286      0.000000  
50%                0.312289                    0.225350      2.000000  
75%                0.718077                    0.263237      3.000000  
max                1.005038                    0.733333      4.000000  

[8 rows x 45 columns]

In [10]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                          0
Have @                           0
URL Length                       0
URL Depth                        0
Redirection                      0
https Domain                     0
TinyURL                          0
Prefix/Suffix                    0
Have client                      0
Have admin                       0
Have login                       0
Have server                      0
.php                             0
.html                            0
.info                            0
.txt                             0
.js                              0
.exe                             0
Num of periods                   0
Is encoded                       0
Num of encoded char              0
Num of parameters                0
Num of digits                    0
Num of spec char                 0
iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page token

In [11]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          3            0             0        0   
1        0       0           1          1            0             0        0   
2        0       0           1          1            0             0        0   
3        0       0           1          1            0             0        0   
4        0       0           1          5            0             1        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0          73   
1              1            0           0  ...           0           0   
2              0            0           0  ...           0           0   
3              0            0           0  ...           0           7   
4              0            0           0  ...           0          11   

   Num Links  Num Titles  Num Script  Special Characters  \
0         85          73      786069               31245   
1          1           0           0                 102   
2          4           1           0                 557   
3         38           8         231                 694   
4         68          22       37395               15490   

   Script To Special Chars Ratio  Script To body Ratio  \
0                      25.158233              0.976821   
1                       0.000000              0.000000   
2                       0.000000              0.000000   
3                       0.332853              0.065887   
4                       2.414138              0.768180   

   Body To Special Char Ratio  Label  
0                    0.038827      0  
1                    0.196911      4  
2                    0.423252      3  
3                    0.197946      4  
4                    0.318200      0  

[5 rows x 45 columns]

In [12]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [13]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(8428, 44) (6896, 44)
(8428,) (6896,)


In [14]:
output = {}
output['labels'] = y_test

**Random Forest Classifier**

In [15]:
import keras
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  rfc = RandomForestClassifier(n_estimators=50, max_depth=10)
  #compile model using mse as a measure of model performance

  rfc.fit(x_train, y_train)


  y_pred = rfc.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/RFC/model_'+str(n)+'.h5'
  pickle.dump(rfc, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [16]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[290   0   2   0   0]
 [  2  75   1   0   0]
 [  1   1 149   0   9]
 [  2   1   1 197   0]
 [  0   0   0   0 112]]
Precision: 0.9769
Recall: 0.9763
F1 Score: 0.9763
Validation Accuracy: 0.9762752075919335
model 0 saved
[[270   1   1   1   1]
 [  8  86   1   3   0]
 [  1   0 143   2   5]
 [  1   2   1 194   0]
 [  0   1   0   0 121]]
Precision: 0.9657
Recall: 0.9656
F1 Score: 0.9653
Validation Accuracy: 0.9655990510083037
model 1 saved
[[268   0   1   1   0]
 [  3  88   2   0   0]
 [  0   2 146   0   9]
 [  3   2   0 178   0]
 [  1   0   0   0 139]]
Precision: 0.9720
Recall: 0.9715
F1 Score: 0.9715
Validation Accuracy: 0.9715302491103203
model 2 saved
[[264   1   1   1   0]
 [  5 102   3   1   0]
 [  0   1 159   0   1]
 [  1   1   1 178   1]
 [  0   0   0   0 122]]
Precision: 0.9786
Recall: 0.9786
F1 Score: 0.9785
Validation Accuracy: 0.9786476868327402
model 3 saved
[[277   2   5   1   0]
 [  3  73   5   1   2]
 [  1   1 149   0   2]
 [  1   0   1 204   0]
 [  0   0   0   0 115]]
Prec

In [17]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/RFC/model_3.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['rfc_prediction_non'] = [i[0] for i in y_pred_prob];
output['rfc_prediction_phish'] = [i[1] for i in y_pred_prob];
output['rfc_prediction_spam'] = [i[2] for i in y_pred_prob];
output['rfc_prediction_malware'] = [i[3] for i in y_pred_prob];
output['rfc_prediction_defacemen'] = [i[4] for i in y_pred_prob];

output = pd.DataFrame.from_dict(output)
output



[[0.0115082  0.00458088 0.02186724 0.00761127 0.95443242]
 [0.10060813 0.03327511 0.78038588 0.02056861 0.06516226]
 [0.02365904 0.11627192 0.74887065 0.02188739 0.08931101]
 ...
 [0.01078469 0.01311183 0.01848236 0.02258624 0.93503489]
 [0.01899899 0.01661475 0.02357845 0.00748145 0.93332637]
 [0.02635956 0.05127371 0.0956997  0.01263731 0.81402972]]


labels  rfc_prediction_non  rfc_prediction_phish  rfc_prediction_spam  \
0          4            0.011508              0.004581             0.021867   
1          2            0.100608              0.033275             0.780386   
2          2            0.023659              0.116272             0.748871   
3          3            0.123663              0.033559             0.025220   
4          0            0.565631              0.042625             0.131673   
...      ...                 ...                   ...                  ...   
6891       0            0.982044              0.009646             0.004087   
6892       1            0.854260              0.141283             0.001495   
6893       4            0.010785              0.013112             0.018482   
6894       4            0.018999              0.016615             0.023578   
6895       4            0.026360              0.051274             0.095700   

      rfc_prediction_malware  rfc_prediction_defacemen  
0                   0.007611                  0.954432  
1                   0.020569                  0.065162  
2                   0.021887                  0.089311  
3                   0.702551                  0.115007  
4                   0.066562                  0.193508  
...                      ...                       ...  
6891                0.003513                  0.000711  
6892                0.001437                  0.001525  
6893                0.022586                  0.935035  
6894                0.007481                  0.933326  
6895                0.012637                  0.814030  

[6896 rows x 6 columns]

**SVC**

In [ ]:
import keras

import pickle
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics


def model_svc(x_train, x_val, y_train, y_val, opt, n):
  svclassifier = SVC(kernel='rbf', probability= True)
  #compile model using mse as a measure of model performance
  svclassifier.fit(x_train, y_train)

  y_pred = svclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/SVC/model_'+str(n)+'.h5'
  pickle.dump(svclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
# early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_svc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[185   0   9  73  11]
 [  7   1   0  77   6]
 [ 24   0  51  78  10]
 [ 11   0   0 182   2]
 [ 25   0   0  78  13]]
Precision: 0.6433
Recall: 0.5125
F1 Score: 0.4669
Validation Accuracy: 0.5124555160142349
model 0 saved
[[176   0  10  67   5]
 [ 11   0   0  74   7]
 [ 27   0  41  93   3]
 [  6   0   0 182   1]
 [ 26   0   0  90  24]]
Precision: 0.5556
Recall: 0.5018
F1 Score: 0.4497
Validation Accuracy: 0.501779359430605


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 1 saved
[[196   0  15  84   6]
 [ 11   0   0  61   9]
 [ 20   0  42  73  14]
 [ 14   0   0 192   4]
 [ 15   0   0  70  17]]
Precision: 0.5444
Recall: 0.5302
F1 Score: 0.4891
Validation Accuracy: 0.5302491103202847


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 2 saved
[[184   0  13  76   5]
 [ 11   1   0  63   5]
 [ 13   0  60  91  17]
 [  7   0   1 178   6]
 [ 20   0   0  73  19]]
Precision: 0.6600
Recall: 0.5243
F1 Score: 0.4912
Validation Accuracy: 0.5243179122182681
model 3 saved
[[197   0  14  72   6]
 [ 12   0   1  68   4]
 [ 30   0  39  96   0]
 [  6   0   1 165   0]
 [ 19   0   0  94  19]]
Precision: 0.5652
Recall: 0.4982
F1 Score: 0.4516
Validation Accuracy: 0.498220640569395


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 4 saved
[[176   0  15  76  10]
 [ 15   0   0  70  10]
 [ 24   0  44  77   3]
 [ 10   0   0 184   4]
 [ 22   0   0  86  17]]
Precision: 0.5100
Recall: 0.4994
F1 Score: 0.4503
Validation Accuracy: 0.49940688018979834


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 5 saved
[[170   0  14  76   4]
 [  3   0   0  68   7]
 [ 39   0  50  80   5]
 [  3   0   2 192   7]
 [ 18   0   0  82  23]]
Precision: 0.5511
Recall: 0.5160
F1 Score: 0.4723
Validation Accuracy: 0.5160142348754448


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 6 saved
[[158   0  13  68  11]
 [ 13   0   1  80   4]
 [ 22   0  47  91  13]
 [  3   0   1 179   7]
 [ 20   0   0  91  21]]
Precision: 0.5105
Recall: 0.4804
F1 Score: 0.4336
Validation Accuracy: 0.4804270462633452


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 7 saved
[[186   0   9  72   8]
 [ 13   0   0  72  11]
 [ 37   0  43  76   1]
 [ 11   0   1 173   3]
 [ 24   0   0  81  21]]
Precision: 0.5284
Recall: 0.5024
F1 Score: 0.4526
Validation Accuracy: 0.502375296912114


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 8 saved
[[195   0  12  75  11]
 [ 10   0   0  60   5]
 [ 17   0  54  79  15]
 [ 10   0   2 184   2]
 [ 26   0   0  76   9]]
Precision: 0.5382
Recall: 0.5249
F1 Score: 0.4814
Validation Accuracy: 0.5249406175771971


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 9 saved
Average Validation Accuracy: 0.5090186614370688


In [18]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/SVC/model_2.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['svc_prediction_non'] = [i[0] for i in y_pred_prob];
output['svc_prediction_phish'] = [i[1] for i in y_pred_prob];
output['svc_prediction_spam'] = [i[2] for i in y_pred_prob];
output['svc_prediction_malware'] = [i[3] for i in y_pred_prob];
output['svc_prediction_defacemen'] = [i[4] for i in y_pred_prob];

output = pd.DataFrame.from_dict(output)
output


[[0.50405412 0.03965045 0.04575095 0.04936516 0.36117933]
 [0.42227774 0.07910739 0.29704682 0.10679766 0.09477039]
 [0.13194988 0.12723938 0.20902003 0.36177662 0.17001409]
 ...
 [0.11428662 0.13034901 0.19095849 0.39133215 0.17307374]
 [0.33197691 0.11590441 0.27307509 0.13984187 0.13920172]
 [0.38786741 0.13422341 0.18498071 0.0933418  0.19958666]]


labels  rfc_prediction_non  rfc_prediction_phish  rfc_prediction_spam  \
0          4            0.011508              0.004581             0.021867   
1          2            0.100608              0.033275             0.780386   
2          2            0.023659              0.116272             0.748871   
3          3            0.123663              0.033559             0.025220   
4          0            0.565631              0.042625             0.131673   
...      ...                 ...                   ...                  ...   
6891       0            0.982044              0.009646             0.004087   
6892       1            0.854260              0.141283             0.001495   
6893       4            0.010785              0.013112             0.018482   
6894       4            0.018999              0.016615             0.023578   
6895       4            0.026360              0.051274             0.095700   

      rfc_prediction_malware  rfc_prediction_defacemen  svc_prediction_non  \
0                   0.007611                  0.954432            0.504054   
1                   0.020569                  0.065162            0.422278   
2                   0.021887                  0.089311            0.131950   
3                   0.702551                  0.115007            0.123007   
4                   0.066562                  0.193508            0.234104   
...                      ...                       ...                 ...   
6891                0.003513                  0.000711            0.807336   
6892                0.001437                  0.001525            0.637574   
6893                0.022586                  0.935035            0.114287   
6894                0.007481                  0.933326            0.331977   
6895                0.012637                  0.814030            0.387867   

      svc_prediction_phish  svc_prediction_spam  svc_prediction_malware  \
0                 0.039650             0.045751                0.049365   
1                 0.079107             0.297047                0.106798   
2                 0.127239             0.209020                0.361777   
3                 0.129962             0.200915                0.374736   
4                 0.121611             0.238581                0.214531   
...                    ...                  ...                     ...   
6891              0.029268             0.146792                0.004346   
6892              0.170702             0.015159                0.168285   
6893              0.130349             0.190958                0.391332   
6894              0.115904             0.273075                0.139842   
6895              0.134223             0.184981                0.093342   

      svc_prediction_defacemen  
0                     0.361179  
1                     0.094770  
2                     0.170014  
3                     0.171379  
4                     0.191173  
...                        ...  
6891                  0.012258  
6892                  0.008281  
6893                  0.173074  
6894                  0.139202  
6895                  0.199587  

[6896 rows x 11 columns]

**Logistic Regression**

In [ ]:
import keras

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
import pickle

def model_lr(x_train, x_val, y_train, y_val, opt, n):
  lrclassifier = LogisticRegression()
  #compile model using mse as a measure of model performance
  lrclassifier.fit(x_train, y_train)

  y_pred = lrclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))
  

  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/LR/model_'+str(n)+'.h5'
  pickle.dump(lrclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_lr(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[231   5  38   4   0]
 [ 76   0  14   1   0]
 [ 92   0  71   0   0]
 [ 75  13  14  93   0]
 [ 93   0  22   1   0]]
Precision: 0.4380
Recall: 0.4686
F1 Score: 0.4119
Validation Accuracy: 0.46856465005931197
model 0 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[227   0  27   4   0]
 [ 84   0   6   2   0]
 [100   0  64   0   0]
 [ 75   0  14  93   7]
 [121   0  18   1   0]]
Precision: 0.4195
Recall: 0.4555
F1 Score: 0.3899
Validation Accuracy: 0.4555160142348754
model 1 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[258   0  37   6   0]
 [ 74   0   7   0   0]
 [ 93   0  56   0   0]
 [ 92   0  10 102   6]
 [ 88   0  10   4   0]]
Precision: 0.4616
Recall: 0.4935
F1 Score: 0.4348
Validation Accuracy: 0.49347568208778175
model 2 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[260   0  15   3   0]
 [ 73   0   7   0   0]
 [102   0  79   0   0]
 [ 76  13  10  93   0]
 [ 99   0  13   0   0]]
Precision: 0.4980
Recall: 0.5125
F1 Score: 0.4514
Validation Accuracy: 0.5124555160142349
model 3 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[251   1  31   6   0]
 [ 76   0   9   0   0]
 [101   0  64   0   0]
 [ 61   0  11 100   0]
 [117   0  15   0   0]]
Precision: 0.4308
Recall: 0.4923
F1 Score: 0.4240
Validation Accuracy: 0.49228944246737844
model 4 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[243   0  27   7   0]
 [ 80   0  15   0   0]
 [ 91   0  57   0   0]
 [ 80   0   6 112   0]
 [108   0  15   2   0]]
Precision: 0.4334
Recall: 0.4887
F1 Score: 0.4213
Validation Accuracy: 0.4887307236061684
model 5 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[227   3  27   7   0]
 [ 71   0   6   1   0]
 [111   0  63   0   0]
 [ 95   0   7 102   0]
 [110   0  13   0   0]]
Precision: 0.4523
Recall: 0.4650
F1 Score: 0.4088
Validation Accuracy: 0.465005931198102
model 6 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[217   0  27   4   2]
 [ 84   0  14   0   0]
 [112   0  61   0   0]
 [ 86   0   5  99   0]
 [104   0  25   3   0]]
Precision: 0.4121
Recall: 0.4472
F1 Score: 0.3837
Validation Accuracy: 0.4472123368920522
model 7 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[238   0  29   8   0]
 [ 84   0  12   0   0]
 [ 91   0  66   0   0]
 [ 83   0  14  91   0]
 [101   0  21   4   0]]
Precision: 0.4141
Recall: 0.4691
F1 Score: 0.4002
Validation Accuracy: 0.4691211401425178
model 8 saved
[[256   4  30   3   0]
 [ 71   0   3   1   0]
 [ 95   0  70   0   0]
 [ 75   0  14 101   8]
 [ 99   0  11   1   0]]
Precision: 0.4807
Recall: 0.5071
F1 Score: 0.4503
Validation Accuracy: 0.5071258907363421
model 9 saved
Average Validation Accuracy: 0.47994973274387637


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/LR/model_3.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['lr_prediction_non'] = [i[0] for i in y_pred_prob];
output['lr_prediction_phish'] = [i[1] for i in y_pred_prob];
output['lr_prediction_spam'] = [i[2] for i in y_pred_prob];
output['lr_prediction_malware'] = [i[3] for i in y_pred_prob];
output['lr_prediction_defacemen'] = [i[4] for i in y_pred_prob];

output = pd.DataFrame.from_dict(output)
output


[[8.57927315e-01 4.65004245e-04 4.25402238e-02 2.84002451e-03
  9.62274324e-02]
 [2.50114218e-01 1.55323123e-01 2.11716263e-01 1.68735708e-01
  2.14110688e-01]
 [2.06046014e-01 1.93250278e-01 1.98365094e-01 1.98411093e-01
  2.03927522e-01]
 ...
 [2.01175017e-01 1.99600145e-01 1.99746308e-01 1.99410981e-01
  2.00067548e-01]
 [2.66664327e-01 1.50927678e-01 2.56538512e-01 1.31232030e-01
  1.94637452e-01]
 [3.76520925e-01 1.12334173e-01 2.28582022e-01 9.43060111e-02
  1.88256868e-01]]


labels  rfc_prediction_non  rfc_prediction_phish  rfc_prediction_spam  \
0          4            0.011508              0.004581             0.021867   
1          2            0.100608              0.033275             0.780386   
2          2            0.023659              0.116272             0.748871   
3          3            0.123663              0.033559             0.025220   
4          0            0.565631              0.042625             0.131673   
...      ...                 ...                   ...                  ...   
6891       0            0.982044              0.009646             0.004087   
6892       1            0.854260              0.141283             0.001495   
6893       4            0.010785              0.013112             0.018482   
6894       4            0.018999              0.016615             0.023578   
6895       4            0.026360              0.051274             0.095700   

      rfc_prediction_malware  rfc_prediction_defacemen  svc_prediction_non  \
0                   0.007611                  0.954432            0.504054   
1                   0.020569                  0.065162            0.422278   
2                   0.021887                  0.089311            0.131950   
3                   0.702551                  0.115007            0.123007   
4                   0.066562                  0.193508            0.234104   
...                      ...                       ...                 ...   
6891                0.003513                  0.000711            0.807336   
6892                0.001437                  0.001525            0.637574   
6893                0.022586                  0.935035            0.114287   
6894                0.007481                  0.933326            0.331977   
6895                0.012637                  0.814030            0.387867   

      svc_prediction_phish  svc_prediction_spam  svc_prediction_malware  \
0                 0.039650             0.045751                0.049365   
1                 0.079107             0.297047                0.106798   
2                 0.127239             0.209020                0.361777   
3                 0.129962             0.200915                0.374736   
4                 0.121611             0.238581                0.214531   
...                    ...                  ...                     ...   
6891              0.029268             0.146792                0.004346   
6892              0.170702             0.015159                0.168285   
6893              0.130349             0.190958                0.391332   
6894              0.115904             0.273075                0.139842   
6895              0.134223             0.184981                0.093342   

      svc_prediction_defacemen  lr_prediction_non  lr_prediction_phish  \
0                     0.361179           0.857927             0.000465   
1                     0.094770           0.250114             0.155323   
2                     0.170014           0.206046             0.193250   
3                     0.171379           0.202549             0.198721   
4                     0.191173           0.319656             0.114360   
...                        ...                ...                  ...   
6891                  0.012258           0.367866             0.131878   
6892                  0.008281           0.941514             0.017520   
6893                  0.173074           0.201175             0.199600   
6894                  0.139202           0.266664             0.150928   
6895                  0.199587           0.376521             0.112334   

      lr_prediction_spam  lr_prediction_malware  lr_prediction_defacemen  
0               0.042540               0.002840                 0.096227  
1               0.211716               0.168736                 0.214111  
2               0.198365               0.198411                 0.203928  
3               0.199183      

In [20]:
output.shape


(6896, 16)

In [21]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Multi/Base_classifier_result(URL-HTML cross)(2).csv', index=False)