In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(multi).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0               0        0       0           1          1            0   
1               1        0       0           1          1            1   
2               2        0       0           1          1            0   
3               3        0       0           1          3            0   
4               4        0       0           1          3            0   
...           ...      ...     ...         ...        ...          ...   
15319       23429        0       0           1          1            0   
15320       23430        0       0           1          1            0   
15321       23431        0       0           1          1            0   
15322       23432        0       0           1          1            0   
15323       23433        0       0           1          1            0   

       https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                 0        0              0            0  ...           0   
1                 0        0              0            0  ...           0   
2                 1        0              0            0  ...           0   
3                 0        0              0            0  ...           0   
4                 0        0              0            0  ...           0   
...             ...      ...            ...          ...  ...         ...   
15319             0        0              0            0  ...           0   
15320             0        0              0            0  ...           0   
15321             0        0              0            0  ...           0   
15322             0        0              0            0  ...           0   
15323             0        0              0            0  ...           0   

       Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0              49        691          42       13135                6400   
1               4         66           3        2034                 818   
2               1        100          27       32987               10451   
3               0          0           1           0                  52   
4             117        219          23        7944                3468   
...           ...        ...         ...         ...                 ...   
15319           0          0           1           0                   4   
15320           0          0           1           0                   4   
15321           0          0           1           0                   4   
15322           0          0           1           0                   4   
15323           0          0           1           0                   4   

       Script To Special Chars Ratio  Script To body Ratio  \
0                           2.052344              0.528869   
1                           2.486553              0.676197   
2                           3.156349              0.836681   
3                           0.000000              0.000000   
4                           2.290657              0.524460   
...                              ...                   ...   
15319                       0.000000              0.000000   
15320                       0.000000              0.000000   
15321                       0.000000              0.000000   
15322                       0.000000              0.000000   
15323                       0.000000              0.000000   

       Body To Special Char Ratio  Label  
0                        0.257690      0  
1                        0.271941      0  
2                        0.265079      0  
3                        0.227074      0  
4                        0.228956      0  
...                           ...    ...  
15319                    0.121212      4  
15320                    0.121212      4  
15321                    0.121212      4  
15322                    0.121212      4  
15323                    0.121212      4  

[15324 rows x 46 c

In [ ]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [ ]:
urldata = urldata.drop(['Unnamed: 0'], axis = 1).copy()

urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0          49   
1              0            0           0  ...           0           4   
2              0            0           0  ...           0           1   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0         117   

   Num Links  Num Titles  Num Script  Special Characters  \
0        691          42       13135                6400   
1         66           3        2034                 818   
2        100          27       32987               10451   
3          0           1           0                  52   
4        219          23        7944                3468   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.052344              0.528869   
1                       2.486553              0.676197   
2                       3.156349              0.836681   
3                       0.000000              0.000000   
4                       2.290657              0.524460   

   Body To Special Char Ratio  Label  
0                    0.257690      0  
1                    0.271941      0  
2                    0.265079      0  
3                    0.227074      0  
4                    0.228956      0  

[5 rows x 45 columns]

In [ ]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15324 entries, 0 to 15323
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Have IP                        15324 non-null  int64  
 1   Have @                         15324 non-null  int64  
 2   URL Length                     15324 non-null  int64  
 3   URL Depth                      15324 non-null  int64  
 4   Redirection                    15324 non-null  int64  
 5   https Domain                   15324 non-null  int64  
 6   TinyURL                        15324 non-null  int64  
 7   Prefix/Suffix                  15324 non-null  int64  
 8   Have client                    15324 non-null  int64  
 9   Have admin                     15324 non-null  int64  
 10  Have login                     15324 non-null  int64  
 11  Have server                    15324 non-null  int64  
 12  .php                           15324 non-null 

In [ ]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
2    3002
3    3543
4    2252
dtype: int64

In [ ]:

import numpy as np


In [ ]:
urldata.describe()

Have IP        Have @    URL Length     URL Depth   Redirection  \
count  15324.0  15324.000000  15324.000000  15324.000000  15324.000000   
mean       0.0      0.003067      0.897938      3.190029      0.027212   
std        0.0      0.055298      0.302740      2.526227      0.162707   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      1.000000      1.000000      0.000000   
50%        0.0      0.000000      1.000000      2.000000      0.000000   
75%        0.0      0.000000      1.000000      4.000000      0.000000   
max        0.0      1.000000      1.000000     18.000000      1.000000   

       https Domain       TinyURL  Prefix/Suffix   Have client    Have admin  \
count  15324.000000  15324.000000   15324.000000  15324.000000  15324.000000   
mean       0.027930      0.034978       0.073871      0.001305      0.010702   
std        0.164778      0.183730       0.261569      0.036104      0.102900   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      0.000000   
50%        0.000000      0.000000       0.000000      0.000000      0.000000   
75%        0.000000      0.000000       0.000000      0.000000      0.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

       ...    Num Embeds    Num Images     Num Links    Num Titles  \
count  ...  15324.000000  15324.000000  15324.000000  15324.000000   
mean   ...      0.000261      9.431480     53.732642      8.138476   
std    ...      0.016155     31.982449    105.014700     30.703307   
min    ...      0.000000      0.000000     -1.000000     -1.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      2.000000      1.000000   
75%    ...      0.000000      4.000000     66.000000      4.000000   
max    ...      1.000000    816.000000   1740.000000   1042.000000   

         Num Script  Special Characters  Script To Special Chars Ratio  \
count  1.532400e+04        15324.000000                   15324.000000   
mean   1.907060e+04         7416.632407                       3.722576   
std    6.790900e+04        18369.465282                      17.536106   
min   -1.000000e+00            0.000000                      -1.000000   
25%    0.000000e+00           12.000000                       0.000000   
50%    7.770000e+02          557.000000                       1.324700   
75%    1.592400e+04         8311.000000                       2.625806   
max    2.076633e+06       359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio         Label  
count          15324.000000                15324.000000  15324.000000  
mean               0.367024                    0.192536      1.775907  
std                0.375838                    0.112498      1.471309  
min               -1.000000                    0.000000      0.000000  
25%                0.000000                    0.141286      0.000000  
50%                0.312289                    0.225350      2.000000  
75%                0.718077                    0.263237      3.000000  
max                1.005038                    0.733333      4.000000  

[8 rows x 45 columns]

In [ ]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                          0
Have @                           0
URL Length                       0
URL Depth                        0
Redirection                      0
https Domain                     0
TinyURL                          0
Prefix/Suffix                    0
Have client                      0
Have admin                       0
Have login                       0
Have server                      0
.php                             0
.html                            0
.info                            0
.txt                             0
.js                              0
.exe                             0
Num of periods                   0
Is encoded                       0
Num of encoded char              0
Num of parameters                0
Num of digits                    0
Num of spec char                 0
iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page token

In [ ]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           0          4            0             0        0   
3        0       0           1          1            0             0        0   
4        0       0           1          5            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0           0   
1              0            0           0  ...           0           0   
2              0            0           0  ...           0          29   
3              0            0           0  ...           0           1   
4              0            0           0  ...           0           0   

   Num Links  Num Titles  Num Script  Special Characters  \
0          1           0           0                   0   
1          0           0           0                   0   
2        166          38       68310               23419   
3          0           0           0                  12   
4          0           1           0                   4   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       0.000000               0.00000   
1                       0.000000               0.00000   
2                       2.916862               0.88034   
3                       0.000000               0.00000   
4                       0.000000               0.00000   

   Body To Special Char Ratio  Label  
0                    0.000000      3  
1                    0.000000      1  
2                    0.301811      2  
3                    0.162162      0  
4                    0.121212      3  

[5 rows x 45 columns]

In [ ]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [ ]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(8428, 44) (6896, 44)
(8428,) (6896,)


In [ ]:
output = {}
output['labels'] = y_test

**MLP**

In [ ]:
import keras

from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle

def model_mlp(x_train, x_val, y_train, y_val, opt, n):
  mlpclassifier = MLPClassifier(alpha=0.0001, hidden_layer_sizes=([100,100,100]))
  #compile model using mse as a measure of model performance
  mlpclassifier.fit(x_train, y_train)

  y_pred = mlpclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/MLP/model_'+str(n)+'.h5'
  pickle.dump(mlpclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_mlp(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[203   1   8  16  35]
 [  9  44   7   3  16]
 [ 11   0 137   2  14]
 [  2   5   0 177  12]
 [  4   1   4   1 131]]
Precision: 0.8404
Recall: 0.8209
F1 Score: 0.8214
Validation Accuracy: 0.8208778173190985
model 0 saved
[[241   1  30   4  15]
 [ 11  44   3   6  10]
 [  3   0 155   0  11]
 [  4   3   3 173   8]
 [  1   0   1   2 114]]
Precision: 0.8751
Recall: 0.8624
F1 Score: 0.8616
Validation Accuracy: 0.8623962040332147
model 1 saved
[[241   4  10   4  11]
 [ 20  45   4   4   2]
 [ 50   2 120   3   3]
 [ 11   6   4 159   2]
 [ 43   6  11   2  76]]
Precision: 0.7770
Recall: 0.7604
F1 Score: 0.7573
Validation Accuracy: 0.7603795966785291
model 2 saved
[[233  22  20  13   0]
 [ 14  61   5   6   0]
 [ 33  13 108   0   2]
 [  8  11   0 173   2]
 [ 19  32   6   1  61]]
Precision: 0.7866
Recall: 0.7544
F1 Score: 0.7577
Validation Accuracy: 0.7544483985765125
model 3 saved
[[211   1  29  10  12]
 [ 17  42   7  10   6]
 [  5   0 147   2   9]
 [  8   2   6 195   3]
 [ 14   0  14  11  82]]
Prec

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/MLP/model_1.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['mlp_prediction_non'] = [i[0] for i in y_pred_prob];
output['mlp_prediction_phish'] = [i[1] for i in y_pred_prob];
output['mlp_prediction_spam'] = [i[2] for i in y_pred_prob];
output['mlp_prediction_malware'] = [i[3] for i in y_pred_prob];
output['mlp_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[3.91553873e-060 2.68015846e-220 1.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [2.88464362e-006 3.83570678e-005 2.71159524e-023 9.99958758e-001
  7.63722366e-026]
 [5.90508965e-001 2.19733288e-001 1.59528637e-002 1.40523164e-002
  1.59752567e-001]
 ...
 [1.68863697e-002 1.03265965e-008 2.13086729e-003 1.38728674e-016
  9.80982753e-001]
 [1.00000000e+000 1.98653622e-037 3.73134969e-032 1.15221709e-078
  3.13849159e-038]
 [3.10639870e-005 9.01686443e-005 8.75004392e-003 5.05086029e-006
  9.91123673e-001]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0        3.915539e-60         2.680158e-220       3.915539e-60   
1          3        2.884644e-06          3.835707e-05       2.884644e-06   
2          0        5.905090e-01          2.197333e-01       5.905090e-01   
3          1        2.825485e-02          4.110084e-01       2.825485e-02   
4          1        1.825027e-43          3.029391e-36       1.825027e-43   
...      ...                 ...                   ...                ...   
6891       1        6.344460e-06          9.982762e-01       6.344460e-06   
6892       3        9.905528e-03          1.295311e-02       9.905528e-03   
6893       2        1.688637e-02          1.032660e-08       1.688637e-02   
6894       0        1.000000e+00          1.986536e-37       1.000000e+00   
6895       4        3.106399e-05          9.016864e-05       3.106399e-05   

      nn_prediction_phish  nn2_prediction_non  nn2_prediction_phish  \
0           2.680158e-220        3.915539e-60         2.680158e-220   
1            3.835707e-05        2.884644e-06          3.835707e-05   
2            2.197333e-01        5.905090e-01          2.197333e-01   
3            4.110084e-01        2.825485e-02          4.110084e-01   
4            3.029391e-36        1.825027e-43          3.029391e-36   
...                   ...                 ...                   ...   
6891         9.982762e-01        6.344460e-06          9.982762e-01   
6892         1.295311e-02        9.905528e-03          1.295311e-02   
6893         1.032660e-08        1.688637e-02          1.032660e-08   
6894         1.986536e-37        1.000000e+00          1.986536e-37   
6895         9.016864e-05        3.106399e-05          9.016864e-05   

      mlp_prediction_spam  mlp_prediction_malware  mlp_prediction_defacemen  
0            1.000000e+00            0.000000e+00              0.000000e+00  
1            2.711595e-23            9.999588e-01              7.637224e-26  
2            1.595286e-02            1.405232e-02              1.597526e-01  
3            2.974864e-02            6.680746e-03              5.243073e-01  
4            1.000000e+00           3.531859e-183             6.471977e-232  
...                   ...                     ...                       ...  
6891         5.259414e-05            1.664911e-03              1.978808e-10  
6892         6.272989e-03            9.691422e-01              1.726208e-03  
6893         2.130867e-03            1.387287e-16              9.809828e-01  
6894         3.731350e-32            1.152217e-78              3.138492e-38  
6895         8.750044e-03            5.050860e-06              9.911237e-01  

[6896 rows x 10 columns]

**Neural Network**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_aa(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]
  # print("check point")
  #create model
  model = Sequential()
  model.add(Dense(30, activation='relu', input_shape=(n_cols,)))
  model.add(Dense(10, activation='relu'))

  model.add(Dense(1, activation = 'sigmoid'))
  # softmax
  #compile model using mse as a measure of model performance
  model.compile(optimizer = opt, loss= 'binary_crossentropy', metrics=["accuracy"])

  history = model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/NN/model_'+str(n)+'.h5'
  pickle.dump(model, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_aa(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
238/238 [==============================] - 2s 6ms/step - loss: 126.3983 - accuracy: 0.1206 - val_loss: -52.9108 - val_accuracy: 0.0949
Epoch 2/100
238/238 [==============================] - 1s 5ms/step - loss: -139.7192 - accuracy: 0.1608 - val_loss: -373.5852 - val_accuracy: 0.0937
Epoch 3/100
238/238 [==============================] - 1s 4ms/step - loss: -414.3650 - accuracy: 0.1475 - val_loss: -947.5576 - val_accuracy: 0.1483
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -963.2092 - accuracy: 0.1511 - val_loss: -2007.5138 - val_accuracy: 0.1649
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -1917.5194 - accuracy: 0.1556 - val_loss: -3562.3250 - val_accuracy: 0.1767
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -3261.0491 - accuracy: 0.1544 - val_loss: -5656.6294 - val_accuracy: 0.1767
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: -5168.2524 - accuracy: 0.151

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://93fa8d61-41fc-4dbd-9441-2aa5cb344467/assets
model 0 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -236.8557 - accuracy: 0.1171 - val_loss: -741.6003 - val_accuracy: 0.0878
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1126.0507 - accuracy: 0.1462 - val_loss: -1949.5227 - val_accuracy: 0.0902
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -2646.3984 - accuracy: 0.1374 - val_loss: -3851.6465 - val_accuracy: 0.0878
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -4859.3584 - accuracy: 0.1291 - val_loss: -6755.2104 - val_accuracy: 0.1874
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -8342.0117 - accuracy: 0.1390 - val_loss: -11006.0186 - val_accuracy: 0.1791
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -13522.3955 - accuracy: 0.1287 - val_loss: -16516.3516 - val_accuracy: 0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://7787b18d-fc72-4cfa-84c0-57ac6784a619/assets
model 1 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -181.7656 - accuracy: 0.1035 - val_loss: -457.7724 - val_accuracy: 0.0890
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1219.2405 - accuracy: 0.0987 - val_loss: -1624.5643 - val_accuracy: 0.0890
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -3380.4756 - accuracy: 0.0987 - val_loss: -4004.1689 - val_accuracy: 0.0890
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -6931.4204 - accuracy: 0.0987 - val_loss: -7252.1045 - val_accuracy: 0.0890
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -11937.0029 - accuracy: 0.0987 - val_loss: -11585.3145 - val_accuracy: 0.0890
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -18290.2109 - accuracy: 0.0987 - val_loss: -17481.3613 - val_accuracy: 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://fde02fee-babf-46ca-959e-05ebbade9244/assets
model 2 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 29.9379 - accuracy: 0.1231 - val_loss: -90.6780 - val_accuracy: 0.2444
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1890.2737 - accuracy: 0.1284 - val_loss: -1594.1606 - val_accuracy: 0.1590
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -4056.1111 - accuracy: 0.1187 - val_loss: -2765.8674 - val_accuracy: 0.1020
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -6929.2007 - accuracy: 0.1267 - val_loss: -4745.6758 - val_accuracy: 0.1922
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -10768.5459 - accuracy: 0.1403 - val_loss: -6920.6689 - val_accuracy: 0.1020
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -15753.8584 - accuracy: 0.1295 - val_loss: -10820.1016 - val_accuracy: 0.10

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://1545fc7e-be0e-44ff-807e-5407e3abb7d4/assets
model 3 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -67.2216 - accuracy: 0.1465 - val_loss: -28.8473 - val_accuracy: 0.0973
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -435.3719 - accuracy: 0.1337 - val_loss: -656.8365 - val_accuracy: 0.2147
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -1106.6980 - accuracy: 0.1396 - val_loss: -1692.4261 - val_accuracy: 0.1922
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -2339.3022 - accuracy: 0.1354 - val_loss: -3461.4058 - val_accuracy: 0.1910
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -4374.8330 - accuracy: 0.1421 - val_loss: -6314.0083 - val_accuracy: 0.1234
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -7192.8398 - accuracy: 0.1521 - val_loss: -9779.5518 - val_accuracy: 0.1079
E

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://82e5b4f7-130b-4402-8a66-7dae7073d0e3/assets
model 4 saved
Epoch 1/100
238/238 [==============================] - 1s 4ms/step - loss: -175.5787 - accuracy: 0.1503 - val_loss: -665.0745 - val_accuracy: 0.1815
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1312.9534 - accuracy: 0.1606 - val_loss: -1869.5239 - val_accuracy: 0.1032
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -3220.6890 - accuracy: 0.1602 - val_loss: -3913.9641 - val_accuracy: 0.1032
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -5969.9565 - accuracy: 0.1678 - val_loss: -7118.5420 - val_accuracy: 0.1874
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -9760.2764 - accuracy: 0.1661 - val_loss: -10878.5264 - val_accuracy: 0.2028
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -14378.2646 - accuracy: 0.1465 - val_loss: -15350.1875 - val_accuracy: 0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://fc32f210-7a6c-428d-821a-24547aa28437/assets
model 5 saved
Epoch 1/100
238/238 [==============================] - 2s 4ms/step - loss: -36.2872 - accuracy: 0.1392 - val_loss: -417.5096 - val_accuracy: 0.1103
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -719.6921 - accuracy: 0.1314 - val_loss: -1148.1742 - val_accuracy: 0.1756
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -1622.3390 - accuracy: 0.1446 - val_loss: -2360.5293 - val_accuracy: 0.1115
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -3244.2068 - accuracy: 0.1329 - val_loss: -4480.1265 - val_accuracy: 0.1127
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -5640.5093 - accuracy: 0.1171 - val_loss: -7228.7344 - val_accuracy: 0.1174
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -8889.9561 - accuracy: 0.1245 - val_loss: -11010.0283 - val_accuracy: 0.111

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://395166ac-a0ff-44aa-92c5-074f391639b9/assets
model 6 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -68.0221 - accuracy: 0.1557 - val_loss: -418.6419 - val_accuracy: 0.1103
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -672.5538 - accuracy: 0.1503 - val_loss: -1071.8026 - val_accuracy: 0.1103
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -1537.2386 - accuracy: 0.1463 - val_loss: -2156.7373 - val_accuracy: 0.1103
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -2947.1536 - accuracy: 0.1388 - val_loss: -3892.3298 - val_accuracy: 0.1779
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -5119.9009 - accuracy: 0.1280 - val_loss: -6350.9360 - val_accuracy: 0.1079
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -8196.1699 - accuracy: 0.1345 - val_loss: -9821.2490 - val_accuracy: 0.1103

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://db77090f-a8d7-436e-9335-fcd7348661e7/assets
model 7 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -398.0439 - accuracy: 0.1391 - val_loss: -516.9250 - val_accuracy: 0.0998
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -2063.7585 - accuracy: 0.1302 - val_loss: -2038.1974 - val_accuracy: 0.1698
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -4433.9448 - accuracy: 0.1330 - val_loss: -4321.9780 - val_accuracy: 0.1734
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -8036.3237 - accuracy: 0.1355 - val_loss: -7472.0444 - val_accuracy: 0.1746
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -13340.3359 - accuracy: 0.1246 - val_loss: -11663.1885 - val_accuracy: 0.1045
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -20666.7305 - accuracy: 0.1169 - val_loss: -17494.0527 - val_accuracy: 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://90d3604a-7c62-489a-af01-5f28770f1d5e/assets
model 8 saved
Epoch 1/100
238/238 [==============================] - 1s 4ms/step - loss: -471.2248 - accuracy: 0.1492 - val_loss: -1017.0510 - val_accuracy: 0.0914
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -2539.3513 - accuracy: 0.1487 - val_loss: -4277.3184 - val_accuracy: 0.0914
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -6425.3013 - accuracy: 0.1413 - val_loss: -8138.4194 - val_accuracy: 0.0914
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -11375.5371 - accuracy: 0.1538 - val_loss: -13277.4062 - val_accuracy: 0.1615
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -17586.8398 - accuracy: 0.1559 - val_loss: -19389.5684 - val_accuracy: 0.1627
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -25039.8184 - accuracy: 0.1405 - val_loss: -26315.2559 - val_accurac

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://4075d837-89bb-495a-9b92-52924b6fafb2/assets
model 9 saved
Average Validation Accuracy: 0.12731366035226527


In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/NN/model_0.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn_prediction_phish'] = [i[1] for i in y_pred_prob];
output['nn_prediction_spam'] = [i[2] for i in y_pred_prob];
output['nn_prediction_malware'] = [i[3] for i in y_pred_prob];
output['nn_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[3.91553873e-060 2.68015846e-220 1.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [2.88464362e-006 3.83570678e-005 2.71159524e-023 9.99958758e-001
  7.63722366e-026]
 [5.90508965e-001 2.19733288e-001 1.59528637e-002 1.40523164e-002
  1.59752567e-001]
 ...
 [1.68863697e-002 1.03265965e-008 2.13086729e-003 1.38728674e-016
  9.80982753e-001]
 [1.00000000e+000 1.98653622e-037 3.73134969e-032 1.15221709e-078
  3.13849159e-038]
 [3.10639870e-005 9.01686443e-005 8.75004392e-003 5.05086029e-006
  9.91123673e-001]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0        3.915539e-60         2.680158e-220       3.915539e-60   
1          3        2.884644e-06          3.835707e-05       2.884644e-06   
2          0        5.905090e-01          2.197333e-01       5.905090e-01   
3          1        2.825485e-02          4.110084e-01       2.825485e-02   
4          1        1.825027e-43          3.029391e-36       1.825027e-43   
...      ...                 ...                   ...                ...   
6891       1        6.344460e-06          9.982762e-01       6.344460e-06   
6892       3        9.905528e-03          1.295311e-02       9.905528e-03   
6893       2        1.688637e-02          1.032660e-08       1.688637e-02   
6894       0        1.000000e+00          1.986536e-37       1.000000e+00   
6895       4        3.106399e-05          9.016864e-05       3.106399e-05   

      nn_prediction_phish  nn2_prediction_non  nn2_prediction_phish  \
0           2.680158e-220        3.915539e-60         2.680158e-220   
1            3.835707e-05        2.884644e-06          3.835707e-05   
2            2.197333e-01        5.905090e-01          2.197333e-01   
3            4.110084e-01        2.825485e-02          4.110084e-01   
4            3.029391e-36        1.825027e-43          3.029391e-36   
...                   ...                 ...                   ...   
6891         9.982762e-01        6.344460e-06          9.982762e-01   
6892         1.295311e-02        9.905528e-03          1.295311e-02   
6893         1.032660e-08        1.688637e-02          1.032660e-08   
6894         1.986536e-37        1.000000e+00          1.986536e-37   
6895         9.016864e-05        3.106399e-05          9.016864e-05   

      mlp_prediction_spam  mlp_prediction_malware  mlp_prediction_defacemen  \
0            1.000000e+00            0.000000e+00              0.000000e+00   
1            2.711595e-23            9.999588e-01              7.637224e-26   
2            1.595286e-02            1.405232e-02              1.597526e-01   
3            2.974864e-02            6.680746e-03              5.243073e-01   
4            1.000000e+00           3.531859e-183             6.471977e-232   
...                   ...                     ...                       ...   
6891         5.259414e-05            1.664911e-03              1.978808e-10   
6892         6.272989e-03            9.691422e-01              1.726208e-03   
6893         2.130867e-03            1.387287e-16              9.809828e-01   
6894         3.731350e-32            1.152217e-78              3.138492e-38   
6895         8.750044e-03            5.050860e-06              9.911237e-01   

      nn_prediction_spam  nn_prediction_malware  nn_prediction_defacemen  
0           1.000000e+00           0.000000e+00             0.000000e+00  
1           2.711595e-23           9.999588e-01             7.637224e-26  
2           1.595286e-02           1.405232e-02             1.597526e-01  
3           2.974864e-02           6.680746e-03             5.243073e-01  
4           1.000000e+00          3.531859e-183            6.471977e-232  
...                  ...                    ...                      ...  
6891        5.259414e-05           1.664911e-03             1.978808e-10  
6892        6.272989e-03           9.691422e-01             1.726208e-03  
6893        2.130867e-03           1.387287e-16             9.809828e-01  
6894        3.731350e-32           1.152217e-78             3.138492e-38  
6895        8.750044e-03           5.050860e-06             9.911237e-01  

[6896 rows x 13 columns]

**Neural Network 2**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_a(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]

  #create model
  model_2 = Sequential()
  model_2.add(Dense(30, activation='sigmoid', input_shape=(n_cols,)))
  model_2.add(Dense(25, activation='sigmoid'))
  model_2.add(Dense(20, activation='sigmoid'))
  model_2.add(Dense(15, activation='sigmoid'))
  model_2.add(Dense(10, activation='sigmoid'))
  model_2.add(Dense(1, activation = 'sigmoid'))

  #compile model using mse as a measure of model performance
  model_2.compile(optimizer='adam', loss='mean_squared_error')



  history = model_2.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model_2.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/NN_2/model_'+str(n)+'.h5'
  pickle.dump(model_2, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_a(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.1673 - val_loss: 3.0985
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8466 - val_loss: 3.0040
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8005 - val_loss: 2.9767
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7839 - val_loss: 2.9645
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7758 - val_loss: 2.9578
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7711 - val_loss: 2.9537
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7681 - val_loss: 2.9510
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7660 - val_loss: 2.9490
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7645 - val_loss: 2.9475
Epoch 10/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7632 - val_lo

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://cfd95568-27d8-4d2f-aa38-100def86b421/assets
model 0 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.3022 - val_loss: 2.8785
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8986 - val_loss: 2.7835
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8422 - val_loss: 2.7531
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8194 - val_loss: 2.7382
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8079 - val_loss: 2.7303
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8013 - val_loss: 2.7254
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7971 - val_loss: 2.7223
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7943 - val_loss: 2.7200
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7923 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       291
           1       0.09      1.00      0.16        74
           2       0.00      0.00      0.00       169
           3       0.00      0.00      0.00       191
           4       0.00      0.00      0.00       118

    accuracy                           0.09       843
   macro avg       0.02      0.20      0.03       843
weighted avg       0.01      0.09      0.01       843

Accuracy: 0.08778173190984578
[[  0 291   0   0   0]
 [  0  74   0   0   0]
 [  0 169   0   0   0]
 [  0 191   0   0   0]
 [  0 118   0   0   0]]
Precision: 0.0077
Recall: 0.0878
F1 Score: 0.0142
INFO:tensorflow:Assets written to: ram://380e1e23-c6cd-4524-ba0a-859268f8725f/assets
model 1 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.1608 - val_loss: 2.9896
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8390 - val_loss: 2.9176
Epoch 3/100
23

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://8afc5b5d-ca7f-4663-99fa-0d4b7b104d2d/assets
model 2 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.0372 - val_loss: 2.7903
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8340 - val_loss: 2.7497
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8101 - val_loss: 2.7370
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8007 - val_loss: 2.7309
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7957 - val_loss: 2.7273
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7927 - val_loss: 2.7250
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7906 - val_loss: 2.7234
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7892 - val_loss: 2.7223
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7881 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       288
           1       0.10      1.00      0.19        86
           2       0.00      0.00      0.00       156
           3       0.00      0.00      0.00       194
           4       0.00      0.00      0.00       119

    accuracy                           0.10       843
   macro avg       0.02      0.20      0.04       843
weighted avg       0.01      0.10      0.02       843

Accuracy: 0.10201660735468565
[[  0 288   0   0   0]
 [  0  86   0   0   0]
 [  0 156   0   0   0]
 [  0 194   0   0   0]
 [  0 119   0   0   0]]
Precision: 0.0104
Recall: 0.1020
F1 Score: 0.0189
INFO:tensorflow:Assets written to: ram://4f3f905e-60e0-446d-8079-52d01e28376d/assets
model 3 saved
Epoch 1/100
238/238 [==============================] - 1s 5ms/step - loss: 3.5885 - val_loss: 3.1475
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.9783 - val_loss: 2.9591
Epoch 3/100
23

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://c95ae5cd-5cf5-405a-ba58-5c6b17b245b8/assets
model 4 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 2.9971 - val_loss: 2.9883
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8262 - val_loss: 2.9386
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7976 - val_loss: 2.9212
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7854 - val_loss: 2.9124
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7789 - val_loss: 2.9074
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7750 - val_loss: 2.9042
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7724 - val_loss: 2.9020
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7706 - val_loss: 2.9004
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7693 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://74c31276-4405-494b-a36b-46ee2aa8ca75/assets
model 5 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.6258 - val_loss: 3.0559
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 3.0615 - val_loss: 2.8748
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.9386 - val_loss: 2.7948
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8742 - val_loss: 2.7524
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8433 - val_loss: 2.7321
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8268 - val_loss: 2.7202
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8167 - val_loss: 2.7126
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8100 - val_loss: 2.7073
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8052 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       280
           1       0.11      1.00      0.20        93
           2       0.00      0.00      0.00       158
           3       0.00      0.00      0.00       196
           4       0.00      0.00      0.00       116

    accuracy                           0.11       843
   macro avg       0.02      0.20      0.04       843
weighted avg       0.01      0.11      0.02       843

Accuracy: 0.1103202846975089
[[  0 280   0   0   0]
 [  0  93   0   0   0]
 [  0 158   0   0   0]
 [  0 196   0   0   0]
 [  0 116   0   0   0]]
Precision: 0.0122
Recall: 0.1103
F1 Score: 0.0219
INFO:tensorflow:Assets written to: ram://fe13eb14-82ea-43e6-94e8-53923c5bcb97/assets
model 6 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.1647 - val_loss: 2.7311
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8739 - val_loss: 2.6606
Epoch 3/100
238

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://4aacd8a0-5a26-4468-91ea-57dc90fb27b8/assets
model 7 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.1138 - val_loss: 2.8463
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8634 - val_loss: 2.7795
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8243 - val_loss: 2.7582
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8091 - val_loss: 2.7480
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8011 - val_loss: 2.7421
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7962 - val_loss: 2.7383
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7931 - val_loss: 2.7358
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7908 - val_loss: 2.7340
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7892 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       279
           1       0.10      1.00      0.18        84
           2       0.00      0.00      0.00       163
           3       0.00      0.00      0.00       198
           4       0.00      0.00      0.00       118

    accuracy                           0.10       842
   macro avg       0.02      0.20      0.04       842
weighted avg       0.01      0.10      0.02       842

Accuracy: 0.0997624703087886
[[  0 279   0   0   0]
 [  0  84   0   0   0]
 [  0 163   0   0   0]
 [  0 198   0   0   0]
 [  0 118   0   0   0]]
Precision: 0.0100
Recall: 0.0998
F1 Score: 0.0181
INFO:tensorflow:Assets written to: ram://9bf1f5eb-5c71-4f90-a0dc-c6e0844874f8/assets
model 8 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.5037 - val_loss: 3.1067
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.9891 - val_loss: 2.9485
Epoch 3/100
238

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       273
           1       0.09      1.00      0.17        77
           2       0.00      0.00      0.00       170
           3       0.00      0.00      0.00       198
           4       0.00      0.00      0.00       124

    accuracy                           0.09       842
   macro avg       0.02      0.20      0.03       842
weighted avg       0.01      0.09      0.02       842

Accuracy: 0.09144893111638955
[[  0 273   0   0   0]
 [  0  77   0   0   0]
 [  0 170   0   0   0]
 [  0 198   0   0   0]
 [  0 124   0   0   0]]
Precision: 0.0084
Recall: 0.0914
F1 Score: 0.0153
INFO:tensorflow:Assets written to: ram://3acb15f3-c1d9-4cec-9578-e49a79892b7c/assets
model 9 saved
Average Validation Accuracy: 0.09776882697525803


In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL-HTML/NN_2/model_6.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn2_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn2_prediction_phish'] = [i[1] for i in y_pred_prob];
output['nn2_prediction_spam'] = [i[2] for i in y_pred_prob];
output['nn2_prediction_malware'] = [i[3] for i in y_pred_prob];
output['nn2_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[3.91553873e-060 2.68015846e-220 1.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [2.88464362e-006 3.83570678e-005 2.71159524e-023 9.99958758e-001
  7.63722366e-026]
 [5.90508965e-001 2.19733288e-001 1.59528637e-002 1.40523164e-002
  1.59752567e-001]
 ...
 [1.68863697e-002 1.03265965e-008 2.13086729e-003 1.38728674e-016
  9.80982753e-001]
 [1.00000000e+000 1.98653622e-037 3.73134969e-032 1.15221709e-078
  3.13849159e-038]
 [3.10639870e-005 9.01686443e-005 8.75004392e-003 5.05086029e-006
  9.91123673e-001]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0        3.915539e-60         2.680158e-220       3.915539e-60   
1          3        2.884644e-06          3.835707e-05       2.884644e-06   
2          0        5.905090e-01          2.197333e-01       5.905090e-01   
3          1        2.825485e-02          4.110084e-01       2.825485e-02   
4          1        1.825027e-43          3.029391e-36       1.825027e-43   
...      ...                 ...                   ...                ...   
6891       1        6.344460e-06          9.982762e-01       6.344460e-06   
6892       3        9.905528e-03          1.295311e-02       9.905528e-03   
6893       2        1.688637e-02          1.032660e-08       1.688637e-02   
6894       0        1.000000e+00          1.986536e-37       1.000000e+00   
6895       4        3.106399e-05          9.016864e-05       3.106399e-05   

      nn_prediction_phish  nn2_prediction_non  nn2_prediction_phish  \
0           2.680158e-220        3.915539e-60         2.680158e-220   
1            3.835707e-05        2.884644e-06          3.835707e-05   
2            2.197333e-01        5.905090e-01          2.197333e-01   
3            4.110084e-01        2.825485e-02          4.110084e-01   
4            3.029391e-36        1.825027e-43          3.029391e-36   
...                   ...                 ...                   ...   
6891         9.982762e-01        6.344460e-06          9.982762e-01   
6892         1.295311e-02        9.905528e-03          1.295311e-02   
6893         1.032660e-08        1.688637e-02          1.032660e-08   
6894         1.986536e-37        1.000000e+00          1.986536e-37   
6895         9.016864e-05        3.106399e-05          9.016864e-05   

      mlp_prediction_spam  mlp_prediction_malware  mlp_prediction_defacemen  \
0            1.000000e+00            0.000000e+00              0.000000e+00   
1            2.711595e-23            9.999588e-01              7.637224e-26   
2            1.595286e-02            1.405232e-02              1.597526e-01   
3            2.974864e-02            6.680746e-03              5.243073e-01   
4            1.000000e+00           3.531859e-183             6.471977e-232   
...                   ...                     ...                       ...   
6891         5.259414e-05            1.664911e-03              1.978808e-10   
6892         6.272989e-03            9.691422e-01              1.726208e-03   
6893         2.130867e-03            1.387287e-16              9.809828e-01   
6894         3.731350e-32            1.152217e-78              3.138492e-38   
6895         8.750044e-03            5.050860e-06              9.911237e-01   

      nn_prediction_spam  nn_prediction_malware  nn_prediction_defacemen  \
0           1.000000e+00           0.000000e+00             0.000000e+00   
1           2.711595e-23           9.999588e-01             7.637224e-26   
2           1.595286e-02           1.405232e-02             1.597526e-01   
3           2.974864e-02           6.680746e-03             5.243073e-01   
4           1.000000e+00          3.531859e-183            6.471977e-232   
...                  ...                    ...                      ...   
6891        5.259414e-05           1.664911e-03             1.978808e-10   
6892        6.272989e-03           9.691422e-01             1.726208e-03   
6893        2.130867e-03           1.387287e-16             9.809828e-01   
6894        3.731350e-32           1.152217e-78             3.138492e-38   
6895        8.750044e-03           5.050860e-06             9.911237e-01   

      nn2_prediction_spam  nn2_prediction_malware  nn2_prediction_defacemen  
0            1.000000e+00            0.000000e+00              0.000000e+00  
1            2.711595e-23            9.999588e-01              7.637224e-26  
2            1.595286e-02            1.405232e-02              1.597526e-01  
3            2.974864e-02            6.680746e-03     

In [ ]:
output.shape


(6896, 16)

In [ ]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Multi/Base_classifier_result(URL-HTML cross)(3).csv', index=False)