In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(multi).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0               0        0       0           1          1            0   
1               1        0       0           1          1            1   
2               2        0       0           1          1            0   
3               3        0       0           1          3            0   
4               4        0       0           1          3            0   
...           ...      ...     ...         ...        ...          ...   
15319       23429        0       0           1          1            0   
15320       23430        0       0           1          1            0   
15321       23431        0       0           1          1            0   
15322       23432        0       0           1          1            0   
15323       23433        0       0           1          1            0   

       https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                 0        0              0            0  ...           0   
1                 0        0              0            0  ...           0   
2                 1        0              0            0  ...           0   
3                 0        0              0            0  ...           0   
4                 0        0              0            0  ...           0   
...             ...      ...            ...          ...  ...         ...   
15319             0        0              0            0  ...           0   
15320             0        0              0            0  ...           0   
15321             0        0              0            0  ...           0   
15322             0        0              0            0  ...           0   
15323             0        0              0            0  ...           0   

       Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0              49        691          42       13135                6400   
1               4         66           3        2034                 818   
2               1        100          27       32987               10451   
3               0          0           1           0                  52   
4             117        219          23        7944                3468   
...           ...        ...         ...         ...                 ...   
15319           0          0           1           0                   4   
15320           0          0           1           0                   4   
15321           0          0           1           0                   4   
15322           0          0           1           0                   4   
15323           0          0           1           0                   4   

       Script To Special Chars Ratio  Script To body Ratio  \
0                           2.052344              0.528869   
1                           2.486553              0.676197   
2                           3.156349              0.836681   
3                           0.000000              0.000000   
4                           2.290657              0.524460   
...                              ...                   ...   
15319                       0.000000              0.000000   
15320                       0.000000              0.000000   
15321                       0.000000              0.000000   
15322                       0.000000              0.000000   
15323                       0.000000              0.000000   

       Body To Special Char Ratio  Label  
0                        0.257690      0  
1                        0.271941      0  
2                        0.265079      0  
3                        0.227074      0  
4                        0.228956      0  
...                           ...    ...  
15319                    0.121212      4  
15320                    0.121212      4  
15321                    0.121212      4  
15322                    0.121212      4  
15323                    0.121212      4  

[15324 rows x 46 c

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio'], axis = 1)

In [6]:
urldata.shape

(15324, 25)

In [7]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15324 entries, 0 to 15323
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Have IP              15324 non-null  int64
 1   Have @               15324 non-null  int64
 2   URL Length           15324 non-null  int64
 3   URL Depth            15324 non-null  int64
 4   Redirection          15324 non-null  int64
 5   https Domain         15324 non-null  int64
 6   TinyURL              15324 non-null  int64
 7   Prefix/Suffix        15324 non-null  int64
 8   Have client          15324 non-null  int64
 9   Have admin           15324 non-null  int64
 10  Have login           15324 non-null  int64
 11  Have server          15324 non-null  int64
 12  .php                 15324 non-null  int64
 13  .html                15324 non-null  int64
 14  .info                15324 non-null  int64
 15  .txt                 15324 non-null  int64
 16  .js                  1

In [8]:
urldata.describe()

Have IP        Have @    URL Length     URL Depth   Redirection  \
count  15324.0  15324.000000  15324.000000  15324.000000  15324.000000   
mean       0.0      0.003067      0.897938      3.190029      0.027212   
std        0.0      0.055298      0.302740      2.526227      0.162707   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      1.000000      1.000000      0.000000   
50%        0.0      0.000000      1.000000      2.000000      0.000000   
75%        0.0      0.000000      1.000000      4.000000      0.000000   
max        0.0      1.000000      1.000000     18.000000      1.000000   

       https Domain       TinyURL  Prefix/Suffix   Have client    Have admin  \
count  15324.000000  15324.000000   15324.000000  15324.000000  15324.000000   
mean       0.027930      0.034978       0.073871      0.001305      0.010702   
std        0.164778      0.183730       0.261569      0.036104      0.102900   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      0.000000   
50%        0.000000      0.000000       0.000000      0.000000      0.000000   
75%        0.000000      0.000000       0.000000      0.000000      0.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

       ...          .txt           .js          .exe  Num of periods  \
count  ...  15324.000000  15324.000000  15324.000000    15324.000000   
mean   ...      0.003132      0.026429      0.001305        2.598865   
std    ...      0.055881      0.160413      0.036104        1.816973   
min    ...      0.000000      0.000000      0.000000        1.000000   
25%    ...      0.000000      0.000000      0.000000        1.000000   
50%    ...      0.000000      0.000000      0.000000        2.000000   
75%    ...      0.000000      0.000000      0.000000        3.000000   
max    ...      1.000000      1.000000      1.000000       21.000000   

         Is encoded  Num of encoded char  Num of parameters  Num of digits  \
count  15324.000000         15324.000000       15324.000000   15324.000000   
mean       0.211564             5.016445           1.348147      15.870204   
std        0.408430            12.407880           2.519592      16.435665   
min        0.000000             0.000000           0.000000       0.000000   
25%        0.000000             0.000000           0.000000       4.000000   
50%        0.000000             0.000000           0.000000      11.000000   
75%        0.000000             0.000000           2.000000      25.000000   
max        1.000000           201.000000          19.000000     259.000000   

       Num of spec char         Label  
count      15324.000000  15324.000000  
mean          10.220765      1.775907  
std           12.732849      1.471309  
min            0.000000      0.000000  
25%            1.000000      0.000000  
50%            7.000000      2.000000  
75%           13.000000      3.000000  
max          201.000000      4.000000  

[8 rows x 25 columns]

In [9]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                0
Have @                 0
URL Length             0
URL Depth              0
Redirection            0
https Domain           0
TinyURL                0
Prefix/Suffix          0
Have client            0
Have admin             0
Have login             0
Have server            0
.php                   0
.html                  0
.info                  0
.txt                   0
.js                    0
.exe                   0
Num of periods         0
Is encoded             0
Num of encoded char    0
Num of parameters      0
Num of digits          0
Num of spec char       0
Label                  0
dtype: int64

In [10]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          2            0             0        0   
1        0       0           1          4            0             0        0   
2        0       0           1          5            0             0        0   
3        0       0           1         10            0             0        0   
4        0       0           1          6            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               8           0                    0                  1   
1               1           1                   51                  0   
2               2           0                    0                  6   
3               1           0                    0                  0   
4               4           0                    0                  0   

   Num of digits  Num of spec char  Label  
0             30                 1      0  
1             59                54      0  
2             67                30      2  
3             23                 0      0  
4             18                 0      1  

[5 rows x 25 columns]

In [11]:
import numpy as np

# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))


print(x.shape, y.shape)


(15324, 24) (15324,)


In [12]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(8428, 24) (6896, 24)
(8428,) (6896,)


In [13]:
output = {}
output['labels'] = y_test

**DecisionTree Classifier**

In [14]:
import keras

from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import pickle
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  dtcclassifier = DecisionTreeClassifier(max_depth=5)
  #compile model using mse as a measure of model performance
  dtcclassifier.fit(x_train, y_train)

  y_pred = dtcclassifier.predict(x_val)
  
  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/DTC/model_'+str(n)+'.h5'
  pickle.dump(dtcclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [15]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[259   7   8   5   1]
 [  5  54  23   2   0]
 [  8   1 134   5  12]
 [ 17   0  42 132  10]
 [  4   1  28   4  81]]
Precision: 0.8089
Recall: 0.7829
F1 Score: 0.7848
Validation Accuracy: 0.7829181494661922
model 0 saved
[[217  10   9  15   4]
 [  2  66  25   2   1]
 [  6   0 135   7   5]
 [ 14   2  32 154   8]
 [  4   4  28   6  87]]
Precision: 0.8041
Recall: 0.7817
F1 Score: 0.7849
Validation Accuracy: 0.7817319098457889
model 1 saved
[[262   5   7   2   6]
 [  3  65  15   3   4]
 [  2   0 127  11  18]
 [  7   0  46 131  17]
 [  4   1  14   5  88]]
Precision: 0.8203
Recall: 0.7983
F1 Score: 0.8013
Validation Accuracy: 0.7983392645314353
model 2 saved
[[240   8  11   7   0]
 [  6  65  19   2   0]
 [  6   1 131   8  11]
 [ 16   0  43 134  12]
 [  0   2  24   0  97]]
Precision: 0.8167
Recall: 0.7912
F1 Score: 0.7944
Validation Accuracy: 0.7912218268090154
model 3 saved
[[272   5   9   6   0]
 [  2  65  23   3   0]
 [ 10   2 130   8  11]
 [  6   3  37 124   0]
 [  4   3  34   1  85]]
Prec

In [17]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/DTC/model_4.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['dt_prediction_non'] = [i[0] for i in y_pred_prob];
output['dt_prediction_phish'] = [i[1] for i in y_pred_prob];
output['dt_prediction_spam'] = [i[2] for i in y_pred_prob];
output['dt_prediction_malware'] = [i[3] for i in y_pred_prob];
output['dt_prediction_defacemen'] = [i[4] for i in y_pred_prob];

output = pd.DataFrame.from_dict(output)
output


[[0.2        0.70666667 0.01777778 0.02222222 0.05333333]
 [0.         0.         0.         1.         0.        ]
 [0.00782779 0.02152642 0.94716243 0.         0.02348337]
 ...
 [0.0655527  0.11696658 0.35861183 0.10154242 0.35732648]
 [0.2        0.70666667 0.01777778 0.02222222 0.05333333]
 [0.99243466 0.00412655 0.         0.00343879 0.        ]]


labels  dt_prediction_non  dt_prediction_phish  dt_prediction_spam  \
0          0           0.200000             0.706667            0.017778   
1          3           0.000000             0.000000            0.000000   
2          2           0.007828             0.021526            0.947162   
3          4           0.000000             0.001522            0.108067   
4          0           0.992435             0.004127            0.000000   
...      ...                ...                  ...                 ...   
6891       0           0.992435             0.004127            0.000000   
6892       0           0.992435             0.004127            0.000000   
6893       1           0.065553             0.116967            0.358612   
6894       1           0.200000             0.706667            0.017778   
6895       0           0.992435             0.004127            0.000000   

      dt_prediction_malware  dt_prediction_defacemen  
0                  0.022222                 0.053333  
1                  1.000000                 0.000000  
2                  0.000000                 0.023483  
3                  0.009132                 0.881279  
4                  0.003439                 0.000000  
...                     ...                      ...  
6891               0.003439                 0.000000  
6892               0.003439                 0.000000  
6893               0.101542                 0.357326  
6894               0.022222                 0.053333  
6895               0.003439                 0.000000  

[6896 rows x 6 columns]

**KNN**

In [18]:
import keras

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_knn(x_train, x_val, y_train, y_val, opt, n):
  knnclassifier = KNeighborsClassifier(n_neighbors=7, weights='uniform', algorithm='kd_tree', leaf_size=5)
  #compile model using mse as a measure of model performance
  knnclassifier.fit(x_train, y_train)

  y_pred = knnclassifier.predict(x_val)
  
  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/KNN/model_'+str(n)+'.h5'
  pickle.dump(knnclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [19]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_knn(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[266   2   6   4   2]
 [  4  63  10   4   3]
 [  4   2 142   1  11]
 [  8   5   6 181   1]
 [  2   1   3   1 111]]
Precision: 0.9058
Recall: 0.9051
F1 Score: 0.9046
Validation Accuracy: 0.9051008303677343
model 0 saved
[[229   5  10  11   0]
 [  6  76  12   1   1]
 [  2   2 144   0   5]
 [  4   1   6 199   0]
 [  2   2  10   5 110]]
Precision: 0.9039
Recall: 0.8992
F1 Score: 0.8995
Validation Accuracy: 0.8991696322657177
model 1 saved
[[267   3   5   6   1]
 [  5  73   7   2   3]
 [  1   2 148   0   7]
 [  4   6   6 184   1]
 [  1   0   2   3 106]]
Precision: 0.9235
Recall: 0.9229
F1 Score: 0.9228
Validation Accuracy: 0.9228944246737841
model 2 saved
[[253   4   2   6   1]
 [  4  73  11   3   1]
 [  3   2 143   2   7]
 [ 12   1   7 184   1]
 [  1   0   7   1 114]]
Precision: 0.9111
Recall: 0.9098
F1 Score: 0.9096
Validation Accuracy: 0.9098457888493475
model 3 saved
[[271   3   5  12   1]
 [  4  75   4   6   4]
 [  1   0 150   2   8]
 [  6   6   5 151   2]
 [  4   0   5   1 117]]
Prec

In [20]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/KNN/model_2.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['knn_prediction_non'] = [i[0] for i in y_pred_prob];
output['knn_prediction_phish'] = [i[1] for i in y_pred_prob];
output['knn_prediction_spam'] = [i[2] for i in y_pred_prob];
output['knn_prediction_malware'] = [i[3] for i in y_pred_prob];
output['knn_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[1.         0.         0.         0.         0.        ]
 [0.         0.         0.         1.         0.        ]
 [0.         0.         1.         0.         0.        ]
 ...
 [0.         0.         0.14285714 0.         0.85714286]
 [0.         1.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.        ]]


labels  dt_prediction_non  dt_prediction_phish  dt_prediction_spam  \
0          0           0.200000             0.706667            0.017778   
1          3           0.000000             0.000000            0.000000   
2          2           0.007828             0.021526            0.947162   
3          4           0.000000             0.001522            0.108067   
4          0           0.992435             0.004127            0.000000   
...      ...                ...                  ...                 ...   
6891       0           0.992435             0.004127            0.000000   
6892       0           0.992435             0.004127            0.000000   
6893       1           0.065553             0.116967            0.358612   
6894       1           0.200000             0.706667            0.017778   
6895       0           0.992435             0.004127            0.000000   

      dt_prediction_malware  dt_prediction_defacemen  knn_prediction_non  \
0                  0.022222                 0.053333                 1.0   
1                  1.000000                 0.000000                 0.0   
2                  0.000000                 0.023483                 0.0   
3                  0.009132                 0.881279                 0.0   
4                  0.003439                 0.000000                 1.0   
...                     ...                      ...                 ...   
6891               0.003439                 0.000000                 1.0   
6892               0.003439                 0.000000                 1.0   
6893               0.101542                 0.357326                 0.0   
6894               0.022222                 0.053333                 0.0   
6895               0.003439                 0.000000                 1.0   

      knn_prediction_phish  knn_prediction_spam  knn_prediction_malware  \
0                      0.0             0.000000                     0.0   
1                      0.0             0.000000                     1.0   
2                      0.0             1.000000                     0.0   
3                      0.0             0.000000                     0.0   
4                      0.0             0.000000                     0.0   
...                    ...                  ...                     ...   
6891                   0.0             0.000000                     0.0   
6892                   0.0             0.000000                     0.0   
6893                   0.0             0.142857                     0.0   
6894                   1.0             0.000000                     0.0   
6895                   0.0             0.000000                     0.0   

      knn_prediction_defacemen  
0                     0.000000  
1                     0.000000  
2                     0.000000  
3                     1.000000  
4                     0.000000  
...                        ...  
6891                  0.000000  
6892                  0.000000  
6893                  0.857143  
6894                  0.000000  
6895                  0.000000  

[6896 rows x 11 columns]

**XGB Classifier**

In [ ]:
import keras

from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_xgb(x_train, x_val, y_train, y_val, opt, n):
  xgbclassifier = XGBClassifier(n_neighbors=5)
  #compile model using mse as a measure of model performance
  xgbclassifier.fit(x_train, y_train)

  y_pred = xgbclassifier.predict(x_val)
  
  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))


  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/XGBoost/model_'+str(n)+'.h5'
  pickle.dump(xgbclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_xgb(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[266   3   4   2   0]
 [  6  66   9   1   3]
 [  2   1 136   2  18]
 [  5   2  11 171   1]
 [  1   1   2   2 128]]
Precision: 0.9116
Recall: 0.9098
F1 Score: 0.9095
Validation Accuracy: 0.9098457888493475
model 0 saved
[[259   1   7   3   1]
 [ 10  85   5   0   3]
 [  5   0 133   2  20]
 [  9   3   2 170   1]
 [  0   0   4   1 119]]
Precision: 0.9116
Recall: 0.9087
F1 Score: 0.9084
Validation Accuracy: 0.9086595492289442
model 1 saved
[[237   5   6   5   2]
 [  6  72   7   0   1]
 [  4   0 136   3  18]
 [  6   3   6 193   0]
 [  0   1   8   4 120]]
Precision: 0.9000
Recall: 0.8992
F1 Score: 0.8993
Validation Accuracy: 0.8991696322657177
model 2 saved
[[258   0   3   2   1]
 [  2  64   4   3   1]
 [  5   0 136   0  21]
 [ 11   8   9 192   3]
 [  1   0   4   0 115]]
Precision: 0.9112
Recall: 0.9075
F1 Score: 0.9073
Validation Accuracy: 0.9074733096085409
model 3 saved
[[261   2  13   6   0]
 [  5  82   8   1   0]
 [  3   2 133   1  19]
 [ 10   1  10 167   2]
 [  0   0   5   1 111]]
Prec

In [21]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/URL/XGBoost/model_5.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['XGB_prediction_non'] = [i[0] for i in y_pred_prob];
output['XGB_prediction_phish'] = [i[1] for i in y_pred_prob];
output['XGB_prediction_spam'] = [i[2] for i in y_pred_prob];
output['XGB_prediction_malware'] = [i[3] for i in y_pred_prob];
output['XGB_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[7.5223672e-01 1.8642022e-01 1.8277053e-02 3.7348256e-02 5.7177669e-03]
 [4.2283959e-03 1.8964837e-03 1.2486348e-03 9.9226123e-01 3.6527935e-04]
 [2.8793477e-03 6.8283235e-03 9.7687519e-01 1.8579804e-03 1.1559188e-02]
 ...
 [1.5573910e-01 2.7374424e-02 2.7484602e-01 8.0760606e-03 5.3396440e-01]
 [1.4852868e-01 5.9961587e-01 5.8034945e-02 1.8343455e-01 1.0385946e-02]
 [9.8972160e-01 6.4860550e-03 6.8609638e-04 2.9457856e-03 1.6053248e-04]]


labels  dt_prediction_non  dt_prediction_phish  dt_prediction_spam  \
0          0           0.200000             0.706667            0.017778   
1          3           0.000000             0.000000            0.000000   
2          2           0.007828             0.021526            0.947162   
3          4           0.000000             0.001522            0.108067   
4          0           0.992435             0.004127            0.000000   
...      ...                ...                  ...                 ...   
6891       0           0.992435             0.004127            0.000000   
6892       0           0.992435             0.004127            0.000000   
6893       1           0.065553             0.116967            0.358612   
6894       1           0.200000             0.706667            0.017778   
6895       0           0.992435             0.004127            0.000000   

      dt_prediction_malware  dt_prediction_defacemen  knn_prediction_non  \
0                  0.022222                 0.053333                 1.0   
1                  1.000000                 0.000000                 0.0   
2                  0.000000                 0.023483                 0.0   
3                  0.009132                 0.881279                 0.0   
4                  0.003439                 0.000000                 1.0   
...                     ...                      ...                 ...   
6891               0.003439                 0.000000                 1.0   
6892               0.003439                 0.000000                 1.0   
6893               0.101542                 0.357326                 0.0   
6894               0.022222                 0.053333                 0.0   
6895               0.003439                 0.000000                 1.0   

      knn_prediction_phish  knn_prediction_spam  knn_prediction_malware  \
0                      0.0             0.000000                     0.0   
1                      0.0             0.000000                     1.0   
2                      0.0             1.000000                     0.0   
3                      0.0             0.000000                     0.0   
4                      0.0             0.000000                     0.0   
...                    ...                  ...                     ...   
6891                   0.0             0.000000                     0.0   
6892                   0.0             0.000000                     0.0   
6893                   0.0             0.142857                     0.0   
6894                   1.0             0.000000                     0.0   
6895                   0.0             0.000000                     0.0   

      knn_prediction_defacemen  XGB_prediction_non  XGB_prediction_phish  \
0                     0.000000            0.752237              0.186420   
1                     0.000000            0.004228              0.001896   
2                     0.000000            0.002879              0.006828   
3                     1.000000            0.001252              0.002887   
4                     0.000000            0.990474              0.006491   
...                        ...                 ...                   ...   
6891                  0.000000            0.987138              0.000955   
6892                  0.000000            0.989750              0.006486   
6893                  0.857143            0.155739              0.027374   
6894                  0.000000            0.148529              0.599616   
6895                  0.000000            0.989722              0.006486   

      XGB_prediction_spam  XGB_prediction_malware  XGB_prediction_defacemen  
0                0.018277                0.037348                  0.005718  
1                0.001249                0.992261                  0.000365  
2                0.976875                0.001858                  0.011559  
3                0.025582                0.007450     

In [22]:
output.shape


(6896, 16)

In [23]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Multi/Base_classifier_result(URL cross).csv', index=False)