In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(multi).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0               0        0       0           1          1            0   
1               1        0       0           1          1            1   
2               2        0       0           1          1            0   
3               3        0       0           1          3            0   
4               4        0       0           1          3            0   
...           ...      ...     ...         ...        ...          ...   
15319       23429        0       0           1          1            0   
15320       23430        0       0           1          1            0   
15321       23431        0       0           1          1            0   
15322       23432        0       0           1          1            0   
15323       23433        0       0           1          1            0   

       https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                 0        0              0            0  ...           0   
1                 0        0              0            0  ...           0   
2                 1        0              0            0  ...           0   
3                 0        0              0            0  ...           0   
4                 0        0              0            0  ...           0   
...             ...      ...            ...          ...  ...         ...   
15319             0        0              0            0  ...           0   
15320             0        0              0            0  ...           0   
15321             0        0              0            0  ...           0   
15322             0        0              0            0  ...           0   
15323             0        0              0            0  ...           0   

       Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0              49        691          42       13135                6400   
1               4         66           3        2034                 818   
2               1        100          27       32987               10451   
3               0          0           1           0                  52   
4             117        219          23        7944                3468   
...           ...        ...         ...         ...                 ...   
15319           0          0           1           0                   4   
15320           0          0           1           0                   4   
15321           0          0           1           0                   4   
15322           0          0           1           0                   4   
15323           0          0           1           0                   4   

       Script To Special Chars Ratio  Script To body Ratio  \
0                           2.052344              0.528869   
1                           2.486553              0.676197   
2                           3.156349              0.836681   
3                           0.000000              0.000000   
4                           2.290657              0.524460   
...                              ...                   ...   
15319                       0.000000              0.000000   
15320                       0.000000              0.000000   
15321                       0.000000              0.000000   
15322                       0.000000              0.000000   
15323                       0.000000              0.000000   

       Body To Special Char Ratio  Label  
0                        0.257690      0  
1                        0.271941      0  
2                        0.265079      0  
3                        0.227074      0  
4                        0.228956      0  
...                           ...    ...  
15319                    0.121212      4  
15320                    0.121212      4  
15321                    0.121212      4  
15322                    0.121212      4  
15323                    0.121212      4  

[15324 rows x 46 c

In [ ]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [ ]:
urldata = urldata.drop(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                  21444   
1       1           0            0             1                   1075   
2       1           0            0             1                   4531   
3       1           0            0             1                     32   
4       1           0            0             1                   4880   

   number of sentences  number of html tags  number of whitespace  \
0                 1853                 3247                     0   
1                  136                  236                     0   
2                 2634                  486                     0   
3                    9                    8                     0   
4                  981                 1412                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1        24836  ...           0          49        691   
1            1         3008  ...           0           4         66   
2            1        39426  ...           0           1        100   
3            0          229  ...           0           0          0   
4            1        15147  ...           0         117        219   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0          42       13135                6400                       2.052344   
1           3        2034                 818                       2.486553   
2          27       32987               10451                       3.156349   
3           1           0                  52                       0.000000   
4          23        7944                3468                       2.290657   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.528869                    0.257690      0  
1              0.676197                    0.271941      0  
2              0.836681                    0.265079      0  
3              0.000000                    0.227074      0  
4              0.524460                    0.228956      0  

[5 rows x 21 columns]

In [ ]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15324 entries, 0 to 15323
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   iFrame                         15324 non-null  int64  
 1   Mouse Over                     15324 non-null  int64  
 2   Right Click                    15324 non-null  int64  
 3   Web Forwards                   15324 non-null  int64  
 4   Number of page tokens          15324 non-null  int64  
 5   number of sentences            15324 non-null  int64  
 6   number of html tags            15324 non-null  int64  
 7   number of whitespace           15324 non-null  int64  
 8   url Is Live                    15324 non-null  int64  
 9   HTML Length                    15324 non-null  int64  
 10  Num Objects                    15324 non-null  int64  
 11  Num Embeds                     15324 non-null  int64  
 12  Num Images                     15324 non-null 

In [ ]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
2    3002
3    3543
4    2252
dtype: int64

In [ ]:

import numpy as np


In [ ]:
urldata.describe()

iFrame    Mouse Over  Right Click  Web Forwards  \
count  15324.000000  15324.000000      15324.0  15324.000000   
mean       0.993148      0.000131          0.0      0.910598   
std        0.082495      0.011424          0.0      0.285333   
min        0.000000      0.000000          0.0      0.000000   
25%        1.000000      0.000000          0.0      1.000000   
50%        1.000000      0.000000          0.0      1.000000   
75%        1.000000      0.000000          0.0      1.000000   
max        1.000000      1.000000          0.0      1.000000   

       Number of page tokens  number of sentences  number of html tags  \
count           15324.000000         15324.000000         15324.000000   
mean             2916.589076          1156.923845           316.643892   
std              5841.863156          2952.857402           644.355934   
min                 1.000000             1.000000             1.000000   
25%                27.000000             7.000000             8.000000   
50%               423.000000            83.000000            42.000000   
75%              3239.000000          1415.000000           416.000000   
max            127712.000000         43777.000000         14280.000000   

       number of whitespace   url Is Live   HTML Length  ...    Num Embeds  \
count               15324.0  15324.000000  1.532400e+04  ...  15324.000000   
mean                    0.0      0.412621  3.038154e+04  ...      0.000261   
std                     0.0      0.499298  8.331941e+04  ...      0.016155   
min                     0.0     -1.000000  0.000000e+00  ...      0.000000   
25%                     0.0      0.000000  7.100000e+01  ...      0.000000   
50%                     0.0      0.000000  2.257000e+03  ...      0.000000   
75%                     0.0      1.000000  3.259600e+04  ...      0.000000   
max                     0.0      1.000000  2.107635e+06  ...      1.000000   

         Num Images     Num Links    Num Titles    Num Script  \
count  15324.000000  15324.000000  15324.000000  1.532400e+04   
mean       9.431480     53.732642      8.138476  1.907060e+04   
std       31.982449    105.014700     30.703307  6.790900e+04   
min        0.000000     -1.000000     -1.000000 -1.000000e+00   
25%        0.000000      0.000000      0.000000  0.000000e+00   
50%        0.000000      2.000000      1.000000  7.770000e+02   
75%        4.000000     66.000000      4.000000  1.592400e+04   
max      816.000000   1740.000000   1042.000000  2.076633e+06   

       Special Characters  Script To Special Chars Ratio  \
count        15324.000000                   15324.000000   
mean          7416.632407                       3.722576   
std          18369.465282                      17.536106   
min              0.000000                      -1.000000   
25%             12.000000                       0.000000   
50%            557.000000                       1.324700   
75%           8311.000000                       2.625806   
max         359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio         Label  
count          15324.000000                15324.000000  15324.000000  
mean               0.367024                    0.192536      1.775907  
std                0.375838                    0.112498      1.471309  
min               -1.000000                    0.000000      0.000000  
25%                0.000000                    0.141286      0.000000  
50%                0.312289                    0.225350      2.000000  
75%                0.718077                    0.263237      3.000000  
max                1.005038                    0.733333      4.000000  

[8 rows x 21 columns]

In [ ]:
#checking the data for null or missing values
urldata.isnull().sum()

iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page tokens            0
number of sentences              0
number of html tags              0
number of whitespace             0
url Is Live                      0
HTML Length                      0
Num Objects                      0
Num Embeds                       0
Num Images                       0
Num Links                        0
Num Titles                       0
Num Script                       0
Special Characters               0
Script To Special Chars Ratio    0
Script To body Ratio             0
Body To Special Char Ratio       0
Label                            0
dtype: int64

In [ ]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                   1417   
1       1           0            0             1                    723   
2       1           0            0             1                    111   
3       1           0            0             1                    395   
4       1           0            0             1                   5899   

   number of sentences  number of html tags  number of whitespace  \
0                  247                  205                     0   
1                  163                  243                     0   
2                    7                   14                     0   
3                   49                   55                     0   
4                 2029                  528                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1         6676  ...           0           9          5   
1            1         2087  ...           0          14         62   
2            0          268  ...           0           0          1   
3            1         1946  ...           0           0          6   
4            1        69543  ...           0           2        134   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0          10        4709                1812                       2.598786   
1           0        1049                 536                       1.957090   
2           2           0                  52                       0.000000   
3           1         149                 555                       0.268468   
4           1       63854               20085                       3.179188   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.705362                    0.271420      4  
1              0.502635                    0.256828      4  
2              0.000000                    0.194030      3  
3              0.076567                    0.285200      1  
4              0.918194                    0.288814      2  

[5 rows x 21 columns]

In [ ]:
import numpy as np
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [ ]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(8428, 20) (6896, 20)
(8428,) (6896,)


In [ ]:
output = {}
output['labels'] = y_test

**MLP**

In [ ]:
import keras

from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle

def model_mlp(x_train, x_val, y_train, y_val, opt, n):
  mlpclassifier = MLPClassifier(alpha=0.0001, hidden_layer_sizes=([100,100,100]))
  #compile model using mse as a measure of model performance
  mlpclassifier.fit(x_train, y_train)

  y_pred = mlpclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/MLP/model_'+str(n)+'.h5'
  pickle.dump(mlpclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_mlp(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[204   1  33   5  43]
 [ 19  19  15  16  32]
 [ 18   2 120   0  11]
 [  8   5  12 162  12]
 [  6  11  13   5  71]]
Precision: 0.6989
Recall: 0.6833
F1 Score: 0.6761
Validation Accuracy: 0.6832740213523132
model 0 saved
[[162   7  63  22  21]
 [ 14  30  20  12  33]
 [ 10   0 127   2   9]
 [  5   2  16 167   9]
 [  6   8  23   5  70]]
Precision: 0.6954
Recall: 0.6595
F1 Score: 0.6529
Validation Accuracy: 0.6595492289442467
model 1 saved
[[209   8  19   7  28]
 [ 16  33  11   6  25]
 [ 13   6 117   7   9]
 [  6   4   1 170  12]
 [  9  11   0   4 112]]
Precision: 0.7633
Recall: 0.7604
F1 Score: 0.7570
Validation Accuracy: 0.7603795966785291
model 2 saved
[[211  11  12   7  25]
 [ 14  43  13   8  12]
 [ 11  18 146   3   8]
 [  2  15   3 156   3]
 [  6  19   9   6  82]]
Precision: 0.7675
Recall: 0.7568
F1 Score: 0.7613
Validation Accuracy: 0.7568208778173191
model 3 saved
[[243  16   5  13   6]
 [ 17  30   2  11  16]
 [ 13  20 115   4   9]
 [ 13  10   1 169   5]
 [  7   9   3   4 102]]
Prec

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/MLP/model_4.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['mlp_prediction_non'] = [i[0] for i in y_pred_prob];
output['mlp_prediction_phish'] = [i[1] for i in y_pred_prob];
output['mlp_prediction_spam'] = [i[2] for i in y_pred_prob];
output['mlp_prediction_malware'] = [i[3] for i in y_pred_prob];
output['mlp_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[3.28595502e-008 2.27595203e-038 9.99999967e-001 3.53644837e-103
  5.45258001e-062]
 [9.87170919e-001 1.40065769e-005 8.88707177e-004 3.09404654e-004
  1.16169622e-002]
 [5.43199900e-003 7.26519788e-003 9.75126111e-001 1.06356829e-002
  1.54100894e-003]
 ...
 [1.95654589e-064 3.95504084e-062 4.27920447e-132 1.00000000e+000
  2.77532688e-194]
 [1.44909380e-001 2.97695615e-001 3.11118892e-001 1.09381100e-001
  1.36895013e-001]
 [9.38118847e-001 6.25375208e-004 6.04173309e-002 2.58007396e-005
  8.12646395e-004]]


labels  mlp_prediction_non  mlp_prediction_phish  mlp_prediction_spam  \
0          2        3.285955e-08          2.275952e-38         1.000000e+00   
1          0        9.871709e-01          1.400658e-05         8.887072e-04   
2          2        5.431999e-03          7.265198e-03         9.751261e-01   
3          3        6.821167e-02          8.999669e-02         4.175485e-02   
4          0        1.000000e+00          9.884499e-29         3.997525e-14   
...      ...                 ...                   ...                  ...   
6891       2        1.120535e-12          1.117325e-44         1.000000e+00   
6892       2        8.522478e-04          1.933313e-04         9.989540e-01   
6893       3        1.956546e-64          3.955041e-62        4.279204e-132   
6894       0        1.449094e-01          2.976956e-01         3.111189e-01   
6895       0        9.381188e-01          6.253752e-04         6.041733e-02   

      mlp_prediction_malware  mlp_prediction_defacemen  
0              3.536448e-103              5.452580e-62  
1               3.094047e-04              1.161696e-02  
2               1.063568e-02              1.541009e-03  
3               7.832318e-01              1.680500e-02  
4               4.412196e-13              2.773055e-33  
...                      ...                       ...  
6891           9.068879e-112              2.337164e-60  
6892            4.423567e-07              4.685219e-15  
6893            1.000000e+00             2.775327e-194  
6894            1.093811e-01              1.368950e-01  
6895            2.580074e-05              8.126464e-04  

[6896 rows x 6 columns]

**Neural Network**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_aa(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]
  # print("check point")
  #create model
  model = Sequential()
  model.add(Dense(30, activation='relu', input_shape=(n_cols,)))
  model.add(Dense(10, activation='relu'))

  model.add(Dense(1, activation = 'sigmoid'))
  # softmax
  #compile model using mse as a measure of model performance
  model.compile(optimizer = opt, loss= 'binary_crossentropy', metrics=["accuracy"])

  history = model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/NN/model_'+str(n)+'.h5'
  pickle.dump(model, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_aa(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
238/238 [==============================] - 5s 5ms/step - loss: 556.1033 - accuracy: 0.1034 - val_loss: 798.4049 - val_accuracy: 0.1198
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -336.1695 - accuracy: 0.1188 - val_loss: -135.1720 - val_accuracy: 0.2183
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -841.2561 - accuracy: 0.1332 - val_loss: -285.2514 - val_accuracy: 0.2052
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -1605.4834 - accuracy: 0.1288 - val_loss: -99.3229 - val_accuracy: 0.2076
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -2588.7893 - accuracy: 0.1346 - val_loss: -641.0293 - val_accuracy: 0.2147
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -3913.5723 - accuracy: 0.1351 - val_loss: -775.1376 - val_accuracy: 0.2064
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: -5784.5952 - accuracy: 0.1312 -

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://bc77b786-686f-442f-9fe1-2af8d3779387/assets
model 0 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 108.9928 - accuracy: 0.1225 - val_loss: -512.5244 - val_accuracy: 0.2064
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -980.0496 - accuracy: 0.1463 - val_loss: -1209.2523 - val_accuracy: 0.2123
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -1929.6737 - accuracy: 0.1390 - val_loss: -2027.9550 - val_accuracy: 0.2195
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -3164.0654 - accuracy: 0.1363 - val_loss: -3153.6836 - val_accuracy: 0.1376
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -5060.2163 - accuracy: 0.1359 - val_loss: -5056.8765 - val_accuracy: 0.2112
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -7555.4634 - accuracy: 0.1508 - val_loss: -7434.6265 - val_accuracy: 0.1329

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://37c249c7-6ab9-48cd-8c45-7daf075b9ba1/assets
model 1 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -145.5618 - accuracy: 0.1354 - val_loss: -551.9398 - val_accuracy: 0.1934
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -557.1210 - accuracy: 0.1383 - val_loss: -871.3253 - val_accuracy: 0.1234
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -919.8246 - accuracy: 0.1342 - val_loss: -1384.3962 - val_accuracy: 0.1945
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -1415.5052 - accuracy: 0.1450 - val_loss: -1889.6941 - val_accuracy: 0.1222
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -2003.9774 - accuracy: 0.1366 - val_loss: -2380.1460 - val_accuracy: 0.1079
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -2729.9075 - accuracy: 0.1310 - val_loss: -3497.4780 - val_accuracy: 0.1993


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://d3c112c6-0fc3-419a-ad1c-078a0d96d616/assets
model 2 saved
Epoch 1/100
238/238 [==============================] - 1s 4ms/step - loss: 58.1056 - accuracy: 0.1136 - val_loss: -62.8636 - val_accuracy: 0.1068
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -126.9797 - accuracy: 0.1049 - val_loss: -382.8535 - val_accuracy: 0.1068
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -373.9973 - accuracy: 0.1048 - val_loss: -942.3461 - val_accuracy: 0.1044
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -752.2592 - accuracy: 0.1072 - val_loss: -1710.4470 - val_accuracy: 0.1044
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -1292.1948 - accuracy: 0.1092 - val_loss: -2809.3396 - val_accuracy: 0.1091
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -2033.6929 - accuracy: 0.1122 - val_loss: -4271.2007 - val_accuracy: 0.1079
Epoch

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://1d153a16-1a03-42b7-abc8-91c1742998cf/assets
model 3 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 4.7957 - accuracy: 0.1446 - val_loss: 46.8994 - val_accuracy: 0.2633
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -256.5463 - accuracy: 0.1549 - val_loss: -547.7361 - val_accuracy: 0.0949
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -702.7317 - accuracy: 0.1601 - val_loss: -1078.0341 - val_accuracy: 0.2005
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -1334.1093 - accuracy: 0.1595 - val_loss: -2164.8662 - val_accuracy: 0.1708
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -2265.2305 - accuracy: 0.1635 - val_loss: -3544.0305 - val_accuracy: 0.1637
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -3530.2529 - accuracy: 0.1504 - val_loss: -5487.3062 - val_accuracy: 0.1032
Epoch

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://129f95c2-607f-4bfe-9ce0-44f7147d138f/assets
model 4 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 444.4575 - accuracy: 0.1643 - val_loss: -289.5561 - val_accuracy: 0.2040
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -386.0880 - accuracy: 0.1678 - val_loss: -967.6592 - val_accuracy: 0.1684
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -860.5122 - accuracy: 0.1697 - val_loss: -1789.8811 - val_accuracy: 0.1684
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -1476.2579 - accuracy: 0.1721 - val_loss: -2872.0149 - val_accuracy: 0.1708
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -2313.0657 - accuracy: 0.1719 - val_loss: -4467.2109 - val_accuracy: 0.1139
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -3488.2510 - accuracy: 0.1764 - val_loss: -6542.7441 - val_accuracy: 0.1139
E

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://05976e5a-36ca-463c-bec5-bd836bd6c949/assets
model 5 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -295.7018 - accuracy: 0.1462 - val_loss: -479.0841 - val_accuracy: 0.1044
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1525.2767 - accuracy: 0.1438 - val_loss: -1112.1831 - val_accuracy: 0.0996
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -3122.1465 - accuracy: 0.1432 - val_loss: -2042.0131 - val_accuracy: 0.1732
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -5448.1226 - accuracy: 0.1454 - val_loss: -3090.1094 - val_accuracy: 0.0973
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -8343.1035 - accuracy: 0.1357 - val_loss: -4794.4565 - val_accuracy: 0.1779
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -12361.3848 - accuracy: 0.1494 - val_loss: -7813.0693 - val_accuracy: 0.1

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://dfbc0b6c-ba5d-43dd-a598-afd074051072/assets
model 6 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 54.8897 - accuracy: 0.1035 - val_loss: -1289.5909 - val_accuracy: 0.1186
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -2457.4062 - accuracy: 0.1035 - val_loss: -3398.3726 - val_accuracy: 0.1186
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -5272.5552 - accuracy: 0.1035 - val_loss: -6425.5420 - val_accuracy: 0.1186
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -9305.8320 - accuracy: 0.1035 - val_loss: -10511.9668 - val_accuracy: 0.1186
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -14361.7559 - accuracy: 0.1035 - val_loss: -16038.5693 - val_accuracy: 0.1186
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -20665.8594 - accuracy: 0.1035 - val_loss: -22409.7305 - val_accuracy: 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://411c06d8-770a-4216-9111-a7b09e445eec/assets
model 7 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: -338.4665 - accuracy: 0.1428 - val_loss: -917.4303 - val_accuracy: 0.1556
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1311.3701 - accuracy: 0.1627 - val_loss: -1791.6987 - val_accuracy: 0.1188
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -2375.3245 - accuracy: 0.1523 - val_loss: -3152.4680 - val_accuracy: 0.1615
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -3861.8403 - accuracy: 0.1588 - val_loss: -5096.8823 - val_accuracy: 0.1556
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -5840.6226 - accuracy: 0.1575 - val_loss: -7272.6006 - val_accuracy: 0.1580
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -8100.1890 - accuracy: 0.1616 - val_loss: -9482.9453 - val_accuracy: 0.16

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://0051f48c-49bd-4aec-9cce-c858109448ca/assets
model 8 saved
Epoch 1/100
238/238 [==============================] - 1s 4ms/step - loss: -483.3956 - accuracy: 0.1720 - val_loss: -961.0836 - val_accuracy: 0.1865
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: -1546.1383 - accuracy: 0.1793 - val_loss: -2445.8770 - val_accuracy: 0.1544
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: -2804.0999 - accuracy: 0.1756 - val_loss: -3562.1228 - val_accuracy: 0.1556
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: -4354.6055 - accuracy: 0.1820 - val_loss: -5469.9175 - val_accuracy: 0.1568
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: -6204.0103 - accuracy: 0.1649 - val_loss: -7435.9443 - val_accuracy: 0.1520
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: -8501.1279 - accuracy: 0.1711 - val_loss: -9782.3916 - val_accuracy: 0.08

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://6c4df2c2-5ddc-4528-983c-a8a1f233fdf5/assets
model 9 saved
Average Validation Accuracy: 0.12197149643705463


In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/NN/model_1.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn_prediction_phish'] = [i[1] for i in y_pred_prob];
output['nn_prediction_spam'] = [i[2] for i in y_pred_prob];
output['nn_prediction_malware'] = [i[3] for i in y_pred_prob];
output['nn_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[3.28595502e-008 2.27595203e-038 9.99999967e-001 3.53644837e-103
  5.45258001e-062]
 [9.87170919e-001 1.40065769e-005 8.88707177e-004 3.09404654e-004
  1.16169622e-002]
 [5.43199900e-003 7.26519788e-003 9.75126111e-001 1.06356829e-002
  1.54100894e-003]
 ...
 [1.95654589e-064 3.95504084e-062 4.27920447e-132 1.00000000e+000
  2.77532688e-194]
 [1.44909380e-001 2.97695615e-001 3.11118892e-001 1.09381100e-001
  1.36895013e-001]
 [9.38118847e-001 6.25375208e-004 6.04173309e-002 2.58007396e-005
  8.12646395e-004]]


labels  mlp_prediction_non  mlp_prediction_phish  mlp_prediction_spam  \
0          2        3.285955e-08          2.275952e-38         1.000000e+00   
1          0        9.871709e-01          1.400658e-05         8.887072e-04   
2          2        5.431999e-03          7.265198e-03         9.751261e-01   
3          3        6.821167e-02          8.999669e-02         4.175485e-02   
4          0        1.000000e+00          9.884499e-29         3.997525e-14   
...      ...                 ...                   ...                  ...   
6891       2        1.120535e-12          1.117325e-44         1.000000e+00   
6892       2        8.522478e-04          1.933313e-04         9.989540e-01   
6893       3        1.956546e-64          3.955041e-62        4.279204e-132   
6894       0        1.449094e-01          2.976956e-01         3.111189e-01   
6895       0        9.381188e-01          6.253752e-04         6.041733e-02   

      mlp_prediction_malware  mlp_prediction_defacemen  nn_prediction_non  \
0              3.536448e-103              5.452580e-62       3.285955e-08   
1               3.094047e-04              1.161696e-02       9.871709e-01   
2               1.063568e-02              1.541009e-03       5.431999e-03   
3               7.832318e-01              1.680500e-02       6.821167e-02   
4               4.412196e-13              2.773055e-33       1.000000e+00   
...                      ...                       ...                ...   
6891           9.068879e-112              2.337164e-60       1.120535e-12   
6892            4.423567e-07              4.685219e-15       8.522478e-04   
6893            1.000000e+00             2.775327e-194       1.956546e-64   
6894            1.093811e-01              1.368950e-01       1.449094e-01   
6895            2.580074e-05              8.126464e-04       9.381188e-01   

      nn_prediction_phish  nn_prediction_spam  nn_prediction_malware  \
0            2.275952e-38        1.000000e+00          3.536448e-103   
1            1.400658e-05        8.887072e-04           3.094047e-04   
2            7.265198e-03        9.751261e-01           1.063568e-02   
3            8.999669e-02        4.175485e-02           7.832318e-01   
4            9.884499e-29        3.997525e-14           4.412196e-13   
...                   ...                 ...                    ...   
6891         1.117325e-44        1.000000e+00          9.068879e-112   
6892         1.933313e-04        9.989540e-01           4.423567e-07   
6893         3.955041e-62       4.279204e-132           1.000000e+00   
6894         2.976956e-01        3.111189e-01           1.093811e-01   
6895         6.253752e-04        6.041733e-02           2.580074e-05   

      nn_prediction_defacemen  
0                5.452580e-62  
1                1.161696e-02  
2                1.541009e-03  
3                1.680500e-02  
4                2.773055e-33  
...                       ...  
6891             2.337164e-60  
6892             4.685219e-15  
6893            2.775327e-194  
6894             1.368950e-01  
6895             8.126464e-04  

[6896 rows x 11 columns]

**Neural Network 2**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_a(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]

  #create model
  model_2 = Sequential()
  model_2.add(Dense(30, activation='sigmoid', input_shape=(n_cols,)))
  model_2.add(Dense(25, activation='sigmoid'))
  model_2.add(Dense(20, activation='sigmoid'))
  model_2.add(Dense(15, activation='sigmoid'))
  model_2.add(Dense(10, activation='sigmoid'))
  model_2.add(Dense(1, activation = 'sigmoid'))

  #compile model using mse as a measure of model performance
  model_2.compile(optimizer='adam', loss='mean_squared_error')



  history = model_2.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model_2.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred, average='weighted'))
  print('Recall: %.4f' % recall_score(y_val, y_pred, average='weighted'))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred, average='weighted'))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/NN_2/model_'+str(n)+'.h5'
  pickle.dump(model_2, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_a(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
238/238 [==============================] - 1s 4ms/step - loss: 3.1442 - val_loss: 2.7094
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8174 - val_loss: 2.6390
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7740 - val_loss: 2.6171
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7582 - val_loss: 2.6081
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7511 - val_loss: 2.6037
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7474 - val_loss: 2.6011
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7451 - val_loss: 2.5995
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7436 - val_loss: 2.5983
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7426 - val_loss: 2.5975
Epoch 10/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7418 - val_lo

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       286
           1       0.12      1.00      0.21       101
           2       0.00      0.00      0.00       151
           3       0.00      0.00      0.00       199
           4       0.00      0.00      0.00       106

    accuracy                           0.12       843
   macro avg       0.02      0.20      0.04       843
weighted avg       0.01      0.12      0.03       843

Accuracy: 0.11981020166073547
[[  0 286   0   0   0]
 [  0 101   0   0   0]
 [  0 151   0   0   0]
 [  0 199   0   0   0]
 [  0 106   0   0   0]]
Precision: 0.0144
Recall: 0.1198
F1 Score: 0.0256
INFO:tensorflow:Assets written to: ram://92d477f4-90f6-4bea-a092-bef39939c653/assets
model 0 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.3787 - val_loss: 2.8700
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8902 - val_loss: 2.7402
Epoch 3/100
23

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       275
           1       0.13      1.00      0.23       109
           2       0.00      0.00      0.00       148
           3       0.00      0.00      0.00       199
           4       0.00      0.00      0.00       112

    accuracy                           0.13       843
   macro avg       0.03      0.20      0.05       843
weighted avg       0.02      0.13      0.03       843

Accuracy: 0.12930011862396204
[[  0 275   0   0   0]
 [  0 109   0   0   0]
 [  0 148   0   0   0]
 [  0 199   0   0   0]
 [  0 112   0   0   0]]
Precision: 0.0167
Recall: 0.1293
F1 Score: 0.0296
INFO:tensorflow:Assets written to: ram://0f7ab600-42f0-45cd-be1d-387c9dbd8b92/assets
model 1 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.1458 - val_loss: 3.0329
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8059 - val_loss: 2.9362
Epoch 3/100
23

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://19aa7e29-0379-4d9d-a0f1-125d2be51f60/assets
model 2 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.0944 - val_loss: 2.8117
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8075 - val_loss: 2.7420
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7693 - val_loss: 2.7202
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7541 - val_loss: 2.7095
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7461 - val_loss: 2.7035
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7414 - val_loss: 2.6997
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7384 - val_loss: 2.6971
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7362 - val_loss: 2.6953
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7346 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       266
           1       0.11      1.00      0.19        90
           2       0.00      0.00      0.00       186
           3       0.00      0.00      0.00       179
           4       0.00      0.00      0.00       122

    accuracy                           0.11       843
   macro avg       0.02      0.20      0.04       843
weighted avg       0.01      0.11      0.02       843

Accuracy: 0.10676156583629894
[[  0 266   0   0   0]
 [  0  90   0   0   0]
 [  0 186   0   0   0]
 [  0 179   0   0   0]
 [  0 122   0   0   0]]
Precision: 0.0114
Recall: 0.1068
F1 Score: 0.0206
INFO:tensorflow:Assets written to: ram://a2f84ee8-06be-488f-aa11-94ba6f3193b7/assets
model 3 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 2.9339 - val_loss: 2.8776
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7659 - val_loss: 2.8353
Epoch 3/100
23

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       283
           1       0.09      1.00      0.17        76
           2       0.00      0.00      0.00       161
           3       0.00      0.00      0.00       198
           4       0.00      0.00      0.00       125

    accuracy                           0.09       843
   macro avg       0.02      0.20      0.03       843
weighted avg       0.01      0.09      0.01       843

Accuracy: 0.09015421115065243
[[  0 283   0   0   0]
 [  0  76   0   0   0]
 [  0 161   0   0   0]
 [  0 198   0   0   0]
 [  0 125   0   0   0]]
Precision: 0.0081
Recall: 0.0902
F1 Score: 0.0149
INFO:tensorflow:Assets written to: ram://d83bfa45-48e0-4527-ba82-9ea763cad872/assets
model 4 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.2012 - val_loss: 2.9192
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8272 - val_loss: 2.8307
Epoch 3/100
23

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       265
           1       0.11      1.00      0.19        90
           2       0.00      0.00      0.00       170
           3       0.00      0.00      0.00       195
           4       0.00      0.00      0.00       123

    accuracy                           0.11       843
   macro avg       0.02      0.20      0.04       843
weighted avg       0.01      0.11      0.02       843

Accuracy: 0.10676156583629894
[[  0 265   0   0   0]
 [  0  90   0   0   0]
 [  0 170   0   0   0]
 [  0 195   0   0   0]
 [  0 123   0   0   0]]
Precision: 0.0114
Recall: 0.1068
F1 Score: 0.0206
INFO:tensorflow:Assets written to: ram://0e264365-ec5b-4b52-99a0-83f274bdd5b3/assets
model 5 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.1839 - val_loss: 2.8663
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8331 - val_loss: 2.7706
Epoch 3/100
23

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://92b422f2-58a6-4187-9242-2e36f230fe2a/assets
model 6 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 3.0819 - val_loss: 2.7730
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8031 - val_loss: 2.7012
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7657 - val_loss: 2.6808
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7523 - val_loss: 2.6717
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7457 - val_loss: 2.6667
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7419 - val_loss: 2.6637
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7395 - val_loss: 2.6616
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7378 - val_loss: 2.6602
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7366 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://34ca09b0-b8aa-4d5f-be47-82bf1d568024/assets
model 7 saved
Epoch 1/100
238/238 [==============================] - 1s 4ms/step - loss: 3.5398 - val_loss: 3.0679
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.9852 - val_loss: 2.8706
Epoch 3/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8493 - val_loss: 2.7818
Epoch 4/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7894 - val_loss: 2.7480
Epoch 5/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7654 - val_loss: 2.7325
Epoch 6/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7535 - val_loss: 2.7239
Epoch 7/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7464 - val_loss: 2.7185
Epoch 8/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7418 - val_loss: 2.7148
Epoch 9/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7386 - val_loss:

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       287
           1       0.10      1.00      0.18        82
           2       0.00      0.00      0.00       153
           3       0.00      0.00      0.00       209
           4       0.00      0.00      0.00       111

    accuracy                           0.10       842
   macro avg       0.02      0.20      0.04       842
weighted avg       0.01      0.10      0.02       842

Accuracy: 0.09738717339667459
[[  0 287   0   0   0]
 [  0  82   0   0   0]
 [  0 153   0   0   0]
 [  0 209   0   0   0]
 [  0 111   0   0   0]]
Precision: 0.0095
Recall: 0.0974
F1 Score: 0.0173
INFO:tensorflow:Assets written to: ram://ee21c0e8-fb4f-463e-8fd1-b5023c4aab90/assets
model 8 saved
Epoch 1/100
238/238 [==============================] - 1s 3ms/step - loss: 2.8481 - val_loss: 2.8696
Epoch 2/100
238/238 [==============================] - 1s 3ms/step - loss: 2.7338 - val_loss: 2.8466
Epoch 3/100
23

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

INFO:tensorflow:Assets written to: ram://0227e7cf-744f-4597-ba30-b2a03c8ab898/assets
model 9 saved
Average Validation Accuracy: 0.10500277540623774


In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Multi/Models/HTML/NN_2/model_1.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn2_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn2_prediction_phish'] = [i[1] for i in y_pred_prob];
output['nn2_prediction_spam'] = [i[2] for i in y_pred_prob];
output['nn2_prediction_malware'] = [i[3] for i in y_pred_prob];
output['nn2_prediction_defacemen'] = [i[4] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[3.28595502e-008 2.27595203e-038 9.99999967e-001 3.53644837e-103
  5.45258001e-062]
 [9.87170919e-001 1.40065769e-005 8.88707177e-004 3.09404654e-004
  1.16169622e-002]
 [5.43199900e-003 7.26519788e-003 9.75126111e-001 1.06356829e-002
  1.54100894e-003]
 ...
 [1.95654589e-064 3.95504084e-062 4.27920447e-132 1.00000000e+000
  2.77532688e-194]
 [1.44909380e-001 2.97695615e-001 3.11118892e-001 1.09381100e-001
  1.36895013e-001]
 [9.38118847e-001 6.25375208e-004 6.04173309e-002 2.58007396e-005
  8.12646395e-004]]


labels  mlp_prediction_non  mlp_prediction_phish  mlp_prediction_spam  \
0          2        3.285955e-08          2.275952e-38         1.000000e+00   
1          0        9.871709e-01          1.400658e-05         8.887072e-04   
2          2        5.431999e-03          7.265198e-03         9.751261e-01   
3          3        6.821167e-02          8.999669e-02         4.175485e-02   
4          0        1.000000e+00          9.884499e-29         3.997525e-14   
...      ...                 ...                   ...                  ...   
6891       2        1.120535e-12          1.117325e-44         1.000000e+00   
6892       2        8.522478e-04          1.933313e-04         9.989540e-01   
6893       3        1.956546e-64          3.955041e-62        4.279204e-132   
6894       0        1.449094e-01          2.976956e-01         3.111189e-01   
6895       0        9.381188e-01          6.253752e-04         6.041733e-02   

      mlp_prediction_malware  mlp_prediction_defacemen  nn_prediction_non  \
0              3.536448e-103              5.452580e-62       3.285955e-08   
1               3.094047e-04              1.161696e-02       9.871709e-01   
2               1.063568e-02              1.541009e-03       5.431999e-03   
3               7.832318e-01              1.680500e-02       6.821167e-02   
4               4.412196e-13              2.773055e-33       1.000000e+00   
...                      ...                       ...                ...   
6891           9.068879e-112              2.337164e-60       1.120535e-12   
6892            4.423567e-07              4.685219e-15       8.522478e-04   
6893            1.000000e+00             2.775327e-194       1.956546e-64   
6894            1.093811e-01              1.368950e-01       1.449094e-01   
6895            2.580074e-05              8.126464e-04       9.381188e-01   

      nn_prediction_phish  nn_prediction_spam  nn_prediction_malware  \
0            2.275952e-38        1.000000e+00          3.536448e-103   
1            1.400658e-05        8.887072e-04           3.094047e-04   
2            7.265198e-03        9.751261e-01           1.063568e-02   
3            8.999669e-02        4.175485e-02           7.832318e-01   
4            9.884499e-29        3.997525e-14           4.412196e-13   
...                   ...                 ...                    ...   
6891         1.117325e-44        1.000000e+00          9.068879e-112   
6892         1.933313e-04        9.989540e-01           4.423567e-07   
6893         3.955041e-62       4.279204e-132           1.000000e+00   
6894         2.976956e-01        3.111189e-01           1.093811e-01   
6895         6.253752e-04        6.041733e-02           2.580074e-05   

      nn_prediction_defacemen  nn2_prediction_non  nn2_prediction_phish  \
0                5.452580e-62        3.285955e-08          2.275952e-38   
1                1.161696e-02        9.871709e-01          1.400658e-05   
2                1.541009e-03        5.431999e-03          7.265198e-03   
3                1.680500e-02        6.821167e-02          8.999669e-02   
4                2.773055e-33        1.000000e+00          9.884499e-29   
...                       ...                 ...                   ...   
6891             2.337164e-60        1.120535e-12          1.117325e-44   
6892             4.685219e-15        8.522478e-04          1.933313e-04   
6893            2.775327e-194        1.956546e-64          3.955041e-62   
6894             1.368950e-01        1.449094e-01          2.976956e-01   
6895             8.126464e-04        9.381188e-01          6.253752e-04   

      nn2_prediction_spam  nn2_prediction_malware  nn2_prediction_defacemen  
0            1.000000e+00           3.536448e-103              5.452580e-62  
1            8.887072e-04            3.094047e-04              1.161696e-02  
2            9.751261e-01            1.063568e-02              1.541009e-03  
3            4.175485e-02            7.832318e-01     

In [ ]:
output.shape


(6896, 16)

In [ ]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Multi/Base_classifier_result(HTML cross)(3).csv', index=False)