In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(binary).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0              0        0       0           1          1            0   
1              1        0       0           1          1            1   
2              2        0       0           1          1            0   
3              3        0       0           1          3            0   
4              4        0       0           1          3            0   
...          ...      ...     ...         ...        ...          ...   
6522        9992        0       0           1          5            0   
6523        9994        0       0           1          3            0   
6524        9995        0       0           1          6            0   
6525        9996        0       0           1          5            0   
6526        9997        0       0           1          4            0   

      https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                0        0              0            0  ...           0   
1                0        0              0            0  ...           0   
2                1        0              0            0  ...           0   
3                0        0              0            0  ...           0   
4                0        0              0            0  ...           0   
...            ...      ...            ...          ...  ...         ...   
6522             0        0              0            0  ...           0   
6523             0        0              0            0  ...           0   
6524             0        0              0            0  ...           0   
6525             0        0              0            0  ...           0   
6526             0        0              0            0  ...           0   

      Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0             49        691          42       13135                6400   
1              4         66           3        2034                 818   
2              1        100          27       32987               10451   
3              0          0           1           0                  52   
4            117        219          23        7944                3468   
...          ...        ...         ...         ...                 ...   
6522           0          0           1           0                  34   
6523           0          0           1           0                  14   
6524           0          0           1           0                 249   
6525           0          0           1           0                   6   
6526           0          0           1           0                 630   

      Script To Special Chars Ratio  Script To body Ratio  \
0                          2.052344              0.528869   
1                          2.486553              0.676197   
2                          3.156349              0.836681   
3                          0.000000              0.000000   
4                          2.290657              0.524460   
...                             ...                   ...   
6522                       0.000000              0.000000   
6523                       0.000000              0.000000   
6524                       0.000000              0.000000   
6525                       0.000000              0.000000   
6526                       0.000000              0.000000   

      Body To Special Char Ratio  Label  
0                       0.257690      0  
1                       0.271941      0  
2                       0.265079      0  
3                       0.227074      0  
4                       0.228956      0  
...                          ...    ...  
6522                    0.185792      1  
6523                    0.197183      1  
6524                    0.315990      1  
6525                    0.139535      1  
6526                    0.310192      1  

[6527 rows x 46 columns]

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                  21444   
1       1           0            0             1                   1075   
2       1           0            0             1                   4531   
3       1           0            0             1                     32   
4       1           0            0             1                   4880   

   number of sentences  number of html tags  number of whitespace  \
0                 1853                 3247                     0   
1                  136                  236                     0   
2                 2634                  486                     0   
3                    9                    8                     0   
4                  981                 1412                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1        24836  ...           0          49        691   
1            1         3008  ...           0           4         66   
2            1        39426  ...           0           1        100   
3            0          229  ...           0           0          0   
4            1        15147  ...           0         117        219   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0          42       13135                6400                       2.052344   
1           3        2034                 818                       2.486553   
2          27       32987               10451                       3.156349   
3           1           0                  52                       0.000000   
4          23        7944                3468                       2.290657   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.528869                    0.257690      0  
1              0.676197                    0.271941      0  
2              0.836681                    0.265079      0  
3              0.000000                    0.227074      0  
4              0.524460                    0.228956      0  

[5 rows x 21 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   iFrame                         6527 non-null   int64  
 1   Mouse Over                     6527 non-null   int64  
 2   Right Click                    6527 non-null   int64  
 3   Web Forwards                   6527 non-null   int64  
 4   Number of page tokens          6527 non-null   int64  
 5   number of sentences            6527 non-null   int64  
 6   number of html tags            6527 non-null   int64  
 7   number of whitespace           6527 non-null   int64  
 8   url Is Live                    6527 non-null   int64  
 9   HTML Length                    6527 non-null   int64  
 10  Num Objects                    6527 non-null   int64  
 11  Num Embeds                     6527 non-null   int64  
 12  Num Images                     6527 non-null   i

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
dtype: int64

In [8]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 6527
Non-Phishing: 4954 (75.90% of total)
Phishing: 1573 (24.10% of total)


In [9]:

import numpy as np


In [10]:
urldata.describe()

iFrame   Mouse Over  Right Click  Web Forwards  \
count  6527.000000  6527.000000       6527.0   6527.000000   
mean      0.999387     0.000306          0.0      0.937490   
std       0.024750     0.017504          0.0      0.242097   
min       0.000000     0.000000          0.0      0.000000   
25%       1.000000     0.000000          0.0      1.000000   
50%       1.000000     0.000000          0.0      1.000000   
75%       1.000000     0.000000          0.0      1.000000   
max       1.000000     1.000000          0.0      1.000000   

       Number of page tokens  number of sentences  number of html tags  \
count            6527.000000          6527.000000          6527.000000   
mean             3606.327256          1812.912364           433.003830   
std              5828.320950          3543.768665           733.633379   
min                 1.000000             1.000000             1.000000   
25%               103.000000            20.000000            16.000000   
50%              1719.000000           666.000000           159.000000   
75%              5131.500000          1683.000000           525.000000   
max             74678.000000         43777.000000          8760.000000   

       number of whitespace  url Is Live   HTML Length  ...   Num Embeds  \
count                6527.0  6527.000000  6.527000e+03  ...  6527.000000   
mean                    0.0     0.422399  4.792708e+04  ...     0.000613   
std                     0.0     0.505630  1.162579e+05  ...     0.024750   
min                     0.0    -1.000000  0.000000e+00  ...     0.000000   
25%                     0.0     0.000000  6.630000e+02  ...     0.000000   
50%                     0.0     0.000000  1.811000e+04  ...     0.000000   
75%                     0.0     1.000000  3.479350e+04  ...     0.000000   
max                     0.0     1.000000  2.107635e+06  ...     1.000000   

        Num Images    Num Links   Num Titles    Num Script  \
count  6527.000000  6527.000000  6527.000000  6.527000e+03   
mean     13.078290    71.623717     8.910679  2.911380e+04   
std      37.301509   117.479116    34.106562  9.681226e+04   
min       0.000000     0.000000     0.000000  0.000000e+00   
25%       0.000000     0.000000     1.000000  4.400000e+01   
50%       3.000000    28.000000     1.000000  6.953000e+03   
75%       8.000000    91.000000     5.000000  1.672850e+04   
max     526.000000  1159.000000  1042.000000  2.076633e+06   

       Special Characters  Script To Special Chars Ratio  \
count         6527.000000                    6527.000000   
mean         11168.757009                       4.175212   
std          24456.427671                      22.109670   
min              0.000000                       0.000000   
25%            143.000000                       0.043897   
50%           4102.000000                       1.916015   
75%           9126.000000                       2.764967   
max         359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio        Label  
count           6527.000000                 6527.000000  6527.000000  
mean               0.456171                    0.227569     0.240999  
std                0.349764                    0.077076     0.427722  
min                0.000000                    0.000000     0.000000  
25%                0.016658                    0.197183     0.000000  
50%                0.488331                    0.248328     0.000000  
75%                0.739913                    0.262355     0.000000  
max                1.005038                    0.605483     1.000000  

[8 rows x 21 columns]

In [11]:
#checking the data for null or missing values
urldata.isnull().sum()

iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page tokens            0
number of sentences              0
number of html tags              0
number of whitespace             0
url Is Live                      0
HTML Length                      0
Num Objects                      0
Num Embeds                       0
Num Images                       0
Num Links                        0
Num Titles                       0
Num Script                       0
Special Characters               0
Script To Special Chars Ratio    0
Script To body Ratio             0
Body To Special Char Ratio       0
Label                            0
dtype: int64

In [12]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                   4791   
1       1           0            0             1                    804   
2       1           0            0             1                     15   
3       1           0            0             1                   2209   
4       1           0            0             1                   1761   

   number of sentences  number of html tags  number of whitespace  \
0                  573                  762                     0   
1                  949                  123                     0   
2                    8                    8                     0   
3                  682                   36                     0   
4                 1693                  174                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1        14366  ...           0          59        145   
1            1        89780  ...           0           1          6   
2            0          352  ...           0           0          0   
3            1        27022  ...           0           0          2   
4            0        32596  ...           0           4         36   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0           3        7912                3594                       2.201447   
1           1       85797               22866                       3.752165   
2           0         213                  81                       2.629630   
3           0       26930                8737                       3.082294   
4           1       15924                8304                       1.917630   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.550745                    0.250174      0  
1              0.955636                    0.254689      0  
2              0.605114                    0.230114      0  
3              0.996595                    0.323329      0  
4              0.488526                    0.254755      0  

[5 rows x 21 columns]

In [13]:
import numpy as np
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [14]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(3589, 20) (2938, 20)
(3589,) (2938,)


In [15]:
output = {}
output['labels'] = y_test

**Random Forest Classifier**

In [16]:
import keras
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  rfc = RandomForestClassifier(n_estimators=50, max_depth=10)
  #compile model using mse as a measure of model performance

  rfc.fit(x_train, y_train)


  y_pred = rfc.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/RFC/model_'+str(n)+'.h5'
  pickle.dump(rfc, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [17]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[264   5]
 [ 11  79]]
Precision: 0.9405
Recall: 0.8778
F1 Score: 0.9080
Validation Accuracy: 0.9554317548746518
model 0 saved
[[276   3]
 [ 12  68]]
Precision: 0.9577
Recall: 0.8500
F1 Score: 0.9007
Validation Accuracy: 0.958217270194986
model 1 saved
[[270   3]
 [  9  77]]
Precision: 0.9625
Recall: 0.8953
F1 Score: 0.9277
Validation Accuracy: 0.9665738161559888
model 2 saved
[[269   2]
 [ 11  77]]
Precision: 0.9747
Recall: 0.8750
F1 Score: 0.9222
Validation Accuracy: 0.9637883008356546
model 3 saved
[[267   5]
 [ 10  77]]
Precision: 0.9390
Recall: 0.8851
F1 Score: 0.9112
Validation Accuracy: 0.958217270194986
model 4 saved
[[271   2]
 [  6  80]]
Precision: 0.9756
Recall: 0.9302
F1 Score: 0.9524
Validation Accuracy: 0.9777158774373259
model 5 saved
[[251   4]
 [ 12  92]]
Precision: 0.9583
Recall: 0.8846
F1 Score: 0.9200
Validation Accuracy: 0.9554317548746518
model 6 saved
[[260   8]
 [ 10  81]]
Precision: 0.9101
Recall: 0.8901
F1 Score: 0.9000
Validation Accuracy: 0.9498607242339833


In [18]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/RFC/model_5.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['rfc_prediction_non'] = [i[0] for i in y_pred_prob];
output['rfc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output



[[0.9869641  0.0130359 ]
 [0.03083038 0.96916962]
 [0.94867424 0.05132576]
 ...
 [0.23965074 0.76034926]
 [0.98085822 0.01914178]
 [0.99690312 0.00309688]]


labels  rfc_prediction_non  rfc_prediction_phish
0          0            0.986964              0.013036
1          1            0.030830              0.969170
2          0            0.948674              0.051326
3          0            0.988278              0.011722
4          0            0.944779              0.055221
...      ...                 ...                   ...
2933       0            0.922347              0.077653
2934       0            0.999651              0.000349
2935       1            0.239651              0.760349
2936       0            0.980858              0.019142
2937       0            0.996903              0.003097

[2938 rows x 3 columns]

**SVM**

In [ ]:
import keras

import pickle
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics


def model_svc(x_train, x_val, y_train, y_val, opt, n):
  svclassifier = SVC(kernel='rbf', probability= True)
  #compile model using mse as a measure of model performance
  svclassifier.fit(x_train, y_train)

  y_pred = svclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/SVC/model_'+str(n)+'.h5'
  pickle.dump(svclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
# early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_svc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[271   0]
 [ 88   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.754874651810585


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 0 saved
[[256   0]
 [103   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.713091922005571
model 1 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[273   0]
 [ 86   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7604456824512534
model 2 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[274   0]
 [ 85   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7632311977715878
model 3 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[262   0]
 [ 96   1]]
Precision: 1.0000
Recall: 0.0103
F1 Score: 0.0204
Validation Accuracy: 0.7325905292479109
model 4 saved
[[285   0]
 [ 74   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7938718662952646


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 5 saved
[[276   0]
 [ 83   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7688022284122563
model 6 saved

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



[[281   0]
 [ 78   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7827298050139275


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


model 7 saved
[[272   0]
 [ 86   1]]
Precision: 1.0000
Recall: 0.0115
F1 Score: 0.0227
Validation Accuracy: 0.7604456824512534
model 8 saved
[[266   0]
 [ 92   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7430167597765364
model 9 saved
Average Validation Accuracy: 0.7573100325236146


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/SVC/model_5.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['svc_prediction_non'] = [i[0] for i in y_pred_prob];
output['svc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.81789526 0.18210474]
 [0.41243491 0.58756509]
 [0.51614167 0.48385833]
 ...
 [0.75275966 0.24724034]
 [0.62950304 0.37049696]
 [0.84331229 0.15668771]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          0            0.986964              0.013036            0.817895   
1          1            0.030830              0.969170            0.412435   
2          0            0.948674              0.051326            0.516142   
3          0            0.988278              0.011722            0.892637   
4          0            0.944779              0.055221            0.966460   
...      ...                 ...                   ...                 ...   
2933       0            0.922347              0.077653            0.902910   
2934       0            0.999651              0.000349            0.939851   
2935       1            0.239651              0.760349            0.752760   
2936       0            0.980858              0.019142            0.629503   
2937       0            0.996903              0.003097            0.843312   

      svc_prediction_phish  
0                 0.182105  
1                 0.587565  
2                 0.483858  
3                 0.107363  
4                 0.033540  
...                    ...  
2933              0.097090  
2934              0.060149  
2935              0.247240  
2936              0.370497  
2937              0.156688  

[2938 rows x 5 columns]

**Logistic Regression**

In [ ]:
import keras

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
import pickle

def model_lr(x_train, x_val, y_train, y_val, opt, n):
  lrclassifier = LogisticRegression()
  #compile model using mse as a measure of model performance
  lrclassifier.fit(x_train, y_train)

  y_pred = lrclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))
  

  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/LR/model_'+str(n)+'.h5'
  pickle.dump(lrclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_lr(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[249  22]
 [ 53  35]]
Precision: 0.6140
Recall: 0.3977
F1 Score: 0.4828
Validation Accuracy: 0.7910863509749304
model 0 saved
[[235  21]
 [ 65  38]]
Precision: 0.6441
Recall: 0.3689
F1 Score: 0.4691
Validation Accuracy: 0.7604456824512534


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 1 saved
[[242  31]
 [ 51  35]]
Precision: 0.5303
Recall: 0.4070
F1 Score: 0.4605
Validation Accuracy: 0.7715877437325905
model 2 saved
[[259  15]
 [ 67  18]]
Precision: 0.5455
Recall: 0.2118
F1 Score: 0.3051
Validation Accuracy: 0.7715877437325905


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 3 saved
[[239  23]
 [ 63  34]]
Precision: 0.5965
Recall: 0.3505
F1 Score: 0.4416
Validation Accuracy: 0.7604456824512534


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 4 saved
[[256  29]
 [ 47  27]]
Precision: 0.4821
Recall: 0.3649
F1 Score: 0.4154
Validation Accuracy: 0.7883008356545961


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 5 saved
[[248  28]
 [ 51  32]]
Precision: 0.5333
Recall: 0.3855
F1 Score: 0.4476
Validation Accuracy: 0.7799442896935933
model 6 saved
[[252  29]
 [ 55  23]]
Precision: 0.4423
Recall: 0.2949
F1 Score: 0.3538
Validation Accuracy: 0.766016713091922


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 7 saved
[[253  19]
 [ 78   9]]
Precision: 0.3214
Recall: 0.1034
F1 Score: 0.1565
Validation Accuracy: 0.7298050139275766


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 8 saved
[[224  42]
 [ 59  33]]
Precision: 0.4400
Recall: 0.3587
F1 Score: 0.3952
Validation Accuracy: 0.7178770949720671
model 9 saved
Average Validation Accuracy: 0.7637097150682373


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [20]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/LR/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['lr_prediction_non'] = [i[0] for i in y_pred_prob];
output['lr_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.71595425 0.28404575]
 [0.49674375 0.50325625]
 [0.52495207 0.47504793]
 ...
 [0.68342059 0.31657941]
 [0.57533272 0.42466728]
 [0.85449515 0.14550485]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          0            0.986964              0.013036            0.817895   
1          1            0.030830              0.969170            0.412435   
2          0            0.948674              0.051326            0.516142   
3          0            0.988278              0.011722            0.892637   
4          0            0.944779              0.055221            0.966460   
...      ...                 ...                   ...                 ...   
2933       0            0.922347              0.077653            0.902910   
2934       0            0.999651              0.000349            0.939851   
2935       1            0.239651              0.760349            0.752760   
2936       0            0.980858              0.019142            0.629503   
2937       0            0.996903              0.003097            0.843312   

      svc_prediction_phish  lr_prediction_non  lr_prediction_phish  
0                 0.182105           0.715954             0.284046  
1                 0.587565           0.496744             0.503256  
2                 0.483858           0.524952             0.475048  
3                 0.107363           0.832495             0.167505  
4                 0.033540           0.950510             0.049490  
...                    ...                ...                  ...  
2933              0.097090           0.817390             0.182610  
2934              0.060149           0.806987             0.193013  
2935              0.247240           0.683421             0.316579  
2936              0.370497           0.575333             0.424667  
2937              0.156688           0.854495             0.145505  

[2938 rows x 7 columns]

In [21]:
output.shape


(2938, 7)

In [22]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Binary/Base_classifier_result(HTML cross)(2).csv', index=False)