In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(binary).csv")
urldata.head()


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0           0        0       0           1          1            0   
1           1        0       0           1          1            1   
2           2        0       0           1          1            0   
3           3        0       0           1          3            0   
4           4        0       0           1          3            0   

   https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0             0        0              0            0  ...           0   
1             0        0              0            0  ...           0   
2             1        0              0            0  ...           0   
3             0        0              0            0  ...           0   
4             0        0              0            0  ...           0   

   Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0          49        691          42       13135                6400   
1           4         66           3        2034                 818   
2           1        100          27       32987               10451   
3           0          0           1           0                  52   
4         117        219          23        7944                3468   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.052344              0.528869   
1                       2.486553              0.676197   
2                       3.156349              0.836681   
3                       0.000000              0.000000   
4                       2.290657              0.524460   

   Body To Special Char Ratio  Label  
0                    0.257690      0  
1                    0.271941      0  
2                    0.265079      0  
3                    0.227074      0  
4                    0.228956      0  

[5 rows x 46 columns]

In [5]:
urldata = urldata.drop(['Unnamed: 0'], axis = 1)

In [6]:
urldata.columns

Index(['Have IP', 'Have @', 'URL Length', 'URL Depth', 'Redirection',
       'https Domain', 'TinyURL', 'Prefix/Suffix', 'Have client', 'Have admin',
       'Have login', 'Have server', '.php', '.html', '.info', '.txt', '.js',
       '.exe', 'Num of periods', 'Is encoded', 'Num of encoded char',
       'Num of parameters', 'Num of digits', 'Num of spec char', 'iFrame',
       'Mouse Over', 'Right Click', 'Web Forwards', 'Number of page tokens',
       'number of sentences', 'number of html tags', 'number of whitespace',
       'url Is Live', 'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images',
       'Num Links', 'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [7]:
urldata.shape

(6527, 45)

In [8]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Have IP                        6527 non-null   int64  
 1   Have @                         6527 non-null   int64  
 2   URL Length                     6527 non-null   int64  
 3   URL Depth                      6527 non-null   int64  
 4   Redirection                    6527 non-null   int64  
 5   https Domain                   6527 non-null   int64  
 6   TinyURL                        6527 non-null   int64  
 7   Prefix/Suffix                  6527 non-null   int64  
 8   Have client                    6527 non-null   int64  
 9   Have admin                     6527 non-null   int64  
 10  Have login                     6527 non-null   int64  
 11  Have server                    6527 non-null   int64  
 12  .php                           6527 non-null   i

In [9]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  \
0           0       0           1         10            0             0   
1           0       0           1          2            0             0   
2           0       0           1          5            0             0   
3           0       0           1         10            0             0   
4           0       0           1          1            0             1   
...       ...     ...         ...        ...          ...           ...   
6522        0       0           1          3            0             0   
6523        0       0           1          6            0             0   
6524        0       0           1          3            0             0   
6525        0       0           1          5            0             0   
6526        0       0           1         10            0             0   

      TinyURL  Prefix/Suffix  Have client  Have admin  ...  Num Embeds  \
0           0              0            0           0  ...           0   
1           0              0            0           0  ...           0   
2           0              0            0           0  ...           0   
3           0              0            0           0  ...           0   
4           0              0            0           0  ...           0   
...       ...            ...          ...         ...  ...         ...   
6522        0              0            0           0  ...           0   
6523        0              0            0           0  ...           0   
6524        0              0            0           0  ...           0   
6525        0              0            0           0  ...           0   
6526        0              0            0           0  ...           0   

      Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0              4         28           1       15924                8311   
1              4         28           1       15924                8341   
2             32        162          39       12735                4314   
3              4         28           1       15924                8311   
4              1          6           1       85571               22816   
...          ...        ...         ...         ...                 ...   
6522           0          0           1           0                  42   
6523           1         18           1          10                2276   
6524           1         51           6       10013               30704   
6525           0          0           1           0                  28   
6526           4         36           1       15924                8304   

      Script To Special Chars Ratio  Script To body Ratio  \
0                          1.916015              0.488331   
1                          1.909124              0.486244   
2                          2.952017              0.726718   
3                          1.916015              0.488331   
4                          3.750482              0.955524   
...                             ...                   ...   
6522                       0.000000              0.000000   
6523                       0.004394              0.001133   
6524                       0.326114              0.069389   
6525                       0.000000              0.000000   
6526                       1.917630              0.488436   

      Body To Special Char Ratio  Label  
0                       0.254868      0  
1                       0.254695      0  
2                       0.246177      0  
3                       0.254868      0  
4                       0.254774      0  
...                          ...    ...  
6522                    0.219895      0  
6523                    0.257874      1  
6524                    0.212775      0  
6525                    0.210526      1  
6526                    0.254708      0  

[6527 rows x 45 columns]

In [10]:
urldata.shape

(6527, 45)

In [11]:
import numpy as np

# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))


print(x.shape, y.shape)


(6527, 44) (6527,)


In [12]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(3589, 44) (2938, 44)
(3589,) (2938,)


In [13]:
output = {}
output['labels'] = y_test

**DecisionTree Classifier**

In [14]:
import keras

from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import pickle
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  dtcclassifier = DecisionTreeClassifier(max_depth=5)
  #compile model using mse as a measure of model performance
  dtcclassifier.fit(x_train, y_train)

  y_pred = dtcclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/DTC/model_'+str(n)+'.h5'
  pickle.dump(dtcclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [15]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[273   8]
 [  6  72]]
Precision: 0.9000
Recall: 0.9231
F1 Score: 0.9114
Validation Accuracy: 0.9610027855153204
model 0 saved
[[264  18]
 [  5  72]]
Precision: 0.8000
Recall: 0.9351
F1 Score: 0.8623
Validation Accuracy: 0.935933147632312
model 1 saved
[[263   6]
 [  9  81]]
Precision: 0.9310
Recall: 0.9000
F1 Score: 0.9153
Validation Accuracy: 0.958217270194986
model 2 saved
[[265   5]
 [  6  83]]
Precision: 0.9432
Recall: 0.9326
F1 Score: 0.9379
Validation Accuracy: 0.9693593314763231
model 3 saved
[[259   8]
 [ 10  82]]
Precision: 0.9111
Recall: 0.8913
F1 Score: 0.9011
Validation Accuracy: 0.9498607242339833
model 4 saved
[[277  11]
 [  5  66]]
Precision: 0.8571
Recall: 0.9296
F1 Score: 0.8919
Validation Accuracy: 0.9554317548746518
model 5 saved
[[259   4]
 [ 10  86]]
Precision: 0.9556
Recall: 0.8958
F1 Score: 0.9247
Validation Accuracy: 0.9610027855153204
model 6 saved
[[261   6]
 [ 13  79]]
Precision: 0.9294
Recall: 0.8587
F1 Score: 0.8927
Validation Accuracy: 0.947075208913649
m

In [16]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/DTC/model_3.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['dt_prediction_non'] = [i[0] for i in y_pred_prob];
output['dt_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.11842105 0.88157895]
 [0.98971193 0.01028807]
 [1.         0.        ]
 ...
 [0.98971193 0.01028807]
 [0.98148148 0.01851852]
 [0.98971193 0.01028807]]


labels  dt_prediction_non  dt_prediction_phish
0          1           0.118421             0.881579
1          0           0.989712             0.010288
2          0           1.000000             0.000000
3          0           0.981481             0.018519
4          0           1.000000             0.000000
...      ...                ...                  ...
2933       0           1.000000             0.000000
2934       1           0.028369             0.971631
2935       0           0.989712             0.010288
2936       0           0.981481             0.018519
2937       0           0.989712             0.010288

[2938 rows x 3 columns]

**KNN**

In [17]:
import keras

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_knn(x_train, x_val, y_train, y_val, opt, n):
  knnclassifier = KNeighborsClassifier(n_neighbors=7, weights='uniform', algorithm='kd_tree', leaf_size=5)
  #compile model using mse as a measure of model performance
  knnclassifier.fit(x_train, y_train)

  y_pred = knnclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/KNN/model_'+str(n)+'.h5'
  pickle.dump(knnclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [18]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_knn(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[279   2]
 [ 11  67]]
Precision: 0.9710
Recall: 0.8590
F1 Score: 0.9116
Validation Accuracy: 0.9637883008356546
model 0 saved
[[270  12]
 [ 15  62]]
Precision: 0.8378
Recall: 0.8052
F1 Score: 0.8212
Validation Accuracy: 0.924791086350975
model 1 saved
[[263   6]
 [ 12  78]]
Precision: 0.9286
Recall: 0.8667
F1 Score: 0.8966
Validation Accuracy: 0.9498607242339833
model 2 saved
[[266   4]
 [ 19  70]]
Precision: 0.9459
Recall: 0.7865
F1 Score: 0.8589
Validation Accuracy: 0.935933147632312
model 3 saved
[[262   5]
 [ 16  76]]
Precision: 0.9383
Recall: 0.8261
F1 Score: 0.8786
Validation Accuracy: 0.9415041782729805
model 4 saved
[[275  13]
 [ 16  55]]
Precision: 0.8088
Recall: 0.7746
F1 Score: 0.7914
Validation Accuracy: 0.9192200557103064
model 5 saved
[[257   6]
 [ 10  86]]
Precision: 0.9348
Recall: 0.8958
F1 Score: 0.9149
Validation Accuracy: 0.9554317548746518
model 6 saved
[[259   8]
 [ 20  72]]
Precision: 0.9000
Recall: 0.7826
F1 Score: 0.8372
Validation Accuracy: 0.9220055710306406


In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/KNN/model_6.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['knn_prediction_non'] = [i[0] for i in y_pred_prob];
output['knn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.71428571 0.28571429]
 [1.         0.        ]
 [1.         0.        ]
 ...
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          1           0.118421             0.881579            0.714286   
1          0           0.989712             0.010288            1.000000   
2          0           1.000000             0.000000            1.000000   
3          0           0.981481             0.018519            1.000000   
4          0           1.000000             0.000000            1.000000   
...      ...                ...                  ...                 ...   
2933       0           1.000000             0.000000            1.000000   
2934       1           0.028369             0.971631            0.285714   
2935       0           0.989712             0.010288            1.000000   
2936       0           0.981481             0.018519            1.000000   
2937       0           0.989712             0.010288            1.000000   

      knn_prediction_phish  
0                 0.285714  
1                 0.000000  
2                 0.000000  
3                 0.000000  
4                 0.000000  
...                    ...  
2933              0.000000  
2934              0.714286  
2935              0.000000  
2936              0.000000  
2937              0.000000  

[2938 rows x 5 columns]

**XGB Classifier**

In [20]:
import keras

from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_xgb(x_train, x_val, y_train, y_val, opt, n):
  xgbclassifier = XGBClassifier(n_neighbors=5)
  #compile model using mse as a measure of model performance
  xgbclassifier.fit(x_train, y_train)

  y_pred = xgbclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/XGBoost/model_'+str(n)+'.h5'
  pickle.dump(xgbclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [21]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_xgb(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[277   4]
 [  5  73]]
Precision: 0.9481
Recall: 0.9359
F1 Score: 0.9419
Validation Accuracy: 0.9749303621169917
model 0 saved
[[274   8]
 [  2  75]]
Precision: 0.9036
Recall: 0.9740
F1 Score: 0.9375
Validation Accuracy: 0.9721448467966574
model 1 saved
[[265   4]
 [  5  85]]
Precision: 0.9551
Recall: 0.9444
F1 Score: 0.9497
Validation Accuracy: 0.9749303621169917
model 2 saved
[[266   4]
 [  3  86]]
Precision: 0.9556
Recall: 0.9663
F1 Score: 0.9609
Validation Accuracy: 0.9805013927576601
model 3 saved
[[263   4]
 [  5  87]]
Precision: 0.9560
Recall: 0.9457
F1 Score: 0.9508
Validation Accuracy: 0.9749303621169917
model 4 saved
[[283   5]
 [  3  68]]
Precision: 0.9315
Recall: 0.9577
F1 Score: 0.9444
Validation Accuracy: 0.9777158774373259
model 5 saved
[[261   2]
 [  4  92]]
Precision: 0.9787
Recall: 0.9583
F1 Score: 0.9684
Validation Accuracy: 0.9832869080779945
model 6 saved
[[263   4]
 [  4  88]]
Precision: 0.9565
Recall: 0.9565
F1 Score: 0.9565
Validation Accuracy: 0.977715877437325

In [22]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/XGBoost/model_6.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['XGB_prediction_non'] = [i[0] for i in y_pred_prob];
output['XGB_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[1.7243111e-01 8.2756889e-01]
 [9.9451357e-01 5.4864455e-03]
 [9.9923432e-01 7.6570408e-04]
 ...
 [9.9451357e-01 5.4864455e-03]
 [9.7667539e-01 2.3324620e-02]
 [9.9451357e-01 5.4864455e-03]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          1           0.118421             0.881579            0.714286   
1          0           0.989712             0.010288            1.000000   
2          0           1.000000             0.000000            1.000000   
3          0           0.981481             0.018519            1.000000   
4          0           1.000000             0.000000            1.000000   
...      ...                ...                  ...                 ...   
2933       0           1.000000             0.000000            1.000000   
2934       1           0.028369             0.971631            0.285714   
2935       0           0.989712             0.010288            1.000000   
2936       0           0.981481             0.018519            1.000000   
2937       0           0.989712             0.010288            1.000000   

      knn_prediction_phish  XGB_prediction_non  XGB_prediction_phish  
0                 0.285714            0.172431              0.827569  
1                 0.000000            0.994514              0.005486  
2                 0.000000            0.999234              0.000766  
3                 0.000000            0.953506              0.046494  
4                 0.000000            0.968014              0.031986  
...                    ...                 ...                   ...  
2933              0.000000            0.995678              0.004322  
2934              0.714286            0.124511              0.875489  
2935              0.000000            0.994514              0.005486  
2936              0.000000            0.976675              0.023325  
2937              0.000000            0.994514              0.005486  

[2938 rows x 7 columns]

In [23]:
output.shape


(2938, 7)

In [24]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Binary/Base_classifier_result(URL-HTML cross).csv', index=False)