In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(binary).csv")
urldata.head()


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0           0        0       0           1          1            0   
1           1        0       0           1          1            1   
2           2        0       0           1          1            0   
3           3        0       0           1          3            0   
4           4        0       0           1          3            0   

   https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0             0        0              0            0  ...           0   
1             0        0              0            0  ...           0   
2             1        0              0            0  ...           0   
3             0        0              0            0  ...           0   
4             0        0              0            0  ...           0   

   Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0          49        691          42       13135                6400   
1           4         66           3        2034                 818   
2           1        100          27       32987               10451   
3           0          0           1           0                  52   
4         117        219          23        7944                3468   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.052344              0.528869   
1                       2.486553              0.676197   
2                       3.156349              0.836681   
3                       0.000000              0.000000   
4                       2.290657              0.524460   

   Body To Special Char Ratio  Label  
0                    0.257690      0  
1                    0.271941      0  
2                    0.265079      0  
3                    0.227074      0  
4                    0.228956      0  

[5 rows x 46 columns]

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio'], axis = 1)

In [6]:
urldata.shape

(6527, 25)

In [7]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Have IP              6527 non-null   int64
 1   Have @               6527 non-null   int64
 2   URL Length           6527 non-null   int64
 3   URL Depth            6527 non-null   int64
 4   Redirection          6527 non-null   int64
 5   https Domain         6527 non-null   int64
 6   TinyURL              6527 non-null   int64
 7   Prefix/Suffix        6527 non-null   int64
 8   Have client          6527 non-null   int64
 9   Have admin           6527 non-null   int64
 10  Have login           6527 non-null   int64
 11  Have server          6527 non-null   int64
 12  .php                 6527 non-null   int64
 13  .html                6527 non-null   int64
 14  .info                6527 non-null   int64
 15  .txt                 6527 non-null   int64
 16  .js                  652

In [8]:
urldata.describe()

Have IP       Have @  URL Length    URL Depth  Redirection  \
count   6527.0  6527.000000      6527.0  6527.000000  6527.000000   
mean       0.0     0.004137         1.0     4.397579     0.050406   
std        0.0     0.064189         0.0     2.997529     0.218798   
min        0.0     0.000000         1.0     0.000000     0.000000   
25%        0.0     0.000000         1.0     2.000000     0.000000   
50%        0.0     0.000000         1.0     4.000000     0.000000   
75%        0.0     0.000000         1.0     6.000000     0.000000   
max        0.0     1.000000         1.0    18.000000     1.000000   

       https Domain      TinyURL  Prefix/Suffix  Have client   Have admin  \
count   6527.000000  6527.000000    6527.000000  6527.000000  6527.000000   
mean       0.060518     0.056841       0.042746     0.001379     0.019304   
std        0.238462     0.231556       0.202298     0.037111     0.137603   
min        0.000000     0.000000       0.000000     0.000000     0.000000   
25%        0.000000     0.000000       0.000000     0.000000     0.000000   
50%        0.000000     0.000000       0.000000     0.000000     0.000000   
75%        0.000000     0.000000       0.000000     0.000000     0.000000   
max        1.000000     1.000000       1.000000     1.000000     1.000000   

       ...    .txt          .js         .exe  Num of periods   Is encoded  \
count  ...  6527.0  6527.000000  6527.000000     6527.000000  6527.000000   
mean   ...     0.0     0.014249     0.002758        2.306573     0.151831   
std    ...     0.0     0.118523     0.052446        2.248695     0.358884   
min    ...     0.0     0.000000     0.000000        1.000000     0.000000   
25%    ...     0.0     0.000000     0.000000        1.000000     0.000000   
50%    ...     0.0     0.000000     0.000000        1.000000     0.000000   
75%    ...     0.0     0.000000     0.000000        2.000000     0.000000   
max    ...     0.0     1.000000     1.000000       21.000000     1.000000   

       Num of encoded char  Num of parameters  Num of digits  \
count          6527.000000        6527.000000    6527.000000   
mean              3.660028           0.640417      16.024207   
std              13.945412           1.608334      19.279340   
min               0.000000           0.000000       0.000000   
25%               0.000000           0.000000       5.000000   
50%               0.000000           0.000000      10.000000   
75%               0.000000           1.000000      21.000000   
max             201.000000          14.000000     259.000000   

       Num of spec char        Label  
count       6527.000000  6527.000000  
mean           9.387008     0.240999  
std           14.849941     0.427722  
min            0.000000     0.000000  
25%            1.000000     0.000000  
50%            6.000000     0.000000  
75%           11.000000     0.000000  
max          201.000000     1.000000  

[8 rows x 25 columns]

In [9]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                0
Have @                 0
URL Length             0
URL Depth              0
Redirection            0
https Domain           0
TinyURL                0
Prefix/Suffix          0
Have client            0
Have admin             0
Have login             0
Have server            0
.php                   0
.html                  0
.info                  0
.txt                   0
.js                    0
.exe                   0
Num of periods         0
Is encoded             0
Num of encoded char    0
Num of parameters      0
Num of digits          0
Num of spec char       0
Label                  0
dtype: int64

In [10]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  \
0           0       0           1          3            0             0   
1           0       0           1          1            0             1   
2           0       0           1          4            0             1   
3           0       0           1         10            0             0   
4           0       0           1          8            0             0   
...       ...     ...         ...        ...          ...           ...   
6522        0       0           1          1            0             0   
6523        0       0           1          2            0             0   
6524        0       0           1         10            0             0   
6525        0       0           1          4            0             0   
6526        0       0           1          1            0             0   

      TinyURL  Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0           0              0            0           0  ...     0    0     0   
1           0              0            0           0  ...     0    0     0   
2           0              0            0           0  ...     0    0     0   
3           0              0            0           0  ...     0    0     0   
4           0              0            0           0  ...     0    0     0   
...       ...            ...          ...         ...  ...   ...  ...   ...   
6522        0              0            0           0  ...     0    0     0   
6523        0              0            0           0  ...     0    0     0   
6524        0              0            0           0  ...     0    0     0   
6525        0              0            0           0  ...     0    0     0   
6526        0              0            0           0  ...     0    0     0   

      Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0                  2           0                    0                  0   
1                  2           1                   50                  1   
2                  3           0                    0                  1   
3                  1           0                    0                  0   
4                  5           0                    0                  0   
...              ...         ...                  ...                ...   
6522               6           0                    0                  2   
6523               1           0                    0                  0   
6524               1           0                    0                  0   
6525               4           0                    0                  5   
6526               3           0                    0                  2   

      Num of digits  Num of spec char  Label  
0                 6                12      0  
1                65                57      0  
2                 5                 1      1  
3                20                 0      0  
4                14                 0      1  
...             ...               ...    ...  
6522              2                 4      1  
6523              0                 9      0  
6524             21                 0      0  
6525              9                13      0  
6526             44                 8      0  

[6527 rows x 25 columns]

In [11]:
urldata.shape

(6527, 25)

In [12]:
import numpy as np

# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))


print(x.shape, y.shape)


(6527, 24) (6527,)


In [13]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(3589, 24) (2938, 24)
(3589,) (2938,)


In [14]:
output = {}
output['labels'] = y_test

**DecisionTree Classifier**

In [15]:
import keras

from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import pickle
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  dtcclassifier = DecisionTreeClassifier(max_depth=5)
  #compile model using mse as a measure of model performance
  dtcclassifier.fit(x_train, y_train)

  y_pred = dtcclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/DTC/model_'+str(n)+'.h5'
  pickle.dump(dtcclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [16]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[265   5]
 [ 12  77]]
Precision: 0.9390
Recall: 0.8652
F1 Score: 0.9006
Validation Accuracy: 0.9526462395543176
model 0 saved
[[280   3]
 [ 14  62]]
Precision: 0.9538
Recall: 0.8158
F1 Score: 0.8794
Validation Accuracy: 0.9526462395543176
model 1 saved
[[263   3]
 [ 18  75]]
Precision: 0.9615
Recall: 0.8065
F1 Score: 0.8772
Validation Accuracy: 0.9415041782729805
model 2 saved
[[271   6]
 [ 10  72]]
Precision: 0.9231
Recall: 0.8780
F1 Score: 0.9000
Validation Accuracy: 0.9554317548746518
model 3 saved
[[279   3]
 [  8  69]]
Precision: 0.9583
Recall: 0.8961
F1 Score: 0.9262
Validation Accuracy: 0.9693593314763231
model 4 saved
[[258   3]
 [ 15  83]]
Precision: 0.9651
Recall: 0.8469
F1 Score: 0.9022
Validation Accuracy: 0.9498607242339833
model 5 saved
[[273   4]
 [ 11  71]]
Precision: 0.9467
Recall: 0.8659
F1 Score: 0.9045
Validation Accuracy: 0.958217270194986
model 6 saved
[[270   4]
 [ 10  75]]
Precision: 0.9494
Recall: 0.8824
F1 Score: 0.9146
Validation Accuracy: 0.9610027855153204

In [17]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/DTC/model_4.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['dt_prediction_non'] = [i[0] for i in y_pred_prob];
output['dt_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.998125   0.001875  ]
 [0.82722513 0.17277487]
 [0.00404858 0.99595142]
 ...
 [0.998125   0.001875  ]
 [1.         0.        ]
 [0.998125   0.001875  ]]


labels  dt_prediction_non  dt_prediction_phish
0          0           0.998125             0.001875
1          0           0.827225             0.172775
2          1           0.004049             0.995951
3          1           0.048276             0.951724
4          0           0.827225             0.172775
...      ...                ...                  ...
2933       0           0.998125             0.001875
2934       0           0.998125             0.001875
2935       0           0.998125             0.001875
2936       0           1.000000             0.000000
2937       0           0.998125             0.001875

[2938 rows x 3 columns]

**KNN**

In [18]:
import keras

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_knn(x_train, x_val, y_train, y_val, opt, n):
  knnclassifier = KNeighborsClassifier(n_neighbors=7, weights='uniform', algorithm='kd_tree', leaf_size=5)
  #compile model using mse as a measure of model performance
  knnclassifier.fit(x_train, y_train)

  y_pred = knnclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/KNN/model_'+str(n)+'.h5'
  pickle.dump(knnclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [19]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_knn(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[265   5]
 [  2  87]]
Precision: 0.9457
Recall: 0.9775
F1 Score: 0.9613
Validation Accuracy: 0.9805013927576601
model 0 saved
[[278   5]
 [  5  71]]
Precision: 0.9342
Recall: 0.9342
F1 Score: 0.9342
Validation Accuracy: 0.9721448467966574
model 1 saved
[[263   3]
 [  8  85]]
Precision: 0.9659
Recall: 0.9140
F1 Score: 0.9392
Validation Accuracy: 0.9693593314763231
model 2 saved
[[267  10]
 [  9  73]]
Precision: 0.8795
Recall: 0.8902
F1 Score: 0.8848
Validation Accuracy: 0.947075208913649
model 3 saved
[[279   3]
 [  7  70]]
Precision: 0.9589
Recall: 0.9091
F1 Score: 0.9333
Validation Accuracy: 0.9721448467966574
model 4 saved
[[256   5]
 [  9  89]]
Precision: 0.9468
Recall: 0.9082
F1 Score: 0.9271
Validation Accuracy: 0.9610027855153204
model 5 saved
[[271   6]
 [ 12  70]]
Precision: 0.9211
Recall: 0.8537
F1 Score: 0.8861
Validation Accuracy: 0.9498607242339833
model 6 saved
[[272   2]
 [  5  80]]
Precision: 0.9756
Recall: 0.9412
F1 Score: 0.9581
Validation Accuracy: 0.9805013927576601

In [20]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/KNN/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['knn_prediction_non'] = [i[0] for i in y_pred_prob];
output['knn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          0           0.998125             0.001875            1.000000   
1          0           0.827225             0.172775            1.000000   
2          1           0.004049             0.995951            0.000000   
3          1           0.048276             0.951724            0.142857   
4          0           0.827225             0.172775            1.000000   
...      ...                ...                  ...                 ...   
2933       0           0.998125             0.001875            1.000000   
2934       0           0.998125             0.001875            1.000000   
2935       0           0.998125             0.001875            1.000000   
2936       0           1.000000             0.000000            1.000000   
2937       0           0.998125             0.001875            1.000000   

      knn_prediction_phish  
0                 0.000000  
1                 0.000000  
2                 1.000000  
3                 0.857143  
4                 0.000000  
...                    ...  
2933              0.000000  
2934              0.000000  
2935              0.000000  
2936              0.000000  
2937              0.000000  

[2938 rows x 5 columns]

**XGB Classifier**

In [ ]:
import keras

from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_xgb(x_train, x_val, y_train, y_val, opt, n):
  xgbclassifier = XGBClassifier(n_neighbors=5)
  #compile model using mse as a measure of model performance
  xgbclassifier.fit(x_train, y_train)

  y_pred = xgbclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/XGBoost/model_'+str(n)+'.h5'
  pickle.dump(xgbclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_xgb(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[255   3]
 [  8  93]]
Precision: 0.9688
Recall: 0.9208
F1 Score: 0.9442
Validation Accuracy: 0.9693593314763231
model 0 saved
[[264   5]
 [  6  84]]
Precision: 0.9438
Recall: 0.9333
F1 Score: 0.9385
Validation Accuracy: 0.9693593314763231
model 1 saved
[[269   3]
 [ 10  77]]
Precision: 0.9625
Recall: 0.8851
F1 Score: 0.9222
Validation Accuracy: 0.9637883008356546
model 2 saved
[[264   5]
 [  6  84]]
Precision: 0.9438
Recall: 0.9333
F1 Score: 0.9385
Validation Accuracy: 0.9693593314763231
model 3 saved
[[264   5]
 [  2  88]]
Precision: 0.9462
Recall: 0.9778
F1 Score: 0.9617
Validation Accuracy: 0.9805013927576601
model 4 saved
[[270   4]
 [  3  82]]
Precision: 0.9535
Recall: 0.9647
F1 Score: 0.9591
Validation Accuracy: 0.9805013927576601
model 5 saved
[[265   1]
 [ 10  83]]
Precision: 0.9881
Recall: 0.8925
F1 Score: 0.9379
Validation Accuracy: 0.9693593314763231
model 6 saved
[[262   7]
 [  4  86]]
Precision: 0.9247
Recall: 0.9556
F1 Score: 0.9399
Validation Accuracy: 0.969359331476323

In [21]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/XGBoost/model_4.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['XGB_prediction_non'] = [i[0] for i in y_pred_prob];
output['XGB_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[9.9737012e-01 2.6298636e-03]
 [9.2216247e-01 7.7837534e-02]
 [4.7328472e-03 9.9526715e-01]
 ...
 [9.9926877e-01 7.3123298e-04]
 [9.9579751e-01 4.2024814e-03]
 [9.9519521e-01 4.8047793e-03]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          0           0.998125             0.001875            1.000000   
1          0           0.827225             0.172775            1.000000   
2          1           0.004049             0.995951            0.000000   
3          1           0.048276             0.951724            0.142857   
4          0           0.827225             0.172775            1.000000   
...      ...                ...                  ...                 ...   
2933       0           0.998125             0.001875            1.000000   
2934       0           0.998125             0.001875            1.000000   
2935       0           0.998125             0.001875            1.000000   
2936       0           1.000000             0.000000            1.000000   
2937       0           0.998125             0.001875            1.000000   

      knn_prediction_phish  XGB_prediction_non  XGB_prediction_phish  
0                 0.000000            0.997370              0.002630  
1                 0.000000            0.922162              0.077838  
2                 1.000000            0.004733              0.995267  
3                 0.857143            0.009208              0.990792  
4                 0.000000            0.908173              0.091827  
...                    ...                 ...                   ...  
2933              0.000000            0.997800              0.002200  
2934              0.000000            0.995195              0.004805  
2935              0.000000            0.999269              0.000731  
2936              0.000000            0.995798              0.004202  
2937              0.000000            0.995195              0.004805  

[2938 rows x 7 columns]

In [22]:
output.shape


(2938, 7)

In [23]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Binary/Base_classifier_result(URL cross).csv', index=False)