In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(binary).csv")
urldata.head()


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0           0        0       0           1          1            0   
1           1        0       0           1          1            1   
2           2        0       0           1          1            0   
3           3        0       0           1          3            0   
4           4        0       0           1          3            0   

   https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0             0        0              0            0  ...           0   
1             0        0              0            0  ...           0   
2             1        0              0            0  ...           0   
3             0        0              0            0  ...           0   
4             0        0              0            0  ...           0   

   Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0          49        691          42       13135                6400   
1           4         66           3        2034                 818   
2           1        100          27       32987               10451   
3           0          0           1           0                  52   
4         117        219          23        7944                3468   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.052344              0.528869   
1                       2.486553              0.676197   
2                       3.156349              0.836681   
3                       0.000000              0.000000   
4                       2.290657              0.524460   

   Body To Special Char Ratio  Label  
0                    0.257690      0  
1                    0.271941      0  
2                    0.265079      0  
3                    0.227074      0  
4                    0.228956      0  

[5 rows x 46 columns]

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char'], axis = 1)

In [6]:
urldata.shape

(6527, 21)

In [7]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   iFrame                         6527 non-null   int64  
 1   Mouse Over                     6527 non-null   int64  
 2   Right Click                    6527 non-null   int64  
 3   Web Forwards                   6527 non-null   int64  
 4   Number of page tokens          6527 non-null   int64  
 5   number of sentences            6527 non-null   int64  
 6   number of html tags            6527 non-null   int64  
 7   number of whitespace           6527 non-null   int64  
 8   url Is Live                    6527 non-null   int64  
 9   HTML Length                    6527 non-null   int64  
 10  Num Objects                    6527 non-null   int64  
 11  Num Embeds                     6527 non-null   int64  
 12  Num Images                     6527 non-null   i

In [8]:
urldata.describe()

iFrame   Mouse Over  Right Click  Web Forwards  \
count  6527.000000  6527.000000       6527.0   6527.000000   
mean      0.999387     0.000306          0.0      0.937490   
std       0.024750     0.017504          0.0      0.242097   
min       0.000000     0.000000          0.0      0.000000   
25%       1.000000     0.000000          0.0      1.000000   
50%       1.000000     0.000000          0.0      1.000000   
75%       1.000000     0.000000          0.0      1.000000   
max       1.000000     1.000000          0.0      1.000000   

       Number of page tokens  number of sentences  number of html tags  \
count            6527.000000          6527.000000          6527.000000   
mean             3606.327256          1812.912364           433.003830   
std              5828.320950          3543.768665           733.633379   
min                 1.000000             1.000000             1.000000   
25%               103.000000            20.000000            16.000000   
50%              1719.000000           666.000000           159.000000   
75%              5131.500000          1683.000000           525.000000   
max             74678.000000         43777.000000          8760.000000   

       number of whitespace  url Is Live   HTML Length  ...   Num Embeds  \
count                6527.0  6527.000000  6.527000e+03  ...  6527.000000   
mean                    0.0     0.422399  4.792708e+04  ...     0.000613   
std                     0.0     0.505630  1.162579e+05  ...     0.024750   
min                     0.0    -1.000000  0.000000e+00  ...     0.000000   
25%                     0.0     0.000000  6.630000e+02  ...     0.000000   
50%                     0.0     0.000000  1.811000e+04  ...     0.000000   
75%                     0.0     1.000000  3.479350e+04  ...     0.000000   
max                     0.0     1.000000  2.107635e+06  ...     1.000000   

        Num Images    Num Links   Num Titles    Num Script  \
count  6527.000000  6527.000000  6527.000000  6.527000e+03   
mean     13.078290    71.623717     8.910679  2.911380e+04   
std      37.301509   117.479116    34.106562  9.681226e+04   
min       0.000000     0.000000     0.000000  0.000000e+00   
25%       0.000000     0.000000     1.000000  4.400000e+01   
50%       3.000000    28.000000     1.000000  6.953000e+03   
75%       8.000000    91.000000     5.000000  1.672850e+04   
max     526.000000  1159.000000  1042.000000  2.076633e+06   

       Special Characters  Script To Special Chars Ratio  \
count         6527.000000                    6527.000000   
mean         11168.757009                       4.175212   
std          24456.427671                      22.109670   
min              0.000000                       0.000000   
25%            143.000000                       0.043897   
50%           4102.000000                       1.916015   
75%           9126.000000                       2.764967   
max         359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio        Label  
count           6527.000000                 6527.000000  6527.000000  
mean               0.456171                    0.227569     0.240999  
std                0.349764                    0.077076     0.427722  
min                0.000000                    0.000000     0.000000  
25%                0.016658                    0.197183     0.000000  
50%                0.488331                    0.248328     0.000000  
75%                0.739913                    0.262355     0.000000  
max                1.005038                    0.605483     1.000000  

[8 rows x 21 columns]

In [9]:
#checking the data for null or missing values
urldata.isnull().sum()

iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page tokens            0
number of sentences              0
number of html tags              0
number of whitespace             0
url Is Live                      0
HTML Length                      0
Num Objects                      0
Num Embeds                       0
Num Images                       0
Num Links                        0
Num Titles                       0
Num Script                       0
Special Characters               0
Script To Special Chars Ratio    0
Script To body Ratio             0
Body To Special Char Ratio       0
Label                            0
dtype: int64

In [10]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0          1           0            0             1                     59   
1          1           0            0             0                   7987   
2          1           0            0             1                   1695   
3          1           0            0             1                    102   
4          1           0            0             1                   4314   
...      ...         ...          ...           ...                    ...   
6522       1           0            0             1                    908   
6523       1           0            0             1                     11   
6524       1           0            0             1                   3833   
6525       1           0            0             1                    100   
6526       1           0            0             1                      3   

      number of sentences  number of html tags  number of whitespace  \
0                      11                    5                     0   
1                    5161                  351                     0   
2                    1679                  162                     0   
3                      20                   23                     0   
4                     750                  568                     0   
...                   ...                  ...                   ...   
6522                  189                  158                     0   
6523                    3                    8                     0   
6524                10053                  758                     0   
6525                    7                   21                     0   
6526                    1                    1                     0   

      url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0               0         1295  ...           0           0          0   
1               1        94948  ...           0           4         44   
2               0        32749  ...           0           4         28   
3               0          275  ...           0           3          1   
4               1         7948  ...           0           0        115   
...           ...          ...  ...         ...         ...        ...   
6522            0         1225  ...           0           4          3   
6523            0           40  ...           0           0          0   
6524            0        43838  ...           0          11        192   
6525           -1          199  ...           0           2          0   
6526            0            0  ...           0           0          0   

      Num Titles  Num Script  Special Characters  \
0              0        1295                 152   
1              2       94135               20990   
2              1       15924                8341   
3              2           0                  51   
4             18        1007                1488   
...          ...         ...                 ...   
6522           2         883                 339   
6523           1           0                   9   
6524          20       13475                9816   
6525           1           0                  43   
6526           1           0                   0   

      Script To Special Chars Ratio  Script To body Ratio  \
0                          8.519737              1.000000   
1                          4.484755              0.991437   
2                          1.909124              0.486244   
3                          0.000000              0.000000   
4                          0.676747              0.126699   
...                             ...                   ...   
6522                       2.604720              0.720816   
6523                       0.000000              0.000000   
6524                       1.372759              0.307382   
6525                       0.000000              0.000000   
6526               

In [11]:
urldata.shape

(6527, 21)

In [12]:
import numpy as np

# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))


print(x.shape, y.shape)


(6527, 20) (6527,)


In [13]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(3589, 20) (2938, 20)
(3589,) (2938,)


In [14]:
output = {}
output['labels'] = y_test

**DecisionTree Classifier**

In [15]:
import keras

from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import pickle
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  dtcclassifier = DecisionTreeClassifier(max_depth=5)
  #compile model using mse as a measure of model performance
  dtcclassifier.fit(x_train, y_train)

  y_pred = dtcclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/DTC/model_'+str(n)+'.h5'
  pickle.dump(dtcclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [16]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[258   4]
 [ 32  65]]
Precision: 0.9420
Recall: 0.6701
F1 Score: 0.7831
Validation Accuracy: 0.8997214484679665
model 0 saved
[[259   5]
 [ 25  70]]
Precision: 0.9333
Recall: 0.7368
F1 Score: 0.8235
Validation Accuracy: 0.9164345403899722
model 1 saved
[[269  11]
 [ 26  53]]
Precision: 0.8281
Recall: 0.6709
F1 Score: 0.7413
Validation Accuracy: 0.8969359331476323
model 2 saved
[[257   8]
 [ 38  56]]
Precision: 0.8750
Recall: 0.5957
F1 Score: 0.7089
Validation Accuracy: 0.871866295264624
model 3 saved
[[261   6]
 [ 26  66]]
Precision: 0.9167
Recall: 0.7174
F1 Score: 0.8049
Validation Accuracy: 0.9108635097493036
model 4 saved
[[263  21]
 [ 13  62]]
Precision: 0.7470
Recall: 0.8267
F1 Score: 0.7848
Validation Accuracy: 0.9052924791086351
model 5 saved
[[251  20]
 [ 20  68]]
Precision: 0.7727
Recall: 0.7727
F1 Score: 0.7727
Validation Accuracy: 0.8885793871866295
model 6 saved
[[256  16]
 [ 30  57]]
Precision: 0.7808
Recall: 0.6552
F1 Score: 0.7125
Validation Accuracy: 0.871866295264624


In [17]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/DTC/model_1.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['dt_prediction_non'] = [i[0] for i in y_pred_prob];
output['dt_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.95592287 0.04407713]
 [0.9939759  0.0060241 ]
 [0.9939759  0.0060241 ]
 ...
 [0.97014925 0.02985075]
 [0.97014925 0.02985075]
 [0.9939759  0.0060241 ]]


labels  dt_prediction_non  dt_prediction_phish
0          1           0.955923             0.044077
1          0           0.993976             0.006024
2          0           0.993976             0.006024
3          0           0.993976             0.006024
4          0           0.993976             0.006024
...      ...                ...                  ...
2933       1           0.027523             0.972477
2934       0           0.955923             0.044077
2935       0           0.970149             0.029851
2936       0           0.970149             0.029851
2937       0           0.993976             0.006024

[2938 rows x 3 columns]

**KNN**

In [18]:
import keras

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_knn(x_train, x_val, y_train, y_val, opt, n):
  knnclassifier = KNeighborsClassifier(n_neighbors=7, weights='uniform', algorithm='kd_tree', leaf_size=5)
  #compile model using mse as a measure of model performance
  knnclassifier.fit(x_train, y_train)

  y_pred = knnclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/KNN/model_'+str(n)+'.h5'
  pickle.dump(knnclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [19]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_knn(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[257   5]
 [ 18  79]]
Precision: 0.9405
Recall: 0.8144
F1 Score: 0.8729
Validation Accuracy: 0.935933147632312
model 0 saved
[[256   8]
 [ 21  74]]
Precision: 0.9024
Recall: 0.7789
F1 Score: 0.8362
Validation Accuracy: 0.9192200557103064
model 1 saved
[[272   8]
 [ 13  66]]
Precision: 0.8919
Recall: 0.8354
F1 Score: 0.8627
Validation Accuracy: 0.9415041782729805
model 2 saved
[[257   8]
 [ 23  71]]
Precision: 0.8987
Recall: 0.7553
F1 Score: 0.8208
Validation Accuracy: 0.9136490250696379
model 3 saved
[[257  10]
 [ 18  74]]
Precision: 0.8810
Recall: 0.8043
F1 Score: 0.8409
Validation Accuracy: 0.9220055710306406
model 4 saved
[[267  17]
 [ 20  55]]
Precision: 0.7639
Recall: 0.7333
F1 Score: 0.7483
Validation Accuracy: 0.8969359331476323
model 5 saved
[[258  13]
 [ 18  70]]
Precision: 0.8434
Recall: 0.7955
F1 Score: 0.8187
Validation Accuracy: 0.9136490250696379
model 6 saved
[[264   8]
 [ 23  64]]
Precision: 0.8889
Recall: 0.7356
F1 Score: 0.8050
Validation Accuracy: 0.9136490250696379

In [20]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/KNN/model_2.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['knn_prediction_non'] = [i[0] for i in y_pred_prob];
output['knn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.71428571 0.28571429]
 [1.         0.        ]
 [1.         0.        ]
 ...
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          1           0.955923             0.044077            0.714286   
1          0           0.993976             0.006024            1.000000   
2          0           0.993976             0.006024            1.000000   
3          0           0.993976             0.006024            1.000000   
4          0           0.993976             0.006024            1.000000   
...      ...                ...                  ...                 ...   
2933       1           0.027523             0.972477            0.000000   
2934       0           0.955923             0.044077            1.000000   
2935       0           0.970149             0.029851            1.000000   
2936       0           0.970149             0.029851            1.000000   
2937       0           0.993976             0.006024            1.000000   

      knn_prediction_phish  
0                 0.285714  
1                 0.000000  
2                 0.000000  
3                 0.000000  
4                 0.000000  
...                    ...  
2933              1.000000  
2934              0.000000  
2935              0.000000  
2936              0.000000  
2937              0.000000  

[2938 rows x 5 columns]

**XGB Classifier**

In [ ]:
import keras

from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_xgb(x_train, x_val, y_train, y_val, opt, n):
  xgbclassifier = XGBClassifier(n_neighbors=5)
  #compile model using mse as a measure of model performance
  xgbclassifier.fit(x_train, y_train)

  y_pred = xgbclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/XGBoost/model_'+str(n)+'.h5'
  pickle.dump(xgbclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_xgb(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[278  12]
 [  3  66]]
Precision: 0.8462
Recall: 0.9565
F1 Score: 0.8980
Validation Accuracy: 0.958217270194986
model 0 saved
[[265  15]
 [ 10  69]]
Precision: 0.8214
Recall: 0.8734
F1 Score: 0.8466
Validation Accuracy: 0.9303621169916435
model 1 saved
[[276  11]
 [ 12  60]]
Precision: 0.8451
Recall: 0.8333
F1 Score: 0.8392
Validation Accuracy: 0.935933147632312
model 2 saved
[[268   5]
 [ 14  72]]
Precision: 0.9351
Recall: 0.8372
F1 Score: 0.8834
Validation Accuracy: 0.947075208913649
model 3 saved
[[276   2]
 [  5  76]]
Precision: 0.9744
Recall: 0.9383
F1 Score: 0.9560
Validation Accuracy: 0.9805013927576601
model 4 saved
[[262   2]
 [ 16  79]]
Precision: 0.9753
Recall: 0.8316
F1 Score: 0.8977
Validation Accuracy: 0.9498607242339833
model 5 saved
[[259   5]
 [ 24  71]]
Precision: 0.9342
Recall: 0.7474
F1 Score: 0.8304
Validation Accuracy: 0.9192200557103064
model 6 saved
[[262   6]
 [ 18  73]]
Precision: 0.9241
Recall: 0.8022
F1 Score: 0.8588
Validation Accuracy: 0.9331476323119777
m

In [21]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/XGBoost/model_4.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['XGB_prediction_non'] = [i[0] for i in y_pred_prob];
output['XGB_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.76045644 0.23954354]
 [0.99130476 0.00869522]
 [0.92559767 0.07440232]
 ...
 [0.995173   0.004827  ]
 [0.9914332  0.0085668 ]
 [0.99434423 0.00565576]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          1           0.955923             0.044077            0.714286   
1          0           0.993976             0.006024            1.000000   
2          0           0.993976             0.006024            1.000000   
3          0           0.993976             0.006024            1.000000   
4          0           0.993976             0.006024            1.000000   
...      ...                ...                  ...                 ...   
2933       1           0.027523             0.972477            0.000000   
2934       0           0.955923             0.044077            1.000000   
2935       0           0.970149             0.029851            1.000000   
2936       0           0.970149             0.029851            1.000000   
2937       0           0.993976             0.006024            1.000000   

      knn_prediction_phish  XGB_prediction_non  XGB_prediction_phish  
0                 0.285714            0.760456              0.239544  
1                 0.000000            0.991305              0.008695  
2                 0.000000            0.925598              0.074402  
3                 0.000000            0.994100              0.005900  
4                 0.000000            0.991305              0.008695  
...                    ...                 ...                   ...  
2933              1.000000            0.093861              0.906139  
2934              0.000000            0.953950              0.046050  
2935              0.000000            0.995173              0.004827  
2936              0.000000            0.991433              0.008567  
2937              0.000000            0.994344              0.005656  

[2938 rows x 7 columns]

In [22]:
output.shape


(2938, 7)

In [23]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Binary/Base_classifier_result(HTML cross).csv', index=False)