In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(binary).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0              0        0       0           1          1            0   
1              1        0       0           1          1            1   
2              2        0       0           1          1            0   
3              3        0       0           1          3            0   
4              4        0       0           1          3            0   
...          ...      ...     ...         ...        ...          ...   
6522        9992        0       0           1          5            0   
6523        9994        0       0           1          3            0   
6524        9995        0       0           1          6            0   
6525        9996        0       0           1          5            0   
6526        9997        0       0           1          4            0   

      https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                0        0              0            0  ...           0   
1                0        0              0            0  ...           0   
2                1        0              0            0  ...           0   
3                0        0              0            0  ...           0   
4                0        0              0            0  ...           0   
...            ...      ...            ...          ...  ...         ...   
6522             0        0              0            0  ...           0   
6523             0        0              0            0  ...           0   
6524             0        0              0            0  ...           0   
6525             0        0              0            0  ...           0   
6526             0        0              0            0  ...           0   

      Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0             49        691          42       13135                6400   
1              4         66           3        2034                 818   
2              1        100          27       32987               10451   
3              0          0           1           0                  52   
4            117        219          23        7944                3468   
...          ...        ...         ...         ...                 ...   
6522           0          0           1           0                  34   
6523           0          0           1           0                  14   
6524           0          0           1           0                 249   
6525           0          0           1           0                   6   
6526           0          0           1           0                 630   

      Script To Special Chars Ratio  Script To body Ratio  \
0                          2.052344              0.528869   
1                          2.486553              0.676197   
2                          3.156349              0.836681   
3                          0.000000              0.000000   
4                          2.290657              0.524460   
...                             ...                   ...   
6522                       0.000000              0.000000   
6523                       0.000000              0.000000   
6524                       0.000000              0.000000   
6525                       0.000000              0.000000   
6526                       0.000000              0.000000   

      Body To Special Char Ratio  Label  
0                       0.257690      0  
1                       0.271941      0  
2                       0.265079      0  
3                       0.227074      0  
4                       0.228956      0  
...                          ...    ...  
6522                    0.185792      1  
6523                    0.197183      1  
6524                    0.315990      1  
6525                    0.139535      1  
6526                    0.310192      1  

[6527 rows x 46 columns]

In [ ]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [ ]:
urldata = urldata.drop(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                  21444   
1       1           0            0             1                   1075   
2       1           0            0             1                   4531   
3       1           0            0             1                     32   
4       1           0            0             1                   4880   

   number of sentences  number of html tags  number of whitespace  \
0                 1853                 3247                     0   
1                  136                  236                     0   
2                 2634                  486                     0   
3                    9                    8                     0   
4                  981                 1412                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1        24836  ...           0          49        691   
1            1         3008  ...           0           4         66   
2            1        39426  ...           0           1        100   
3            0          229  ...           0           0          0   
4            1        15147  ...           0         117        219   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0          42       13135                6400                       2.052344   
1           3        2034                 818                       2.486553   
2          27       32987               10451                       3.156349   
3           1           0                  52                       0.000000   
4          23        7944                3468                       2.290657   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.528869                    0.257690      0  
1              0.676197                    0.271941      0  
2              0.836681                    0.265079      0  
3              0.000000                    0.227074      0  
4              0.524460                    0.228956      0  

[5 rows x 21 columns]

In [ ]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   iFrame                         6527 non-null   int64  
 1   Mouse Over                     6527 non-null   int64  
 2   Right Click                    6527 non-null   int64  
 3   Web Forwards                   6527 non-null   int64  
 4   Number of page tokens          6527 non-null   int64  
 5   number of sentences            6527 non-null   int64  
 6   number of html tags            6527 non-null   int64  
 7   number of whitespace           6527 non-null   int64  
 8   url Is Live                    6527 non-null   int64  
 9   HTML Length                    6527 non-null   int64  
 10  Num Objects                    6527 non-null   int64  
 11  Num Embeds                     6527 non-null   int64  
 12  Num Images                     6527 non-null   i

In [ ]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
dtype: int64

In [ ]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 6527
Non-Phishing: 4954 (75.90% of total)
Phishing: 1573 (24.10% of total)


In [ ]:

import numpy as np


In [ ]:
urldata.describe()

iFrame   Mouse Over  Right Click  Web Forwards  \
count  6527.000000  6527.000000       6527.0   6527.000000   
mean      0.999387     0.000306          0.0      0.937490   
std       0.024750     0.017504          0.0      0.242097   
min       0.000000     0.000000          0.0      0.000000   
25%       1.000000     0.000000          0.0      1.000000   
50%       1.000000     0.000000          0.0      1.000000   
75%       1.000000     0.000000          0.0      1.000000   
max       1.000000     1.000000          0.0      1.000000   

       Number of page tokens  number of sentences  number of html tags  \
count            6527.000000          6527.000000          6527.000000   
mean             3606.327256          1812.912364           433.003830   
std              5828.320950          3543.768665           733.633379   
min                 1.000000             1.000000             1.000000   
25%               103.000000            20.000000            16.000000   
50%              1719.000000           666.000000           159.000000   
75%              5131.500000          1683.000000           525.000000   
max             74678.000000         43777.000000          8760.000000   

       number of whitespace  url Is Live   HTML Length  ...   Num Embeds  \
count                6527.0  6527.000000  6.527000e+03  ...  6527.000000   
mean                    0.0     0.422399  4.792708e+04  ...     0.000613   
std                     0.0     0.505630  1.162579e+05  ...     0.024750   
min                     0.0    -1.000000  0.000000e+00  ...     0.000000   
25%                     0.0     0.000000  6.630000e+02  ...     0.000000   
50%                     0.0     0.000000  1.811000e+04  ...     0.000000   
75%                     0.0     1.000000  3.479350e+04  ...     0.000000   
max                     0.0     1.000000  2.107635e+06  ...     1.000000   

        Num Images    Num Links   Num Titles    Num Script  \
count  6527.000000  6527.000000  6527.000000  6.527000e+03   
mean     13.078290    71.623717     8.910679  2.911380e+04   
std      37.301509   117.479116    34.106562  9.681226e+04   
min       0.000000     0.000000     0.000000  0.000000e+00   
25%       0.000000     0.000000     1.000000  4.400000e+01   
50%       3.000000    28.000000     1.000000  6.953000e+03   
75%       8.000000    91.000000     5.000000  1.672850e+04   
max     526.000000  1159.000000  1042.000000  2.076633e+06   

       Special Characters  Script To Special Chars Ratio  \
count         6527.000000                    6527.000000   
mean         11168.757009                       4.175212   
std          24456.427671                      22.109670   
min              0.000000                       0.000000   
25%            143.000000                       0.043897   
50%           4102.000000                       1.916015   
75%           9126.000000                       2.764967   
max         359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio        Label  
count           6527.000000                 6527.000000  6527.000000  
mean               0.456171                    0.227569     0.240999  
std                0.349764                    0.077076     0.427722  
min                0.000000                    0.000000     0.000000  
25%                0.016658                    0.197183     0.000000  
50%                0.488331                    0.248328     0.000000  
75%                0.739913                    0.262355     0.000000  
max                1.005038                    0.605483     1.000000  

[8 rows x 21 columns]

In [ ]:
#checking the data for null or missing values
urldata.isnull().sum()

iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page tokens            0
number of sentences              0
number of html tags              0
number of whitespace             0
url Is Live                      0
HTML Length                      0
Num Objects                      0
Num Embeds                       0
Num Images                       0
Num Links                        0
Num Titles                       0
Num Script                       0
Special Characters               0
Script To Special Chars Ratio    0
Script To body Ratio             0
Body To Special Char Ratio       0
Label                            0
dtype: int64

In [ ]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                     23   
1       1           0            0             1                  10657   
2       1           0            0             0                   2103   
3       1           0            0             1                   3833   
4       1           0            0             1                   1695   

   number of sentences  number of html tags  number of whitespace  \
0                    3                    6                     0   
1                 2872                 1106                     0   
2                  287                  457                     0   
3                10053                  758                     0   
4                 1679                  162                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            0           71  ...           0           0          0   
1            1        39924  ...           0          44        203   
2            1         6635  ...           0           1        115   
3            0        43843  ...           0          11        192   
4            0        32749  ...           0           4         28   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0           1           0                  14                       0.000000   
1          55       16612               10908                       1.522919   
2          10        2522                1587                       1.589162   
3          20       13480                9816                       1.373268   
4           1       15924                8341                       1.909124   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.000000                    0.197183      0  
1              0.416091                    0.273219      0  
2              0.380106                    0.239186      0  
3              0.307461                    0.223890      0  
4              0.486244                    0.254695      0  

[5 rows x 21 columns]

In [ ]:
import numpy as np
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [ ]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(3589, 20) (2938, 20)
(3589,) (2938,)


In [ ]:
output = {}
output['labels'] = y_test

**MLP**

In [ ]:
import keras

from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle

def model_mlp(x_train, x_val, y_train, y_val, opt, n):
  mlpclassifier = MLPClassifier(alpha=0.0001, hidden_layer_sizes=([100,100,100]))
  #compile model using mse as a measure of model performance
  mlpclassifier.fit(x_train, y_train)

  y_pred = mlpclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/MLP/model_'+str(n)+'.h5'
  pickle.dump(mlpclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_mlp(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[247  25]
 [ 43  44]]
Precision: 0.6377
Recall: 0.5057
F1 Score: 0.5641
Validation Accuracy: 0.8105849582172702
model 0 saved
[[251  37]
 [ 31  40]]
Precision: 0.5195
Recall: 0.5634
F1 Score: 0.5405
Validation Accuracy: 0.8105849582172702
model 1 saved
[[236  41]
 [ 30  52]]
Precision: 0.5591
Recall: 0.6341
F1 Score: 0.5943
Validation Accuracy: 0.8022284122562674
model 2 saved
[[249  37]
 [ 24  49]]
Precision: 0.5698
Recall: 0.6712
F1 Score: 0.6164
Validation Accuracy: 0.83008356545961
model 3 saved
[[227  49]
 [ 32  51]]
Precision: 0.5100
Recall: 0.6145
F1 Score: 0.5574
Validation Accuracy: 0.7743732590529248
model 4 saved
[[234  34]
 [ 28  63]]
Precision: 0.6495
Recall: 0.6923
F1 Score: 0.6702
Validation Accuracy: 0.8272980501392758
model 5 saved
[[ 90 172]
 [  9  88]]
Precision: 0.3385
Recall: 0.9072
F1 Score: 0.4930
Validation Accuracy: 0.4958217270194986
model 6 saved
[[214  52]
 [ 17  76]]
Precision: 0.5938
Recall: 0.8172
F1 Score: 0.6878
Validation Accuracy: 0.807799442896936
m

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/MLP/model_3.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['mlp_prediction_non'] = [i[0] for i in y_pred_prob];
output['mlp_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[1.00000000e+000 4.63278408e-021]
 [1.00000000e+000 1.83409020e-139]
 [2.77758362e-001 7.22241638e-001]
 ...
 [1.21342538e-001 8.78657462e-001]
 [9.99999994e-001 5.69171352e-009]
 [1.00000000e+000 2.72645734e-139]]


labels  mlp_prediction_non  mlp_prediction_phish
0          0            1.000000          4.632784e-21
1          0            1.000000         1.834090e-139
2          0            0.277758          7.222416e-01
3          1            0.303680          6.963204e-01
4          0            1.000000          2.524615e-08
...      ...                 ...                   ...
2933       1            0.000000          1.000000e+00
2934       0            0.168642          8.313583e-01
2935       1            0.121343          8.786575e-01
2936       1            1.000000          5.691714e-09
2937       0            1.000000         2.726457e-139

[2938 rows x 3 columns]

**Neural Network**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_aa(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]
  # print("check point")
  #create model
  model = Sequential()
  model.add(Dense(30, activation='relu', input_shape=(n_cols,)))
  model.add(Dense(10, activation='relu'))

  model.add(Dense(1, activation = 'sigmoid'))
  # softmax
  #compile model using mse as a measure of model performance
  model.compile(optimizer = opt, loss= 'binary_crossentropy', metrics=["accuracy"])

  history = model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/NN/model_'+str(n)+'.h5'
  pickle.dump(model, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_aa(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
101/101 [==============================] - 4s 5ms/step - loss: 616.2397 - accuracy: 0.7585 - val_loss: 149.0274 - val_accuracy: 0.7632
Epoch 2/100
101/101 [==============================] - 0s 3ms/step - loss: 201.4700 - accuracy: 0.7520 - val_loss: 33.6687 - val_accuracy: 0.7437
Epoch 3/100
101/101 [==============================] - 0s 3ms/step - loss: 54.0784 - accuracy: 0.7368 - val_loss: 7.8167 - val_accuracy: 0.7159
Epoch 4/100
101/101 [==============================] - 0s 3ms/step - loss: 18.0066 - accuracy: 0.7616 - val_loss: 7.5425 - val_accuracy: 0.7883
Epoch 5/100
101/101 [==============================] - 0s 3ms/step - loss: 17.6382 - accuracy: 0.7765 - val_loss: 14.0622 - val_accuracy: 0.7409
Epoch 6/100
101/101 [==============================] - 0s 3ms/step - loss: 18.4021 - accuracy: 0.7836 - val_loss: 3.7066 - val_accuracy: 0.7688
Epoch 7/100
101/101 [==============================] - 0s 3ms/step - loss: 23.6051 - accuracy: 0.7582 - val_loss: 9.2740 - val_acc

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.80      1.00      0.89       288
           1       0.00      0.00      0.00        71

    accuracy                           0.80       359
   macro avg       0.40      0.50      0.45       359
weighted avg       0.64      0.80      0.71       359

Accuracy: 0.8022284122562674
[[288   0]
 [ 71   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
INFO:tensorflow:Assets written to: ram://e9375a1c-7d38-4c04-9081-718655436fee/assets
model 1 saved
Epoch 1/100
101/101 [==============================] - 1s 4ms/step - loss: 93.4164 - accuracy: 0.7663 - val_loss: 44.2719 - val_accuracy: 0.7939
Epoch 2/100
101/101 [==============================] - 0s 3ms/step - loss: 32.9086 - accuracy: 0.7576 - val_loss: 65.7437 - val_accuracy: 0.7883
Epoch 3/100
101/101 [==============================] - 0s 3ms/step - loss: 23.1807 - accuracy: 0.7876 - val_loss: 25.7321 - val_accuracy: 0.7103
Epoch 4/100
101/101 [================

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/NN/model_0.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[1.00000000e+000 4.63278408e-021]
 [1.00000000e+000 1.83409020e-139]
 [2.77758362e-001 7.22241638e-001]
 ...
 [1.21342538e-001 8.78657462e-001]
 [9.99999994e-001 5.69171352e-009]
 [1.00000000e+000 2.72645734e-139]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0            1.000000          4.632784e-21           1.000000   
1          0            1.000000         1.834090e-139           1.000000   
2          0            0.277758          7.222416e-01           0.277758   
3          1            0.303680          6.963204e-01           0.303680   
4          0            1.000000          2.524615e-08           1.000000   
...      ...                 ...                   ...                ...   
2933       1            0.000000          1.000000e+00           0.000000   
2934       0            0.168642          8.313583e-01           0.168642   
2935       1            0.121343          8.786575e-01           0.121343   
2936       1            1.000000          5.691714e-09           1.000000   
2937       0            1.000000         2.726457e-139           1.000000   

      nn_prediction_phish  
0            4.632784e-21  
1           1.834090e-139  
2            7.222416e-01  
3            6.963204e-01  
4            2.524615e-08  
...                   ...  
2933         1.000000e+00  
2934         8.313583e-01  
2935         8.786575e-01  
2936         5.691714e-09  
2937        2.726457e-139  

[2938 rows x 5 columns]

**Neural Network 2**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_a(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]

  #create model
  model_2 = Sequential()
  model_2.add(Dense(30, activation='sigmoid', input_shape=(n_cols,)))
  model_2.add(Dense(25, activation='sigmoid'))
  model_2.add(Dense(20, activation='sigmoid'))
  model_2.add(Dense(15, activation='sigmoid'))
  model_2.add(Dense(10, activation='sigmoid'))
  model_2.add(Dense(1, activation = 'sigmoid'))

  #compile model using mse as a measure of model performance
  model_2.compile(optimizer='adam', loss='mean_squared_error')



  history = model_2.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model_2.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/NN_2/model_'+str(n)+'.h5'
  pickle.dump(model_2, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_a(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
101/101 [==============================] - 1s 4ms/step - loss: 0.2033 - val_loss: 0.1847
Epoch 2/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1811 - val_loss: 0.1828
Epoch 3/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1795 - val_loss: 0.1807
Epoch 4/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1751 - val_loss: 0.1723
Epoch 5/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1613 - val_loss: 0.1564
Epoch 6/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1486 - val_loss: 0.1486
Epoch 7/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1432 - val_loss: 0.1431
Epoch 8/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1416 - val_loss: 0.1415
Epoch 9/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1400 - val_loss: 0.1418
Epoch 10/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1384 - val_lo

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/HTML/NN_2/model_0.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn2_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn2_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[1.00000000e+000 4.63278408e-021]
 [1.00000000e+000 1.83409020e-139]
 [2.77758362e-001 7.22241638e-001]
 ...
 [1.21342538e-001 8.78657462e-001]
 [9.99999994e-001 5.69171352e-009]
 [1.00000000e+000 2.72645734e-139]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0            1.000000          4.632784e-21           1.000000   
1          0            1.000000         1.834090e-139           1.000000   
2          0            0.277758          7.222416e-01           0.277758   
3          1            0.303680          6.963204e-01           0.303680   
4          0            1.000000          2.524615e-08           1.000000   
...      ...                 ...                   ...                ...   
2933       1            0.000000          1.000000e+00           0.000000   
2934       0            0.168642          8.313583e-01           0.168642   
2935       1            0.121343          8.786575e-01           0.121343   
2936       1            1.000000          5.691714e-09           1.000000   
2937       0            1.000000         2.726457e-139           1.000000   

      nn_prediction_phish  nn2_prediction_non  nn2_prediction_phish  
0            4.632784e-21            1.000000          4.632784e-21  
1           1.834090e-139            1.000000         1.834090e-139  
2            7.222416e-01            0.277758          7.222416e-01  
3            6.963204e-01            0.303680          6.963204e-01  
4            2.524615e-08            1.000000          2.524615e-08  
...                   ...                 ...                   ...  
2933         1.000000e+00            0.000000          1.000000e+00  
2934         8.313583e-01            0.168642          8.313583e-01  
2935         8.786575e-01            0.121343          8.786575e-01  
2936         5.691714e-09            1.000000          5.691714e-09  
2937        2.726457e-139            1.000000         2.726457e-139  

[2938 rows x 7 columns]

In [ ]:
output.shape


(2938, 7)

In [ ]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Binary/Base_classifier_result(HTML cross)(3).csv', index=False)