In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(binary).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0              0        0       0           1          1            0   
1              1        0       0           1          1            1   
2              2        0       0           1          1            0   
3              3        0       0           1          3            0   
4              4        0       0           1          3            0   
...          ...      ...     ...         ...        ...          ...   
6522        9992        0       0           1          5            0   
6523        9994        0       0           1          3            0   
6524        9995        0       0           1          6            0   
6525        9996        0       0           1          5            0   
6526        9997        0       0           1          4            0   

      https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                0        0              0            0  ...           0   
1                0        0              0            0  ...           0   
2                1        0              0            0  ...           0   
3                0        0              0            0  ...           0   
4                0        0              0            0  ...           0   
...            ...      ...            ...          ...  ...         ...   
6522             0        0              0            0  ...           0   
6523             0        0              0            0  ...           0   
6524             0        0              0            0  ...           0   
6525             0        0              0            0  ...           0   
6526             0        0              0            0  ...           0   

      Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0             49        691          42       13135                6400   
1              4         66           3        2034                 818   
2              1        100          27       32987               10451   
3              0          0           1           0                  52   
4            117        219          23        7944                3468   
...          ...        ...         ...         ...                 ...   
6522           0          0           1           0                  34   
6523           0          0           1           0                  14   
6524           0          0           1           0                 249   
6525           0          0           1           0                   6   
6526           0          0           1           0                 630   

      Script To Special Chars Ratio  Script To body Ratio  \
0                          2.052344              0.528869   
1                          2.486553              0.676197   
2                          3.156349              0.836681   
3                          0.000000              0.000000   
4                          2.290657              0.524460   
...                             ...                   ...   
6522                       0.000000              0.000000   
6523                       0.000000              0.000000   
6524                       0.000000              0.000000   
6525                       0.000000              0.000000   
6526                       0.000000              0.000000   

      Body To Special Char Ratio  Label  
0                       0.257690      0  
1                       0.271941      0  
2                       0.265079      0  
3                       0.227074      0  
4                       0.228956      0  
...                          ...    ...  
6522                    0.185792      1  
6523                    0.197183      1  
6524                    0.315990      1  
6525                    0.139535      1  
6526                    0.310192      1  

[6527 rows x 46 columns]

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0'], axis = 1).copy()

urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0          49   
1              0            0           0  ...           0           4   
2              0            0           0  ...           0           1   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0         117   

   Num Links  Num Titles  Num Script  Special Characters  \
0        691          42       13135                6400   
1         66           3        2034                 818   
2        100          27       32987               10451   
3          0           1           0                  52   
4        219          23        7944                3468   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.052344              0.528869   
1                       2.486553              0.676197   
2                       3.156349              0.836681   
3                       0.000000              0.000000   
4                       2.290657              0.524460   

   Body To Special Char Ratio  Label  
0                    0.257690      0  
1                    0.271941      0  
2                    0.265079      0  
3                    0.227074      0  
4                    0.228956      0  

[5 rows x 45 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Have IP                        6527 non-null   int64  
 1   Have @                         6527 non-null   int64  
 2   URL Length                     6527 non-null   int64  
 3   URL Depth                      6527 non-null   int64  
 4   Redirection                    6527 non-null   int64  
 5   https Domain                   6527 non-null   int64  
 6   TinyURL                        6527 non-null   int64  
 7   Prefix/Suffix                  6527 non-null   int64  
 8   Have client                    6527 non-null   int64  
 9   Have admin                     6527 non-null   int64  
 10  Have login                     6527 non-null   int64  
 11  Have server                    6527 non-null   int64  
 12  .php                           6527 non-null   i

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
dtype: int64

In [8]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 6527
Non-Phishing: 4954 (75.90% of total)
Phishing: 1573 (24.10% of total)


In [9]:

import numpy as np


In [10]:
urldata.describe()

Have IP       Have @  URL Length    URL Depth  Redirection  \
count   6527.0  6527.000000      6527.0  6527.000000  6527.000000   
mean       0.0     0.004137         1.0     4.397579     0.050406   
std        0.0     0.064189         0.0     2.997529     0.218798   
min        0.0     0.000000         1.0     0.000000     0.000000   
25%        0.0     0.000000         1.0     2.000000     0.000000   
50%        0.0     0.000000         1.0     4.000000     0.000000   
75%        0.0     0.000000         1.0     6.000000     0.000000   
max        0.0     1.000000         1.0    18.000000     1.000000   

       https Domain      TinyURL  Prefix/Suffix  Have client   Have admin  \
count   6527.000000  6527.000000    6527.000000  6527.000000  6527.000000   
mean       0.060518     0.056841       0.042746     0.001379     0.019304   
std        0.238462     0.231556       0.202298     0.037111     0.137603   
min        0.000000     0.000000       0.000000     0.000000     0.000000   
25%        0.000000     0.000000       0.000000     0.000000     0.000000   
50%        0.000000     0.000000       0.000000     0.000000     0.000000   
75%        0.000000     0.000000       0.000000     0.000000     0.000000   
max        1.000000     1.000000       1.000000     1.000000     1.000000   

       ...   Num Embeds   Num Images    Num Links   Num Titles    Num Script  \
count  ...  6527.000000  6527.000000  6527.000000  6527.000000  6.527000e+03   
mean   ...     0.000613    13.078290    71.623717     8.910679  2.911380e+04   
std    ...     0.024750    37.301509   117.479116    34.106562  9.681226e+04   
min    ...     0.000000     0.000000     0.000000     0.000000  0.000000e+00   
25%    ...     0.000000     0.000000     0.000000     1.000000  4.400000e+01   
50%    ...     0.000000     3.000000    28.000000     1.000000  6.953000e+03   
75%    ...     0.000000     8.000000    91.000000     5.000000  1.672850e+04   
max    ...     1.000000   526.000000  1159.000000  1042.000000  2.076633e+06   

       Special Characters  Script To Special Chars Ratio  \
count         6527.000000                    6527.000000   
mean         11168.757009                       4.175212   
std          24456.427671                      22.109670   
min              0.000000                       0.000000   
25%            143.000000                       0.043897   
50%           4102.000000                       1.916015   
75%           9126.000000                       2.764967   
max         359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio        Label  
count           6527.000000                 6527.000000  6527.000000  
mean               0.456171                    0.227569     0.240999  
std                0.349764                    0.077076     0.427722  
min                0.000000                    0.000000     0.000000  
25%                0.016658                    0.197183     0.000000  
50%                0.488331                    0.248328     0.000000  
75%                0.739913                    0.262355     0.000000  
max                1.005038                    0.605483     1.000000  

[8 rows x 45 columns]

In [11]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                          0
Have @                           0
URL Length                       0
URL Depth                        0
Redirection                      0
https Domain                     0
TinyURL                          0
Prefix/Suffix                    0
Have client                      0
Have admin                       0
Have login                       0
Have server                      0
.php                             0
.html                            0
.info                            0
.txt                             0
.js                              0
.exe                             0
Num of periods                   0
Is encoded                       0
Num of encoded char              0
Num of parameters                0
Num of digits                    0
Num of spec char                 0
iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page token

In [12]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          3            0             0        0   
1        0       0           1         12            0             0        0   
2        0       0           1          4            0             0        0   
3        0       0           1          2            0             0        0   
4        0       0           1          6            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0          18   
1              1            0           0  ...           0           4   
2              0            0           0  ...           0           2   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0          49   

   Num Links  Num Titles  Num Script  Special Characters  \
0        279          23      105832               41731   
1         16           1        5925                5348   
2        113          10        2522                2515   
3          1           1        6864                1060   
4        266          10        8831                4242   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.536052              0.826528   
1                       1.107891              0.295924   
2                       1.002783              0.220667   
3                       6.475472              0.989192   
4                       2.081801              0.561376   

   Body To Special Char Ratio  Label  
0                    0.325911      0  
1                    0.267106      1  
2                    0.220054      0  
3                    0.152760      0  
4                    0.269659      0  

[5 rows x 45 columns]

In [13]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [14]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(3589, 44) (2938, 44)
(3589,) (2938,)


In [15]:
output = {}
output['labels'] = y_test

**Random Forest Classifier**

In [16]:
import keras
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  rfc = RandomForestClassifier(n_estimators=50, max_depth=10)
  #compile model using mse as a measure of model performance

  rfc.fit(x_train, y_train)


  y_pred = rfc.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/RFC/model_'+str(n)+'.h5'
  pickle.dump(rfc, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [17]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[263   3]
 [  2  91]]
Precision: 0.9681
Recall: 0.9785
F1 Score: 0.9733
Validation Accuracy: 0.9860724233983287
model 0 saved
[[269   1]
 [  5  84]]
Precision: 0.9882
Recall: 0.9438
F1 Score: 0.9655
Validation Accuracy: 0.9832869080779945
model 1 saved
[[273   3]
 [  2  81]]
Precision: 0.9643
Recall: 0.9759
F1 Score: 0.9701
Validation Accuracy: 0.9860724233983287
model 2 saved
[[276   2]
 [  6  75]]
Precision: 0.9740
Recall: 0.9259
F1 Score: 0.9494
Validation Accuracy: 0.9777158774373259
model 3 saved
[[273   0]
 [  4  82]]
Precision: 1.0000
Recall: 0.9535
F1 Score: 0.9762
Validation Accuracy: 0.9888579387186629
model 4 saved
[[264   3]
 [  2  90]]
Precision: 0.9677
Recall: 0.9783
F1 Score: 0.9730
Validation Accuracy: 0.9860724233983287
model 5 saved
[[261   2]
 [  5  91]]
Precision: 0.9785
Recall: 0.9479
F1 Score: 0.9630
Validation Accuracy: 0.9805013927576601
model 6 saved
[[262   3]
 [  2  92]]
Precision: 0.9684
Recall: 0.9787
F1 Score: 0.9735
Validation Accuracy: 0.986072423398328

In [18]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/RFC/model_4.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['rfc_prediction_non'] = [i[0] for i in y_pred_prob];
output['rfc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output



[[0.97510838 0.02489162]
 [0.24773913 0.75226087]
 [0.88724184 0.11275816]
 ...
 [0.99822082 0.00177918]
 [0.02797624 0.97202376]
 [0.07083336 0.92916664]]


labels  rfc_prediction_non  rfc_prediction_phish
0          0            0.975108              0.024892
1          1            0.247739              0.752261
2          0            0.887242              0.112758
3          1            0.001275              0.998725
4          0            0.971820              0.028180
...      ...                 ...                   ...
2933       0            0.999289              0.000711
2934       1            0.577514              0.422486
2935       0            0.998221              0.001779
2936       1            0.027976              0.972024
2937       1            0.070833              0.929167

[2938 rows x 3 columns]

**SVC**

In [ ]:
import keras

import pickle
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics


def model_svc(x_train, x_val, y_train, y_val, opt, n):
  svclassifier = SVC(kernel='rbf', probability= True)
  #compile model using mse as a measure of model performance
  svclassifier.fit(x_train, y_train)

  y_pred = svclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/SVC/model_'+str(n)+'.h5'
  pickle.dump(svclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
# early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_svc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[271   0]
 [ 88   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.754874651810585
model 0 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[278   0]
 [ 81   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7743732590529248
model 1 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[267   0]
 [ 92   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7437325905292479
model 2 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[276   0]
 [ 83   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7688022284122563
model 3 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[261   0]
 [ 98   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7270194986072424
model 4 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[274   0]
 [ 85   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7632311977715878
model 5 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[281   0]
 [ 78   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7827298050139275
model 6 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[270   0]
 [ 89   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7520891364902507
model 7 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[265   0]
 [ 94   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7381615598885793
model 8 saved


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[272   0]
 [ 86   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
Validation Accuracy: 0.7597765363128491
model 9 saved
Average Validation Accuracy: 0.756479046388945


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/SVC/model_6.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['svc_prediction_non'] = [i[0] for i in y_pred_prob];
output['svc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.63398067 0.36601933]
 [0.62763974 0.37236026]
 [0.58093986 0.41906014]
 ...
 [0.97547924 0.02452076]
 [0.59526295 0.40473705]
 [0.58130949 0.41869051]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          0            0.975108              0.024892            0.633981   
1          1            0.247739              0.752261            0.627640   
2          0            0.887242              0.112758            0.580940   
3          1            0.001275              0.998725            0.587953   
4          0            0.971820              0.028180            0.584020   
...      ...                 ...                   ...                 ...   
2933       0            0.999289              0.000711            0.812124   
2934       1            0.577514              0.422486            0.516384   
2935       0            0.998221              0.001779            0.975479   
2936       1            0.027976              0.972024            0.595263   
2937       1            0.070833              0.929167            0.581309   

      svc_prediction_phish  
0                 0.366019  
1                 0.372360  
2                 0.419060  
3                 0.412047  
4                 0.415980  
...                    ...  
2933              0.187876  
2934              0.483616  
2935              0.024521  
2936              0.404737  
2937              0.418691  

[2938 rows x 5 columns]

**Logistic Regression**

In [ ]:
import keras

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
import pickle

def model_lr(x_train, x_val, y_train, y_val, opt, n):
  lrclassifier = LogisticRegression()
  #compile model using mse as a measure of model performance
  lrclassifier.fit(x_train, y_train)

  y_pred = lrclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))
  

  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/LR/model_'+str(n)+'.h5'
  pickle.dump(lrclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_lr(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[271   0]
 [ 81   7]]
Precision: 1.0000
Recall: 0.0795
F1 Score: 0.1474
Validation Accuracy: 0.7743732590529248
model 0 saved
[[278   0]
 [ 75   6]]
Precision: 1.0000
Recall: 0.0741
F1 Score: 0.1379
Validation Accuracy: 0.7910863509749304


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 1 saved
[[266   1]
 [ 78  14]]
Precision: 0.9333
Recall: 0.1522
F1 Score: 0.2617
Validation Accuracy: 0.7799442896935933


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 2 saved
[[276   0]
 [ 76   7]]
Precision: 1.0000
Recall: 0.0843
F1 Score: 0.1556
Validation Accuracy: 0.7883008356545961


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 3 saved
[[261   0]
 [ 87  11]]
Precision: 1.0000
Recall: 0.1122
F1 Score: 0.2018
Validation Accuracy: 0.7576601671309192


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 4 saved
[[268   6]
 [ 61  24]]
Precision: 0.8000
Recall: 0.2824
F1 Score: 0.4174
Validation Accuracy: 0.8133704735376045


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 5 saved
[[281   0]
 [ 73   5]]
Precision: 1.0000
Recall: 0.0641
F1 Score: 0.1205
Validation Accuracy: 0.7966573816155988


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 6 saved
[[258  12]
 [ 49  40]]
Precision: 0.7692
Recall: 0.4494
F1 Score: 0.5674
Validation Accuracy: 0.83008356545961


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 7 saved
[[264   1]
 [ 62  32]]
Precision: 0.9697
Recall: 0.3404
F1 Score: 0.5039
Validation Accuracy: 0.8245125348189415


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 8 saved
[[266   6]
 [ 61  25]]
Precision: 0.8065
Recall: 0.2907
F1 Score: 0.4274
Validation Accuracy: 0.8128491620111732


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 9 saved
Average Validation Accuracy: 0.7968838019949891


In [20]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/LR/model_7.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['lr_prediction_non'] = [i[0] for i in y_pred_prob];
output['lr_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.97843181 0.02156819]
 [0.87577336 0.12422664]
 [0.54508506 0.45491494]
 ...
 [0.96617503 0.03382497]
 [0.67017399 0.32982601]
 [0.39941353 0.60058647]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          0            0.975108              0.024892            0.633981   
1          1            0.247739              0.752261            0.627640   
2          0            0.887242              0.112758            0.580940   
3          1            0.001275              0.998725            0.587953   
4          0            0.971820              0.028180            0.584020   
...      ...                 ...                   ...                 ...   
2933       0            0.999289              0.000711            0.812124   
2934       1            0.577514              0.422486            0.516384   
2935       0            0.998221              0.001779            0.975479   
2936       1            0.027976              0.972024            0.595263   
2937       1            0.070833              0.929167            0.581309   

      svc_prediction_phish  lr_prediction_non  lr_prediction_phish  
0                 0.366019           0.978432             0.021568  
1                 0.372360           0.875773             0.124227  
2                 0.419060           0.545085             0.454915  
3                 0.412047           0.519370             0.480630  
4                 0.415980           0.651903             0.348097  
...                    ...                ...                  ...  
2933              0.187876           0.828533             0.171467  
2934              0.483616           0.531246             0.468754  
2935              0.024521           0.966175             0.033825  
2936              0.404737           0.670174             0.329826  
2937              0.418691           0.399414             0.600586  

[2938 rows x 7 columns]

In [21]:
output.shape


(2938, 7)

In [22]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Binary/Base_classifier_result(URL-HTML cross)(2).csv', index=False)