In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(binary).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0              0        0       0           1          1            0   
1              1        0       0           1          1            1   
2              2        0       0           1          1            0   
3              3        0       0           1          3            0   
4              4        0       0           1          3            0   
...          ...      ...     ...         ...        ...          ...   
6522        9992        0       0           1          5            0   
6523        9994        0       0           1          3            0   
6524        9995        0       0           1          6            0   
6525        9996        0       0           1          5            0   
6526        9997        0       0           1          4            0   

      https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                0        0              0            0  ...           0   
1                0        0              0            0  ...           0   
2                1        0              0            0  ...           0   
3                0        0              0            0  ...           0   
4                0        0              0            0  ...           0   
...            ...      ...            ...          ...  ...         ...   
6522             0        0              0            0  ...           0   
6523             0        0              0            0  ...           0   
6524             0        0              0            0  ...           0   
6525             0        0              0            0  ...           0   
6526             0        0              0            0  ...           0   

      Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0             49        691          42       13135                6400   
1              4         66           3        2034                 818   
2              1        100          27       32987               10451   
3              0          0           1           0                  52   
4            117        219          23        7944                3468   
...          ...        ...         ...         ...                 ...   
6522           0          0           1           0                  34   
6523           0          0           1           0                  14   
6524           0          0           1           0                 249   
6525           0          0           1           0                   6   
6526           0          0           1           0                 630   

      Script To Special Chars Ratio  Script To body Ratio  \
0                          2.052344              0.528869   
1                          2.486553              0.676197   
2                          3.156349              0.836681   
3                          0.000000              0.000000   
4                          2.290657              0.524460   
...                             ...                   ...   
6522                       0.000000              0.000000   
6523                       0.000000              0.000000   
6524                       0.000000              0.000000   
6525                       0.000000              0.000000   
6526                       0.000000              0.000000   

      Body To Special Char Ratio  Label  
0                       0.257690      0  
1                       0.271941      0  
2                       0.265079      0  
3                       0.227074      0  
4                       0.228956      0  
...                          ...    ...  
6522                    0.185792      1  
6523                    0.197183      1  
6524                    0.315990      1  
6525                    0.139535      1  
6526                    0.310192      1  

[6527 rows x 46 columns]

In [ ]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [ ]:
urldata = urldata.drop(['Unnamed: 0'], axis = 1).copy()

urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0          49   
1              0            0           0  ...           0           4   
2              0            0           0  ...           0           1   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0         117   

   Num Links  Num Titles  Num Script  Special Characters  \
0        691          42       13135                6400   
1         66           3        2034                 818   
2        100          27       32987               10451   
3          0           1           0                  52   
4        219          23        7944                3468   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.052344              0.528869   
1                       2.486553              0.676197   
2                       3.156349              0.836681   
3                       0.000000              0.000000   
4                       2.290657              0.524460   

   Body To Special Char Ratio  Label  
0                    0.257690      0  
1                    0.271941      0  
2                    0.265079      0  
3                    0.227074      0  
4                    0.228956      0  

[5 rows x 45 columns]

In [ ]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Have IP                        6527 non-null   int64  
 1   Have @                         6527 non-null   int64  
 2   URL Length                     6527 non-null   int64  
 3   URL Depth                      6527 non-null   int64  
 4   Redirection                    6527 non-null   int64  
 5   https Domain                   6527 non-null   int64  
 6   TinyURL                        6527 non-null   int64  
 7   Prefix/Suffix                  6527 non-null   int64  
 8   Have client                    6527 non-null   int64  
 9   Have admin                     6527 non-null   int64  
 10  Have login                     6527 non-null   int64  
 11  Have server                    6527 non-null   int64  
 12  .php                           6527 non-null   i

In [ ]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
dtype: int64

In [ ]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 6527
Non-Phishing: 4954 (75.90% of total)
Phishing: 1573 (24.10% of total)


In [ ]:

import numpy as np


In [ ]:
urldata.describe()

Have IP       Have @  URL Length    URL Depth  Redirection  \
count   6527.0  6527.000000      6527.0  6527.000000  6527.000000   
mean       0.0     0.004137         1.0     4.397579     0.050406   
std        0.0     0.064189         0.0     2.997529     0.218798   
min        0.0     0.000000         1.0     0.000000     0.000000   
25%        0.0     0.000000         1.0     2.000000     0.000000   
50%        0.0     0.000000         1.0     4.000000     0.000000   
75%        0.0     0.000000         1.0     6.000000     0.000000   
max        0.0     1.000000         1.0    18.000000     1.000000   

       https Domain      TinyURL  Prefix/Suffix  Have client   Have admin  \
count   6527.000000  6527.000000    6527.000000  6527.000000  6527.000000   
mean       0.060518     0.056841       0.042746     0.001379     0.019304   
std        0.238462     0.231556       0.202298     0.037111     0.137603   
min        0.000000     0.000000       0.000000     0.000000     0.000000   
25%        0.000000     0.000000       0.000000     0.000000     0.000000   
50%        0.000000     0.000000       0.000000     0.000000     0.000000   
75%        0.000000     0.000000       0.000000     0.000000     0.000000   
max        1.000000     1.000000       1.000000     1.000000     1.000000   

       ...   Num Embeds   Num Images    Num Links   Num Titles    Num Script  \
count  ...  6527.000000  6527.000000  6527.000000  6527.000000  6.527000e+03   
mean   ...     0.000613    13.078290    71.623717     8.910679  2.911380e+04   
std    ...     0.024750    37.301509   117.479116    34.106562  9.681226e+04   
min    ...     0.000000     0.000000     0.000000     0.000000  0.000000e+00   
25%    ...     0.000000     0.000000     0.000000     1.000000  4.400000e+01   
50%    ...     0.000000     3.000000    28.000000     1.000000  6.953000e+03   
75%    ...     0.000000     8.000000    91.000000     5.000000  1.672850e+04   
max    ...     1.000000   526.000000  1159.000000  1042.000000  2.076633e+06   

       Special Characters  Script To Special Chars Ratio  \
count         6527.000000                    6527.000000   
mean         11168.757009                       4.175212   
std          24456.427671                      22.109670   
min              0.000000                       0.000000   
25%            143.000000                       0.043897   
50%           4102.000000                       1.916015   
75%           9126.000000                       2.764967   
max         359290.000000                     381.227732   

       Script To body Ratio  Body To Special Char Ratio        Label  
count           6527.000000                 6527.000000  6527.000000  
mean               0.456171                    0.227569     0.240999  
std                0.349764                    0.077076     0.427722  
min                0.000000                    0.000000     0.000000  
25%                0.016658                    0.197183     0.000000  
50%                0.488331                    0.248328     0.000000  
75%                0.739913                    0.262355     0.000000  
max                1.005038                    0.605483     1.000000  

[8 rows x 45 columns]

In [ ]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                          0
Have @                           0
URL Length                       0
URL Depth                        0
Redirection                      0
https Domain                     0
TinyURL                          0
Prefix/Suffix                    0
Have client                      0
Have admin                       0
Have login                       0
Have server                      0
.php                             0
.html                            0
.info                            0
.txt                             0
.js                              0
.exe                             0
Num of periods                   0
Is encoded                       0
Num of encoded char              0
Num of parameters                0
Num of digits                    0
Num of spec char                 0
iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page token

In [ ]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          2            0             0        1   
1        0       0           1          1            0             0        0   
2        0       0           1          4            0             0        0   
3        0       0           1          6            0             0        0   
4        0       0           1          2            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0          15   
1              0            0           0  ...           0           3   
2              0            0           0  ...           0           7   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0          11   

   Num Links  Num Titles  Num Script  Special Characters  \
0        118          13      307557              123028   
1          1           2           0                  51   
2         60           2       10118                3487   
3          0           1           0                  28   
4         40           1       15828               22821   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.499894              0.638955   
1                       0.000000              0.000000   
2                       2.901635              0.769254   
3                       0.000000              0.000000   
4                       0.693572              0.164232   

   Body To Special Char Ratio  Label  
0                    0.255593      0  
1                    0.185455      0  
2                    0.265111      0  
3                    0.194444      0  
4                    0.236791      0  

[5 rows x 45 columns]

In [ ]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [ ]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(3589, 44) (2938, 44)
(3589,) (2938,)


In [ ]:
output = {}
output['labels'] = y_test

**MLP**

In [ ]:
import keras

from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle

def model_mlp(x_train, x_val, y_train, y_val, opt, n):
  mlpclassifier = MLPClassifier(alpha=0.0001, hidden_layer_sizes=([100,100,100]))
  #compile model using mse as a measure of model performance
  mlpclassifier.fit(x_train, y_train)

  y_pred = mlpclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/MLP/model_'+str(n)+'.h5'
  pickle.dump(mlpclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_mlp(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[265   2]
 [ 48  44]]
Precision: 0.9565
Recall: 0.4783
F1 Score: 0.6377
Validation Accuracy: 0.8607242339832869
model 0 saved
[[259  21]
 [ 17  62]]
Precision: 0.7470
Recall: 0.7848
F1 Score: 0.7654
Validation Accuracy: 0.8941504178272981
model 1 saved
[[274   3]
 [ 27  55]]
Precision: 0.9483
Recall: 0.6707
F1 Score: 0.7857
Validation Accuracy: 0.9164345403899722
model 2 saved
[[269   1]
 [ 53  36]]
Precision: 0.9730
Recall: 0.4045
F1 Score: 0.5714
Validation Accuracy: 0.8495821727019499
model 3 saved
[[247  20]
 [ 24  68]]
Precision: 0.7727
Recall: 0.7391
F1 Score: 0.7556
Validation Accuracy: 0.8774373259052924
model 4 saved
[[265   6]
 [ 36  52]]
Precision: 0.8966
Recall: 0.5909
F1 Score: 0.7123
Validation Accuracy: 0.883008356545961
model 5 saved
[[225  29]
 [ 34  71]]
Precision: 0.7100
Recall: 0.6762
F1 Score: 0.6927
Validation Accuracy: 0.8245125348189415
model 6 saved
[[220  52]
 [ 35  52]]
Precision: 0.5000
Recall: 0.5977
F1 Score: 0.5445
Validation Accuracy: 0.7576601671309192

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/MLP/model_2.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['mlp_prediction_non'] = [i[0] for i in y_pred_prob];
output['mlp_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[1.00000000e+000 1.54416795e-160]
 [1.00000000e+000 7.87057681e-028]
 [9.98953611e-001 1.04638906e-003]
 ...
 [1.00000000e+000 1.24521817e-074]
 [1.00000000e+000 5.90545813e-043]
 [1.00000000e+000 0.00000000e+000]]


labels  mlp_prediction_non  mlp_prediction_phish
0          0            1.000000         1.544168e-160
1          1            1.000000          7.870577e-28
2          0            0.998954          1.046389e-03
3          0            1.000000         7.799215e-293
4          1            0.041413          9.585872e-01
...      ...                 ...                   ...
2933       1            0.043963          9.560372e-01
2934       0            1.000000          2.109332e-13
2935       0            1.000000          1.245218e-74
2936       0            1.000000          5.905458e-43
2937       0            1.000000          0.000000e+00

[2938 rows x 3 columns]

**Neural Network**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_aa(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]
  # print("check point")
  #create model
  model = Sequential()
  model.add(Dense(30, activation='relu', input_shape=(n_cols,)))
  model.add(Dense(10, activation='relu'))

  model.add(Dense(1, activation = 'sigmoid'))
  # softmax
  #compile model using mse as a measure of model performance
  model.compile(optimizer = opt, loss= 'binary_crossentropy', metrics=["accuracy"])

  history = model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/NN/model_'+str(n)+'.h5'
  pickle.dump(model, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_aa(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
101/101 [==============================] - 4s 5ms/step - loss: 107.2940 - accuracy: 0.7396 - val_loss: 77.4494 - val_accuracy: 0.7214
Epoch 2/100
101/101 [==============================] - 0s 3ms/step - loss: 57.9190 - accuracy: 0.7161 - val_loss: 33.0256 - val_accuracy: 0.6574
Epoch 3/100
101/101 [==============================] - 0s 3ms/step - loss: 29.0957 - accuracy: 0.6709 - val_loss: 9.2210 - val_accuracy: 0.7883
Epoch 4/100
101/101 [==============================] - 0s 4ms/step - loss: 12.7001 - accuracy: 0.7839 - val_loss: 4.2331 - val_accuracy: 0.7799
Epoch 5/100
101/101 [==============================] - 0s 3ms/step - loss: 9.8200 - accuracy: 0.7783 - val_loss: 1.8350 - val_accuracy: 0.8245
Epoch 6/100
101/101 [==============================] - 0s 3ms/step - loss: 4.2479 - accuracy: 0.8009 - val_loss: 1.1370 - val_accuracy: 0.8189
Epoch 7/100
101/101 [==============================] - 0s 3ms/step - loss: 2.8403 - accuracy: 0.8022 - val_loss: 3.4235 - val_accuracy:

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/NN/model_2.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[1.00000000e+000 1.54416795e-160]
 [1.00000000e+000 7.87057681e-028]
 [9.98953611e-001 1.04638906e-003]
 ...
 [1.00000000e+000 1.24521817e-074]
 [1.00000000e+000 5.90545813e-043]
 [1.00000000e+000 0.00000000e+000]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0            1.000000         1.544168e-160           1.000000   
1          1            1.000000          7.870577e-28           1.000000   
2          0            0.998954          1.046389e-03           0.998954   
3          0            1.000000         7.799215e-293           1.000000   
4          1            0.041413          9.585872e-01           0.041413   
...      ...                 ...                   ...                ...   
2933       1            0.043963          9.560372e-01           0.043963   
2934       0            1.000000          2.109332e-13           1.000000   
2935       0            1.000000          1.245218e-74           1.000000   
2936       0            1.000000          5.905458e-43           1.000000   
2937       0            1.000000          0.000000e+00           1.000000   

      nn_prediction_phish  
0           1.544168e-160  
1            7.870577e-28  
2            1.046389e-03  
3           7.799215e-293  
4            9.585872e-01  
...                   ...  
2933         9.560372e-01  
2934         2.109332e-13  
2935         1.245218e-74  
2936         5.905458e-43  
2937         0.000000e+00  

[2938 rows x 5 columns]

**Neural Network 2**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_a(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]

  #create model
  model_2 = Sequential()
  model_2.add(Dense(30, activation='sigmoid', input_shape=(n_cols,)))
  model_2.add(Dense(25, activation='sigmoid'))
  model_2.add(Dense(20, activation='sigmoid'))
  model_2.add(Dense(15, activation='sigmoid'))
  model_2.add(Dense(10, activation='sigmoid'))
  model_2.add(Dense(1, activation = 'sigmoid'))

  #compile model using mse as a measure of model performance
  model_2.compile(optimizer='adam', loss='mean_squared_error')



  history = model_2.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model_2.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/NN_2/model_'+str(n)+'.h5'
  pickle.dump(model_2, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_a(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
101/101 [==============================] - 1s 4ms/step - loss: 0.2153 - val_loss: 0.1918
Epoch 2/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1873 - val_loss: 0.1895
Epoch 3/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1850 - val_loss: 0.1854
Epoch 4/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1791 - val_loss: 0.1736
Epoch 5/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1623 - val_loss: 0.1478
Epoch 6/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1346 - val_loss: 0.1202
Epoch 7/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1144 - val_loss: 0.1131
Epoch 8/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1087 - val_loss: 0.1048
Epoch 9/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1025 - val_loss: 0.1038
Epoch 10/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1002 - val_lo

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL-HTML/NN_2/model_5.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn2_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn2_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[1.00000000e+000 1.54416795e-160]
 [1.00000000e+000 7.87057681e-028]
 [9.98953611e-001 1.04638906e-003]
 ...
 [1.00000000e+000 1.24521817e-074]
 [1.00000000e+000 5.90545813e-043]
 [1.00000000e+000 0.00000000e+000]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0            1.000000         1.544168e-160           1.000000   
1          1            1.000000          7.870577e-28           1.000000   
2          0            0.998954          1.046389e-03           0.998954   
3          0            1.000000         7.799215e-293           1.000000   
4          1            0.041413          9.585872e-01           0.041413   
...      ...                 ...                   ...                ...   
2933       1            0.043963          9.560372e-01           0.043963   
2934       0            1.000000          2.109332e-13           1.000000   
2935       0            1.000000          1.245218e-74           1.000000   
2936       0            1.000000          5.905458e-43           1.000000   
2937       0            1.000000          0.000000e+00           1.000000   

      nn_prediction_phish  nn2_prediction_non  nn2_prediction_phish  
0           1.544168e-160            1.000000         1.544168e-160  
1            7.870577e-28            1.000000          7.870577e-28  
2            1.046389e-03            0.998954          1.046389e-03  
3           7.799215e-293            1.000000         7.799215e-293  
4            9.585872e-01            0.041413          9.585872e-01  
...                   ...                 ...                   ...  
2933         9.560372e-01            0.043963          9.560372e-01  
2934         2.109332e-13            1.000000          2.109332e-13  
2935         1.245218e-74            1.000000          1.245218e-74  
2936         5.905458e-43            1.000000          5.905458e-43  
2937         0.000000e+00            1.000000          0.000000e+00  

[2938 rows x 7 columns]

In [ ]:
output.shape


(2938, 7)

In [ ]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Binary/Base_classifier_result(URL-HTML cross)(3).csv', index=False)