In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(binary).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0              0        0       0           1          1            0   
1              1        0       0           1          1            1   
2              2        0       0           1          1            0   
3              3        0       0           1          3            0   
4              4        0       0           1          3            0   
...          ...      ...     ...         ...        ...          ...   
6522        9992        0       0           1          5            0   
6523        9994        0       0           1          3            0   
6524        9995        0       0           1          6            0   
6525        9996        0       0           1          5            0   
6526        9997        0       0           1          4            0   

      https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                0        0              0            0  ...           0   
1                0        0              0            0  ...           0   
2                1        0              0            0  ...           0   
3                0        0              0            0  ...           0   
4                0        0              0            0  ...           0   
...            ...      ...            ...          ...  ...         ...   
6522             0        0              0            0  ...           0   
6523             0        0              0            0  ...           0   
6524             0        0              0            0  ...           0   
6525             0        0              0            0  ...           0   
6526             0        0              0            0  ...           0   

      Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0             49        691          42       13135                6400   
1              4         66           3        2034                 818   
2              1        100          27       32987               10451   
3              0          0           1           0                  52   
4            117        219          23        7944                3468   
...          ...        ...         ...         ...                 ...   
6522           0          0           1           0                  34   
6523           0          0           1           0                  14   
6524           0          0           1           0                 249   
6525           0          0           1           0                   6   
6526           0          0           1           0                 630   

      Script To Special Chars Ratio  Script To body Ratio  \
0                          2.052344              0.528869   
1                          2.486553              0.676197   
2                          3.156349              0.836681   
3                          0.000000              0.000000   
4                          2.290657              0.524460   
...                             ...                   ...   
6522                       0.000000              0.000000   
6523                       0.000000              0.000000   
6524                       0.000000              0.000000   
6525                       0.000000              0.000000   
6526                       0.000000              0.000000   

      Body To Special Char Ratio  Label  
0                       0.257690      0  
1                       0.271941      0  
2                       0.265079      0  
3                       0.227074      0  
4                       0.228956      0  
...                          ...    ...  
6522                    0.185792      1  
6523                    0.197183      1  
6524                    0.315990      1  
6525                    0.139535      1  
6526                    0.310192      1  

[6527 rows x 46 columns]

In [5]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [6]:
urldata = urldata.drop(['Unnamed: 0', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               1           0                    0                 10   
1               4           1                    2                  3   
2               1           1                    2                  2   
3               4           1                    5                  0   
4               2           0                    0                  1   

   Num of digits  Num of spec char  Label  
0              0                25      0  
1             22                13      0  
2              2                 9      0  
3             19                18      0  
4             17                 7      0  

[5 rows x 25 columns]

In [7]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Have IP              6527 non-null   int64
 1   Have @               6527 non-null   int64
 2   URL Length           6527 non-null   int64
 3   URL Depth            6527 non-null   int64
 4   Redirection          6527 non-null   int64
 5   https Domain         6527 non-null   int64
 6   TinyURL              6527 non-null   int64
 7   Prefix/Suffix        6527 non-null   int64
 8   Have client          6527 non-null   int64
 9   Have admin           6527 non-null   int64
 10  Have login           6527 non-null   int64
 11  Have server          6527 non-null   int64
 12  .php                 6527 non-null   int64
 13  .html                6527 non-null   int64
 14  .info                6527 non-null   int64
 15  .txt                 6527 non-null   int64
 16  .js                  652

In [8]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
dtype: int64

In [9]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 6527
Non-Phishing: 4954 (75.90% of total)
Phishing: 1573 (24.10% of total)


In [10]:

import numpy as np


In [11]:
urldata.describe()

Have IP       Have @  URL Length    URL Depth  Redirection  \
count   6527.0  6527.000000      6527.0  6527.000000  6527.000000   
mean       0.0     0.004137         1.0     4.397579     0.050406   
std        0.0     0.064189         0.0     2.997529     0.218798   
min        0.0     0.000000         1.0     0.000000     0.000000   
25%        0.0     0.000000         1.0     2.000000     0.000000   
50%        0.0     0.000000         1.0     4.000000     0.000000   
75%        0.0     0.000000         1.0     6.000000     0.000000   
max        0.0     1.000000         1.0    18.000000     1.000000   

       https Domain      TinyURL  Prefix/Suffix  Have client   Have admin  \
count   6527.000000  6527.000000    6527.000000  6527.000000  6527.000000   
mean       0.060518     0.056841       0.042746     0.001379     0.019304   
std        0.238462     0.231556       0.202298     0.037111     0.137603   
min        0.000000     0.000000       0.000000     0.000000     0.000000   
25%        0.000000     0.000000       0.000000     0.000000     0.000000   
50%        0.000000     0.000000       0.000000     0.000000     0.000000   
75%        0.000000     0.000000       0.000000     0.000000     0.000000   
max        1.000000     1.000000       1.000000     1.000000     1.000000   

       ...    .txt          .js         .exe  Num of periods   Is encoded  \
count  ...  6527.0  6527.000000  6527.000000     6527.000000  6527.000000   
mean   ...     0.0     0.014249     0.002758        2.306573     0.151831   
std    ...     0.0     0.118523     0.052446        2.248695     0.358884   
min    ...     0.0     0.000000     0.000000        1.000000     0.000000   
25%    ...     0.0     0.000000     0.000000        1.000000     0.000000   
50%    ...     0.0     0.000000     0.000000        1.000000     0.000000   
75%    ...     0.0     0.000000     0.000000        2.000000     0.000000   
max    ...     0.0     1.000000     1.000000       21.000000     1.000000   

       Num of encoded char  Num of parameters  Num of digits  \
count          6527.000000        6527.000000    6527.000000   
mean              3.660028           0.640417      16.024207   
std              13.945412           1.608334      19.279340   
min               0.000000           0.000000       0.000000   
25%               0.000000           0.000000       5.000000   
50%               0.000000           0.000000      10.000000   
75%               0.000000           1.000000      21.000000   
max             201.000000          14.000000     259.000000   

       Num of spec char        Label  
count       6527.000000  6527.000000  
mean           9.387008     0.240999  
std           14.849941     0.427722  
min            0.000000     0.000000  
25%            1.000000     0.000000  
50%            6.000000     0.000000  
75%           11.000000     0.000000  
max          201.000000     1.000000  

[8 rows x 25 columns]

In [12]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                0
Have @                 0
URL Length             0
URL Depth              0
Redirection            0
https Domain           0
TinyURL                0
Prefix/Suffix          0
Have client            0
Have admin             0
Have login             0
Have server            0
.php                   0
.html                  0
.info                  0
.txt                   0
.js                    0
.exe                   0
Num of periods         0
Is encoded             0
Num of encoded char    0
Num of parameters      0
Num of digits          0
Num of spec char       0
Label                  0
dtype: int64

In [13]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1         10            0             0        0   
1        0       0           1          3            0             0        0   
2        0       0           1         10            0             0        0   
3        0       0           1          5            0             0        0   
4        0       0           1          2            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              1            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               1           0                    0                  0   
1               7           0                    0                  0   
2               1           0                    0                  0   
3               3           0                    0                  0   
4               8           0                    0                  1   

   Num of digits  Num of spec char  Label  
0             21                 0      0  
1              3                 2      1  
2             22                 0      0  
3              0                 1      1  
4             36                 1      0  

[5 rows x 25 columns]

In [14]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [15]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(3589, 24) (2938, 24)
(3589,) (2938,)


In [16]:
output = {}
output['labels'] = y_test

**Random Forest Classifier**

In [17]:
import keras
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  rfc = RandomForestClassifier(n_estimators=50, max_depth=10)
  #compile model using mse as a measure of model performance

  rfc.fit(x_train, y_train)


  y_pred = rfc.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/RFC/model_'+str(n)+'.h5'
  pickle.dump(rfc, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [18]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[276   0]
 [  3  80]]
Precision: 1.0000
Recall: 0.9639
F1 Score: 0.9816
Validation Accuracy: 0.9916434540389972
model 0 saved
[[265   3]
 [  3  88]]
Precision: 0.9670
Recall: 0.9670
F1 Score: 0.9670
Validation Accuracy: 0.9832869080779945
model 1 saved
[[273   1]
 [  5  80]]
Precision: 0.9877
Recall: 0.9412
F1 Score: 0.9639
Validation Accuracy: 0.9832869080779945
model 2 saved
[[276   1]
 [  4  78]]
Precision: 0.9873
Recall: 0.9512
F1 Score: 0.9689
Validation Accuracy: 0.9860724233983287
model 3 saved
[[269   5]
 [  6  79]]
Precision: 0.9405
Recall: 0.9294
F1 Score: 0.9349
Validation Accuracy: 0.9693593314763231
model 4 saved
[[278   6]
 [  5  70]]
Precision: 0.9211
Recall: 0.9333
F1 Score: 0.9272
Validation Accuracy: 0.9693593314763231
model 5 saved
[[272   2]
 [  5  80]]
Precision: 0.9756
Recall: 0.9412
F1 Score: 0.9581
Validation Accuracy: 0.9805013927576601
model 6 saved
[[272   2]
 [  1  84]]
Precision: 0.9767
Recall: 0.9882
F1 Score: 0.9825
Validation Accuracy: 0.991643454038997

In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/RFC/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['rfc_prediction_non'] = [i[0] for i in y_pred_prob];
output['rfc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output



[[0.98832173 0.01167827]
 [0.014      0.986     ]
 [0.97640716 0.02359284]
 ...
 [0.99438756 0.00561244]
 [0.27616998 0.72383002]
 [0.30246768 0.69753232]]


labels  rfc_prediction_non  rfc_prediction_phish
0          0            0.988322              0.011678
1          1            0.014000              0.986000
2          0            0.976407              0.023593
3          1            0.013240              0.986760
4          0            0.848585              0.151415
...      ...                 ...                   ...
2933       0            0.960549              0.039451
2934       1            0.071792              0.928208
2935       0            0.994388              0.005612
2936       1            0.276170              0.723830
2937       1            0.302468              0.697532

[2938 rows x 3 columns]

**SVM**

In [ ]:
import keras

import pickle
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics


def model_svc(x_train, x_val, y_train, y_val, opt, n):
  svclassifier = SVC(kernel='rbf', probability= True)
  #compile model using mse as a measure of model performance
  svclassifier.fit(x_train, y_train)

  y_pred = svclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/SVC/model_'+str(n)+'.h5'
  pickle.dump(svclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
# early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_svc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[270   8]
 [ 25  56]]
Precision: 0.8750
Recall: 0.6914
F1 Score: 0.7724
Validation Accuracy: 0.9080779944289693
model 0 saved
[[264   6]
 [ 23  66]]
Precision: 0.9167
Recall: 0.7416
F1 Score: 0.8199
Validation Accuracy: 0.9192200557103064
model 1 saved
[[256   5]
 [ 30  68]]
Precision: 0.9315
Recall: 0.6939
F1 Score: 0.7953
Validation Accuracy: 0.9025069637883009
model 2 saved
[[260   3]
 [ 32  64]]
Precision: 0.9552
Recall: 0.6667
F1 Score: 0.7853
Validation Accuracy: 0.9025069637883009
model 3 saved
[[266   9]
 [ 27  57]]
Precision: 0.8636
Recall: 0.6786
F1 Score: 0.7600
Validation Accuracy: 0.8997214484679665
model 4 saved
[[263   1]
 [ 31  64]]
Precision: 0.9846
Recall: 0.6737
F1 Score: 0.8000
Validation Accuracy: 0.9108635097493036
model 5 saved
[[279   8]
 [ 19  53]]
Precision: 0.8689
Recall: 0.7361
F1 Score: 0.7970
Validation Accuracy: 0.924791086350975
model 6 saved
[[268  11]
 [ 23  57]]
Precision: 0.8382
Recall: 0.7125
F1 Score: 0.7703
Validation Accuracy: 0.9052924791086351

In [20]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/SVC/model_6.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['svc_prediction_non'] = [i[0] for i in y_pred_prob];
output['svc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[9.30231229e-01 6.97687711e-02]
 [6.65925075e-02 9.33407492e-01]
 [9.51598620e-01 4.84013800e-02]
 ...
 [9.99061324e-01 9.38675700e-04]
 [2.55639799e-02 9.74436020e-01]
 [6.05802101e-01 3.94197899e-01]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          0            0.988322              0.011678            0.930231   
1          1            0.014000              0.986000            0.066593   
2          0            0.976407              0.023593            0.951599   
3          1            0.013240              0.986760            0.054215   
4          0            0.848585              0.151415            0.227756   
...      ...                 ...                   ...                 ...   
2933       0            0.960549              0.039451            0.997912   
2934       1            0.071792              0.928208            0.000001   
2935       0            0.994388              0.005612            0.999061   
2936       1            0.276170              0.723830            0.025564   
2937       1            0.302468              0.697532            0.605802   

      svc_prediction_phish  
0                 0.069769  
1                 0.933407  
2                 0.048401  
3                 0.945785  
4                 0.772244  
...                    ...  
2933              0.002088  
2934              0.999999  
2935              0.000939  
2936              0.974436  
2937              0.394198  

[2938 rows x 5 columns]

**Logistic Regression**

In [ ]:
import keras

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
import pickle

def model_lr(x_train, x_val, y_train, y_val, opt, n):
  lrclassifier = LogisticRegression()
  #compile model using mse as a measure of model performance
  lrclassifier.fit(x_train, y_train)

  y_pred = lrclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))
  

  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/LR/model_'+str(n)+'.h5'
  pickle.dump(lrclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_lr(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[269   9]
 [ 16  65]]
Precision: 0.8784
Recall: 0.8025
F1 Score: 0.8387
Validation Accuracy: 0.9303621169916435
model 0 saved
[[257  13]
 [ 27  62]]
Precision: 0.8267
Recall: 0.6966
F1 Score: 0.7561
Validation Accuracy: 0.8885793871866295


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 1 saved
[[246  15]
 [ 21  77]]
Precision: 0.8370
Recall: 0.7857
F1 Score: 0.8105
Validation Accuracy: 0.8997214484679665


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 2 saved
[[260   3]
 [ 24  72]]
Precision: 0.9600
Recall: 0.7500
F1 Score: 0.8421
Validation Accuracy: 0.924791086350975


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 3 saved
[[264  11]
 [ 22  62]]
Precision: 0.8493
Recall: 0.7381
F1 Score: 0.7898
Validation Accuracy: 0.9080779944289693


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 4 saved
[[258   6]
 [ 26  69]]
Precision: 0.9200
Recall: 0.7263
F1 Score: 0.8118
Validation Accuracy: 0.9108635097493036


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 5 saved
[[277  10]
 [ 20  52]]
Precision: 0.8387
Recall: 0.7222
F1 Score: 0.7761
Validation Accuracy: 0.9164345403899722


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 6 saved
[[276   3]
 [ 30  50]]
Precision: 0.9434
Recall: 0.6250
F1 Score: 0.7519
Validation Accuracy: 0.9080779944289693


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 7 saved
[[259  10]
 [ 27  63]]
Precision: 0.8630
Recall: 0.7000
F1 Score: 0.7730
Validation Accuracy: 0.8969359331476323


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 8 saved
[[270   6]
 [ 22  60]]
Precision: 0.9091
Recall: 0.7317
F1 Score: 0.8108
Validation Accuracy: 0.9217877094972067


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 9 saved
Average Validation Accuracy: 0.9105631720639268


In [21]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/LR/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['lr_prediction_non'] = [i[0] for i in y_pred_prob];
output['lr_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[8.66125425e-01 1.33874575e-01]
 [1.58798791e-01 8.41201209e-01]
 [9.99999989e-01 1.07007576e-08]
 ...
 [9.95053356e-01 4.94664361e-03]
 [2.96310642e-01 7.03689358e-01]
 [7.96988246e-01 2.03011754e-01]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          0            0.988322              0.011678            0.930231   
1          1            0.014000              0.986000            0.066593   
2          0            0.976407              0.023593            0.951599   
3          1            0.013240              0.986760            0.054215   
4          0            0.848585              0.151415            0.227756   
...      ...                 ...                   ...                 ...   
2933       0            0.960549              0.039451            0.997912   
2934       1            0.071792              0.928208            0.000001   
2935       0            0.994388              0.005612            0.999061   
2936       1            0.276170              0.723830            0.025564   
2937       1            0.302468              0.697532            0.605802   

      svc_prediction_phish  lr_prediction_non  lr_prediction_phish  
0                 0.069769           0.866125         1.338746e-01  
1                 0.933407           0.158799         8.412012e-01  
2                 0.048401           1.000000         1.070076e-08  
3                 0.945785           0.001640         9.983597e-01  
4                 0.772244           0.522085         4.779155e-01  
...                    ...                ...                  ...  
2933              0.002088           0.980381         1.961941e-02  
2934              0.999999           0.280416         7.195842e-01  
2935              0.000939           0.995053         4.946644e-03  
2936              0.974436           0.296311         7.036894e-01  
2937              0.394198           0.796988         2.030118e-01  

[2938 rows x 7 columns]

In [22]:
output.shape


(2938, 7)

In [23]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Binary/Base_classifier_result(URL cross)(2).csv', index=False)