In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/UNB/URL-HTML/preprocessed_url_features(binary).csv")
urldata


Unnamed: 0  Have IP  Have @  URL Length  URL Depth  Redirection  \
0              0        0       0           1          1            0   
1              1        0       0           1          1            1   
2              2        0       0           1          1            0   
3              3        0       0           1          3            0   
4              4        0       0           1          3            0   
...          ...      ...     ...         ...        ...          ...   
6522        9992        0       0           1          5            0   
6523        9994        0       0           1          3            0   
6524        9995        0       0           1          6            0   
6525        9996        0       0           1          5            0   
6526        9997        0       0           1          4            0   

      https Domain  TinyURL  Prefix/Suffix  Have client  ...  Num Embeds  \
0                0        0              0            0  ...           0   
1                0        0              0            0  ...           0   
2                1        0              0            0  ...           0   
3                0        0              0            0  ...           0   
4                0        0              0            0  ...           0   
...            ...      ...            ...          ...  ...         ...   
6522             0        0              0            0  ...           0   
6523             0        0              0            0  ...           0   
6524             0        0              0            0  ...           0   
6525             0        0              0            0  ...           0   
6526             0        0              0            0  ...           0   

      Num Images  Num Links  Num Titles  Num Script  Special Characters  \
0             49        691          42       13135                6400   
1              4         66           3        2034                 818   
2              1        100          27       32987               10451   
3              0          0           1           0                  52   
4            117        219          23        7944                3468   
...          ...        ...         ...         ...                 ...   
6522           0          0           1           0                  34   
6523           0          0           1           0                  14   
6524           0          0           1           0                 249   
6525           0          0           1           0                   6   
6526           0          0           1           0                 630   

      Script To Special Chars Ratio  Script To body Ratio  \
0                          2.052344              0.528869   
1                          2.486553              0.676197   
2                          3.156349              0.836681   
3                          0.000000              0.000000   
4                          2.290657              0.524460   
...                             ...                   ...   
6522                       0.000000              0.000000   
6523                       0.000000              0.000000   
6524                       0.000000              0.000000   
6525                       0.000000              0.000000   
6526                       0.000000              0.000000   

      Body To Special Char Ratio  Label  
0                       0.257690      0  
1                       0.271941      0  
2                       0.265079      0  
3                       0.227074      0  
4                       0.228956      0  
...                          ...    ...  
6522                    0.185792      1  
6523                    0.197183      1  
6524                    0.315990      1  
6525                    0.139535      1  
6526                    0.310192      1  

[6527 rows x 46 columns]

In [ ]:
urldata.columns

Index(['Unnamed: 0', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [ ]:
urldata = urldata.drop(['Unnamed: 0', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               1           0                    0                 10   
1               4           1                    2                  3   
2               1           1                    2                  2   
3               4           1                    5                  0   
4               2           0                    0                  1   

   Num of digits  Num of spec char  Label  
0              0                25      0  
1             22                13      0  
2              2                 9      0  
3             19                18      0  
4             17                 7      0  

[5 rows x 25 columns]

In [ ]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Have IP              6527 non-null   int64
 1   Have @               6527 non-null   int64
 2   URL Length           6527 non-null   int64
 3   URL Depth            6527 non-null   int64
 4   Redirection          6527 non-null   int64
 5   https Domain         6527 non-null   int64
 6   TinyURL              6527 non-null   int64
 7   Prefix/Suffix        6527 non-null   int64
 8   Have client          6527 non-null   int64
 9   Have admin           6527 non-null   int64
 10  Have login           6527 non-null   int64
 11  Have server          6527 non-null   int64
 12  .php                 6527 non-null   int64
 13  .html                6527 non-null   int64
 14  .info                6527 non-null   int64
 15  .txt                 6527 non-null   int64
 16  .js                  652

In [ ]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    4954
1    1573
dtype: int64

In [ ]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 6527
Non-Phishing: 4954 (75.90% of total)
Phishing: 1573 (24.10% of total)


In [ ]:

import numpy as np


In [ ]:
urldata.describe()

Have IP       Have @  URL Length    URL Depth  Redirection  \
count   6527.0  6527.000000      6527.0  6527.000000  6527.000000   
mean       0.0     0.004137         1.0     4.397579     0.050406   
std        0.0     0.064189         0.0     2.997529     0.218798   
min        0.0     0.000000         1.0     0.000000     0.000000   
25%        0.0     0.000000         1.0     2.000000     0.000000   
50%        0.0     0.000000         1.0     4.000000     0.000000   
75%        0.0     0.000000         1.0     6.000000     0.000000   
max        0.0     1.000000         1.0    18.000000     1.000000   

       https Domain      TinyURL  Prefix/Suffix  Have client   Have admin  \
count   6527.000000  6527.000000    6527.000000  6527.000000  6527.000000   
mean       0.060518     0.056841       0.042746     0.001379     0.019304   
std        0.238462     0.231556       0.202298     0.037111     0.137603   
min        0.000000     0.000000       0.000000     0.000000     0.000000   
25%        0.000000     0.000000       0.000000     0.000000     0.000000   
50%        0.000000     0.000000       0.000000     0.000000     0.000000   
75%        0.000000     0.000000       0.000000     0.000000     0.000000   
max        1.000000     1.000000       1.000000     1.000000     1.000000   

       ...    .txt          .js         .exe  Num of periods   Is encoded  \
count  ...  6527.0  6527.000000  6527.000000     6527.000000  6527.000000   
mean   ...     0.0     0.014249     0.002758        2.306573     0.151831   
std    ...     0.0     0.118523     0.052446        2.248695     0.358884   
min    ...     0.0     0.000000     0.000000        1.000000     0.000000   
25%    ...     0.0     0.000000     0.000000        1.000000     0.000000   
50%    ...     0.0     0.000000     0.000000        1.000000     0.000000   
75%    ...     0.0     0.000000     0.000000        2.000000     0.000000   
max    ...     0.0     1.000000     1.000000       21.000000     1.000000   

       Num of encoded char  Num of parameters  Num of digits  \
count          6527.000000        6527.000000    6527.000000   
mean              3.660028           0.640417      16.024207   
std              13.945412           1.608334      19.279340   
min               0.000000           0.000000       0.000000   
25%               0.000000           0.000000       5.000000   
50%               0.000000           0.000000      10.000000   
75%               0.000000           1.000000      21.000000   
max             201.000000          14.000000     259.000000   

       Num of spec char        Label  
count       6527.000000  6527.000000  
mean           9.387008     0.240999  
std           14.849941     0.427722  
min            0.000000     0.000000  
25%            1.000000     0.000000  
50%            6.000000     0.000000  
75%           11.000000     0.000000  
max          201.000000     1.000000  

[8 rows x 25 columns]

In [ ]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                0
Have @                 0
URL Length             0
URL Depth              0
Redirection            0
https Domain           0
TinyURL                0
Prefix/Suffix          0
Have client            0
Have admin             0
Have login             0
Have server            0
.php                   0
.html                  0
.info                  0
.txt                   0
.js                    0
.exe                   0
Num of periods         0
Is encoded             0
Num of encoded char    0
Num of parameters      0
Num of digits          0
Num of spec char       0
Label                  0
dtype: int64

In [ ]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          3            0             0        0   
1        0       0           1         10            0             0        0   
2        0       0           1         10            0             0        0   
3        0       0           1          2            0             0        0   
4        0       0           1          5            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               1           0                    0                  0   
1               1           0                    0                  0   
2               1           0                    0                  0   
3               2           0                    0                  0   
4               3           0                    0                  0   

   Num of digits  Num of spec char  Label  
0              9                14      0  
1             20                 0      0  
2             22                 0      0  
3             20                12      0  
4              0                 1      1  

[5 rows x 25 columns]

In [ ]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [ ]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(3589, 24) (2938, 24)
(3589,) (2938,)


In [ ]:
output = {}
output['labels'] = y_test

**MLP**

In [ ]:
import keras

from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle

def model_mlp(x_train, x_val, y_train, y_val, opt, n):
  mlpclassifier = MLPClassifier(alpha=0.0001, hidden_layer_sizes=([100,100,100]))
  #compile model using mse as a measure of model performance
  mlpclassifier.fit(x_train, y_train)

  y_pred = mlpclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/MLP/model_'+str(n)+'.h5'
  pickle.dump(mlpclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_mlp(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[281   2]
 [  6  70]]
Precision: 0.9722
Recall: 0.9211
F1 Score: 0.9459
Validation Accuracy: 0.9777158774373259
model 0 saved
[[266   3]
 [  5  85]]
Precision: 0.9659
Recall: 0.9444
F1 Score: 0.9551
Validation Accuracy: 0.9777158774373259
model 1 saved
[[273   5]
 [  0  81]]
Precision: 0.9419
Recall: 1.0000
F1 Score: 0.9701
Validation Accuracy: 0.9860724233983287
model 2 saved
[[272   3]
 [  4  80]]
Precision: 0.9639
Recall: 0.9524
F1 Score: 0.9581
Validation Accuracy: 0.9805013927576601
model 3 saved
[[264   2]
 [ 13  80]]
Precision: 0.9756
Recall: 0.8602
F1 Score: 0.9143
Validation Accuracy: 0.958217270194986
model 4 saved
[[281   3]
 [  2  73]]
Precision: 0.9605
Recall: 0.9733
F1 Score: 0.9669
Validation Accuracy: 0.9860724233983287
model 5 saved
[[270   1]
 [  3  85]]
Precision: 0.9884
Recall: 0.9659
F1 Score: 0.9770
Validation Accuracy: 0.9888579387186629
model 6 saved
[[266   2]
 [  1  90]]
Precision: 0.9783
Recall: 0.9890
F1 Score: 0.9836
Validation Accuracy: 0.9916434540389972

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/MLP/model_7.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['mlp_prediction_non'] = [i[0] for i in y_pred_prob];
output['mlp_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[4.11735529e-05 9.99958826e-01]
 [4.55413485e-12 1.00000000e+00]
 [9.99995064e-01 4.93597482e-06]
 ...
 [9.99999997e-01 2.56480135e-09]
 [9.99998836e-01 1.16405465e-06]
 [9.99994216e-01 5.78401868e-06]]


labels  mlp_prediction_non  mlp_prediction_phish
0          1        4.117355e-05          9.999588e-01
1          1        4.554135e-12          1.000000e+00
2          0        9.999951e-01          4.935975e-06
3          0        1.000000e+00          2.150433e-19
4          1        1.044356e-01          8.955644e-01
...      ...                 ...                   ...
2933       1        3.264056e-14          1.000000e+00
2934       0        9.980053e-01          1.994709e-03
2935       0        1.000000e+00          2.564801e-09
2936       0        9.999988e-01          1.164055e-06
2937       0        9.999942e-01          5.784019e-06

[2938 rows x 3 columns]

**Neural Network**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_aa(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]
  # print("check point")
  #create model
  model = Sequential()
  model.add(Dense(30, activation='relu', input_shape=(n_cols,)))
  model.add(Dense(10, activation='relu'))

  model.add(Dense(1, activation = 'sigmoid'))
  # softmax
  #compile model using mse as a measure of model performance
  model.compile(optimizer = opt, loss= 'binary_crossentropy', metrics=["accuracy"])

  history = model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/NN/model_'+str(n)+'.h5'
  pickle.dump(model, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_aa(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
101/101 [==============================] - 4s 4ms/step - loss: 1.0135 - accuracy: 0.7954 - val_loss: 0.4135 - val_accuracy: 0.8579
Epoch 2/100
101/101 [==============================] - 0s 3ms/step - loss: 0.3343 - accuracy: 0.8836 - val_loss: 0.3131 - val_accuracy: 0.8942
Epoch 3/100
101/101 [==============================] - 0s 3ms/step - loss: 0.2614 - accuracy: 0.9192 - val_loss: 0.2503 - val_accuracy: 0.9136
Epoch 4/100
101/101 [==============================] - 0s 3ms/step - loss: 0.2209 - accuracy: 0.9272 - val_loss: 0.2179 - val_accuracy: 0.9248
Epoch 5/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1960 - accuracy: 0.9316 - val_loss: 0.1979 - val_accuracy: 0.9331
Epoch 6/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1796 - accuracy: 0.9387 - val_loss: 0.1813 - val_accuracy: 0.9443
Epoch 7/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1675 - accuracy: 0.9415 - val_loss: 0.1742 - val_accuracy: 0.9443

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/NN/model_6.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[4.11735529e-05 9.99958826e-01]
 [4.55413485e-12 1.00000000e+00]
 [9.99995064e-01 4.93597482e-06]
 ...
 [9.99999997e-01 2.56480135e-09]
 [9.99998836e-01 1.16405465e-06]
 [9.99994216e-01 5.78401868e-06]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          1        4.117355e-05          9.999588e-01       4.117355e-05   
1          1        4.554135e-12          1.000000e+00       4.554135e-12   
2          0        9.999951e-01          4.935975e-06       9.999951e-01   
3          0        1.000000e+00          2.150433e-19       1.000000e+00   
4          1        1.044356e-01          8.955644e-01       1.044356e-01   
...      ...                 ...                   ...                ...   
2933       1        3.264056e-14          1.000000e+00       3.264056e-14   
2934       0        9.980053e-01          1.994709e-03       9.980053e-01   
2935       0        1.000000e+00          2.564801e-09       1.000000e+00   
2936       0        9.999988e-01          1.164055e-06       9.999988e-01   
2937       0        9.999942e-01          5.784019e-06       9.999942e-01   

      nn_prediction_phish  
0            9.999588e-01  
1            1.000000e+00  
2            4.935975e-06  
3            2.150433e-19  
4            8.955644e-01  
...                   ...  
2933         1.000000e+00  
2934         1.994709e-03  
2935         2.564801e-09  
2936         1.164055e-06  
2937         5.784019e-06  

[2938 rows x 5 columns]

**Neural Network 2**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_a(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]

  #create model
  model_2 = Sequential()
  model_2.add(Dense(30, activation='sigmoid', input_shape=(n_cols,)))
  model_2.add(Dense(25, activation='sigmoid'))
  model_2.add(Dense(20, activation='sigmoid'))
  model_2.add(Dense(15, activation='sigmoid'))
  model_2.add(Dense(10, activation='sigmoid'))
  model_2.add(Dense(1, activation = 'sigmoid'))

  #compile model using mse as a measure of model performance
  model_2.compile(optimizer='adam', loss='mean_squared_error')



  history = model_2.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model_2.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/NN_2/model_'+str(n)+'.h5'
  pickle.dump(model_2, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_a(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
101/101 [==============================] - 1s 4ms/step - loss: 0.1819 - val_loss: 0.1682
Epoch 2/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1780 - val_loss: 0.1578
Epoch 3/100
101/101 [==============================] - 0s 3ms/step - loss: 0.1411 - val_loss: 0.1000
Epoch 4/100
101/101 [==============================] - 0s 3ms/step - loss: 0.0839 - val_loss: 0.0691
Epoch 5/100
101/101 [==============================] - 0s 3ms/step - loss: 0.0676 - val_loss: 0.0623
Epoch 6/100
101/101 [==============================] - 0s 3ms/step - loss: 0.0621 - val_loss: 0.0597
Epoch 7/100
101/101 [==============================] - 0s 3ms/step - loss: 0.0603 - val_loss: 0.0589
Epoch 8/100
101/101 [==============================] - 0s 3ms/step - loss: 0.0580 - val_loss: 0.0621
Epoch 9/100
101/101 [==============================] - 0s 3ms/step - loss: 0.0563 - val_loss: 0.0538
Epoch 10/100
101/101 [==============================] - 0s 3ms/step - loss: 0.0534 - val_lo

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/UNB/Binary/Models/URL/NN_2/model_7.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn2_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn2_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[4.11735529e-05 9.99958826e-01]
 [4.55413485e-12 1.00000000e+00]
 [9.99995064e-01 4.93597482e-06]
 ...
 [9.99999997e-01 2.56480135e-09]
 [9.99998836e-01 1.16405465e-06]
 [9.99994216e-01 5.78401868e-06]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          1        4.117355e-05          9.999588e-01       4.117355e-05   
1          1        4.554135e-12          1.000000e+00       4.554135e-12   
2          0        9.999951e-01          4.935975e-06       9.999951e-01   
3          0        1.000000e+00          2.150433e-19       1.000000e+00   
4          1        1.044356e-01          8.955644e-01       1.044356e-01   
...      ...                 ...                   ...                ...   
2933       1        3.264056e-14          1.000000e+00       3.264056e-14   
2934       0        9.980053e-01          1.994709e-03       9.980053e-01   
2935       0        1.000000e+00          2.564801e-09       1.000000e+00   
2936       0        9.999988e-01          1.164055e-06       9.999988e-01   
2937       0        9.999942e-01          5.784019e-06       9.999942e-01   

      nn_prediction_phish  nn2_prediction_non  nn2_prediction_phish  
0            9.999588e-01        4.117355e-05          9.999588e-01  
1            1.000000e+00        4.554135e-12          1.000000e+00  
2            4.935975e-06        9.999951e-01          4.935975e-06  
3            2.150433e-19        1.000000e+00          2.150433e-19  
4            8.955644e-01        1.044356e-01          8.955644e-01  
...                   ...                 ...                   ...  
2933         1.000000e+00        3.264056e-14          1.000000e+00  
2934         1.994709e-03        9.980053e-01          1.994709e-03  
2935         2.564801e-09        1.000000e+00          2.564801e-09  
2936         1.164055e-06        9.999988e-01          1.164055e-06  
2937         5.784019e-06        9.999942e-01          5.784019e-06  

[2938 rows x 7 columns]

In [ ]:
output.shape


(2938, 7)

In [ ]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/UNB/Binary/Base_classifier_result(URL cross)(3).csv', index=False)