In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/PhishTank/URL-HTML/preprocessed_url_features.csv")
urldata


Unnamed: 0                                       Domain  Have IP  \
0               0                             graphicriver.net        0   
1               1                                    ecnavi.jp        0   
2               2                                 hubpages.com        0   
3               3                              extratorrent.cc        0   
4               4                                icicibank.com        0   
...           ...                                          ...      ...   
10332       11932                             sites.google.com        0   
10333       11933                             sites.google.com        0   
10334       11934             habbocreditosparati.blogspot.com        0   
10335       11935  creditiperhabbogratissicuro100.blogspot.com        0   
10336       11936                           aijcs.blogspot.com        0   

       Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0           0           1          1            0             0        0   
1           0           1          1            1             0        0   
2           0           1          1            0             1        0   
3           0           1          3            0             0        0   
4           0           1          3            0             0        0   
...       ...         ...        ...          ...           ...      ...   
10332       0           0          2            0             1        0   
10333       0           0          2            0             0        0   
10334       0           0          0            0             0        1   
10335       0           1          3            0             0        1   
10336       0           1          3            0             0        1   

       Prefix/Suffix  ...  Num Embeds  Num Images  Num Links  Num Titles  \
0                  0  ...           0          49        691          42   
1                  0  ...           0           4         66           3   
2                  0  ...           0           1        100          27   
3                  0  ...           0           0          0           1   
4                  0  ...           0         117        219          23   
...              ...  ...         ...         ...        ...         ...   
10332              0  ...           0           0         17           4   
10333              0  ...           0           6         24           7   
10334              0  ...           0           4         17           4   
10335              0  ...           0           1         23           8   
10336              0  ...           0          19         42           7   

       Num Script  Special Characters  Script To Special Chars Ratio  \
0           13135                6400                       2.052344   
1            2034                 818                       2.486553   
2           32987               10451                       3.156349   
3               0                  52                       0.000000   
4            7944                3468                       2.290657   
...           ...                 ...                            ...   
10332        8146                2203                       3.697685   
10333        8353                2250                       3.712444   
10334        6403                4560                       1.404167   
10335        9817                7292                       1.346270   
10336        2550                3225                       0.790698   

       Script To body Ratio  Body To Special Char Ratio  Label  
0                  0.528869                    0.257690      0  
1                  0.676197                    0.271941      0  
2                  0.836681                    0.265079      0  
3                  0.000000                    0.227074      0  
4                  0.524460                    0.228956      0  
...                     .

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'Domain', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               1           0                    0                 10   
1               4           1                    2                  3   
2               1           1                    2                  2   
3               4           1                    5                  0   
4               2           0                    0                  1   

   Num of digits  Num of spec char  Label  
0              0                25      0  
1             22                13      0  
2              2                 9      0  
3             19                18      0  
4             17                 7      0  

[5 rows x 25 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Have IP              10337 non-null  int64
 1   Have @               10337 non-null  int64
 2   URL Length           10337 non-null  int64
 3   URL Depth            10337 non-null  int64
 4   Redirection          10337 non-null  int64
 5   https Domain         10337 non-null  int64
 6   TinyURL              10337 non-null  int64
 7   Prefix/Suffix        10337 non-null  int64
 8   Have client          10337 non-null  int64
 9   Have admin           10337 non-null  int64
 10  Have login           10337 non-null  int64
 11  Have server          10337 non-null  int64
 12  .php                 10337 non-null  int64
 13  .html                10337 non-null  int64
 14  .info                10337 non-null  int64
 15  .txt                 10337 non-null  int64
 16  .js                  1

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    5828
1    4509
dtype: int64

In [8]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 10337
Non-Phishing: 5828 (56.38% of total)
Phishing: 4509 (43.62% of total)


In [9]:
urldata.describe()

Have IP        Have @    URL Length     URL Depth   Redirection  \
count  10337.0  10337.000000  10337.000000  10337.000000  10337.000000   
mean       0.0      0.025636      0.698462      3.048660      0.013060   
std        0.0      0.158055      0.458948      2.951401      0.113537   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      0.000000      1.000000      0.000000   
50%        0.0      0.000000      1.000000      2.000000      0.000000   
75%        0.0      0.000000      1.000000      4.000000      0.000000   
max        0.0      1.000000      1.000000     18.000000      1.000000   

       https Domain       TinyURL  Prefix/Suffix   Have client    Have admin  \
count  10337.000000  10337.000000   10337.000000  10337.000000  10337.000000   
mean       0.365773      0.068105       0.074877      0.003676      0.008610   
std        0.481670      0.251938       0.263205      0.060522      0.092393   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      0.000000   
50%        0.000000      0.000000       0.000000      0.000000      0.000000   
75%        1.000000      0.000000       0.000000      0.000000      0.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

       ...     .txt           .js          .exe  Num of periods    Is encoded  \
count  ...  10337.0  10337.000000  10337.000000    10337.000000  10337.000000   
mean   ...      0.0      0.009577      0.001935        1.973010      0.110283   
std    ...      0.0      0.097398      0.043946        1.713616      0.313258   
min    ...      0.0      0.000000      0.000000        1.000000      0.000000   
25%    ...      0.0      0.000000      0.000000        1.000000      0.000000   
50%    ...      0.0      0.000000      0.000000        2.000000      0.000000   
75%    ...      0.0      0.000000      0.000000        2.000000      0.000000   
max    ...      0.0      1.000000      1.000000       22.000000      1.000000   

       Num of encoded char  Num of parameters  Num of digits  \
count         10337.000000       10337.000000   10337.000000   
mean              2.770340           0.430396      11.646029   
std              12.289657           1.363932      22.957867   
min               0.000000           0.000000       0.000000   
25%               0.000000           0.000000       1.000000   
50%               0.000000           0.000000       6.000000   
75%               0.000000           0.000000      17.000000   
max             201.000000          40.000000    1374.000000   

       Num of spec char         Label  
count      10337.000000  10337.000000  
mean           7.240882      0.436200  
std           14.025774      0.495937  
min            0.000000      0.000000  
25%            0.000000      0.000000  
50%            3.000000      0.000000  
75%           10.000000      1.000000  
max          356.000000      1.000000  

[8 rows x 25 columns]

In [10]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                0
Have @                 0
URL Length             0
URL Depth              0
Redirection            0
https Domain           0
TinyURL                0
Prefix/Suffix          0
Have client            0
Have admin             0
Have login             0
Have server            0
.php                   0
.html                  0
.info                  0
.txt                   0
.js                    0
.exe                   0
Num of periods         0
Is encoded             0
Num of encoded char    0
Num of parameters      0
Num of digits          0
Num of spec char       0
Label                  0
dtype: int64

In [11]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          2            0             0        0   
1        0       0           1         10            0             0        0   
2        0       0           0          0            0             1        0   
3        0       0           1         10            0             0        0   
4        0       0           0          0            0             1        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               2           1                    6                  4   
1               1           0                    0                  0   
2               2           0                    0                  0   
3               1           0                    0                  0   
4               2           0                    0                  0   

   Num of digits  Num of spec char  Label  
0             12                16      0  
1             24                 0      0  
2              2                 0      1  
3             21                 0      0  
4              0                 0      1  

[5 rows x 25 columns]

In [12]:
import numpy as np
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [13]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(5685, 24) (4652, 24)
(5685,) (4652,)


In [14]:
output = {}
output['labels'] = y_test

**Random Forest Classifier**

In [15]:
import keras
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  rfc = RandomForestClassifier(n_estimators=50, max_depth=10)
  #compile model using mse as a measure of model performance

  rfc.fit(x_train, y_train)


  y_pred = rfc.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/SVC/model_'+str(n)+'.h5'
  pickle.dump(rfc, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [16]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[317   3]
 [  9 240]]
Precision: 0.9877
Recall: 0.9639
F1 Score: 0.9756
Validation Accuracy: 0.9789103690685413
model 0 saved
[[336   5]
 [  4 224]]
Precision: 0.9782
Recall: 0.9825
F1 Score: 0.9803
Validation Accuracy: 0.984182776801406
model 1 saved
[[313   6]
 [  4 246]]
Precision: 0.9762
Recall: 0.9840
F1 Score: 0.9801
Validation Accuracy: 0.9824253075571178
model 2 saved
[[334   4]
 [  6 225]]
Precision: 0.9825
Recall: 0.9740
F1 Score: 0.9783
Validation Accuracy: 0.9824253075571178
model 3 saved
[[318   2]
 [  3 246]]
Precision: 0.9919
Recall: 0.9880
F1 Score: 0.9899
Validation Accuracy: 0.9912126537785588
model 4 saved
[[314   0]
 [  6 248]]
Precision: 1.0000
Recall: 0.9764
F1 Score: 0.9880
Validation Accuracy: 0.9894366197183099
model 5 saved
[[300   5]
 [  4 259]]
Precision: 0.9811
Recall: 0.9848
F1 Score: 0.9829
Validation Accuracy: 0.9841549295774648
model 6 saved
[[314   1]
 [  9 244]]
Precision: 0.9959
Recall: 0.9644
F1 Score: 0.9799
Validation Accuracy: 0.9823943661971831

In [17]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/SVC/model_4.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['rfc_prediction_non'] = [i[0] for i in y_pred_prob];
output['rfc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output



[[0.88787058 0.11212942]
 [0.98824326 0.01175674]
 [0.99533678 0.00466322]
 ...
 [0.98824326 0.01175674]
 [0.63776793 0.36223207]
 [0.98824326 0.01175674]]


labels  rfc_prediction_non  rfc_prediction_phish
0          0            0.887871              0.112129
1          0            0.988243              0.011757
2          0            0.995337              0.004663
3          0            0.939165              0.060835
4          0            0.988243              0.011757
...      ...                 ...                   ...
4647       0            0.661663              0.338337
4648       1            0.052999              0.947001
4649       0            0.988243              0.011757
4650       0            0.637768              0.362232
4651       0            0.988243              0.011757

[4652 rows x 3 columns]

**SVM**

In [ ]:
import keras

import pickle
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics


def model_svc(x_train, x_val, y_train, y_val, opt, n):
  svclassifier = SVC(kernel='rbf', probability= True)
  #compile model using mse as a measure of model performance
  svclassifier.fit(x_train, y_train)

  y_pred = svclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/SVC/model_'+str(n)+'.h5'
  pickle.dump(svclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
# early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_svc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[333   4]
 [ 21 211]]
Precision: 0.9814
Recall: 0.9095
F1 Score: 0.9441
Validation Accuracy: 0.9560632688927944
model 0 saved
[[310   1]
 [ 20 238]]
Precision: 0.9958
Recall: 0.9225
F1 Score: 0.9577
Validation Accuracy: 0.9630931458699473
model 1 saved
[[315   5]
 [ 20 229]]
Precision: 0.9786
Recall: 0.9197
F1 Score: 0.9482
Validation Accuracy: 0.9560632688927944
model 2 saved
[[298   6]
 [ 19 246]]
Precision: 0.9762
Recall: 0.9283
F1 Score: 0.9516
Validation Accuracy: 0.9560632688927944
model 3 saved
[[320   4]
 [ 21 224]]
Precision: 0.9825
Recall: 0.9143
F1 Score: 0.9471
Validation Accuracy: 0.9560632688927944
model 4 saved
[[299  12]
 [ 15 242]]
Precision: 0.9528
Recall: 0.9416
F1 Score: 0.9472
Validation Accuracy: 0.9524647887323944
model 5 saved
[[314   7]
 [ 23 224]]
Precision: 0.9697
Recall: 0.9069
F1 Score: 0.9372
Validation Accuracy: 0.9471830985915493
model 6 saved
[[321   6]
 [ 23 218]]
Precision: 0.9732
Recall: 0.9046
F1 Score: 0.9376
Validation Accuracy: 0.948943661971831

In [18]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/SVC/model_1.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['svc_prediction_non'] = [i[0] for i in y_pred_prob];
output['svc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.97019164 0.02980836]
 [0.97412801 0.02587199]
 [0.99394918 0.00605082]
 ...
 [0.97499486 0.02500514]
 [0.65474274 0.34525726]
 [0.97412801 0.02587199]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          0            0.887871              0.112129            0.970192   
1          0            0.988243              0.011757            0.974128   
2          0            0.995337              0.004663            0.993949   
3          0            0.939165              0.060835            0.978377   
4          0            0.988243              0.011757            0.974128   
...      ...                 ...                   ...                 ...   
4647       0            0.661663              0.338337            0.707679   
4648       1            0.052999              0.947001            0.071019   
4649       0            0.988243              0.011757            0.974995   
4650       0            0.637768              0.362232            0.654743   
4651       0            0.988243              0.011757            0.974128   

      svc_prediction_phish  
0                 0.029808  
1                 0.025872  
2                 0.006051  
3                 0.021623  
4                 0.025872  
...                    ...  
4647              0.292321  
4648              0.928981  
4649              0.025005  
4650              0.345257  
4651              0.025872  

[4652 rows x 5 columns]

**Logistic Regression**

In [ ]:
import keras

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
import pickle

def model_lr(x_train, x_val, y_train, y_val, opt, n):
  lrclassifier = LogisticRegression()
  #compile model using mse as a measure of model performance
  lrclassifier.fit(x_train, y_train)

  y_pred = lrclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))
  

  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/LR/model_'+str(n)+'.h5'
  pickle.dump(lrclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_lr(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[324  13]
 [ 12 220]]
Precision: 0.9442
Recall: 0.9483
F1 Score: 0.9462
Validation Accuracy: 0.9560632688927944
model 0 saved
[[308   3]
 [ 12 246]]
Precision: 0.9880
Recall: 0.9535
F1 Score: 0.9704
Validation Accuracy: 0.9736379613356766


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 1 saved
[[314   6]
 [  9 240]]
Precision: 0.9756
Recall: 0.9639
F1 Score: 0.9697
Validation Accuracy: 0.9736379613356766


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 2 saved
[[293  11]
 [ 15 250]]
Precision: 0.9579
Recall: 0.9434
F1 Score: 0.9506
Validation Accuracy: 0.9543057996485061


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 3 saved
[[319   5]
 [  9 236]]
Precision: 0.9793
Recall: 0.9633
F1 Score: 0.9712
Validation Accuracy: 0.9753954305799648


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 4 saved
[[298  13]
 [ 16 241]]
Precision: 0.9488
Recall: 0.9377
F1 Score: 0.9432
Validation Accuracy: 0.948943661971831


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 5 saved
[[312   9]
 [ 12 235]]
Precision: 0.9631
Recall: 0.9514
F1 Score: 0.9572
Validation Accuracy: 0.9630281690140845


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 6 saved
[[322   5]
 [ 17 224]]
Precision: 0.9782
Recall: 0.9295
F1 Score: 0.9532
Validation Accuracy: 0.9612676056338029


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 7 saved
[[309   5]
 [ 21 233]]
Precision: 0.9790
Recall: 0.9173
F1 Score: 0.9472
Validation Accuracy: 0.954225352112676


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 8 saved
[[332   4]
 [ 14 218]]
Precision: 0.9820
Recall: 0.9397
F1 Score: 0.9604
Validation Accuracy: 0.9683098591549296


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 9 saved
Average Validation Accuracy: 0.9628815069679943


In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/LR/model_4.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['lr_prediction_non'] = [i[0] for i in y_pred_prob];
output['lr_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[9.99076655e-01 9.23344591e-04]
 [9.50621458e-01 4.93785416e-02]
 [9.97517201e-01 2.48279932e-03]
 ...
 [9.43967016e-01 5.60329843e-02]
 [3.93501213e-02 9.60649879e-01]
 [9.53661014e-01 4.63389863e-02]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          0            0.887871              0.112129            0.970192   
1          0            0.988243              0.011757            0.974128   
2          0            0.995337              0.004663            0.993949   
3          0            0.939165              0.060835            0.978377   
4          0            0.988243              0.011757            0.974128   
...      ...                 ...                   ...                 ...   
4647       0            0.661663              0.338337            0.707679   
4648       1            0.052999              0.947001            0.071019   
4649       0            0.988243              0.011757            0.974995   
4650       0            0.637768              0.362232            0.654743   
4651       0            0.988243              0.011757            0.974128   

      svc_prediction_phish  lr_prediction_non  lr_prediction_phish  
0                 0.029808           0.999077             0.000923  
1                 0.025872           0.950621             0.049379  
2                 0.006051           0.997517             0.002483  
3                 0.021623           0.782452             0.217548  
4                 0.025872           0.950621             0.049379  
...                    ...                ...                  ...  
4647              0.292321           0.882528             0.117472  
4648              0.928981           0.216068             0.783932  
4649              0.025005           0.943967             0.056033  
4650              0.345257           0.039350             0.960650  
4651              0.025872           0.953661             0.046339  

[4652 rows x 7 columns]

In [20]:
output.shape


(4652, 7)

In [21]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/PhishTank/Base_classifier_result(pre URL cross)(2).csv', index=False)