In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/PhishTank/URL-HTML/preprocessed_url_features.csv")
urldata


Unnamed: 0                                       Domain  Have IP  \
0               0                             graphicriver.net        0   
1               1                                    ecnavi.jp        0   
2               2                                 hubpages.com        0   
3               3                              extratorrent.cc        0   
4               4                                icicibank.com        0   
...           ...                                          ...      ...   
10332       11932                             sites.google.com        0   
10333       11933                             sites.google.com        0   
10334       11934             habbocreditosparati.blogspot.com        0   
10335       11935  creditiperhabbogratissicuro100.blogspot.com        0   
10336       11936                           aijcs.blogspot.com        0   

       Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0           0           1          1            0             0        0   
1           0           1          1            1             0        0   
2           0           1          1            0             1        0   
3           0           1          3            0             0        0   
4           0           1          3            0             0        0   
...       ...         ...        ...          ...           ...      ...   
10332       0           0          2            0             1        0   
10333       0           0          2            0             0        0   
10334       0           0          0            0             0        1   
10335       0           1          3            0             0        1   
10336       0           1          3            0             0        1   

       Prefix/Suffix  ...  Num Embeds  Num Images  Num Links  Num Titles  \
0                  0  ...           0          49        691          42   
1                  0  ...           0           4         66           3   
2                  0  ...           0           1        100          27   
3                  0  ...           0           0          0           1   
4                  0  ...           0         117        219          23   
...              ...  ...         ...         ...        ...         ...   
10332              0  ...           0           0         17           4   
10333              0  ...           0           6         24           7   
10334              0  ...           0           4         17           4   
10335              0  ...           0           1         23           8   
10336              0  ...           0          19         42           7   

       Num Script  Special Characters  Script To Special Chars Ratio  \
0           13135                6400                       2.052344   
1            2034                 818                       2.486553   
2           32987               10451                       3.156349   
3               0                  52                       0.000000   
4            7944                3468                       2.290657   
...           ...                 ...                            ...   
10332        8146                2203                       3.697685   
10333        8353                2250                       3.712444   
10334        6403                4560                       1.404167   
10335        9817                7292                       1.346270   
10336        2550                3225                       0.790698   

       Script To body Ratio  Body To Special Char Ratio  Label  
0                  0.528869                    0.257690      0  
1                  0.676197                    0.271941      0  
2                  0.836681                    0.265079      0  
3                  0.000000                    0.227074      0  
4                  0.524460                    0.228956      0  
...                     .

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0'], axis = 1).copy()
urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0          49   
1              0            0           0  ...           0           4   
2              0            0           0  ...           0           1   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0         117   

   Num Links  Num Titles  Num Script  Special Characters  \
0        691          42       13135                6400   
1         66           3        2034                 818   
2        100          27       32987               10451   
3          0           1           0                  52   
4        219          23        7944                3468   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.052344              0.528869   
1                       2.486553              0.676197   
2                       3.156349              0.836681   
3                       0.000000              0.000000   
4                       2.290657              0.524460   

   Body To Special Char Ratio  Label  
0                    0.257690      0  
1                    0.271941      0  
2                    0.265079      0  
3                    0.227074      0  
4                    0.228956      0  

[5 rows x 45 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Have IP                        10337 non-null  int64  
 1   Have @                         10337 non-null  int64  
 2   URL Length                     10337 non-null  int64  
 3   URL Depth                      10337 non-null  int64  
 4   Redirection                    10337 non-null  int64  
 5   https Domain                   10337 non-null  int64  
 6   TinyURL                        10337 non-null  int64  
 7   Prefix/Suffix                  10337 non-null  int64  
 8   Have client                    10337 non-null  int64  
 9   Have admin                     10337 non-null  int64  
 10  Have login                     10337 non-null  int64  
 11  Have server                    10337 non-null  int64  
 12  .php                           10337 non-null 

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    5828
1    4509
dtype: int64

In [8]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 10337
Non-Phishing: 5828 (56.38% of total)
Phishing: 4509 (43.62% of total)


In [9]:

import numpy as np


In [10]:
urldata.describe()

Have IP        Have @    URL Length     URL Depth   Redirection  \
count  10337.0  10337.000000  10337.000000  10337.000000  10337.000000   
mean       0.0      0.025636      0.698462      3.048660      0.013060   
std        0.0      0.158055      0.458948      2.951401      0.113537   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      0.000000      1.000000      0.000000   
50%        0.0      0.000000      1.000000      2.000000      0.000000   
75%        0.0      0.000000      1.000000      4.000000      0.000000   
max        0.0      1.000000      1.000000     18.000000      1.000000   

       https Domain       TinyURL  Prefix/Suffix   Have client    Have admin  \
count  10337.000000  10337.000000   10337.000000  10337.000000  10337.000000   
mean       0.365773      0.068105       0.074877      0.003676      0.008610   
std        0.481670      0.251938       0.263205      0.060522      0.092393   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      0.000000   
50%        0.000000      0.000000       0.000000      0.000000      0.000000   
75%        1.000000      0.000000       0.000000      0.000000      0.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

       ...    Num Embeds    Num Images     Num Links    Num Titles  \
count  ...  10337.000000  10337.000000  10337.000000  10337.000000   
mean   ...      0.000871     10.595627     54.459998      6.805553   
std    ...      0.029496     33.772343    105.521327     25.206153   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      1.000000      1.000000   
50%    ...      0.000000      1.000000      5.000000      1.000000   
75%    ...      0.000000      5.000000     54.000000      3.000000   
max    ...      1.000000    688.000000   2078.000000   1042.000000   

         Num Script  Special Characters  Script To Special Chars Ratio  \
count  1.033700e+04        10337.000000                   10337.000000   
mean   2.805686e+04        10823.200445                       3.695922   
std    9.871191e+04        28279.638035                      21.605333   
min    0.000000e+00            0.000000                       0.000000   
25%    0.000000e+00          421.000000                       0.000000   
50%    5.162000e+03         2142.000000                       1.916015   
75%    1.665200e+04         8705.000000                       2.737587   
max    2.450669e+06       631036.000000                     519.266010   

       Script To body Ratio  Body To Special Char Ratio         Label  
count          10337.000000                10337.000000  10337.000000  
mean               0.443764                    0.241135      0.436200  
std                0.368330                    0.075312      0.495937  
min                0.000000                   -0.000119      0.000000  
25%                0.000000                    0.209596      0.000000  
50%                0.488331                    0.254868      0.000000  
75%                0.790474                    0.295025      1.000000  
max                1.142857                    0.605483      1.000000  

[8 rows x 45 columns]

In [11]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                          0
Have @                           0
URL Length                       0
URL Depth                        0
Redirection                      0
https Domain                     0
TinyURL                          0
Prefix/Suffix                    0
Have client                      0
Have admin                       0
Have login                       0
Have server                      0
.php                             0
.html                            0
.info                            0
.txt                             0
.js                              0
.exe                             0
Num of periods                   0
Is encoded                       0
Num of encoded char              0
Num of parameters                0
Num of digits                    0
Num of spec char                 0
iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page token

In [12]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           0          3            0             1        0   
1        0       0           1          3            0             0        0   
2        0       0           1          3            0             0        0   
3        0       0           1          5            0             0        0   
4        0       0           0          0            0             1        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0           1   
1              0            0           0  ...           0           0   
2              0            0           0  ...           0          10   
3              0            0           0  ...           0           9   
4              0            0           0  ...           0           1   

   Num Links  Num Titles  Num Script  Special Characters  \
0          3           1       69545               29676   
1          0           0           0                   0   
2        165          17      111029               39558   
3        141           2        2029               79595   
4          2           1       26815               10404   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.343476              0.804249   
1                       0.000000              0.000000   
2                       2.806739              0.932476   
3                       0.025492              0.007446   
4                       2.577374              0.947627   

   Body To Special Char Ratio  Label  
0                    0.343186      1  
1                    0.000000      0  
2                    0.332228      0  
3                    0.292096      0  
4                    0.367671      1  

[5 rows x 45 columns]

In [13]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [14]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(5685, 44) (4652, 44)
(5685,) (4652,)


In [15]:
output = {}
output['labels'] = y_test

**Decision Tree Classifier**

In [24]:
import keras
from matplotlib import pyplot as plt
from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  dtcclassifier = DecisionTreeClassifier( max_depth=5)
  #compile model using mse as a measure of model performance

  dtcclassifier.fit(x_train, y_train)


  y_pred = dtcclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/DTC/model_'+str(n)+'.h5'
  pickle.dump(dtcclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [25]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[316  10]
 [ 12 231]]
Precision: 0.9585
Recall: 0.9506
F1 Score: 0.9545
Validation Accuracy: 0.961335676625659
model 0 saved
[[308  11]
 [ 16 234]]
Precision: 0.9551
Recall: 0.9360
F1 Score: 0.9455
Validation Accuracy: 0.9525483304042179
model 1 saved
[[310   7]
 [ 17 235]]
Precision: 0.9711
Recall: 0.9325
F1 Score: 0.9514
Validation Accuracy: 0.9578207381370826
model 2 saved
[[297   3]
 [ 16 253]]
Precision: 0.9883
Recall: 0.9405
F1 Score: 0.9638
Validation Accuracy: 0.9666080843585237
model 3 saved
[[308   6]
 [ 21 234]]
Precision: 0.9750
Recall: 0.9176
F1 Score: 0.9455
Validation Accuracy: 0.9525483304042179
model 4 saved
[[337   8]
 [ 14 209]]
Precision: 0.9631
Recall: 0.9372
F1 Score: 0.9500
Validation Accuracy: 0.9612676056338029
model 5 saved
[[301   7]
 [  9 251]]
Precision: 0.9729
Recall: 0.9654
F1 Score: 0.9691
Validation Accuracy: 0.971830985915493
model 6 saved
[[316   7]
 [ 16 229]]
Precision: 0.9703
Recall: 0.9347
F1 Score: 0.9522
Validation Accuracy: 0.9595070422535211


In [27]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/DTC/model_6.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['dt_prediction_non'] = [i[0] for i in y_pred_prob];
output['dt_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output



[[0.92964824 0.07035176]
 [0.97559055 0.02440945]
 [0.         1.        ]
 ...
 [0.00630915 0.99369085]
 [0.45       0.55      ]
 [0.97559055 0.02440945]]


labels  dt_prediction_non  dt_prediction_phish
0          0           0.929648             0.070352
1          0           0.975591             0.024409
2          1           0.000000             1.000000
3          0           0.975591             0.024409
4          0           0.975591             0.024409
...      ...                ...                  ...
4647       0           0.975591             0.024409
4648       0           0.975591             0.024409
4649       1           0.006309             0.993691
4650       0           0.450000             0.550000
4651       0           0.975591             0.024409

[4652 rows x 3 columns]

**KNN**

In [70]:
import keras

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_knn(x_train, x_val, y_train, y_val, opt, n):
  knnclassifier = KNeighborsClassifier(n_neighbors=7, weights='uniform', algorithm='kd_tree', leaf_size=5)
  #compile model using mse as a measure of model performance
  knnclassifier.fit(x_train, y_train)

  y_pred = knnclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/KNN/model_'+str(n)+'.h5'
  pickle.dump(knnclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [71]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_knn(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[309  17]
 [ 26 217]]
Precision: 0.9274
Recall: 0.8930
F1 Score: 0.9099
Validation Accuracy: 0.9244288224956063
model 0 saved
[[306  13]
 [ 27 223]]
Precision: 0.9449
Recall: 0.8920
F1 Score: 0.9177
Validation Accuracy: 0.929701230228471
model 1 saved
[[298  19]
 [ 29 223]]
Precision: 0.9215
Recall: 0.8849
F1 Score: 0.9028
Validation Accuracy: 0.9156414762741653
model 2 saved
[[289  11]
 [ 31 238]]
Precision: 0.9558
Recall: 0.8848
F1 Score: 0.9189
Validation Accuracy: 0.9261862917398945
model 3 saved
[[303  11]
 [ 28 227]]
Precision: 0.9538
Recall: 0.8902
F1 Score: 0.9209
Validation Accuracy: 0.9314586994727593
model 4 saved
[[330  15]
 [ 24 199]]
Precision: 0.9299
Recall: 0.8924
F1 Score: 0.9108
Validation Accuracy: 0.9313380281690141
model 5 saved
[[288  20]
 [ 28 232]]
Precision: 0.9206
Recall: 0.8923
F1 Score: 0.9062
Validation Accuracy: 0.9154929577464789
model 6 saved
[[308  15]
 [ 29 216]]
Precision: 0.9351
Recall: 0.8816
F1 Score: 0.9076
Validation Accuracy: 0.9225352112676056

In [73]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/KNN/model_4.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['knn_prediction_non'] = [i[0] for i in y_pred_prob];
output['knn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          0           0.929648             0.070352                 1.0   
1          0           0.975591             0.024409                 1.0   
2          1           0.000000             1.000000                 0.0   
3          0           0.975591             0.024409                 1.0   
4          0           0.975591             0.024409                 1.0   
...      ...                ...                  ...                 ...   
4647       0           0.975591             0.024409                 1.0   
4648       0           0.975591             0.024409                 1.0   
4649       1           0.006309             0.993691                 0.0   
4650       0           0.450000             0.550000                 1.0   
4651       0           0.975591             0.024409                 1.0   

      knn_prediction_phish  
0                      0.0  
1                      0.0  
2                      1.0  
3                      0.0  
4                      0.0  
...                    ...  
4647                   0.0  
4648                   0.0  
4649                   1.0  
4650                   0.0  
4651                   0.0  

[4652 rows x 5 columns]

**XGB Classifier**

In [74]:
import keras

from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_xgb(x_train, x_val, y_train, y_val, opt, n):
  xgbclassifier = XGBClassifier(n_neighbors=5)
  #compile model using mse as a measure of model performance
  xgbclassifier.fit(x_train, y_train)

  y_pred = xgbclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/XGBoost/model_'+str(n)+'.h5'
  pickle.dump(xgbclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_xgb(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[318   5]
 [  1 245]]
Precision: 0.9800
Recall: 0.9959
F1 Score: 0.9879
Validation Accuracy: 0.9894551845342706
model 0 saved
[[313   0]
 [  2 254]]
Precision: 1.0000
Recall: 0.9922
F1 Score: 0.9961
Validation Accuracy: 0.9964850615114236
model 1 saved
[[313   2]
 [  2 252]]
Precision: 0.9921
Recall: 0.9921
F1 Score: 0.9921
Validation Accuracy: 0.9929701230228472
model 2 saved
[[330   1]
 [  6 232]]
Precision: 0.9957
Recall: 0.9748
F1 Score: 0.9851
Validation Accuracy: 0.9876977152899824
model 3 saved
[[336   3]
 [  4 226]]
Precision: 0.9869
Recall: 0.9826
F1 Score: 0.9847
Validation Accuracy: 0.9876977152899824
model 4 saved
[[317   1]
 [  3 247]]
Precision: 0.9960
Recall: 0.9880
F1 Score: 0.9920
Validation Accuracy: 0.9929577464788732
model 5 saved
[[307   2]
 [  4 255]]
Precision: 0.9922
Recall: 0.9846
F1 Score: 0.9884
Validation Accuracy: 0.9894366197183099
model 6 saved
[[312   3]
 [  3 250]]
Precision: 0.9881
Recall: 0.9881
F1 Score: 0.9881
Validation Accuracy: 0.989436619718309

In [75]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/XGBoost/model_8.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['XGB_prediction_non'] = [i[0] for i in y_pred_prob];
output['XGB_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[9.8633784e-01 1.3662180e-02]
 [9.9882579e-01 1.1741996e-03]
 [9.0849400e-04 9.9909151e-01]
 ...
 [2.6642680e-03 9.9733573e-01]
 [9.9510443e-01 4.8955609e-03]
 [9.9845558e-01 1.5444183e-03]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          0           0.929648             0.070352                 1.0   
1          0           0.975591             0.024409                 1.0   
2          1           0.000000             1.000000                 0.0   
3          0           0.975591             0.024409                 1.0   
4          0           0.975591             0.024409                 1.0   
...      ...                ...                  ...                 ...   
4647       0           0.975591             0.024409                 1.0   
4648       0           0.975591             0.024409                 1.0   
4649       1           0.006309             0.993691                 0.0   
4650       0           0.450000             0.550000                 1.0   
4651       0           0.975591             0.024409                 1.0   

      knn_prediction_phish  XGB_prediction_non  XGB_prediction_phish  
0                      0.0            0.986338              0.013662  
1                      0.0            0.998826              0.001174  
2                      1.0            0.000908              0.999092  
3                      0.0            0.995848              0.004152  
4                      0.0            0.997278              0.002722  
...                    ...                 ...                   ...  
4647                   0.0            0.999137              0.000864  
4648                   0.0            0.997809              0.002191  
4649                   1.0            0.002664              0.997336  
4650                   0.0            0.995104              0.004896  
4651                   0.0            0.998456              0.001544  

[4652 rows x 7 columns]

In [76]:
output.shape


(4652, 7)

In [77]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/PhishTank/Base_classifier_result(pre URL-HTML cross).csv', index=False)