In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/PhishTank/URL-HTML/preprocessed_url_features.csv")
urldata


Unnamed: 0                                       Domain  Have IP  \
0               0                             graphicriver.net        0   
1               1                                    ecnavi.jp        0   
2               2                                 hubpages.com        0   
3               3                              extratorrent.cc        0   
4               4                                icicibank.com        0   
...           ...                                          ...      ...   
10332       11932                             sites.google.com        0   
10333       11933                             sites.google.com        0   
10334       11934             habbocreditosparati.blogspot.com        0   
10335       11935  creditiperhabbogratissicuro100.blogspot.com        0   
10336       11936                           aijcs.blogspot.com        0   

       Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0           0           1          1            0             0        0   
1           0           1          1            1             0        0   
2           0           1          1            0             1        0   
3           0           1          3            0             0        0   
4           0           1          3            0             0        0   
...       ...         ...        ...          ...           ...      ...   
10332       0           0          2            0             1        0   
10333       0           0          2            0             0        0   
10334       0           0          0            0             0        1   
10335       0           1          3            0             0        1   
10336       0           1          3            0             0        1   

       Prefix/Suffix  ...  Num Embeds  Num Images  Num Links  Num Titles  \
0                  0  ...           0          49        691          42   
1                  0  ...           0           4         66           3   
2                  0  ...           0           1        100          27   
3                  0  ...           0           0          0           1   
4                  0  ...           0         117        219          23   
...              ...  ...         ...         ...        ...         ...   
10332              0  ...           0           0         17           4   
10333              0  ...           0           6         24           7   
10334              0  ...           0           4         17           4   
10335              0  ...           0           1         23           8   
10336              0  ...           0          19         42           7   

       Num Script  Special Characters  Script To Special Chars Ratio  \
0           13135                6400                       2.052344   
1            2034                 818                       2.486553   
2           32987               10451                       3.156349   
3               0                  52                       0.000000   
4            7944                3468                       2.290657   
...           ...                 ...                            ...   
10332        8146                2203                       3.697685   
10333        8353                2250                       3.712444   
10334        6403                4560                       1.404167   
10335        9817                7292                       1.346270   
10336        2550                3225                       0.790698   

       Script To body Ratio  Body To Special Char Ratio  Label  
0                  0.528869                    0.257690      0  
1                  0.676197                    0.271941      0  
2                  0.836681                    0.265079      0  
3                  0.000000                    0.227074      0  
4                  0.524460                    0.228956      0  
...                     .

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'Domain'], axis = 1).copy()

urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0          49   
1              0            0           0  ...           0           4   
2              0            0           0  ...           0           1   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0         117   

   Num Links  Num Titles  Num Script  Special Characters  \
0        691          42       13135                6400   
1         66           3        2034                 818   
2        100          27       32987               10451   
3          0           1           0                  52   
4        219          23        7944                3468   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.052344              0.528869   
1                       2.486553              0.676197   
2                       3.156349              0.836681   
3                       0.000000              0.000000   
4                       2.290657              0.524460   

   Body To Special Char Ratio  Label  
0                    0.257690      0  
1                    0.271941      0  
2                    0.265079      0  
3                    0.227074      0  
4                    0.228956      0  

[5 rows x 45 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Have IP                        10337 non-null  int64  
 1   Have @                         10337 non-null  int64  
 2   URL Length                     10337 non-null  int64  
 3   URL Depth                      10337 non-null  int64  
 4   Redirection                    10337 non-null  int64  
 5   https Domain                   10337 non-null  int64  
 6   TinyURL                        10337 non-null  int64  
 7   Prefix/Suffix                  10337 non-null  int64  
 8   Have client                    10337 non-null  int64  
 9   Have admin                     10337 non-null  int64  
 10  Have login                     10337 non-null  int64  
 11  Have server                    10337 non-null  int64  
 12  .php                           10337 non-null 

In [ ]:
# Class Distribution of Labels
urldata.groupby('Label').size()

In [ ]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

In [ ]:
urldata.describe()

In [ ]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                          0
Have @                           0
URL Length                       0
URL Depth                        0
Redirection                      0
https Domain                     0
TinyURL                          0
Prefix/Suffix                    0
Have client                      0
Have admin                       0
Have login                       0
Have server                      0
.php                             0
.html                            0
.info                            0
.txt                             0
.js                              0
.exe                             0
Num of periods                   0
Is encoded                       0
Num of encoded char              0
Num of parameters                0
Num of digits                    0
Num of spec char                 0
iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page token

In [ ]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          4            0             0        0   
1        0       0           1          2            0             1        0   
2        0       0           1          3            0             0        0   
3        0       0           0          0            0             1        1   
4        0       0           1          3            0             0        1   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0           5   
1              1            0           0  ...           0           0   
2              0            0           0  ...           0           0   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0          59   

   Num Links  Num Titles  Num Script  Special Characters  \
0         11           5      242609               76820   
1          0           0           0                   0   
2          0           1           0                  46   
3          0           1        4748                1488   
4        147           3        7912                3552   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       3.158149              0.946209   
1                       0.000000              0.000000   
2                       0.000000              0.000000   
3                       3.190860              0.968782   
4                       2.227477              0.561892   

   Body To Special Char Ratio  Label  
0                    0.299609      0  
1                    0.000000      1  
2                    0.216981      0  
3                    0.303612      1  
4                    0.252255      0  

[5 rows x 45 columns]

In [ ]:
import numpy as np
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [ ]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(5685, 44) (4652, 44)
(5685,) (4652,)


In [ ]:
output = {}
output['labels'] = y_test

**MLP**

In [ ]:
import keras

from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle

def model_mlp(x_train, x_val, y_train, y_val, opt, n):
  mlpclassifier = MLPClassifier(alpha=0.0001, hidden_layer_sizes=([100,100,100]))
  #compile model using mse as a measure of model performance
  mlpclassifier.fit(x_train, y_train)

  y_pred = mlpclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/MLP/model_'+str(n)+'.h5'
  pickle.dump(mlpclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_mlp(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[318  10]
 [ 95 146]]
Precision: 0.9359
Recall: 0.6058
F1 Score: 0.7355
Validation Accuracy: 0.8154657293497364
model 0 saved
[[297   8]
 [ 57 207]]
Precision: 0.9628
Recall: 0.7841
F1 Score: 0.8643
Validation Accuracy: 0.8857644991212654
model 1 saved
[[181 145]
 [ 14 229]]
Precision: 0.6123
Recall: 0.9424
F1 Score: 0.7423
Validation Accuracy: 0.7205623901581723
model 2 saved
[[277  40]
 [ 51 201]]
Precision: 0.8340
Recall: 0.7976
F1 Score: 0.8154
Validation Accuracy: 0.8400702987697716
model 3 saved
[[311  10]
 [110 138]]
Precision: 0.9324
Recall: 0.5565
F1 Score: 0.6970
Validation Accuracy: 0.789103690685413
model 4 saved
[[310   9]
 [ 61 188]]
Precision: 0.9543
Recall: 0.7550
F1 Score: 0.8430
Validation Accuracy: 0.8767605633802817
model 5 saved
[[331  11]
 [ 56 170]]
Precision: 0.9392
Recall: 0.7522
F1 Score: 0.8354
Validation Accuracy: 0.8820422535211268
model 6 saved
[[291  37]
 [ 37 203]]
Precision: 0.8458
Recall: 0.8458
F1 Score: 0.8458
Validation Accuracy: 0.8697183098591549

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/MLP/model_1.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['mlp_prediction_non'] = [i[0] for i in y_pred_prob];
output['mlp_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[9.99989064e-01 1.09358504e-05]
 [1.00000000e+00 5.71218323e-20]
 [1.00000000e+00 1.80439015e-83]
 ...
 [9.99999999e-01 1.36435856e-09]
 [1.00000000e+00 1.35258179e-12]
 [1.00000000e+00 7.21198602e-13]]


labels  mlp_prediction_non  mlp_prediction_phish
0          0            0.999989          1.093585e-05
1          0            1.000000          5.712183e-20
2          0            1.000000          1.804390e-83
3          0            0.991853          8.147189e-03
4          0            0.998126          1.874161e-03
...      ...                 ...                   ...
4647       1            0.010479          9.895206e-01
4648       0            0.999998          1.553756e-06
4649       0            1.000000          1.364359e-09
4650       0            1.000000          1.352582e-12
4651       0            1.000000          7.211986e-13

[4652 rows x 3 columns]

**Neural Network**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_aa(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]
  # print("check point")
  #create model
  model = Sequential()
  model.add(Dense(30, activation='relu', input_shape=(n_cols,)))
  model.add(Dense(10, activation='relu'))

  model.add(Dense(1, activation = 'sigmoid'))
  # softmax
  #compile model using mse as a measure of model performance
  model.compile(optimizer = opt, loss= 'binary_crossentropy', metrics=["accuracy"])

  history = model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/NN/model_'+str(n)+'.h5'
  pickle.dump(model, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_aa(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
160/160 [==============================] - 4s 4ms/step - loss: 531.2415 - accuracy: 0.5940 - val_loss: 83.2652 - val_accuracy: 0.5694
Epoch 2/100
160/160 [==============================] - 0s 3ms/step - loss: 76.6814 - accuracy: 0.6501 - val_loss: 39.9997 - val_accuracy: 0.6608
Epoch 3/100
160/160 [==============================] - 1s 3ms/step - loss: 58.1835 - accuracy: 0.7183 - val_loss: 21.4702 - val_accuracy: 0.7838
Epoch 4/100
160/160 [==============================] - 0s 3ms/step - loss: 31.0870 - accuracy: 0.7533 - val_loss: 65.0925 - val_accuracy: 0.6344
Epoch 5/100
160/160 [==============================] - 1s 3ms/step - loss: 31.1484 - accuracy: 0.7748 - val_loss: 35.0175 - val_accuracy: 0.8084
Epoch 6/100
160/160 [==============================] - 0s 3ms/step - loss: 29.1642 - accuracy: 0.7852 - val_loss: 38.4875 - val_accuracy: 0.7944
Epoch 7/100
160/160 [==============================] - 1s 3ms/step - loss: 75.3237 - accuracy: 0.7602 - val_loss: 65.0725 - val_a

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/NN/model_9.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[9.99989064e-01 1.09358504e-05]
 [1.00000000e+00 5.71218323e-20]
 [1.00000000e+00 1.80439015e-83]
 ...
 [9.99999999e-01 1.36435856e-09]
 [1.00000000e+00 1.35258179e-12]
 [1.00000000e+00 7.21198602e-13]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0            0.999989          1.093585e-05           0.999989   
1          0            1.000000          5.712183e-20           1.000000   
2          0            1.000000          1.804390e-83           1.000000   
3          0            0.991853          8.147189e-03           0.991853   
4          0            0.998126          1.874161e-03           0.998126   
...      ...                 ...                   ...                ...   
4647       1            0.010479          9.895206e-01           0.010479   
4648       0            0.999998          1.553756e-06           0.999998   
4649       0            1.000000          1.364359e-09           1.000000   
4650       0            1.000000          1.352582e-12           1.000000   
4651       0            1.000000          7.211986e-13           1.000000   

      nn_prediction_phish  
0            1.093585e-05  
1            5.712183e-20  
2            1.804390e-83  
3            8.147189e-03  
4            1.874161e-03  
...                   ...  
4647         9.895206e-01  
4648         1.553756e-06  
4649         1.364359e-09  
4650         1.352582e-12  
4651         7.211986e-13  

[4652 rows x 5 columns]

**Neural Network 2**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_a(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]

  #create model
  model_2 = Sequential()
  model_2.add(Dense(30, activation='sigmoid', input_shape=(n_cols,)))
  model_2.add(Dense(25, activation='sigmoid'))
  model_2.add(Dense(20, activation='sigmoid'))
  model_2.add(Dense(15, activation='sigmoid'))
  model_2.add(Dense(10, activation='sigmoid'))
  model_2.add(Dense(1, activation = 'sigmoid'))

  #compile model using mse as a measure of model performance
  model_2.compile(optimizer='adam', loss='mean_squared_error')



  history = model_2.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model_2.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/NN_2/model_'+str(n)+'.h5'
  pickle.dump(model_2, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_a(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
160/160 [==============================] - 2s 6ms/step - loss: 0.2466 - val_loss: 0.2479
Epoch 2/100
160/160 [==============================] - 1s 5ms/step - loss: 0.2463 - val_loss: 0.2469
Epoch 3/100
160/160 [==============================] - 1s 5ms/step - loss: 0.2421 - val_loss: 0.2347
Epoch 4/100
160/160 [==============================] - 1s 5ms/step - loss: 0.2065 - val_loss: 0.1862
Epoch 5/100
160/160 [==============================] - 1s 3ms/step - loss: 0.1825 - val_loss: 0.1769
Epoch 6/100
160/160 [==============================] - 0s 3ms/step - loss: 0.1800 - val_loss: 0.1823
Epoch 7/100
160/160 [==============================] - 1s 3ms/step - loss: 0.1851 - val_loss: 0.1795
Epoch 8/100
160/160 [==============================] - 1s 3ms/step - loss: 0.1793 - val_loss: 0.1730
Epoch 9/100
160/160 [==============================] - 0s 3ms/step - loss: 0.1781 - val_loss: 0.1691
Epoch 10/100
160/160 [==============================] - 1s 3ms/step - loss: 0.1668 - val_lo

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/NN_2/model_4.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn2_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn2_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[9.99989064e-01 1.09358504e-05]
 [1.00000000e+00 5.71218323e-20]
 [1.00000000e+00 1.80439015e-83]
 ...
 [9.99999999e-01 1.36435856e-09]
 [1.00000000e+00 1.35258179e-12]
 [1.00000000e+00 7.21198602e-13]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0            0.999989          1.093585e-05           0.999989   
1          0            1.000000          5.712183e-20           1.000000   
2          0            1.000000          1.804390e-83           1.000000   
3          0            0.991853          8.147189e-03           0.991853   
4          0            0.998126          1.874161e-03           0.998126   
...      ...                 ...                   ...                ...   
4647       1            0.010479          9.895206e-01           0.010479   
4648       0            0.999998          1.553756e-06           0.999998   
4649       0            1.000000          1.364359e-09           1.000000   
4650       0            1.000000          1.352582e-12           1.000000   
4651       0            1.000000          7.211986e-13           1.000000   

      nn_prediction_phish  nn2_prediction_non  nn2_prediction_phish  
0            1.093585e-05            0.999989          1.093585e-05  
1            5.712183e-20            1.000000          5.712183e-20  
2            1.804390e-83            1.000000          1.804390e-83  
3            8.147189e-03            0.991853          8.147189e-03  
4            1.874161e-03            0.998126          1.874161e-03  
...                   ...                 ...                   ...  
4647         9.895206e-01            0.010479          9.895206e-01  
4648         1.553756e-06            0.999998          1.553756e-06  
4649         1.364359e-09            1.000000          1.364359e-09  
4650         1.352582e-12            1.000000          1.352582e-12  
4651         7.211986e-13            1.000000          7.211986e-13  

[4652 rows x 7 columns]

In [ ]:
output.shape

(4652, 7)

In [ ]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/PhishTank/Base_classifier_result(pre URL-HTML cross)(3).csv', index=False)