In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/PhishTank/URL-HTML/preprocessed_url_features.csv")
urldata


Unnamed: 0                                       Domain  Have IP  \
0               0                             graphicriver.net        0   
1               1                                    ecnavi.jp        0   
2               2                                 hubpages.com        0   
3               3                              extratorrent.cc        0   
4               4                                icicibank.com        0   
...           ...                                          ...      ...   
10332       11932                             sites.google.com        0   
10333       11933                             sites.google.com        0   
10334       11934             habbocreditosparati.blogspot.com        0   
10335       11935  creditiperhabbogratissicuro100.blogspot.com        0   
10336       11936                           aijcs.blogspot.com        0   

       Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0           0           1          1            0             0        0   
1           0           1          1            1             0        0   
2           0           1          1            0             1        0   
3           0           1          3            0             0        0   
4           0           1          3            0             0        0   
...       ...         ...        ...          ...           ...      ...   
10332       0           0          2            0             1        0   
10333       0           0          2            0             0        0   
10334       0           0          0            0             0        1   
10335       0           1          3            0             0        1   
10336       0           1          3            0             0        1   

       Prefix/Suffix  ...  Num Embeds  Num Images  Num Links  Num Titles  \
0                  0  ...           0          49        691          42   
1                  0  ...           0           4         66           3   
2                  0  ...           0           1        100          27   
3                  0  ...           0           0          0           1   
4                  0  ...           0         117        219          23   
...              ...  ...         ...         ...        ...         ...   
10332              0  ...           0           0         17           4   
10333              0  ...           0           6         24           7   
10334              0  ...           0           4         17           4   
10335              0  ...           0           1         23           8   
10336              0  ...           0          19         42           7   

       Num Script  Special Characters  Script To Special Chars Ratio  \
0           13135                6400                       2.052344   
1            2034                 818                       2.486553   
2           32987               10451                       3.156349   
3               0                  52                       0.000000   
4            7944                3468                       2.290657   
...           ...                 ...                            ...   
10332        8146                2203                       3.697685   
10333        8353                2250                       3.712444   
10334        6403                4560                       1.404167   
10335        9817                7292                       1.346270   
10336        2550                3225                       0.790698   

       Script To body Ratio  Body To Special Char Ratio  Label  
0                  0.528869                    0.257690      0  
1                  0.676197                    0.271941      0  
2                  0.836681                    0.265079      0  
3                  0.000000                    0.227074      0  
4                  0.524460                    0.228956      0  
...                     .

In [ ]:
urldata.columns

Index(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [ ]:
urldata = urldata.drop(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char'], axis = 1).copy()

urldata.shape
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                  21444   
1       1           0            0             1                   1075   
2       1           0            0             1                   4531   
3       1           0            0             1                     32   
4       1           0            0             1                   4880   

   number of sentences  number of html tags  number of whitespace  \
0                 1853                 3247                     0   
1                  136                  236                     0   
2                 2634                  486                     0   
3                    9                    8                     0   
4                  981                 1412                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1        24836  ...           0          49        691   
1            1         3008  ...           0           4         66   
2            1        39426  ...           0           1        100   
3            0          229  ...           0           0          0   
4            1        15147  ...           0         117        219   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0          42       13135                6400                       2.052344   
1           3        2034                 818                       2.486553   
2          27       32987               10451                       3.156349   
3           1           0                  52                       0.000000   
4          23        7944                3468                       2.290657   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.528869                    0.257690      0  
1              0.676197                    0.271941      0  
2              0.836681                    0.265079      0  
3              0.000000                    0.227074      0  
4              0.524460                    0.228956      0  

[5 rows x 21 columns]

In [ ]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   iFrame                         10337 non-null  int64  
 1   Mouse Over                     10337 non-null  int64  
 2   Right Click                    10337 non-null  int64  
 3   Web Forwards                   10337 non-null  int64  
 4   Number of page tokens          10337 non-null  int64  
 5   number of sentences            10337 non-null  int64  
 6   number of html tags            10337 non-null  int64  
 7   number of whitespace           10337 non-null  int64  
 8   url Is Live                    10337 non-null  int64  
 9   HTML Length                    10337 non-null  int64  
 10  Num Objects                    10337 non-null  int64  
 11  Num Embeds                     10337 non-null  int64  
 12  Num Images                     10337 non-null 

In [ ]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    5828
1    4509
dtype: int64

In [ ]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 10337
Non-Phishing: 5828 (56.38% of total)
Phishing: 4509 (43.62% of total)


In [ ]:
#checking the data for null or missing values
urldata.isnull().sum()

iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page tokens            0
number of sentences              0
number of html tags              0
number of whitespace             0
url Is Live                      0
HTML Length                      0
Num Objects                      0
Num Embeds                       0
Num Images                       0
Num Links                        0
Num Titles                       0
Num Script                       0
Special Characters               0
Script To Special Chars Ratio    0
Script To body Ratio             0
Body To Special Char Ratio       0
Label                            0
dtype: int64

In [ ]:
import numpy as np
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                     22   
1       1           0            0             1                     37   
2       1           0            0             1                     16   
3       1           0            0             1                  33577   
4       1           0            0             1                     87   

   number of sentences  number of html tags  number of whitespace  \
0                    3                    6                     0   
1                    4                    7                     0   
2                   12                    9                     0   
3                 4430                 1320                     0   
4                  113                   18                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            0          164  ...           0           0          0   
1            0          186  ...           0           0          0   
2            1           83  ...           0           0          0   
3            1       402091  ...           0           8        188   
4            1         2403  ...           0           0          0   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0           1           0                  28                       0.000000   
1           1           0                  31                       0.000000   
2           0          83                  14                       5.928571   
3           8      263443              103749                       2.539234   
4           0        2343                 828                       2.829710   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.000000                    0.170732      1  
1              0.000000                    0.166667      1  
2              1.000000                    0.168675      1  
3              0.655183                    0.258024      0  
4              0.975031                    0.344569      1  

[5 rows x 21 columns]

In [ ]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [ ]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(5685, 20) (4652, 20)
(5685,) (4652,)


In [ ]:
output = {}
output['labels'] = y_test

**MLP**

In [ ]:
import keras

from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle

def model_mlp(x_train, x_val, y_train, y_val, opt, n):
  mlpclassifier = MLPClassifier(alpha=0.0001, hidden_layer_sizes=([100,100,100]))
  #compile model using mse as a measure of model performance
  mlpclassifier.fit(x_train, y_train)

  y_pred = mlpclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/MLP/model_'+str(n)+'.h5'
  pickle.dump(mlpclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_mlp(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[219 103]
 [ 34 213]]
Precision: 0.6741
Recall: 0.8623
F1 Score: 0.7567
Validation Accuracy: 0.7592267135325131
model 0 saved
[[295  25]
 [ 86 163]]
Precision: 0.8670
Recall: 0.6546
F1 Score: 0.7460
Validation Accuracy: 0.804920913884007
model 1 saved
[[ 98 226]
 [ 23 222]]
Precision: 0.4955
Recall: 0.9061
F1 Score: 0.6407
Validation Accuracy: 0.562390158172232
model 2 saved
[[259  75]
 [ 63 172]]
Precision: 0.6964
Recall: 0.7319
F1 Score: 0.7137
Validation Accuracy: 0.7574692442882249
model 3 saved
[[272  52]
 [ 90 155]]
Precision: 0.7488
Recall: 0.6327
F1 Score: 0.6858
Validation Accuracy: 0.7504393673110721
model 4 saved
[[282  55]
 [ 73 158]]
Precision: 0.7418
Recall: 0.6840
F1 Score: 0.7117
Validation Accuracy: 0.7746478873239436
model 5 saved
[[271  31]
 [ 77 189]]
Precision: 0.8591
Recall: 0.7105
F1 Score: 0.7778
Validation Accuracy: 0.8098591549295775
model 6 saved
[[179 138]
 [ 19 232]]
Precision: 0.6270
Recall: 0.9243
F1 Score: 0.7472
Validation Accuracy: 0.7235915492957746


In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/MLP/model_6.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['mlp_prediction_non'] = [i[0] for i in y_pred_prob];
output['mlp_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[9.99999374e-01 6.25759875e-07]
 [6.02153377e-01 3.97846623e-01]
 [9.66002549e-01 3.39974510e-02]
 ...
 [1.00000000e+00 9.16716182e-28]
 [9.99999997e-01 2.65941634e-09]
 [9.99999486e-01 5.14457726e-07]]


labels  mlp_prediction_non  mlp_prediction_phish
0          0            0.999999          6.257599e-07
1          0            0.602153          3.978466e-01
2          1            0.966003          3.399745e-02
3          1            0.580367          4.196330e-01
4          1            0.113440          8.865602e-01
...      ...                 ...                   ...
4647       1            0.075658          9.243419e-01
4648       0            1.000000          9.731610e-27
4649       0            1.000000          9.167162e-28
4650       0            1.000000          2.659416e-09
4651       0            0.999999          5.144577e-07

[4652 rows x 3 columns]

**Neural Network**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_aa(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]
  # print("check point")
  #create model
  model = Sequential()
  model.add(Dense(30, activation='relu', input_shape=(n_cols,)))
  model.add(Dense(10, activation='relu'))

  model.add(Dense(1, activation = 'sigmoid'))
  # softmax
  #compile model using mse as a measure of model performance
  model.compile(optimizer = opt, loss= 'binary_crossentropy', metrics=["accuracy"])

  history = model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/NN/model_'+str(n)+'.h5'
  pickle.dump(model, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_aa(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
160/160 [==============================] - 4s 4ms/step - loss: 2053.9919 - accuracy: 0.5784 - val_loss: 279.5327 - val_accuracy: 0.5975
Epoch 2/100
160/160 [==============================] - 1s 3ms/step - loss: 161.9198 - accuracy: 0.6335 - val_loss: 75.5217 - val_accuracy: 0.6397
Epoch 3/100
160/160 [==============================] - 1s 4ms/step - loss: 68.9886 - accuracy: 0.6724 - val_loss: 34.7369 - val_accuracy: 0.7083
Epoch 4/100
160/160 [==============================] - 1s 3ms/step - loss: 47.5932 - accuracy: 0.6951 - val_loss: 34.1017 - val_accuracy: 0.7153
Epoch 5/100
160/160 [==============================] - 1s 3ms/step - loss: 44.6418 - accuracy: 0.7136 - val_loss: 132.0211 - val_accuracy: 0.6028
Epoch 6/100
160/160 [==============================] - 1s 4ms/step - loss: 46.8089 - accuracy: 0.7080 - val_loss: 29.2888 - val_accuracy: 0.7417
Epoch 7/100
160/160 [==============================] - 1s 3ms/step - loss: 50.2680 - accuracy: 0.6968 - val_loss: 30.8347 - v

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.57      1.00      0.73       324
           1       0.00      0.00      0.00       245

    accuracy                           0.57       569
   macro avg       0.28      0.50      0.36       569
weighted avg       0.32      0.57      0.41       569

Accuracy: 0.5694200351493849
[[324   0]
 [245   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000
INFO:tensorflow:Assets written to: ram://2909b241-ca88-4243-9ee6-1b7e1c917c2b/assets
model 2 saved
Epoch 1/100
160/160 [==============================] - 1s 5ms/step - loss: 179.2388 - accuracy: 0.5444 - val_loss: 89.2186 - val_accuracy: 0.6134
Epoch 2/100
160/160 [==============================] - 1s 4ms/step - loss: 52.9039 - accuracy: 0.5884 - val_loss: 23.6565 - val_accuracy: 0.6397
Epoch 3/100
160/160 [==============================] - 1s 4ms/step - loss: 52.1703 - accuracy: 0.6419 - val_loss: 30.7135 - val_accuracy: 0.5501
Epoch 4/100
160/160 [===============

In [ ]:
 # load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/NN/model_1.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[9.99999374e-01 6.25759875e-07]
 [6.02153377e-01 3.97846623e-01]
 [9.66002549e-01 3.39974510e-02]
 ...
 [1.00000000e+00 9.16716182e-28]
 [9.99999997e-01 2.65941634e-09]
 [9.99999486e-01 5.14457726e-07]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0            0.999999          6.257599e-07           0.999999   
1          0            0.602153          3.978466e-01           0.602153   
2          1            0.966003          3.399745e-02           0.966003   
3          1            0.580367          4.196330e-01           0.580367   
4          1            0.113440          8.865602e-01           0.113440   
...      ...                 ...                   ...                ...   
4647       1            0.075658          9.243419e-01           0.075658   
4648       0            1.000000          9.731610e-27           1.000000   
4649       0            1.000000          9.167162e-28           1.000000   
4650       0            1.000000          2.659416e-09           1.000000   
4651       0            0.999999          5.144577e-07           0.999999   

      nn_prediction_phish  
0            6.257599e-07  
1            3.978466e-01  
2            3.399745e-02  
3            4.196330e-01  
4            8.865602e-01  
...                   ...  
4647         9.243419e-01  
4648         9.731610e-27  
4649         9.167162e-28  
4650         2.659416e-09  
4651         5.144577e-07  

[4652 rows x 5 columns]

**Neural Network 2**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_a(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]

  #create model
  model_2 = Sequential()
  model_2.add(Dense(30, activation='sigmoid', input_shape=(n_cols,)))
  model_2.add(Dense(25, activation='sigmoid'))
  model_2.add(Dense(20, activation='sigmoid'))
  model_2.add(Dense(15, activation='sigmoid'))
  model_2.add(Dense(10, activation='sigmoid'))
  model_2.add(Dense(1, activation = 'sigmoid'))

  #compile model using mse as a measure of model performance
  model_2.compile(optimizer='adam', loss='mean_squared_error')



  history = model_2.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model_2.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/NN_2/model_'+str(n)+'.h5'
  pickle.dump(model_2, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_a(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
160/160 [==============================] - 2s 6ms/step - loss: 0.2462 - val_loss: 0.2456
Epoch 2/100
160/160 [==============================] - 1s 5ms/step - loss: 0.2453 - val_loss: 0.2430
Epoch 3/100
160/160 [==============================] - 1s 5ms/step - loss: 0.2394 - val_loss: 0.2257
Epoch 4/100
160/160 [==============================] - 1s 5ms/step - loss: 0.2198 - val_loss: 0.2058
Epoch 5/100
160/160 [==============================] - 1s 4ms/step - loss: 0.2063 - val_loss: 0.1979
Epoch 6/100
160/160 [==============================] - 1s 5ms/step - loss: 0.1983 - val_loss: 0.1853
Epoch 7/100
160/160 [==============================] - 1s 4ms/step - loss: 0.1947 - val_loss: 0.1924
Epoch 8/100
160/160 [==============================] - 1s 5ms/step - loss: 0.1932 - val_loss: 0.1861
Epoch 9/100
160/160 [==============================] - 1s 5ms/step - loss: 0.1900 - val_loss: 0.1830
Epoch 10/100
160/160 [==============================] - 1s 5ms/step - loss: 0.1874 - val_lo

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/NN_2/model_4.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn2_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn2_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[9.99999374e-01 6.25759875e-07]
 [6.02153377e-01 3.97846623e-01]
 [9.66002549e-01 3.39974510e-02]
 ...
 [1.00000000e+00 9.16716182e-28]
 [9.99999997e-01 2.65941634e-09]
 [9.99999486e-01 5.14457726e-07]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0            0.999999          6.257599e-07           0.999999   
1          0            0.602153          3.978466e-01           0.602153   
2          1            0.966003          3.399745e-02           0.966003   
3          1            0.580367          4.196330e-01           0.580367   
4          1            0.113440          8.865602e-01           0.113440   
...      ...                 ...                   ...                ...   
4647       1            0.075658          9.243419e-01           0.075658   
4648       0            1.000000          9.731610e-27           1.000000   
4649       0            1.000000          9.167162e-28           1.000000   
4650       0            1.000000          2.659416e-09           1.000000   
4651       0            0.999999          5.144577e-07           0.999999   

      nn_prediction_phish  nn2_prediction_non  nn2_prediction_phish  
0            6.257599e-07            0.999999          6.257599e-07  
1            3.978466e-01            0.602153          3.978466e-01  
2            3.399745e-02            0.966003          3.399745e-02  
3            4.196330e-01            0.580367          4.196330e-01  
4            8.865602e-01            0.113440          8.865602e-01  
...                   ...                 ...                   ...  
4647         9.243419e-01            0.075658          9.243419e-01  
4648         9.731610e-27            1.000000          9.731610e-27  
4649         9.167162e-28            1.000000          9.167162e-28  
4650         2.659416e-09            1.000000          2.659416e-09  
4651         5.144577e-07            0.999999          5.144577e-07  

[4652 rows x 7 columns]

In [ ]:
output.shape

(4652, 7)

In [ ]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/PhishTank/Base_classifier_result(pre HTML cross)(3).csv', index=False)