In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/PhishTank/URL-HTML/preprocessed_url_features.csv")
urldata


Unnamed: 0                                       Domain  Have IP  \
0               0                             graphicriver.net        0   
1               1                                    ecnavi.jp        0   
2               2                                 hubpages.com        0   
3               3                              extratorrent.cc        0   
4               4                                icicibank.com        0   
...           ...                                          ...      ...   
10332       11932                             sites.google.com        0   
10333       11933                             sites.google.com        0   
10334       11934             habbocreditosparati.blogspot.com        0   
10335       11935  creditiperhabbogratissicuro100.blogspot.com        0   
10336       11936                           aijcs.blogspot.com        0   

       Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0           0           1          1            0             0        0   
1           0           1          1            1             0        0   
2           0           1          1            0             1        0   
3           0           1          3            0             0        0   
4           0           1          3            0             0        0   
...       ...         ...        ...          ...           ...      ...   
10332       0           0          2            0             1        0   
10333       0           0          2            0             0        0   
10334       0           0          0            0             0        1   
10335       0           1          3            0             0        1   
10336       0           1          3            0             0        1   

       Prefix/Suffix  ...  Num Embeds  Num Images  Num Links  Num Titles  \
0                  0  ...           0          49        691          42   
1                  0  ...           0           4         66           3   
2                  0  ...           0           1        100          27   
3                  0  ...           0           0          0           1   
4                  0  ...           0         117        219          23   
...              ...  ...         ...         ...        ...         ...   
10332              0  ...           0           0         17           4   
10333              0  ...           0           6         24           7   
10334              0  ...           0           4         17           4   
10335              0  ...           0           1         23           8   
10336              0  ...           0          19         42           7   

       Num Script  Special Characters  Script To Special Chars Ratio  \
0           13135                6400                       2.052344   
1            2034                 818                       2.486553   
2           32987               10451                       3.156349   
3               0                  52                       0.000000   
4            7944                3468                       2.290657   
...           ...                 ...                            ...   
10332        8146                2203                       3.697685   
10333        8353                2250                       3.712444   
10334        6403                4560                       1.404167   
10335        9817                7292                       1.346270   
10336        2550                3225                       0.790698   

       Script To body Ratio  Body To Special Char Ratio  Label  
0                  0.528869                    0.257690      0  
1                  0.676197                    0.271941      0  
2                  0.836681                    0.265079      0  
3                  0.000000                    0.227074      0  
4                  0.524460                    0.228956      0  
...                     .

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'Domain', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               1           0                    0                 10   
1               4           1                    2                  3   
2               1           1                    2                  2   
3               4           1                    5                  0   
4               2           0                    0                  1   

   Num of digits  Num of spec char  Label  
0              0                25      0  
1             22                13      0  
2              2                 9      0  
3             19                18      0  
4             17                 7      0  

[5 rows x 25 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Have IP              10337 non-null  int64
 1   Have @               10337 non-null  int64
 2   URL Length           10337 non-null  int64
 3   URL Depth            10337 non-null  int64
 4   Redirection          10337 non-null  int64
 5   https Domain         10337 non-null  int64
 6   TinyURL              10337 non-null  int64
 7   Prefix/Suffix        10337 non-null  int64
 8   Have client          10337 non-null  int64
 9   Have admin           10337 non-null  int64
 10  Have login           10337 non-null  int64
 11  Have server          10337 non-null  int64
 12  .php                 10337 non-null  int64
 13  .html                10337 non-null  int64
 14  .info                10337 non-null  int64
 15  .txt                 10337 non-null  int64
 16  .js                  1

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    5828
1    4509
dtype: int64

In [8]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 10337
Non-Phishing: 5828 (56.38% of total)
Phishing: 4509 (43.62% of total)


In [9]:
urldata.describe()

Have IP        Have @    URL Length     URL Depth   Redirection  \
count  10337.0  10337.000000  10337.000000  10337.000000  10337.000000   
mean       0.0      0.025636      0.698462      3.048660      0.013060   
std        0.0      0.158055      0.458948      2.951401      0.113537   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      0.000000      1.000000      0.000000   
50%        0.0      0.000000      1.000000      2.000000      0.000000   
75%        0.0      0.000000      1.000000      4.000000      0.000000   
max        0.0      1.000000      1.000000     18.000000      1.000000   

       https Domain       TinyURL  Prefix/Suffix   Have client    Have admin  \
count  10337.000000  10337.000000   10337.000000  10337.000000  10337.000000   
mean       0.365773      0.068105       0.074877      0.003676      0.008610   
std        0.481670      0.251938       0.263205      0.060522      0.092393   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      0.000000   
50%        0.000000      0.000000       0.000000      0.000000      0.000000   
75%        1.000000      0.000000       0.000000      0.000000      0.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

       ...     .txt           .js          .exe  Num of periods    Is encoded  \
count  ...  10337.0  10337.000000  10337.000000    10337.000000  10337.000000   
mean   ...      0.0      0.009577      0.001935        1.973010      0.110283   
std    ...      0.0      0.097398      0.043946        1.713616      0.313258   
min    ...      0.0      0.000000      0.000000        1.000000      0.000000   
25%    ...      0.0      0.000000      0.000000        1.000000      0.000000   
50%    ...      0.0      0.000000      0.000000        2.000000      0.000000   
75%    ...      0.0      0.000000      0.000000        2.000000      0.000000   
max    ...      0.0      1.000000      1.000000       22.000000      1.000000   

       Num of encoded char  Num of parameters  Num of digits  \
count         10337.000000       10337.000000   10337.000000   
mean              2.770340           0.430396      11.646029   
std              12.289657           1.363932      22.957867   
min               0.000000           0.000000       0.000000   
25%               0.000000           0.000000       1.000000   
50%               0.000000           0.000000       6.000000   
75%               0.000000           0.000000      17.000000   
max             201.000000          40.000000    1374.000000   

       Num of spec char         Label  
count      10337.000000  10337.000000  
mean           7.240882      0.436200  
std           14.025774      0.495937  
min            0.000000      0.000000  
25%            0.000000      0.000000  
50%            3.000000      0.000000  
75%           10.000000      1.000000  
max          356.000000      1.000000  

[8 rows x 25 columns]

In [10]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                0
Have @                 0
URL Length             0
URL Depth              0
Redirection            0
https Domain           0
TinyURL                0
Prefix/Suffix          0
Have client            0
Have admin             0
Have login             0
Have server            0
.php                   0
.html                  0
.info                  0
.txt                   0
.js                    0
.exe                   0
Num of periods         0
Is encoded             0
Num of encoded char    0
Num of parameters      0
Num of digits          0
Num of spec char       0
Label                  0
dtype: int64

In [11]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           0          0            0             1        0   
1        0       0           0          0            0             1        0   
2        0       0           1          6            0             0        0   
3        0       0           0          0            0             1        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    1     0   
3              1            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               1           0                    0                  0   
1               4           0                    0                  0   
2               2           0                    0                  0   
3               1           0                    0                  0   
4               9           0                    0                  0   

   Num of digits  Num of spec char  Label  
0              0                 0      1  
1              0                 0      1  
2              1                 2      0  
3              0                 1      1  
4             19                 3      0  

[5 rows x 25 columns]

In [12]:
import numpy as np
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [13]:

# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(5685, 24) (4652, 24)
(5685,) (4652,)


In [14]:
output = {}
output['labels'] = y_test

**Decision Tree Classifier**

In [16]:
import keras
from matplotlib import pyplot as plt
from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  dtcclassifier = DecisionTreeClassifier(max_depth=5)
  #compile model using mse as a measure of model performance

  dtcclassifier.fit(x_train, y_train)


  y_pred = dtcclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/DTC/model_'+str(n)+'.h5'
  pickle.dump(dtcclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [16]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[324   4]
 [ 12 229]]
Precision: 0.9828
Recall: 0.9502
F1 Score: 0.9662
Validation Accuracy: 0.9718804920913884
model 0 saved
[[323   3]
 [ 18 225]]
Precision: 0.9868
Recall: 0.9259
F1 Score: 0.9554
Validation Accuracy: 0.9630931458699473
model 1 saved
[[301   4]
 [ 25 239]]
Precision: 0.9835
Recall: 0.9053
F1 Score: 0.9428
Validation Accuracy: 0.9490333919156415
model 2 saved
[[316   5]
 [ 20 228]]
Precision: 0.9785
Recall: 0.9194
F1 Score: 0.9480
Validation Accuracy: 0.9560632688927944
model 3 saved
[[308   6]
 [ 16 239]]
Precision: 0.9755
Recall: 0.9373
F1 Score: 0.9560
Validation Accuracy: 0.961335676625659
model 4 saved
[[308   3]
 [ 15 242]]
Precision: 0.9878
Recall: 0.9416
F1 Score: 0.9641
Validation Accuracy: 0.9683098591549296
model 5 saved
[[328   7]
 [ 19 214]]
Precision: 0.9683
Recall: 0.9185
F1 Score: 0.9427
Validation Accuracy: 0.954225352112676
model 6 saved
[[301  10]
 [ 15 242]]
Precision: 0.9603
Recall: 0.9416
F1 Score: 0.9509
Validation Accuracy: 0.9559859154929577


In [17]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/DTC/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['dt_prediction_non'] = [i[0] for i in y_pred_prob];
output['dt_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output



[[0.06711409 0.93288591]
 [0.97468863 0.02531137]
 [0.         1.        ]
 ...
 [0.97468863 0.02531137]
 [0.         1.        ]
 [0.97468863 0.02531137]]


labels  dt_prediction_non  dt_prediction_phish
0          1           0.067114             0.932886
1          0           0.974689             0.025311
2          1           0.000000             1.000000
3          0           0.974689             0.025311
4          1           0.000000             1.000000
...      ...                ...                  ...
4647       0           0.974689             0.025311
4648       0           1.000000             0.000000
4649       0           0.974689             0.025311
4650       1           0.000000             1.000000
4651       0           0.974689             0.025311

[4652 rows x 3 columns]

**KNN**

In [19]:
import keras

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_knn(x_train, x_val, y_train, y_val, opt, n):
  knnclassifier = KNeighborsClassifier(n_neighbors=7, weights='uniform', algorithm='kd_tree', leaf_size=5)
  #compile model using mse as a measure of model performance
  knnclassifier.fit(x_train, y_train)

  y_pred = knnclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/KNN/model_'+str(n)+'.h5'
  pickle.dump(knnclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [20]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_knn(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[321   7]
 [ 11 230]]
Precision: 0.9705
Recall: 0.9544
F1 Score: 0.9623
Validation Accuracy: 0.968365553602812
model 0 saved
[[317   9]
 [  6 237]]
Precision: 0.9634
Recall: 0.9753
F1 Score: 0.9693
Validation Accuracy: 0.9736379613356766
model 1 saved
[[295  10]
 [ 15 249]]
Precision: 0.9614
Recall: 0.9432
F1 Score: 0.9522
Validation Accuracy: 0.9560632688927944
model 2 saved
[[316   5]
 [  6 242]]
Precision: 0.9798
Recall: 0.9758
F1 Score: 0.9778
Validation Accuracy: 0.9806678383128296
model 3 saved
[[309   5]
 [  9 246]]
Precision: 0.9801
Recall: 0.9647
F1 Score: 0.9723
Validation Accuracy: 0.9753954305799648
model 4 saved
[[309   2]
 [  6 251]]
Precision: 0.9921
Recall: 0.9767
F1 Score: 0.9843
Validation Accuracy: 0.9859154929577465
model 5 saved
[[326   9]
 [ 12 221]]
Precision: 0.9609
Recall: 0.9485
F1 Score: 0.9546
Validation Accuracy: 0.9630281690140845
model 6 saved
[[307   4]
 [ 12 245]]
Precision: 0.9839
Recall: 0.9533
F1 Score: 0.9684
Validation Accuracy: 0.971830985915493


In [18]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/KNN/model_5.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['knn_prediction_non'] = [i[0] for i in y_pred_prob];
output['knn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.14285714 0.85714286]
 [1.         0.        ]
 [0.         1.        ]
 ...
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          1           0.067114             0.932886            0.142857   
1          0           0.974689             0.025311            1.000000   
2          1           0.000000             1.000000            0.000000   
3          0           0.974689             0.025311            1.000000   
4          1           0.000000             1.000000            0.000000   
...      ...                ...                  ...                 ...   
4647       0           0.974689             0.025311            1.000000   
4648       0           1.000000             0.000000            1.000000   
4649       0           0.974689             0.025311            1.000000   
4650       1           0.000000             1.000000            0.000000   
4651       0           0.974689             0.025311            1.000000   

      knn_prediction_phish  
0                 0.857143  
1                 0.000000  
2                 1.000000  
3                 0.000000  
4                 1.000000  
...                    ...  
4647              0.000000  
4648              0.000000  
4649              0.000000  
4650              1.000000  
4651              0.000000  

[4652 rows x 5 columns]

**XGB Classifier**

In [23]:
import keras

from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_xgb(x_train, x_val, y_train, y_val, opt, n):
  xgbclassifier = XGBClassifier(n_neighbors=5)
  #compile model using mse as a measure of model performance
  xgbclassifier.fit(x_train, y_train)

  y_pred = xgbclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/XGBoost/model_'+str(n)+'.h5'
  pickle.dump(xgbclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_xgb(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[311   3]
 [  4 251]]
Precision: 0.9882
Recall: 0.9843
F1 Score: 0.9862
Validation Accuracy: 0.9876977152899824
model 0 saved
[[315   5]
 [  7 242]]
Precision: 0.9798
Recall: 0.9719
F1 Score: 0.9758
Validation Accuracy: 0.9789103690685413
model 1 saved
[[331  10]
 [  4 224]]
Precision: 0.9573
Recall: 0.9825
F1 Score: 0.9697
Validation Accuracy: 0.9753954305799648
model 2 saved
[[302   2]
 [  9 256]]
Precision: 0.9922
Recall: 0.9660
F1 Score: 0.9790
Validation Accuracy: 0.9806678383128296
model 3 saved
[[313   4]
 [  8 244]]
Precision: 0.9839
Recall: 0.9683
F1 Score: 0.9760
Validation Accuracy: 0.9789103690685413
model 4 saved
[[306   4]
 [ 11 247]]
Precision: 0.9841
Recall: 0.9574
F1 Score: 0.9705
Validation Accuracy: 0.9735915492957746
model 5 saved
[[302   7]
 [  4 255]]
Precision: 0.9733
Recall: 0.9846
F1 Score: 0.9789
Validation Accuracy: 0.9806338028169014
model 6 saved
[[318   4]
 [  4 242]]
Precision: 0.9837
Recall: 0.9837
F1 Score: 0.9837
Validation Accuracy: 0.985915492957746

In [24]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/XGBoost/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['XGB_prediction_non'] = [i[0] for i in y_pred_prob];
output['XGB_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.9967833  0.0032167 ]
 [0.9942463  0.00575368]
 [0.51830703 0.48169297]
 ...
 [0.98955625 0.01044375]
 [0.00659215 0.99340785]
 [0.00123942 0.9987606 ]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          0           0.974689             0.025311            1.000000   
1          0           0.974689             0.025311            1.000000   
2          1           0.067114             0.932886            0.857143   
3          1           0.000000             1.000000            0.000000   
4          1           0.000000             1.000000            0.000000   
...      ...                ...                  ...                 ...   
4647       0           0.974689             0.025311            1.000000   
4648       0           0.974689             0.025311            1.000000   
4649       0           0.974689             0.025311            1.000000   
4650       1           0.000000             1.000000            0.000000   
4651       1           0.000000             1.000000            0.000000   

      knn_prediction_phish  XGB_prediction_non  XGB_prediction_phish  
0                 0.000000            0.996783              0.003217  
1                 0.000000            0.994246              0.005754  
2                 0.142857            0.518307              0.481693  
3                 1.000000            0.000809              0.999191  
4                 1.000000            0.000622              0.999378  
...                    ...                 ...                   ...  
4647              0.000000            0.992907              0.007093  
4648              0.000000            0.993572              0.006428  
4649              0.000000            0.989556              0.010444  
4650              1.000000            0.006592              0.993408  
4651              1.000000            0.001239              0.998761  

[4652 rows x 7 columns]

In [25]:
output.shape


(4652, 7)

In [26]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/PhishTank/Base_classifier_result(pre URL cross).csv', index=False)