In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/PhishTank/URL-HTML/preprocessed_url_features.csv")
urldata


Unnamed: 0                                       Domain  Have IP  \
0               0                             graphicriver.net        0   
1               1                                    ecnavi.jp        0   
2               2                                 hubpages.com        0   
3               3                              extratorrent.cc        0   
4               4                                icicibank.com        0   
...           ...                                          ...      ...   
10332       11932                             sites.google.com        0   
10333       11933                             sites.google.com        0   
10334       11934             habbocreditosparati.blogspot.com        0   
10335       11935  creditiperhabbogratissicuro100.blogspot.com        0   
10336       11936                           aijcs.blogspot.com        0   

       Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0           0           1          1            0             0        0   
1           0           1          1            1             0        0   
2           0           1          1            0             1        0   
3           0           1          3            0             0        0   
4           0           1          3            0             0        0   
...       ...         ...        ...          ...           ...      ...   
10332       0           0          2            0             1        0   
10333       0           0          2            0             0        0   
10334       0           0          0            0             0        1   
10335       0           1          3            0             0        1   
10336       0           1          3            0             0        1   

       Prefix/Suffix  ...  Num Embeds  Num Images  Num Links  Num Titles  \
0                  0  ...           0          49        691          42   
1                  0  ...           0           4         66           3   
2                  0  ...           0           1        100          27   
3                  0  ...           0           0          0           1   
4                  0  ...           0         117        219          23   
...              ...  ...         ...         ...        ...         ...   
10332              0  ...           0           0         17           4   
10333              0  ...           0           6         24           7   
10334              0  ...           0           4         17           4   
10335              0  ...           0           1         23           8   
10336              0  ...           0          19         42           7   

       Num Script  Special Characters  Script To Special Chars Ratio  \
0           13135                6400                       2.052344   
1            2034                 818                       2.486553   
2           32987               10451                       3.156349   
3               0                  52                       0.000000   
4            7944                3468                       2.290657   
...           ...                 ...                            ...   
10332        8146                2203                       3.697685   
10333        8353                2250                       3.712444   
10334        6403                4560                       1.404167   
10335        9817                7292                       1.346270   
10336        2550                3225                       0.790698   

       Script To body Ratio  Body To Special Char Ratio  Label  
0                  0.528869                    0.257690      0  
1                  0.676197                    0.271941      0  
2                  0.836681                    0.265079      0  
3                  0.000000                    0.227074      0  
4                  0.524460                    0.228956      0  
...                     .

In [ ]:
urldata.columns

Index(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [ ]:
urldata = urldata.drop(['Unnamed: 0', 'Domain', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio'], axis = 1).copy()

urldata.shape
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               1           0                    0                 10   
1               4           1                    2                  3   
2               1           1                    2                  2   
3               4           1                    5                  0   
4               2           0                    0                  1   

   Num of digits  Num of spec char  Label  
0              0                25      0  
1             22                13      0  
2              2                 9      0  
3             19                18      0  
4             17                 7      0  

[5 rows x 25 columns]

In [ ]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Have IP              10337 non-null  int64
 1   Have @               10337 non-null  int64
 2   URL Length           10337 non-null  int64
 3   URL Depth            10337 non-null  int64
 4   Redirection          10337 non-null  int64
 5   https Domain         10337 non-null  int64
 6   TinyURL              10337 non-null  int64
 7   Prefix/Suffix        10337 non-null  int64
 8   Have client          10337 non-null  int64
 9   Have admin           10337 non-null  int64
 10  Have login           10337 non-null  int64
 11  Have server          10337 non-null  int64
 12  .php                 10337 non-null  int64
 13  .html                10337 non-null  int64
 14  .info                10337 non-null  int64
 15  .txt                 10337 non-null  int64
 16  .js                  1

In [ ]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    5828
1    4509
dtype: int64

In [ ]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 10337
Non-Phishing: 5828 (56.38% of total)
Phishing: 4509 (43.62% of total)


In [ ]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                0
Have @                 0
URL Length             0
URL Depth              0
Redirection            0
https Domain           0
TinyURL                0
Prefix/Suffix          0
Have client            0
Have admin             0
Have login             0
Have server            0
.php                   0
.html                  0
.info                  0
.txt                   0
.js                    0
.exe                   0
Num of periods         0
Is encoded             0
Num of encoded char    0
Num of parameters      0
Num of digits          0
Num of spec char       0
Label                  0
dtype: int64

In [ ]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          2            0             0        0   
1        0       0           0          1            0             1        0   
2        0       0           0          0            0             1        0   
3        0       0           1         10            0             0        0   
4        0       0           0          3            0             1        0   

   Prefix/Suffix  Have client  Have admin  ...  .txt  .js  .exe  \
0              0            0           0  ...     0    0     0   
1              0            0           0  ...     0    0     0   
2              0            0           0  ...     0    0     0   
3              0            0           0  ...     0    0     0   
4              0            0           0  ...     0    0     0   

   Num of periods  Is encoded  Num of encoded char  Num of parameters  \
0               2           0                    0                  5   
1               1           0                    0                  0   
2               2           0                    0                  0   
3               1           0                    0                  0   
4               2           0                    0                  0   

   Num of digits  Num of spec char  Label  
0             27                11      0  
1              0                 0      1  
2              3                 0      1  
3             22                 0      0  
4              0                 0      1  

[5 rows x 25 columns]

In [ ]:
import numpy as np
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [ ]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(5685, 24) (4652, 24)
(5685,) (4652,)


In [ ]:
output = {}
output['labels'] = y_test

**MLP**

In [ ]:
import keras

from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pickle

def model_mlp(x_train, x_val, y_train, y_val, opt, n):
  mlpclassifier = MLPClassifier(alpha=0.0001, hidden_layer_sizes=([100,100,100]))
  #compile model using mse as a measure of model performance
  mlpclassifier.fit(x_train, y_train)

  y_pred = mlpclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/MLP/model_'+str(n)+'.h5'
  pickle.dump(mlpclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_mlp(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[312   1]
 [  4 252]]
Precision: 0.9960
Recall: 0.9844
F1 Score: 0.9902
Validation Accuracy: 0.9912126537785588
model 0 saved
[[324   6]
 [  3 236]]
Precision: 0.9752
Recall: 0.9874
F1 Score: 0.9813
Validation Accuracy: 0.984182776801406
model 1 saved
[[318   5]
 [  3 243]]
Precision: 0.9798
Recall: 0.9878
F1 Score: 0.9838
Validation Accuracy: 0.9859402460456942
model 2 saved
[[323  12]
 [  7 227]]
Precision: 0.9498
Recall: 0.9701
F1 Score: 0.9598
Validation Accuracy: 0.9666080843585237
model 3 saved
[[321   4]
 [  3 241]]
Precision: 0.9837
Recall: 0.9877
F1 Score: 0.9857
Validation Accuracy: 0.9876977152899824
model 4 saved
[[296   5]
 [  3 264]]
Precision: 0.9814
Recall: 0.9888
F1 Score: 0.9851
Validation Accuracy: 0.9859154929577465
model 5 saved
[[334   0]
 [ 10 224]]
Precision: 1.0000
Recall: 0.9573
F1 Score: 0.9782
Validation Accuracy: 0.9823943661971831
model 6 saved
[[316   2]
 [  9 241]]
Precision: 0.9918
Recall: 0.9640
F1 Score: 0.9777
Validation Accuracy: 0.9806338028169014

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/MLP/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['mlp_prediction_non'] = [i[0] for i in y_pred_prob];
output['mlp_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[9.93201827e-01 6.79817348e-03]
 [9.99954244e-01 4.57560327e-05]
 [9.97641069e-01 2.35893122e-03]
 ...
 [9.99999997e-01 3.34157655e-09]
 [9.98309614e-01 1.69038601e-03]
 [2.22044605e-16 1.00000000e+00]]


labels  mlp_prediction_non  mlp_prediction_phish
0          0        9.932018e-01          6.798173e-03
1          0        9.999542e-01          4.575603e-05
2          0        9.976411e-01          2.358931e-03
3          0        9.875554e-01          1.244462e-02
4          0        9.999881e-01          1.189933e-05
...      ...                 ...                   ...
4647       1        2.401408e-10          1.000000e+00
4648       0        9.999578e-01          4.222117e-05
4649       0        1.000000e+00          3.341577e-09
4650       0        9.983096e-01          1.690386e-03
4651       1        2.220446e-16          1.000000e+00

[4652 rows x 3 columns]

**Neural Network**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_aa(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]
  # print("check point")
  #create model
  model = Sequential()
  model.add(Dense(30, activation='relu', input_shape=(n_cols,)))
  model.add(Dense(10, activation='relu'))

  model.add(Dense(1, activation = 'sigmoid'))
  # softmax
  #compile model using mse as a measure of model performance
  model.compile(optimizer = opt, loss= 'binary_crossentropy', metrics=["accuracy"])

  history = model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/NN/model_'+str(n)+'.h5'
  pickle.dump(model, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_aa(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
160/160 [==============================] - 5s 6ms/step - loss: 1.2054 - accuracy: 0.5420 - val_loss: 0.4943 - val_accuracy: 0.8946
Epoch 2/100
160/160 [==============================] - 1s 5ms/step - loss: 0.3750 - accuracy: 0.9081 - val_loss: 0.2795 - val_accuracy: 0.9174
Epoch 3/100
160/160 [==============================] - 1s 5ms/step - loss: 0.2278 - accuracy: 0.9345 - val_loss: 0.1745 - val_accuracy: 0.9596
Epoch 4/100
160/160 [==============================] - 1s 5ms/step - loss: 0.1630 - accuracy: 0.9517 - val_loss: 0.1322 - val_accuracy: 0.9649
Epoch 5/100
160/160 [==============================] - 1s 5ms/step - loss: 0.1343 - accuracy: 0.9617 - val_loss: 0.1098 - val_accuracy: 0.9719
Epoch 6/100
160/160 [==============================] - 1s 4ms/step - loss: 0.1188 - accuracy: 0.9650 - val_loss: 0.0963 - val_accuracy: 0.9736
Epoch 7/100
160/160 [==============================] - 1s 4ms/step - loss: 0.1100 - accuracy: 0.9660 - val_loss: 0.0867 - val_accuracy: 0.9754

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/NN/model_9.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[9.93201827e-01 6.79817348e-03]
 [9.99954244e-01 4.57560327e-05]
 [9.97641069e-01 2.35893122e-03]
 ...
 [9.99999997e-01 3.34157655e-09]
 [9.98309614e-01 1.69038601e-03]
 [2.22044605e-16 1.00000000e+00]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0        9.932018e-01          6.798173e-03       9.932018e-01   
1          0        9.999542e-01          4.575603e-05       9.999542e-01   
2          0        9.976411e-01          2.358931e-03       9.976411e-01   
3          0        9.875554e-01          1.244462e-02       9.875554e-01   
4          0        9.999881e-01          1.189933e-05       9.999881e-01   
...      ...                 ...                   ...                ...   
4647       1        2.401408e-10          1.000000e+00       2.401408e-10   
4648       0        9.999578e-01          4.222117e-05       9.999578e-01   
4649       0        1.000000e+00          3.341577e-09       1.000000e+00   
4650       0        9.983096e-01          1.690386e-03       9.983096e-01   
4651       1        2.220446e-16          1.000000e+00       2.220446e-16   

      nn_prediction_phish  
0            6.798173e-03  
1            4.575603e-05  
2            2.358931e-03  
3            1.244462e-02  
4            1.189933e-05  
...                   ...  
4647         1.000000e+00  
4648         4.222117e-05  
4649         3.341577e-09  
4650         1.690386e-03  
4651         1.000000e+00  

[4652 rows x 5 columns]

**Neural Network 2**

In [ ]:

import keras
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

def model_a(x_train, x_val, y_train, y_val, opt, n, early_stopping_monitor):

  n_cols = x_train.shape[1]

  #create model
  model_2 = Sequential()
  model_2.add(Dense(30, activation='sigmoid', input_shape=(n_cols,)))
  model_2.add(Dense(25, activation='sigmoid'))
  model_2.add(Dense(20, activation='sigmoid'))
  model_2.add(Dense(15, activation='sigmoid'))
  model_2.add(Dense(10, activation='sigmoid'))
  model_2.add(Dense(1, activation = 'sigmoid'))

  #compile model using mse as a measure of model performance
  model_2.compile(optimizer='adam', loss='mean_squared_error')



  history = model_2.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping_monitor])


  # plt.plot(history.history['loss'])
  # plt.plot(history.history['val_loss'])
  # plt.title('model loss')
  # plt.ylabel('Loss')
  # plt.xlabel('Epoch')
  # plt.legend(['Training Loss', 'Validation Loss'], loc='upper right')
  # plt.show()


  print('Validation Accuracy: ')
  # Predicting the Test set results
  y_pred = model_2.predict(x_val)
  y_pred = (y_pred > 0.5)


  print(classification_report(y_val, y_pred))

  # Model Accuracy, how often is the classifier correct?
  print("Accuracy:",metrics.accuracy_score(y_val, y_pred))

  # Creating the Confusion Matrix
  cm = confusion_matrix(y_val, y_pred)
  print(cm)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/NN_2/model_'+str(n)+'.h5'
  pickle.dump(model_2, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)



In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_a(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n, early_stopping_monitor)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)



Epoch 1/100
160/160 [==============================] - 1s 4ms/step - loss: 0.2617 - val_loss: 0.2414
Epoch 2/100
160/160 [==============================] - 0s 3ms/step - loss: 0.1866 - val_loss: 0.1074
Epoch 3/100
160/160 [==============================] - 0s 3ms/step - loss: 0.0777 - val_loss: 0.0526
Epoch 4/100
160/160 [==============================] - 0s 3ms/step - loss: 0.0548 - val_loss: 0.0436
Epoch 5/100
160/160 [==============================] - 0s 3ms/step - loss: 0.0491 - val_loss: 0.0394
Epoch 6/100
160/160 [==============================] - 0s 3ms/step - loss: 0.0469 - val_loss: 0.0388
Epoch 7/100
160/160 [==============================] - 1s 3ms/step - loss: 0.0453 - val_loss: 0.0353
Epoch 8/100
160/160 [==============================] - 1s 4ms/step - loss: 0.0440 - val_loss: 0.0341
Epoch 9/100
160/160 [==============================] - 1s 4ms/step - loss: 0.0426 - val_loss: 0.0339
Epoch 10/100
160/160 [==============================] - 1s 5ms/step - loss: 0.0404 - val_lo

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL/NN_2/model_8.h5'

loaded_model = pickle.load(open(filename, 'rb'))

def predict_prob(number):
  return [number[0],1-number[0]]

y_prob = np.array(list(map(predict_prob, loaded_model.predict(x_test))))
y_prob 

# y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['nn2_prediction_non'] = [i[0] for i in y_pred_prob];
output['nn2_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output

[[9.93201827e-01 6.79817348e-03]
 [9.99954244e-01 4.57560327e-05]
 [9.97641069e-01 2.35893122e-03]
 ...
 [9.99999997e-01 3.34157655e-09]
 [9.98309614e-01 1.69038601e-03]
 [2.22044605e-16 1.00000000e+00]]


labels  mlp_prediction_non  mlp_prediction_phish  nn_prediction_non  \
0          0        9.932018e-01          6.798173e-03       9.932018e-01   
1          0        9.999542e-01          4.575603e-05       9.999542e-01   
2          0        9.976411e-01          2.358931e-03       9.976411e-01   
3          0        9.875554e-01          1.244462e-02       9.875554e-01   
4          0        9.999881e-01          1.189933e-05       9.999881e-01   
...      ...                 ...                   ...                ...   
4647       1        2.401408e-10          1.000000e+00       2.401408e-10   
4648       0        9.999578e-01          4.222117e-05       9.999578e-01   
4649       0        1.000000e+00          3.341577e-09       1.000000e+00   
4650       0        9.983096e-01          1.690386e-03       9.983096e-01   
4651       1        2.220446e-16          1.000000e+00       2.220446e-16   

      nn_prediction_phish  nn2_prediction_non  nn2_prediction_phish  
0            6.798173e-03        9.932018e-01          6.798173e-03  
1            4.575603e-05        9.999542e-01          4.575603e-05  
2            2.358931e-03        9.976411e-01          2.358931e-03  
3            1.244462e-02        9.875554e-01          1.244462e-02  
4            1.189933e-05        9.999881e-01          1.189933e-05  
...                   ...                 ...                   ...  
4647         1.000000e+00        2.401408e-10          1.000000e+00  
4648         4.222117e-05        9.999578e-01          4.222117e-05  
4649         3.341577e-09        1.000000e+00          3.341577e-09  
4650         1.690386e-03        9.983096e-01          1.690386e-03  
4651         1.000000e+00        2.220446e-16          1.000000e+00  

[4652 rows x 7 columns]

In [ ]:
output.shape

In [ ]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/PhishTank/Base_classifier_result(pre URL cross)(3).csv', index=False)