In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/PhishTank/URL-HTML/preprocessed_url_features.csv")
urldata


Unnamed: 0                                       Domain  Have IP  \
0               0                             graphicriver.net        0   
1               1                                    ecnavi.jp        0   
2               2                                 hubpages.com        0   
3               3                              extratorrent.cc        0   
4               4                                icicibank.com        0   
...           ...                                          ...      ...   
10332       11932                             sites.google.com        0   
10333       11933                             sites.google.com        0   
10334       11934             habbocreditosparati.blogspot.com        0   
10335       11935  creditiperhabbogratissicuro100.blogspot.com        0   
10336       11936                           aijcs.blogspot.com        0   

       Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0           0           1          1            0             0        0   
1           0           1          1            1             0        0   
2           0           1          1            0             1        0   
3           0           1          3            0             0        0   
4           0           1          3            0             0        0   
...       ...         ...        ...          ...           ...      ...   
10332       0           0          2            0             1        0   
10333       0           0          2            0             0        0   
10334       0           0          0            0             0        1   
10335       0           1          3            0             0        1   
10336       0           1          3            0             0        1   

       Prefix/Suffix  ...  Num Embeds  Num Images  Num Links  Num Titles  \
0                  0  ...           0          49        691          42   
1                  0  ...           0           4         66           3   
2                  0  ...           0           1        100          27   
3                  0  ...           0           0          0           1   
4                  0  ...           0         117        219          23   
...              ...  ...         ...         ...        ...         ...   
10332              0  ...           0           0         17           4   
10333              0  ...           0           6         24           7   
10334              0  ...           0           4         17           4   
10335              0  ...           0           1         23           8   
10336              0  ...           0          19         42           7   

       Num Script  Special Characters  Script To Special Chars Ratio  \
0           13135                6400                       2.052344   
1            2034                 818                       2.486553   
2           32987               10451                       3.156349   
3               0                  52                       0.000000   
4            7944                3468                       2.290657   
...           ...                 ...                            ...   
10332        8146                2203                       3.697685   
10333        8353                2250                       3.712444   
10334        6403                4560                       1.404167   
10335        9817                7292                       1.346270   
10336        2550                3225                       0.790698   

       Script To body Ratio  Body To Special Char Ratio  Label  
0                  0.528869                    0.257690      0  
1                  0.676197                    0.271941      0  
2                  0.836681                    0.265079      0  
3                  0.000000                    0.227074      0  
4                  0.524460                    0.228956      0  
...                     .

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                  21444   
1       1           0            0             1                   1075   
2       1           0            0             1                   4531   
3       1           0            0             1                     32   
4       1           0            0             1                   4880   

   number of sentences  number of html tags  number of whitespace  \
0                 1853                 3247                     0   
1                  136                  236                     0   
2                 2634                  486                     0   
3                    9                    8                     0   
4                  981                 1412                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1        24836  ...           0          49        691   
1            1         3008  ...           0           4         66   
2            1        39426  ...           0           1        100   
3            0          229  ...           0           0          0   
4            1        15147  ...           0         117        219   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0          42       13135                6400                       2.052344   
1           3        2034                 818                       2.486553   
2          27       32987               10451                       3.156349   
3           1           0                  52                       0.000000   
4          23        7944                3468                       2.290657   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.528869                    0.257690      0  
1              0.676197                    0.271941      0  
2              0.836681                    0.265079      0  
3              0.000000                    0.227074      0  
4              0.524460                    0.228956      0  

[5 rows x 21 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   iFrame                         10337 non-null  int64  
 1   Mouse Over                     10337 non-null  int64  
 2   Right Click                    10337 non-null  int64  
 3   Web Forwards                   10337 non-null  int64  
 4   Number of page tokens          10337 non-null  int64  
 5   number of sentences            10337 non-null  int64  
 6   number of html tags            10337 non-null  int64  
 7   number of whitespace           10337 non-null  int64  
 8   url Is Live                    10337 non-null  int64  
 9   HTML Length                    10337 non-null  int64  
 10  Num Objects                    10337 non-null  int64  
 11  Num Embeds                     10337 non-null  int64  
 12  Num Images                     10337 non-null 

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    5828
1    4509
dtype: int64

In [8]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 10337
Non-Phishing: 5828 (56.38% of total)
Phishing: 4509 (43.62% of total)


In [9]:
urldata.describe()

iFrame    Mouse Over   Right Click  Web Forwards  \
count  10337.000000  10337.000000  10337.000000  10337.000000   
mean       0.999807      0.000290      0.000097      0.952307   
std        0.013909      0.017034      0.009836      0.213126   
min        0.000000      0.000000      0.000000      0.000000   
25%        1.000000      0.000000      0.000000      1.000000   
50%        1.000000      0.000000      0.000000      1.000000   
75%        1.000000      0.000000      0.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000   

       Number of page tokens  number of sentences  number of html tags  \
count           10337.000000          10337.00000         10337.000000   
mean             3198.006965           1661.99526           353.834478   
std              5664.530703           3873.01854           671.004262   
min                 1.000000              1.00000            -1.000000   
25%               247.000000             16.00000            19.000000   
50%              1100.000000            293.00000           110.000000   
75%              3835.000000           1679.00000           413.000000   
max             79130.000000          55924.00000          8760.000000   

       number of whitespace   url Is Live   HTML Length  ...    Num Embeds  \
count               10337.0  10337.000000  1.033700e+04  ...  10337.000000   
mean                    0.0      0.549386  4.422439e+04  ...      0.000871   
std                     0.0      0.505680  1.154572e+05  ...      0.029496   
min                     0.0     -1.000000  0.000000e+00  ...      0.000000   
25%                     0.0      0.000000  1.427000e+03  ...      0.000000   
50%                     0.0      1.000000  9.675000e+03  ...      0.000000   
75%                     0.0      1.000000  3.381200e+04  ...      0.000000   
max                     0.0      1.000000  2.450669e+06  ...      1.000000   

         Num Images     Num Links    Num Titles    Num Script  \
count  10337.000000  10337.000000  10337.000000  1.033700e+04   
mean      10.595627     54.459998      6.805553  2.805686e+04   
std       33.772343    105.521327     25.206153  9.871191e+04   
min        0.000000      0.000000      0.000000  0.000000e+00   
25%        0.000000      1.000000      1.000000  0.000000e+00   
50%        1.000000      5.000000      1.000000  5.162000e+03   
75%        5.000000     54.000000      3.000000  1.665200e+04   
max      688.000000   2078.000000   1042.000000  2.450669e+06   

       Special Characters  Script To Special Chars Ratio  \
count        10337.000000                   10337.000000   
mean         10823.200445                       3.695922   
std          28279.638035                      21.605333   
min              0.000000                       0.000000   
25%            421.000000                       0.000000   
50%           2142.000000                       1.916015   
75%           8705.000000                       2.737587   
max         631036.000000                     519.266010   

       Script To body Ratio  Body To Special Char Ratio         Label  
count          10337.000000                10337.000000  10337.000000  
mean               0.443764                    0.241135      0.436200  
std                0.368330                    0.075312      0.495937  
min                0.000000                   -0.000119      0.000000  
25%                0.000000                    0.209596      0.000000  
50%                0.488331                    0.254868      0.000000  
75%                0.790474                    0.295025      1.000000  
max                1.142857                    0.605483      1.000000  

[8 rows x 21 columns]

In [10]:
#checking the data for null or missing values
urldata.isnull().sum()

iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page tokens            0
number of sentences              0
number of html tags              0
number of whitespace             0
url Is Live                      0
HTML Length                      0
Num Objects                      0
Num Embeds                       0
Num Images                       0
Num Links                        0
Num Titles                       0
Num Script                       0
Special Characters               0
Script To Special Chars Ratio    0
Script To body Ratio             0
Body To Special Char Ratio       0
Label                            0
dtype: int64

In [11]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                   3835   
1       1           0            0             1                    108   
2       1           0            0             1                   2661   
3       1           0            0             1                    247   
4       1           0            0             1                   3494   

   number of sentences  number of html tags  number of whitespace  \
0                10042                  754                     0   
1                   41                    9                     0   
2                  579                  115                     0   
3                   16                   19                     0   
4                 1314                  433                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            0        43888  ...           0          11        190   
1            1         1050  ...           0           0          0   
2            1        31025  ...           0           4         14   
3            0         1427  ...           0           1          2   
4            1        19878  ...           0           2         88   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0          20       13472                9798                       1.374974   
1           0        1050                 372                       2.822581   
2           2       23049                7291                       3.161295   
3           3           0                 421                       0.000000   
4           1        6299                3944                       1.597110   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.306963                    0.223250      0  
1              1.000000                    0.354286      0  
2              0.742917                    0.235004      1  
3              0.000000                    0.295025      1  
4              0.316883                    0.198410      0  

[5 rows x 21 columns]

In [12]:
import numpy as np
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [13]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(5685, 20) (4652, 20)
(5685,) (4652,)


In [14]:
output = {}
output['labels'] = y_test

**Decision Tree Classifier**

In [15]:
import keras
from matplotlib import pyplot as plt
from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  dtcclassifier = DecisionTreeClassifier(max_depth=5)
  #compile model using mse as a measure of model performance

  dtcclassifier.fit(x_train, y_train)


  y_pred = dtcclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/DTC/model_'+str(n)+'.h5'
  pickle.dump(dtcclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [16]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[286  38]
 [ 24 221]]
Precision: 0.8533
Recall: 0.9020
F1 Score: 0.8770
Validation Accuracy: 0.8910369068541301
model 0 saved
[[282  17]
 [ 56 214]]
Precision: 0.9264
Recall: 0.7926
F1 Score: 0.8543
Validation Accuracy: 0.8717047451669596
model 1 saved
[[308  23]
 [ 22 216]]
Precision: 0.9038
Recall: 0.9076
F1 Score: 0.9057
Validation Accuracy: 0.9209138840070299
model 2 saved
[[299  19]
 [ 23 228]]
Precision: 0.9231
Recall: 0.9084
F1 Score: 0.9157
Validation Accuracy: 0.9261862917398945
model 3 saved
[[286  30]
 [ 27 226]]
Precision: 0.8828
Recall: 0.8933
F1 Score: 0.8880
Validation Accuracy: 0.8998242530755711
model 4 saved
[[302  25]
 [ 31 210]]
Precision: 0.8936
Recall: 0.8714
F1 Score: 0.8824
Validation Accuracy: 0.9014084507042254
model 5 saved
[[263  27]
 [ 18 260]]
Precision: 0.9059
Recall: 0.9353
F1 Score: 0.9204
Validation Accuracy: 0.920774647887324
model 6 saved
[[302  27]
 [ 25 214]]
Precision: 0.8880
Recall: 0.8954
F1 Score: 0.8917
Validation Accuracy: 0.9084507042253521

In [17]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/DTC/model_3.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['dt_prediction_non'] = [i[0] for i in y_pred_prob];
output['dt_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output



[[0.96565774 0.03434226]
 [0.0053135  0.9946865 ]
 [0.96565774 0.03434226]
 ...
 [0.96565774 0.03434226]
 [0.96067416 0.03932584]
 [0.         1.        ]]


labels  dt_prediction_non  dt_prediction_phish
0          0           0.965658             0.034342
1          1           0.005313             0.994687
2          0           0.965658             0.034342
3          0           0.965658             0.034342
4          0           0.821229             0.178771
...      ...                ...                  ...
4647       0           0.965658             0.034342
4648       1           0.056225             0.943775
4649       0           0.965658             0.034342
4650       0           0.960674             0.039326
4651       1           0.000000             1.000000

[4652 rows x 3 columns]

**KNN**

In [19]:
import keras

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_knn(x_train, x_val, y_train, y_val, opt, n):
  knnclassifier = KNeighborsClassifier(n_neighbors=7, weights='uniform', algorithm='kd_tree', leaf_size=5)
  #compile model using mse as a measure of model performance
  knnclassifier.fit(x_train, y_train)

  y_pred = knnclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/KNN/model_'+str(n)+'.h5'
  pickle.dump(knnclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [20]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_knn(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[309  15]
 [ 25 220]]
Precision: 0.9362
Recall: 0.8980
F1 Score: 0.9167
Validation Accuracy: 0.929701230228471
model 0 saved
[[283  16]
 [ 40 230]]
Precision: 0.9350
Recall: 0.8519
F1 Score: 0.8915
Validation Accuracy: 0.9015817223198594
model 1 saved
[[319  12]
 [ 18 220]]
Precision: 0.9483
Recall: 0.9244
F1 Score: 0.9362
Validation Accuracy: 0.9472759226713533
model 2 saved
[[307  11]
 [ 36 215]]
Precision: 0.9513
Recall: 0.8566
F1 Score: 0.9015
Validation Accuracy: 0.9173989455184535
model 3 saved
[[304  12]
 [ 21 232]]
Precision: 0.9508
Recall: 0.9170
F1 Score: 0.9336
Validation Accuracy: 0.9420035149384886
model 4 saved
[[313  14]
 [ 25 216]]
Precision: 0.9391
Recall: 0.8963
F1 Score: 0.9172
Validation Accuracy: 0.9313380281690141
model 5 saved
[[281   9]
 [ 27 251]]
Precision: 0.9654
Recall: 0.9029
F1 Score: 0.9331
Validation Accuracy: 0.9366197183098591
model 6 saved
[[314  15]
 [ 30 209]]
Precision: 0.9330
Recall: 0.8745
F1 Score: 0.9028
Validation Accuracy: 0.920774647887324


In [21]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/KNN/model_2.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['knn_prediction_non'] = [i[0] for i in y_pred_prob];
output['knn_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 ...
 [1.         0.        ]
 [1.         0.        ]
 [0.28571429 0.71428571]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          0           0.965658             0.034342            1.000000   
1          1           0.005313             0.994687            0.000000   
2          0           0.965658             0.034342            1.000000   
3          0           0.965658             0.034342            1.000000   
4          0           0.821229             0.178771            1.000000   
...      ...                ...                  ...                 ...   
4647       0           0.965658             0.034342            1.000000   
4648       1           0.056225             0.943775            0.000000   
4649       0           0.965658             0.034342            1.000000   
4650       0           0.960674             0.039326            1.000000   
4651       1           0.000000             1.000000            0.285714   

      knn_prediction_phish  
0                 0.000000  
1                 1.000000  
2                 0.000000  
3                 0.000000  
4                 0.000000  
...                    ...  
4647              0.000000  
4648              1.000000  
4649              0.000000  
4650              0.000000  
4651              0.714286  

[4652 rows x 5 columns]

**XGB Classifier**

In [22]:
import keras

from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import pickle

def model_xgb(x_train, x_val, y_train, y_val, opt, n):
  xgbclassifier = XGBClassifier(n_neighbors=5)
  #compile model using mse as a measure of model performance
  xgbclassifier.fit(x_train, y_train)

  y_pred = xgbclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/XGBoost/model_'+str(n)+'.h5'
  pickle.dump(xgbclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_xgb(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[303   6]
 [ 15 245]]
Precision: 0.9761
Recall: 0.9423
F1 Score: 0.9589
Validation Accuracy: 0.9630931458699473
model 0 saved
[[301   9]
 [ 21 238]]
Precision: 0.9636
Recall: 0.9189
F1 Score: 0.9407
Validation Accuracy: 0.9472759226713533
model 1 saved
[[299  11]
 [ 19 240]]
Precision: 0.9562
Recall: 0.9266
F1 Score: 0.9412
Validation Accuracy: 0.9472759226713533
model 2 saved
[[303  14]
 [ 16 236]]
Precision: 0.9440
Recall: 0.9365
F1 Score: 0.9402
Validation Accuracy: 0.9472759226713533
model 3 saved
[[304  25]
 [ 23 217]]
Precision: 0.8967
Recall: 0.9042
F1 Score: 0.9004
Validation Accuracy: 0.9156414762741653
model 4 saved
[[316  15]
 [ 19 218]]
Precision: 0.9356
Recall: 0.9198
F1 Score: 0.9277
Validation Accuracy: 0.9401408450704225
model 5 saved
[[283  17]
 [ 31 237]]
Precision: 0.9331
Recall: 0.8843
F1 Score: 0.9080
Validation Accuracy: 0.9154929577464789
model 6 saved
[[297  13]
 [ 14 244]]
Precision: 0.9494
Recall: 0.9457
F1 Score: 0.9476
Validation Accuracy: 0.952464788732394

In [23]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/XGBoost/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['XGB_prediction_non'] = [i[0] for i in y_pred_prob];
output['XGB_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.9889652  0.0110348 ]
 [0.01220524 0.98779476]
 [0.9161812  0.08381881]
 ...
 [0.9848314  0.01516863]
 [0.9578477  0.04215229]
 [0.06867659 0.9313234 ]]


labels  dt_prediction_non  dt_prediction_phish  knn_prediction_non  \
0          0           0.965658             0.034342            1.000000   
1          1           0.005313             0.994687            0.000000   
2          0           0.965658             0.034342            1.000000   
3          0           0.965658             0.034342            1.000000   
4          0           0.821229             0.178771            1.000000   
...      ...                ...                  ...                 ...   
4647       0           0.965658             0.034342            1.000000   
4648       1           0.056225             0.943775            0.000000   
4649       0           0.965658             0.034342            1.000000   
4650       0           0.960674             0.039326            1.000000   
4651       1           0.000000             1.000000            0.285714   

      knn_prediction_phish  XGB_prediction_non  XGB_prediction_phish  
0                 0.000000            0.988965              0.011035  
1                 1.000000            0.012205              0.987795  
2                 0.000000            0.916181              0.083819  
3                 0.000000            0.929762              0.070237  
4                 0.000000            0.848500              0.151500  
...                    ...                 ...                   ...  
4647              0.000000            0.984831              0.015169  
4648              1.000000            0.040416              0.959584  
4649              0.000000            0.984831              0.015169  
4650              0.000000            0.957848              0.042152  
4651              0.714286            0.068677              0.931323  

[4652 rows x 7 columns]

In [24]:
output.shape


(4652, 7)

In [25]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/PhishTank/Base_classifier_result(pre HTML cross).csv', index=False)