In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/PhishTank/URL-HTML/preprocessed_url_features.csv")
urldata


Unnamed: 0                                       Domain  Have IP  \
0               0                             graphicriver.net        0   
1               1                                    ecnavi.jp        0   
2               2                                 hubpages.com        0   
3               3                              extratorrent.cc        0   
4               4                                icicibank.com        0   
...           ...                                          ...      ...   
10332       11932                             sites.google.com        0   
10333       11933                             sites.google.com        0   
10334       11934             habbocreditosparati.blogspot.com        0   
10335       11935  creditiperhabbogratissicuro100.blogspot.com        0   
10336       11936                           aijcs.blogspot.com        0   

       Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0           0           1          1            0             0        0   
1           0           1          1            1             0        0   
2           0           1          1            0             1        0   
3           0           1          3            0             0        0   
4           0           1          3            0             0        0   
...       ...         ...        ...          ...           ...      ...   
10332       0           0          2            0             1        0   
10333       0           0          2            0             0        0   
10334       0           0          0            0             0        1   
10335       0           1          3            0             0        1   
10336       0           1          3            0             0        1   

       Prefix/Suffix  ...  Num Embeds  Num Images  Num Links  Num Titles  \
0                  0  ...           0          49        691          42   
1                  0  ...           0           4         66           3   
2                  0  ...           0           1        100          27   
3                  0  ...           0           0          0           1   
4                  0  ...           0         117        219          23   
...              ...  ...         ...         ...        ...         ...   
10332              0  ...           0           0         17           4   
10333              0  ...           0           6         24           7   
10334              0  ...           0           4         17           4   
10335              0  ...           0           1         23           8   
10336              0  ...           0          19         42           7   

       Num Script  Special Characters  Script To Special Chars Ratio  \
0           13135                6400                       2.052344   
1            2034                 818                       2.486553   
2           32987               10451                       3.156349   
3               0                  52                       0.000000   
4            7944                3468                       2.290657   
...           ...                 ...                            ...   
10332        8146                2203                       3.697685   
10333        8353                2250                       3.712444   
10334        6403                4560                       1.404167   
10335        9817                7292                       1.346270   
10336        2550                3225                       0.790698   

       Script To body Ratio  Body To Special Char Ratio  Label  
0                  0.528869                    0.257690      0  
1                  0.676197                    0.271941      0  
2                  0.836681                    0.265079      0  
3                  0.000000                    0.227074      0  
4                  0.524460                    0.228956      0  
...                     .

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'Domain'], axis = 1).copy()
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          1            0             0        0   
1        0       0           1          1            1             0        0   
2        0       0           1          1            0             1        0   
3        0       0           1          3            0             0        0   
4        0       0           1          3            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0          49   
1              0            0           0  ...           0           4   
2              0            0           0  ...           0           1   
3              0            0           0  ...           0           0   
4              0            0           0  ...           0         117   

   Num Links  Num Titles  Num Script  Special Characters  \
0        691          42       13135                6400   
1         66           3        2034                 818   
2        100          27       32987               10451   
3          0           1           0                  52   
4        219          23        7944                3468   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       2.052344              0.528869   
1                       2.486553              0.676197   
2                       3.156349              0.836681   
3                       0.000000              0.000000   
4                       2.290657              0.524460   

   Body To Special Char Ratio  Label  
0                    0.257690      0  
1                    0.271941      0  
2                    0.265079      0  
3                    0.227074      0  
4                    0.228956      0  

[5 rows x 45 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Have IP                        10337 non-null  int64  
 1   Have @                         10337 non-null  int64  
 2   URL Length                     10337 non-null  int64  
 3   URL Depth                      10337 non-null  int64  
 4   Redirection                    10337 non-null  int64  
 5   https Domain                   10337 non-null  int64  
 6   TinyURL                        10337 non-null  int64  
 7   Prefix/Suffix                  10337 non-null  int64  
 8   Have client                    10337 non-null  int64  
 9   Have admin                     10337 non-null  int64  
 10  Have login                     10337 non-null  int64  
 11  Have server                    10337 non-null  int64  
 12  .php                           10337 non-null 

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    5828
1    4509
dtype: int64

In [8]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 10337
Non-Phishing: 5828 (56.38% of total)
Phishing: 4509 (43.62% of total)


In [9]:
import numpy as np


In [10]:
urldata.describe()

Have IP        Have @    URL Length     URL Depth   Redirection  \
count  10337.0  10337.000000  10337.000000  10337.000000  10337.000000   
mean       0.0      0.025636      0.698462      3.048660      0.013060   
std        0.0      0.158055      0.458948      2.951401      0.113537   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      0.000000      1.000000      0.000000   
50%        0.0      0.000000      1.000000      2.000000      0.000000   
75%        0.0      0.000000      1.000000      4.000000      0.000000   
max        0.0      1.000000      1.000000     18.000000      1.000000   

       https Domain       TinyURL  Prefix/Suffix   Have client    Have admin  \
count  10337.000000  10337.000000   10337.000000  10337.000000  10337.000000   
mean       0.365773      0.068105       0.074877      0.003676      0.008610   
std        0.481670      0.251938       0.263205      0.060522      0.092393   
min        0.000000      0.000000       0.000000      0.000000      0.000000   
25%        0.000000      0.000000       0.000000      0.000000      0.000000   
50%        0.000000      0.000000       0.000000      0.000000      0.000000   
75%        1.000000      0.000000       0.000000      0.000000      0.000000   
max        1.000000      1.000000       1.000000      1.000000      1.000000   

       ...    Num Embeds    Num Images     Num Links    Num Titles  \
count  ...  10337.000000  10337.000000  10337.000000  10337.000000   
mean   ...      0.000871     10.595627     54.459998      6.805553   
std    ...      0.029496     33.772343    105.521327     25.206153   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      1.000000      1.000000   
50%    ...      0.000000      1.000000      5.000000      1.000000   
75%    ...      0.000000      5.000000     54.000000      3.000000   
max    ...      1.000000    688.000000   2078.000000   1042.000000   

         Num Script  Special Characters  Script To Special Chars Ratio  \
count  1.033700e+04        10337.000000                   10337.000000   
mean   2.805686e+04        10823.200445                       3.695922   
std    9.871191e+04        28279.638035                      21.605333   
min    0.000000e+00            0.000000                       0.000000   
25%    0.000000e+00          421.000000                       0.000000   
50%    5.162000e+03         2142.000000                       1.916015   
75%    1.665200e+04         8705.000000                       2.737587   
max    2.450669e+06       631036.000000                     519.266010   

       Script To body Ratio  Body To Special Char Ratio         Label  
count          10337.000000                10337.000000  10337.000000  
mean               0.443764                    0.241135      0.436200  
std                0.368330                    0.075312      0.495937  
min                0.000000                   -0.000119      0.000000  
25%                0.000000                    0.209596      0.000000  
50%                0.488331                    0.254868      0.000000  
75%                0.790474                    0.295025      1.000000  
max                1.142857                    0.605483      1.000000  

[8 rows x 45 columns]

In [11]:
#checking the data for null or missing values
urldata.isnull().sum()

Have IP                          0
Have @                           0
URL Length                       0
URL Depth                        0
Redirection                      0
https Domain                     0
TinyURL                          0
Prefix/Suffix                    0
Have client                      0
Have admin                       0
Have login                       0
Have server                      0
.php                             0
.html                            0
.info                            0
.txt                             0
.js                              0
.exe                             0
Num of periods                   0
Is encoded                       0
Num of encoded char              0
Num of parameters                0
Num of digits                    0
Num of spec char                 0
iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page token

In [12]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

Have IP  Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0        0       0           1          2            0             0        0   
1        0       0           0          0            0             1        0   
2        0       0           1          3            0             0        0   
3        0       0           1          3            0             1        0   
4        0       0           0          2            0             0        0   

   Prefix/Suffix  Have client  Have admin  ...  Num Embeds  Num Images  \
0              0            0           0  ...           0           2   
1              1            0           0  ...           0           0   
2              0            0           0  ...           0           0   
3              0            1           0  ...           0           0   
4              0            0           0  ...           0           0   

   Num Links  Num Titles  Num Script  Special Characters  \
0         10           3        1362               11815   
1          0           0          57                  14   
2          0           1           0                  29   
3          3           1        6268                7107   
4          0           1           0                  34   

   Script To Special Chars Ratio  Script To body Ratio  \
0                       0.115277              0.031724   
1                       4.071429              0.770270   
2                       0.000000              0.000000   
3                       0.881947              0.229412   
4                       0.000000              0.000000   

   Body To Special Char Ratio  Label  
0                    0.275196      1  
1                    0.189189      1  
2                    0.174699      0  
3                    0.260120      1  
4                    0.185792      1  

[5 rows x 45 columns]

In [13]:
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [14]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(5685, 44) (4652, 44)
(5685,) (4652,)


In [15]:
output = {}
output['labels'] = y_test

**Random Forest Classifier**

In [ ]:
import keras
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  rfc = RandomForestClassifier(n_estimators=50, max_depth=10)
  #compile model using mse as a measure of model performance

  rfc.fit(x_train, y_train)


  y_pred = rfc.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/RFC/model_'+str(n)+'.h5'
  pickle.dump(rfc, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[313   1]
 [  1 254]]
Precision: 0.9961
Recall: 0.9961
F1 Score: 0.9961
Validation Accuracy: 0.9964850615114236
model 0 saved
[[330   1]
 [  4 234]]
Precision: 0.9957
Recall: 0.9832
F1 Score: 0.9894
Validation Accuracy: 0.9912126537785588
model 1 saved
[[320   5]
 [  3 241]]
Precision: 0.9797
Recall: 0.9877
F1 Score: 0.9837
Validation Accuracy: 0.9859402460456942
model 2 saved
[[319   2]
 [  3 245]]
Precision: 0.9919
Recall: 0.9879
F1 Score: 0.9899
Validation Accuracy: 0.9912126537785588
model 3 saved
[[306   2]
 [  0 261]]
Precision: 0.9924
Recall: 1.0000
F1 Score: 0.9962
Validation Accuracy: 0.9964850615114236
model 4 saved
[[321   1]
 [  0 246]]
Precision: 0.9960
Recall: 1.0000
F1 Score: 0.9980
Validation Accuracy: 0.9982394366197183
model 5 saved
[[312   2]
 [  2 252]]
Precision: 0.9921
Recall: 0.9921
F1 Score: 0.9921
Validation Accuracy: 0.9929577464788732
model 6 saved
[[316   2]
 [  3 247]]
Precision: 0.9920
Recall: 0.9880
F1 Score: 0.9900
Validation Accuracy: 0.991197183098591

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/RFC/model_0.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['rfc_prediction_non'] = [i[0] for i in y_pred_prob];
output['rfc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output



[[5.27112237e-03 9.94728878e-01]
 [6.02889550e-03 9.93971104e-01]
 [2.20000000e-02 9.78000000e-01]
 ...
 [9.99658277e-01 3.41722682e-04]
 [9.99217525e-01 7.82474686e-04]
 [8.44099409e-01 1.55900591e-01]]


labels  rfc_prediction_non  rfc_prediction_phish
0          1            0.005271              0.994729
1          1            0.006029              0.993971
2          1            0.022000              0.978000
3          1            0.000000              1.000000
4          0            0.999658              0.000342
...      ...                 ...                   ...
4647       1            0.425595              0.574405
4648       0            0.979070              0.020930
4649       0            0.999658              0.000342
4650       0            0.999218              0.000782
4651       0            0.844099              0.155901

[4652 rows x 3 columns]

**SVM**

In [ ]:
import keras

import pickle
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics


def model_svc(x_train, x_val, y_train, y_val, opt, n):
  svclassifier = SVC(kernel='rbf', probability= True)
  #compile model using mse as a measure of model performance
  svclassifier.fit(x_train, y_train)

  y_pred = svclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/SVC/model_'+str(n)+'.h5'
  pickle.dump(svclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
# early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_svc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[207 102]
 [ 69 191]]
Precision: 0.6519
Recall: 0.7346
F1 Score: 0.6908
Validation Accuracy: 0.6994727592267135
model 0 saved
[[224 101]
 [ 55 189]]
Precision: 0.6517
Recall: 0.7746
F1 Score: 0.7079
Validation Accuracy: 0.7258347978910369
model 1 saved
[[206 114]
 [ 59 190]]
Precision: 0.6250
Recall: 0.7631
F1 Score: 0.6872
Validation Accuracy: 0.6959578207381371
model 2 saved
[[224 107]
 [ 60 178]]
Precision: 0.6246
Recall: 0.7479
F1 Score: 0.6807
Validation Accuracy: 0.7065026362038664
model 3 saved
[[205 110]
 [ 53 201]]
Precision: 0.6463
Recall: 0.7913
F1 Score: 0.7115
Validation Accuracy: 0.7135325131810193
model 4 saved
[[238 104]
 [ 54 172]]
Precision: 0.6232
Recall: 0.7611
F1 Score: 0.6853
Validation Accuracy: 0.721830985915493
model 5 saved
[[207 105]
 [ 73 183]]
Precision: 0.6354
Recall: 0.7148
F1 Score: 0.6728
Validation Accuracy: 0.6866197183098591
model 6 saved
[[213 110]
 [ 60 185]]
Precision: 0.6271
Recall: 0.7551
F1 Score: 0.6852
Validation Accuracy: 0.7007042253521126

In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/SVC/model_1.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['svc_prediction_non'] = [i[0] for i in y_pred_prob];
output['svc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.6916921  0.3083079 ]
 [0.70685948 0.29314052]
 [0.70688463 0.29311537]
 ...
 [0.78849089 0.21150911]
 [0.79822318 0.20177682]
 [0.32721522 0.67278478]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          1            0.005271              0.994729            0.691692   
1          1            0.006029              0.993971            0.706859   
2          1            0.022000              0.978000            0.706885   
3          1            0.000000              1.000000            0.332890   
4          0            0.999658              0.000342            0.788914   
...      ...                 ...                   ...                 ...   
4647       1            0.425595              0.574405            0.354900   
4648       0            0.979070              0.020930            0.494299   
4649       0            0.999658              0.000342            0.788491   
4650       0            0.999218              0.000782            0.798223   
4651       0            0.844099              0.155901            0.327215   

      svc_prediction_phish  
0                 0.308308  
1                 0.293141  
2                 0.293115  
3                 0.667110  
4                 0.211086  
...                    ...  
4647              0.645100  
4648              0.505701  
4649              0.211509  
4650              0.201777  
4651              0.672785  

[4652 rows x 5 columns]

**Logistic Regression**

In [ ]:
import keras

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
import pickle

def model_lr(x_train, x_val, y_train, y_val, opt, n):
  lrclassifier = LogisticRegression()
  #compile model using mse as a measure of model performance
  lrclassifier.fit(x_train, y_train)

  y_pred = lrclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))
  

  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/LR/model_'+str(n)+'.h5'
  pickle.dump(lrclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_lr(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[309   0]
 [167  93]]
Precision: 1.0000
Recall: 0.3577
F1 Score: 0.5269
Validation Accuracy: 0.7065026362038664
model 0 saved
[[322   3]
 [165  79]]
Precision: 0.9634
Recall: 0.3238
F1 Score: 0.4847
Validation Accuracy: 0.7047451669595782


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 1 saved
[[318   2]
 [162  87]]
Precision: 0.9775
Recall: 0.3494
F1 Score: 0.5148
Validation Accuracy: 0.7117750439367311


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 2 saved
[[326   5]
 [166  72]]
Precision: 0.9351
Recall: 0.3025
F1 Score: 0.4571
Validation Accuracy: 0.6994727592267135


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 3 saved
[[311   4]
 [172  82]]
Precision: 0.9535
Recall: 0.3228
F1 Score: 0.4824
Validation Accuracy: 0.6906854130052724


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 4 saved
[[335   7]
 [149  77]]
Precision: 0.9167
Recall: 0.3407
F1 Score: 0.4968
Validation Accuracy: 0.7253521126760564


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 5 saved
[[295  17]
 [ 61 195]]
Precision: 0.9198
Recall: 0.7617
F1 Score: 0.8333
Validation Accuracy: 0.8626760563380281


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 6 saved
[[323   0]
 [157  88]]
Precision: 1.0000
Recall: 0.3592
F1 Score: 0.5285
Validation Accuracy: 0.7235915492957746


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 7 saved
[[311  10]
 [ 89 158]]
Precision: 0.9405
Recall: 0.6397
F1 Score: 0.7614
Validation Accuracy: 0.8257042253521126


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 8 saved
[[312   5]
 [166  85]]
Precision: 0.9444
Recall: 0.3386
F1 Score: 0.4985
Validation Accuracy: 0.698943661971831


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 9 saved
Average Validation Accuracy: 0.7349448624965965


In [ ]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed URL-HTML/LR/model_6.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['lr_prediction_non'] = [i[0] for i in y_pred_prob];
output['lr_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.27795646 0.72204354]
 [0.37438309 0.62561691]
 [0.4576409  0.5423591 ]
 ...
 [0.67576421 0.32423579]
 [0.92294868 0.07705132]
 [0.68965037 0.31034963]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          1            0.005271              0.994729            0.691692   
1          1            0.006029              0.993971            0.706859   
2          1            0.022000              0.978000            0.706885   
3          1            0.000000              1.000000            0.332890   
4          0            0.999658              0.000342            0.788914   
...      ...                 ...                   ...                 ...   
4647       1            0.425595              0.574405            0.354900   
4648       0            0.979070              0.020930            0.494299   
4649       0            0.999658              0.000342            0.788491   
4650       0            0.999218              0.000782            0.798223   
4651       0            0.844099              0.155901            0.327215   

      svc_prediction_phish  lr_prediction_non  lr_prediction_phish  
0                 0.308308           0.277956             0.722044  
1                 0.293141           0.374383             0.625617  
2                 0.293115           0.457641             0.542359  
3                 0.667110           0.448804             0.551196  
4                 0.211086           0.676933             0.323067  
...                    ...                ...                  ...  
4647              0.645100           0.758620             0.241380  
4648              0.505701           0.999987             0.000013  
4649              0.211509           0.675764             0.324236  
4650              0.201777           0.922949             0.077051  
4651              0.672785           0.689650             0.310350  

[4652 rows x 7 columns]

In [ ]:
output.shape


(4652, 7)

In [ ]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/PhishTank/Base_classifier_result(pre URL-HTML cross)(2).csv', index=False)