In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
urldata = pd.read_csv("/content/drive/MyDrive/Phishing/PhishTank/URL-HTML/preprocessed_url_features.csv")
urldata


Unnamed: 0                                       Domain  Have IP  \
0               0                             graphicriver.net        0   
1               1                                    ecnavi.jp        0   
2               2                                 hubpages.com        0   
3               3                              extratorrent.cc        0   
4               4                                icicibank.com        0   
...           ...                                          ...      ...   
10332       11932                             sites.google.com        0   
10333       11933                             sites.google.com        0   
10334       11934             habbocreditosparati.blogspot.com        0   
10335       11935  creditiperhabbogratissicuro100.blogspot.com        0   
10336       11936                           aijcs.blogspot.com        0   

       Have @  URL Length  URL Depth  Redirection  https Domain  TinyURL  \
0           0           1          1            0             0        0   
1           0           1          1            1             0        0   
2           0           1          1            0             1        0   
3           0           1          3            0             0        0   
4           0           1          3            0             0        0   
...       ...         ...        ...          ...           ...      ...   
10332       0           0          2            0             1        0   
10333       0           0          2            0             0        0   
10334       0           0          0            0             0        1   
10335       0           1          3            0             0        1   
10336       0           1          3            0             0        1   

       Prefix/Suffix  ...  Num Embeds  Num Images  Num Links  Num Titles  \
0                  0  ...           0          49        691          42   
1                  0  ...           0           4         66           3   
2                  0  ...           0           1        100          27   
3                  0  ...           0           0          0           1   
4                  0  ...           0         117        219          23   
...              ...  ...         ...         ...        ...         ...   
10332              0  ...           0           0         17           4   
10333              0  ...           0           6         24           7   
10334              0  ...           0           4         17           4   
10335              0  ...           0           1         23           8   
10336              0  ...           0          19         42           7   

       Num Script  Special Characters  Script To Special Chars Ratio  \
0           13135                6400                       2.052344   
1            2034                 818                       2.486553   
2           32987               10451                       3.156349   
3               0                  52                       0.000000   
4            7944                3468                       2.290657   
...           ...                 ...                            ...   
10332        8146                2203                       3.697685   
10333        8353                2250                       3.712444   
10334        6403                4560                       1.404167   
10335        9817                7292                       1.346270   
10336        2550                3225                       0.790698   

       Script To body Ratio  Body To Special Char Ratio  Label  
0                  0.528869                    0.257690      0  
1                  0.676197                    0.271941      0  
2                  0.836681                    0.265079      0  
3                  0.000000                    0.227074      0  
4                  0.524460                    0.228956      0  
...                     .

In [4]:
urldata.columns

Index(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char', 'iFrame', 'Mouse Over', 'Right Click',
       'Web Forwards', 'Number of page tokens', 'number of sentences',
       'number of html tags', 'number of whitespace', 'url Is Live',
       'HTML Length', 'Num Objects', 'Num Embeds', 'Num Images', 'Num Links',
       'Num Titles', 'Num Script', 'Special Characters',
       'Script To Special Chars Ratio', 'Script To body Ratio',
       'Body To Special Char Ratio', 'Label'],
      dtype='object')

In [5]:
urldata = urldata.drop(['Unnamed: 0', 'Domain', 'Have IP', 'Have @', 'URL Length', 'URL Depth',
       'Redirection', 'https Domain', 'TinyURL', 'Prefix/Suffix',
       'Have client', 'Have admin', 'Have login', 'Have server', '.php',
       '.html', '.info', '.txt', '.js', '.exe', 'Num of periods', 'Is encoded',
       'Num of encoded char', 'Num of parameters', 'Num of digits',
       'Num of spec char'], axis = 1).copy()
# urldata = urldata.drop(['Domain'], axis = 1).copy()
urldata.shape
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                  21444   
1       1           0            0             1                   1075   
2       1           0            0             1                   4531   
3       1           0            0             1                     32   
4       1           0            0             1                   4880   

   number of sentences  number of html tags  number of whitespace  \
0                 1853                 3247                     0   
1                  136                  236                     0   
2                 2634                  486                     0   
3                    9                    8                     0   
4                  981                 1412                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            1        24836  ...           0          49        691   
1            1         3008  ...           0           4         66   
2            1        39426  ...           0           1        100   
3            0          229  ...           0           0          0   
4            1        15147  ...           0         117        219   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0          42       13135                6400                       2.052344   
1           3        2034                 818                       2.486553   
2          27       32987               10451                       3.156349   
3           1           0                  52                       0.000000   
4          23        7944                3468                       2.290657   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.528869                    0.257690      0  
1              0.676197                    0.271941      0  
2              0.836681                    0.265079      0  
3              0.000000                    0.227074      0  
4              0.524460                    0.228956      0  

[5 rows x 21 columns]

In [6]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   iFrame                         10337 non-null  int64  
 1   Mouse Over                     10337 non-null  int64  
 2   Right Click                    10337 non-null  int64  
 3   Web Forwards                   10337 non-null  int64  
 4   Number of page tokens          10337 non-null  int64  
 5   number of sentences            10337 non-null  int64  
 6   number of html tags            10337 non-null  int64  
 7   number of whitespace           10337 non-null  int64  
 8   url Is Live                    10337 non-null  int64  
 9   HTML Length                    10337 non-null  int64  
 10  Num Objects                    10337 non-null  int64  
 11  Num Embeds                     10337 non-null  int64  
 12  Num Images                     10337 non-null 

In [7]:
# Class Distribution of Labels
urldata.groupby('Label').size()

Label
0    5828
1    4509
dtype: int64

In [8]:
# Analysis of Postives and Negatives in the Dataset
pos,neg = urldata['Label'].value_counts()
total = neg + pos
print ('Total of Samples: %s'% total)
print('Non-Phishing: {} ({:.2f}% of total)'.format(pos, 100 * pos / total))
print('Phishing: {} ({:.2f}% of total)'.format(neg, 100 * neg / total))

Total of Samples: 10337
Non-Phishing: 5828 (56.38% of total)
Phishing: 4509 (43.62% of total)


In [9]:
urldata.describe()

iFrame    Mouse Over   Right Click  Web Forwards  \
count  10337.000000  10337.000000  10337.000000  10337.000000   
mean       0.999807      0.000290      0.000097      0.952307   
std        0.013909      0.017034      0.009836      0.213126   
min        0.000000      0.000000      0.000000      0.000000   
25%        1.000000      0.000000      0.000000      1.000000   
50%        1.000000      0.000000      0.000000      1.000000   
75%        1.000000      0.000000      0.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000   

       Number of page tokens  number of sentences  number of html tags  \
count           10337.000000          10337.00000         10337.000000   
mean             3198.006965           1661.99526           353.834478   
std              5664.530703           3873.01854           671.004262   
min                 1.000000              1.00000            -1.000000   
25%               247.000000             16.00000            19.000000   
50%              1100.000000            293.00000           110.000000   
75%              3835.000000           1679.00000           413.000000   
max             79130.000000          55924.00000          8760.000000   

       number of whitespace   url Is Live   HTML Length  ...    Num Embeds  \
count               10337.0  10337.000000  1.033700e+04  ...  10337.000000   
mean                    0.0      0.549386  4.422439e+04  ...      0.000871   
std                     0.0      0.505680  1.154572e+05  ...      0.029496   
min                     0.0     -1.000000  0.000000e+00  ...      0.000000   
25%                     0.0      0.000000  1.427000e+03  ...      0.000000   
50%                     0.0      1.000000  9.675000e+03  ...      0.000000   
75%                     0.0      1.000000  3.381200e+04  ...      0.000000   
max                     0.0      1.000000  2.450669e+06  ...      1.000000   

         Num Images     Num Links    Num Titles    Num Script  \
count  10337.000000  10337.000000  10337.000000  1.033700e+04   
mean      10.595627     54.459998      6.805553  2.805686e+04   
std       33.772343    105.521327     25.206153  9.871191e+04   
min        0.000000      0.000000      0.000000  0.000000e+00   
25%        0.000000      1.000000      1.000000  0.000000e+00   
50%        1.000000      5.000000      1.000000  5.162000e+03   
75%        5.000000     54.000000      3.000000  1.665200e+04   
max      688.000000   2078.000000   1042.000000  2.450669e+06   

       Special Characters  Script To Special Chars Ratio  \
count        10337.000000                   10337.000000   
mean         10823.200445                       3.695922   
std          28279.638035                      21.605333   
min              0.000000                       0.000000   
25%            421.000000                       0.000000   
50%           2142.000000                       1.916015   
75%           8705.000000                       2.737587   
max         631036.000000                     519.266010   

       Script To body Ratio  Body To Special Char Ratio         Label  
count          10337.000000                10337.000000  10337.000000  
mean               0.443764                    0.241135      0.436200  
std                0.368330                    0.075312      0.495937  
min                0.000000                   -0.000119      0.000000  
25%                0.000000                    0.209596      0.000000  
50%                0.488331                    0.254868      0.000000  
75%                0.790474                    0.295025      1.000000  
max                1.142857                    0.605483      1.000000  

[8 rows x 21 columns]

In [10]:
#checking the data for null or missing values
urldata.isnull().sum()

iFrame                           0
Mouse Over                       0
Right Click                      0
Web Forwards                     0
Number of page tokens            0
number of sentences              0
number of html tags              0
number of whitespace             0
url Is Live                      0
HTML Length                      0
Num Objects                      0
Num Embeds                       0
Num Images                       0
Num Links                        0
Num Titles                       0
Num Script                       0
Special Characters               0
Script To Special Chars Ratio    0
Script To body Ratio             0
Body To Special Char Ratio       0
Label                            0
dtype: int64

In [11]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
urldata = urldata.sample(frac=1).reset_index(drop=True)
urldata.head()

iFrame  Mouse Over  Right Click  Web Forwards  Number of page tokens  \
0       1           0            0             1                    683   
1       1           0            0             1                      3   
2       1           0            0             1                   1719   
3       1           0            0             1                    247   
4       1           0            0             1                   4622   

   number of sentences  number of html tags  number of whitespace  \
0                  121                   69                     0   
1                    1                    1                     0   
2                 1679                  159                     0   
3                   16                   19                     0   
4                 3856                  328                     0   

   url Is Live  HTML Length  ...  Num Embeds  Num Images  Num Links  \
0            0         5144  ...           0           0          1   
1            0            0  ...           0           0          0   
2            0        32609  ...           0           4         28   
3            0         1427  ...           0           1          2   
4            0        95656  ...           0          11         40   

   Num Titles  Num Script  Special Characters  Script To Special Chars Ratio  \
0           5        3453                1201                       2.875104   
1           1           0                   0                       0.000000   
2           1       15924                8311                       1.916015   
3           3           0                 421                       0.000000   
4           1       15089               22639                       0.666505   

   Script To body Ratio  Body To Special Char Ratio  Label  
0              0.671267                    0.233476      0  
1              0.000000                    0.000000      1  
2              0.488331                    0.254868      0  
3              0.000000                    0.295025      1  
4              0.157742                    0.236671      0  

[5 rows x 21 columns]

In [12]:
import numpy as np
# Sepratating & assigning features and target columns to X & y
y = urldata['Label'].values
x = np.array(urldata.drop('Label',axis=1))



In [13]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size = 0.45, random_state = 12)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)



(5685, 20) (4652, 20)
(5685,) (4652,)


In [14]:
output = {}
output['labels'] = y_test

**Random Forest Classifier**

In [15]:
import keras
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics
from sklearn.metrics import classification_report
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

def model_dtc(x_train, x_val, y_train, y_val, opt, n):
  rfc = RandomForestClassifier(n_estimators=50, max_depth=10)
  #compile model using mse as a measure of model performance

  rfc.fit(x_train, y_train)


  y_pred = rfc.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))


  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/RFC/model_'+str(n)+'.h5'
  pickle.dump(rfc, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')

  return metrics.accuracy_score(y_val, y_pred)

In [16]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_dtc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[328   5]
 [ 18 218]]
Precision: 0.9776
Recall: 0.9237
F1 Score: 0.9499
Validation Accuracy: 0.9595782073813708
model 0 saved
[[329   7]
 [ 17 216]]
Precision: 0.9686
Recall: 0.9270
F1 Score: 0.9474
Validation Accuracy: 0.9578207381370826
model 1 saved
[[312   0]
 [ 18 239]]
Precision: 1.0000
Recall: 0.9300
F1 Score: 0.9637
Validation Accuracy: 0.968365553602812
model 2 saved
[[325   4]
 [  6 234]]
Precision: 0.9832
Recall: 0.9750
F1 Score: 0.9791
Validation Accuracy: 0.9824253075571178
model 3 saved
[[318   3]
 [  9 239]]
Precision: 0.9876
Recall: 0.9637
F1 Score: 0.9755
Validation Accuracy: 0.9789103690685413
model 4 saved
[[309   9]
 [ 15 235]]
Precision: 0.9631
Recall: 0.9400
F1 Score: 0.9514
Validation Accuracy: 0.9577464788732394
model 5 saved
[[305   2]
 [ 13 248]]
Precision: 0.9920
Recall: 0.9502
F1 Score: 0.9706
Validation Accuracy: 0.9735915492957746
model 6 saved
[[309   3]
 [ 19 237]]
Precision: 0.9875
Recall: 0.9258
F1 Score: 0.9556
Validation Accuracy: 0.9612676056338029

In [17]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/RFC/model_9.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['rfc_prediction_non'] = [i[0] for i in y_pred_prob];
output['rfc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output



[[9.97151352e-01 2.84864826e-03]
 [9.34405964e-01 6.55940361e-02]
 [1.44027116e-03 9.98559729e-01]
 ...
 [9.99945897e-01 5.41027953e-05]
 [9.19027332e-01 8.09726679e-02]
 [1.41187199e-04 9.99858813e-01]]


labels  rfc_prediction_non  rfc_prediction_phish
0          0            0.997151              0.002849
1          0            0.934406              0.065594
2          1            0.001440              0.998560
3          0            0.949782              0.050218
4          0            0.980158              0.019842
...      ...                 ...                   ...
4647       0            0.924580              0.075420
4648       1            0.018547              0.981453
4649       0            0.999946              0.000054
4650       0            0.919027              0.080973
4651       1            0.000141              0.999859

[4652 rows x 3 columns]

**SVM**

In [ ]:
import keras

import pickle
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics


def model_svc(x_train, x_val, y_train, y_val, opt, n):
  svclassifier = SVC(kernel='rbf', probability= True)
  #compile model using mse as a measure of model performance
  svclassifier.fit(x_train, y_train)

  y_pred = svclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))

  
  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/SVC/model_'+str(n)+'.h5'
  pickle.dump(svclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
# early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_svc(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


[[194 121]
 [ 63 191]]
Precision: 0.6122
Recall: 0.7520
F1 Score: 0.6749
Validation Accuracy: 0.6766256590509666
model 0 saved
[[212 104]
 [ 66 187]]
Precision: 0.6426
Recall: 0.7391
F1 Score: 0.6875
Validation Accuracy: 0.7012302284710018
model 1 saved
[[214 112]
 [ 62 181]]
Precision: 0.6177
Recall: 0.7449
F1 Score: 0.6754
Validation Accuracy: 0.6942003514938488
model 2 saved
[[236  98]
 [ 58 177]]
Precision: 0.6436
Recall: 0.7532
F1 Score: 0.6941
Validation Accuracy: 0.7258347978910369
model 3 saved
[[226 112]
 [ 70 161]]
Precision: 0.5897
Recall: 0.6970
F1 Score: 0.6389
Validation Accuracy: 0.680140597539543
model 4 saved
[[202 104]
 [ 56 206]]
Precision: 0.6645
Recall: 0.7863
F1 Score: 0.7203
Validation Accuracy: 0.7183098591549296
model 5 saved
[[219 108]
 [ 79 162]]
Precision: 0.6000
Recall: 0.6722
F1 Score: 0.6341
Validation Accuracy: 0.670774647887324
model 6 saved
[[203 120]
 [ 60 185]]
Precision: 0.6066
Recall: 0.7551
F1 Score: 0.6727
Validation Accuracy: 0.6830985915492958


In [18]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/SVC/model_3.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['svc_prediction_non'] = [i[0] for i in y_pred_prob];
output['svc_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.78938765 0.21061235]
 [0.31701881 0.68298119]
 [0.5        0.5       ]
 ...
 [0.77536489 0.22463511]
 [0.3175512  0.6824488 ]
 [0.7159354  0.2840646 ]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          0            0.997151              0.002849            0.789388   
1          0            0.934406              0.065594            0.317019   
2          1            0.001440              0.998560            0.500000   
3          0            0.949782              0.050218            0.316952   
4          0            0.980158              0.019842            0.817363   
...      ...                 ...                   ...                 ...   
4647       0            0.924580              0.075420            0.361246   
4648       1            0.018547              0.981453            0.331664   
4649       0            0.999946              0.000054            0.775365   
4650       0            0.919027              0.080973            0.317551   
4651       1            0.000141              0.999859            0.715935   

      svc_prediction_phish  
0                 0.210612  
1                 0.682981  
2                 0.500000  
3                 0.683048  
4                 0.182637  
...                    ...  
4647              0.638754  
4648              0.668336  
4649              0.224635  
4650              0.682449  
4651              0.284065  

[4652 rows x 5 columns]

**Logistic Regression**

In [ ]:
import keras

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
import pickle

def model_lr(x_train, x_val, y_train, y_val, opt, n):
  lrclassifier = LogisticRegression()
  #compile model using mse as a measure of model performance
  lrclassifier.fit(x_train, y_train)

  y_pred = lrclassifier.predict(x_val)

  conf_matrix = confusion_matrix(y_val, y_pred)
  print(conf_matrix)
  print('Precision: %.4f' % precision_score(y_val, y_pred))
  print('Recall: %.4f' % recall_score(y_val, y_pred))
  print('F1 Score: %.4f' % f1_score(y_val, y_pred))
  

  print("Validation Accuracy:",metrics.accuracy_score(y_val, y_pred))
  # save the model to disk
  filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/LR/model_'+str(n)+'.h5'
  pickle.dump(lrclassifier, open(filename, 'wb'))

  print('model ' + str(n) + ' saved')
  return metrics.accuracy_score(y_val, y_pred)

In [ ]:
from sklearn.model_selection import KFold
import tensorflow as tf

optimizer1=tf.keras.optimizers.Adam(learning_rate=0.0005)

from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)
n_split = 10
acc = 0
n=0
kf = KFold(n_split, random_state=10, shuffle=True)
for train, val in kf.split(x_train, y_train):
  val_acc = model_lr(x_train[train], x_train[val], y_train[train], y_train[val], optimizer1, n)
  n = n+1
  acc = acc + val_acc

print("Average Validation Accuracy:",acc/n_split)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[248  62]
 [145 114]]
Precision: 0.6477
Recall: 0.4402
F1 Score: 0.5241
Validation Accuracy: 0.6362038664323374
model 0 saved
[[241  79]
 [148 101]]
Precision: 0.5611
Recall: 0.4056
F1 Score: 0.4709
Validation Accuracy: 0.6010544815465729


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 1 saved
[[257  76]
 [133 103]]
Precision: 0.5754
Recall: 0.4364
F1 Score: 0.4964
Validation Accuracy: 0.632688927943761


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 2 saved
[[246  78]
 [131 114]]
Precision: 0.5938
Recall: 0.4653
F1 Score: 0.5217
Validation Accuracy: 0.632688927943761


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 3 saved
[[245  79]
 [120 125]]
Precision: 0.6127
Recall: 0.5102
F1 Score: 0.5568
Validation Accuracy: 0.6502636203866432


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 4 saved
[[260  77]
 [129 102]]
Precision: 0.5698
Recall: 0.4416
F1 Score: 0.4976
Validation Accuracy: 0.6373239436619719


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 5 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[250  64]
 [ 95 159]]
Precision: 0.7130
Recall: 0.6260
F1 Score: 0.6667
Validation Accuracy: 0.7200704225352113
model 6 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[273  53]
 [ 70 172]]
Precision: 0.7644
Recall: 0.7107
F1 Score: 0.7366
Validation Accuracy: 0.7834507042253521
model 7 saved


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


[[252  78]
 [117 121]]
Precision: 0.6080
Recall: 0.5084
F1 Score: 0.5538
Validation Accuracy: 0.6566901408450704
model 8 saved
[[259  57]
 [ 83 169]]
Precision: 0.7478
Recall: 0.6706
F1 Score: 0.7071
Validation Accuracy: 0.7535211267605634


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


model 9 saved
Average Validation Accuracy: 0.6703956162281244


In [19]:
# load the model from disk
filename = '/content/drive/MyDrive/Phishing/PhishTank/Models/preprocessed HTML/LR/model_7.h5'
loaded_model = pickle.load(open(filename, 'rb'))

y_pred_prob = loaded_model.predict_proba(x_test)

print(y_pred_prob)

output['lr_prediction_non'] = [i[0] for i in y_pred_prob];
output['lr_prediction_phish'] = [i[1] for i in y_pred_prob];
output = pd.DataFrame.from_dict(output)
output


[[0.95967928 0.04032072]
 [0.49653395 0.50346605]
 [0.50183225 0.49816775]
 ...
 [0.65666158 0.34333842]
 [0.49251346 0.50748654]
 [0.56557861 0.43442139]]


labels  rfc_prediction_non  rfc_prediction_phish  svc_prediction_non  \
0          0            0.997151              0.002849            0.789388   
1          0            0.934406              0.065594            0.317019   
2          1            0.001440              0.998560            0.500000   
3          0            0.949782              0.050218            0.316952   
4          0            0.980158              0.019842            0.817363   
...      ...                 ...                   ...                 ...   
4647       0            0.924580              0.075420            0.361246   
4648       1            0.018547              0.981453            0.331664   
4649       0            0.999946              0.000054            0.775365   
4650       0            0.919027              0.080973            0.317551   
4651       1            0.000141              0.999859            0.715935   

      svc_prediction_phish  lr_prediction_non  lr_prediction_phish  
0                 0.210612           0.959679             0.040321  
1                 0.682981           0.496534             0.503466  
2                 0.500000           0.501832             0.498168  
3                 0.683048           0.496137             0.503863  
4                 0.182637           0.753955             0.246045  
...                    ...                ...                  ...  
4647              0.638754           0.762970             0.237030  
4648              0.668336           0.581115             0.418885  
4649              0.224635           0.656662             0.343338  
4650              0.682449           0.492513             0.507487  
4651              0.284065           0.565579             0.434421  

[4652 rows x 7 columns]

In [20]:
output.shape


(4652, 7)

In [21]:
# Storing the data in CSV file
output.to_csv('/content/drive/MyDrive/Phishing/PhishTank/Base_classifier_result(pre HTML cross)(2).csv', index=False)